# NB — 50-Agent Swarm for Global Insurance Corporate & Tax Architecture

## A synthetic, compliance-first experiment in organizational design

This notebook asks a deliberately difficult question: **how might a very large, London-listed insurance group simplify an extraordinarily fragmented international structure into one group headquarters and three regional operating subsidiaries while improving tax efficiency, regulatory coherence, capital mobility, resilience, and governance?** The purpose is not to discover a tax “loophole.” It is to demonstrate how a swarm of specialized AI agents can reason over a problem in which tax is only one layer of a much larger institutional system.

We construct a synthetic insurer, **Atlas Global Insurance Group plc (AGIG)**. AGIG is assumed to serve clients in roughly 150 countries, maintain regulated insurance entities in at least 20 important jurisdictions, write property and casualty, specialty, catastrophe, marine, cyber, health, life and retirement business, and purchase and provide reinsurance through a dense internal and external network. Its shares are listed in London and its shareholder base is globally distributed. The legacy group grew through acquisitions, leaving behind duplicated legal entities, uneven capitalization, multiple service companies, trapped capital, intercompany balances, intellectual-property arrangements, local tax attributes, and a web of reinsurance treaties.

The redesign target is intentionally severe: a **listed parent / group headquarters plus three principal regional platforms — Europe, Americas and Asia-Pacific**. Local regulated carriers are not magically eliminated. Insurance law, licensing, policyholder protection, local capital requirements and supervisory expectations often require legal entities to remain in place. Therefore “three subsidiaries” means three principal regional holding and operating platforms beneath which necessary regulated local entities may continue to exist. The swarm must distinguish economic simplification from fictional legal simplification.

The notebook treats the company as a **multilayer graph**. Nodes represent legal entities and jurisdictions. Edges represent ownership, premiums, claims, reinsurance, dividends, service charges, financing and operational dependencies. Each jurisdiction receives synthetic attributes covering corporate tax, Pillar Two exposure, withholding friction, regulatory intensity, capital fungibility, insurance-market depth, treaty-network quality, operating cost, talent, political and legal stability, and the practical ability to demonstrate management substance. These values are deliberately illustrative. They are not a database of current tax law.

A second layer models business risk. Synthetic exposures are generated by geography and line of business, including catastrophe sensitivity, life-duration risk, cyber concentration, health volatility and specialty-tail risk. A third layer models reinsurance. The notebook creates ceded-risk relationships among operating entities and regional reinsurance centers, allowing the swarm to reason about diversification, counterparty concentration and the possibility that a tax-efficient structure may be economically inferior if it weakens capital mobility or creates regulatory fragmentation.

The analytical architecture uses **50 specialist agents**. They are not fifty copies of the same prompt. The swarm contains international-tax specialists, Pillar Two specialists, transfer-pricing experts, insurance-regulation experts, solvency and capital experts, reinsurance specialists, corporate lawyers, governance specialists, treasury specialists, accounting experts, operational-resilience specialists, data and technology specialists, geopolitical-risk analysts and institutional-design critics. Each agent receives a bounded mandate and the same structured evidence pack. Claude is asked to return machine-readable judgments rather than free-form advocacy.

The swarm is organized as a deliberative institution. First, deterministic code creates the synthetic company and calculates candidate architectures. Second, agents inspect the evidence from their disciplines. Third, a synthesis layer aggregates their objections, constraints and preferences. Fourth, a red-team stage searches for designs that appear tax-efficient only because they ignore substance, transfer pricing, minimum-tax rules, regulatory capital, policyholder protection, governance or implementation costs. Finally, a constrained scoring engine identifies a **Pareto-style shortlist**, not a magical single answer produced by an opaque language model.

Tax efficiency is therefore defined carefully. The objective is to reduce **lawful structural friction**: unnecessary withholding leakage, duplicated tax costs, avoidable entity complexity, stranded losses, inefficient capital routing, inconsistent transfer-pricing arrangements and administrative burden. The notebook explicitly penalizes structures whose apparent advantage depends on very low effective tax rates, weak substance, artificial profit allocation, regulatory arbitrage or assumptions inconsistent with the OECD/G20 Pillar Two environment. For a group of this scale, a 15% jurisdictional minimum-tax framework can materially reduce the value of locating profits in low-tax jurisdictions; the design problem increasingly becomes one of **substance, capital efficiency, treaty access, supervisory credibility and operating coherence**, rather than simply choosing the lowest headline rate.

This is especially important for insurance. A global insurer cannot be optimized as if it were a collection of invoices. Underwriting authority, claims management, actuarial judgment, investment management, reinsurance purchasing, risk ownership, board oversight, capital and policyholder obligations must align with the legal architecture. A regional hub that books risk but lacks people, decision rights, systems and capital is not an economically credible solution. The notebook therefore treats “substance” as an explicit constraint.

The intended output is a board-level architecture: the recommended location of the parent/headquarters and the three regional platforms; the logic for retaining local regulated entities; a proposed pattern for reinsurance and shared services; an estimate of structural tax and capital friction under synthetic assumptions; a map of critical legal and regulatory dependencies; dissenting agent views; and a staged implementation roadmap. The notebook does **not** produce legal or tax advice and should not be used to execute a real restructuring without jurisdiction-specific advice, current tax data, actuarial analysis, regulatory engagement and board approval.

Methodologically, the exercise is also about advanced autonomous systems. The 50-agent swarm demonstrates that difficult institutional problems are not solved merely by adding more model calls. The useful unit is a governed system: **data → graph → constraints → specialists → debate → red team → deterministic validation → recommendation → provenance**. The language model supplies judgment and hypothesis generation; deterministic code supplies arithmetic, reproducibility and constraint enforcement. The result is an auditable collaboration between statistical computation and machine reasoning.

## Pedagogical orientation

The central lesson is that corporate architecture is a **multi-objective constrained optimization problem**. A naïve tax optimizer might minimize an estimated tax rate. A realistic insurer must simultaneously consider taxation, regulatory capital, solvency, legal enforceability, reinsurance economics, operational resilience, transfer pricing, governance, market access, talent, reporting, political risk and implementation cost. Some of these dimensions can be quantified; others require expert judgment. The swarm is designed to combine both.

Students should pay particular attention to the distinction between **objective functions and constraints**. A lower tax burden can be an objective, but legal compliance, minimum regulatory capital, policyholder protection, credible economic substance and arm’s-length pricing are constraints. A solution that violates a constraint is not “high return”; it is infeasible. This distinction is fundamental to responsible AI in finance.

The second lesson concerns graphs. A multinational insurer is not naturally represented by a flat spreadsheet. Ownership links, premium flows, claims, reinsurance, dividends and services create networks. Network representations reveal concentration, centrality, bottlenecks and dependencies that disappear in consolidated financial statements. By collapsing a legacy graph into a regional architecture, we can measure whether simplification genuinely reduces complexity or merely hides it.

The third lesson is institutional pluralism. Different specialists optimize different things. A tax lawyer may value treaty access; a chief risk officer may value capital fungibility; a supervisor may value local resolvability; a reinsurance expert may value diversification; a CFO may value distributable cash; an operations executive may value talent and infrastructure. The 50-agent design makes these tensions explicit rather than forcing one general-purpose model to impersonate consensus.

Finally, the notebook uses AI as a **decision-support layer**, not as the final legal authority. Claude can identify issues, challenge assumptions and synthesize competing perspectives, but the numerical scoring and hard feasibility gates remain inspectable. In a real project, every material assumption would be replaced with verified legal, tax, actuarial, accounting and regulatory data, and each proposed transaction would require professional sign-off.

### Code Unit 1 — Environment, reproducibility and model access

The first code unit establishes the computational environment and the governance boundary for the experiment. It imports the libraries used for tabular analysis, numerical computation, graph construction and visualization, fixes random seeds so that the synthetic company can be reproduced, and attempts to retrieve the Anthropic credential from the **Google Colab Secrets** facility under the name `ANTHROPIC_API_KEY`. The key is never written into the notebook. This is an important operational pattern: credentials belong in a secrets manager, while notebooks contain only the name of the secret they expect.

The variable `MODEL` is set to `claude-sonnet-5`, following the model choice for this experiment. Because API availability and model identifiers can change, the notebook exposes the model name as a single configurable constant rather than scattering it through the code. `LIVE_LLM` defaults to `False`. This makes the notebook safe to execute end-to-end without accidentally issuing fifty or more paid API calls. When the user deliberately switches it to `True`, the later swarm cells can invoke Anthropic.

The cell also defines a small JSON-extraction helper. Swarm systems become much easier to audit when agents return structured objects rather than unconstrained prose. In production, schema validation would be stricter, with retries and explicit failure states. Here, the helper is intentionally transparent. The broader design principle is that an LLM should be treated as a probabilistic component inside a deterministic system. The notebook will never depend on the model for arithmetic that Python can perform directly, and it will retain enough intermediate state to explain how the final architecture was selected.

## Infographic — Code Unit 1

In [ ]:
# CODE UNIT 1 — Environment, reproducibility and secure model configuration
!pip -q install anthropic networkx pandas numpy matplotlib scipy

import os, json, re, math, random, itertools, hashlib
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

SEED = 766
random.seed(SEED)
np.random.seed(SEED)

MODEL = "claude-sonnet-5"
LIVE_LLM = True  # Set True deliberately to run the 50-agent live swarm.

try:
    from google.colab import userdata
    ANTHROPIC_API_KEY = userdata.get("ANTHROPIC_API_KEY")
except Exception:
    ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

def extract_json(text):
    text = text.strip()
    m = re.search(r"\{.*\}", text, flags=re.S)
    if not m:
        raise ValueError("No JSON object found in model response.")
    return json.loads(m.group(0))

print("Model:", MODEL)
print("Live LLM:", LIVE_LLM)
print("Secret available:", bool(ANTHROPIC_API_KEY))

Model: claude-sonnet-5
Live LLM: True
Secret available: True

### Code Unit 2 — Constructing the synthetic global insurer

This cell creates the synthetic institutional footprint. Twenty-four regulated jurisdictions are assigned to Europe, the Americas or Asia-Pacific, and the group is assumed to serve customers in approximately 150 countries through these carriers, branches, fronting arrangements and cross-border permissions. Each regulated entity receives synthetic premiums, claims, reserves, capital, employees and business-mix weights. The resulting table is not intended to mimic any named insurer; it is a pedagogical “mammoth” large enough to make restructuring genuinely difficult.

The design deliberately separates **regulated entities** from **client countries**. A company can have customers in far more jurisdictions than it has incorporated insurance carriers. This distinction matters because tax nexus, insurance licensing, permanent-establishment questions and policyholder obligations do not map one-for-one to customer geography.

Financial quantities are generated with correlated logic rather than independently. Premium scale influences reserves and capital; claims are derived from a loss ratio; employee counts scale with activity; and each entity is assigned a business line that affects its risk characteristics. This gives the synthetic data enough internal structure for later analysis.

The cell also assigns every entity a unique identifier and regional classification. In a real engagement, this table would be assembled from legal-entity management systems, general ledgers, regulatory returns, actuarial systems, tax provision data and reinsurance administration systems. The notebook intentionally creates it in one place so students can see exactly what the agents are allowed to know. A central principle of the experiment is **evidence symmetry**: every specialist receives the same factual base, while their mandates differ. That reduces the risk that apparent disagreement among agents is simply caused by inconsistent input data.

## Infographic — Code Unit 2

In [ ]:
# CODE UNIT 2 — Synthetic insurer: 24 regulated jurisdictions, ~150 client countries
regulated = [
("United Kingdom","Europe"),("Ireland","Europe"),("France","Europe"),("Germany","Europe"),
("Netherlands","Europe"),("Spain","Europe"),("Italy","Europe"),("Switzerland","Europe"),
("United States","Americas"),("Canada","Americas"),("Mexico","Americas"),("Brazil","Americas"),
("Chile","Americas"),("Colombia","Americas"),("Argentina","Americas"),("Panama","Americas"),
("Singapore","Asia-Pacific"),("Hong Kong","Asia-Pacific"),("Japan","Asia-Pacific"),("Australia","Asia-Pacific"),
("India","Asia-Pacific"),("South Korea","Asia-Pacific"),("Malaysia","Asia-Pacific"),("Indonesia","Asia-Pacific")
]
lines = ["Property","Casualty","Life","Health","Specialty","Marine","Cyber","Retirement"]
rows = []
for i,(country,region) in enumerate(regulated,1):
    premiums = np.random.lognormal(mean=7.0, sigma=.55)
    loss_ratio = np.clip(np.random.normal(.66,.09),.40,.90)
    rows.append({
        "entity_id":f"AGIG_{i:02d}","country":country,"region":region,
        "primary_line":random.choice(lines),
        "gross_premium_usdm":round(premiums,1),
        "claims_usdm":round(premiums*loss_ratio,1),
        "reserves_usdm":round(premiums*np.random.uniform(1.2,4.5),1),
        "reg_capital_usdm":round(premiums*np.random.uniform(.18,.42),1),
        "employees":int(max(80,premiums*np.random.uniform(.25,.65))),
        "cat_exposure":round(np.random.beta(2,3),3),
        "duration_risk":round(np.random.beta(2,3),3),
        "cyber_concentration":round(np.random.beta(2,4),3)
    })
entities = pd.DataFrame(rows)
client_countries = [f"ClientCountry_{i:03d}" for i in range(1,151)]

print("Synthetic AGIG regulated entities:", len(entities))
print("Synthetic client-country footprint:", len(client_countries))
print("Gross premium (USD bn):", round(entities.gross_premium_usdm.sum()/1000,2))
display(entities.head(10))

Synthetic AGIG regulated entities: 24
Synthetic client-country footprint: 150
Gross premium (USD bn): 34.84

,entity_id,country,region,primary_line,gross_premium_usdm,claims_usdm,reserves_usdm,reg_capital_usdm,employees,cat_exposure,duration_risk,cyber_concentration
0,AGIG_01,United Kingdom,Europe,Specialty,852.4,760.1,2582.6,156.1,246,0.258,0.493,0.153
1,AGIG_02,Ireland,Europe,Health,902.2,690.5,1618.6,257.9,283,0.273,0.750,0.208
2,AGIG_03,France,Europe,Marine,220.9,130.3,527.1,70.3,96,0.148,0.090,0.634
3,AGIG_04,Germany,Europe,Specialty,1141.3,889.8,4317.6,365.4,620,0.372,0.523,0.440
4,AGIG_05,Netherlands,Europe,Marine,2340.2,1496.0,7359.6,620.9,1294,0.269,0.386,0.015
5,AGIG_06,Spain,Europe,Life,1050.2,824.2,3287.3,352.9,405,0.043,0.473,0.355
6,AGIG_07,Italy,Europe,Specialty,589.2,396.9,1778.7,146.3,255,0.108,0.616,0.053
7,AGIG_08,Switzerland,Europe,Casualty,556.6,300.3,820.0,122.1,184,0.173,0.751,0.292
8,AGIG_09,United States,Americas,Marine,3337.2,1967.7,7118.6,1156.1,1041,0.402,0.390,0.579
9,AGIG_10,Canada,Americas,Retirement,853.7,572.6,2239.7,212.0,256,0.364,0.116,0.546

### Code Unit 3 — Jurisdiction attributes and compliance gates

The third unit creates the jurisdiction-level decision surface. Candidate locations are described by synthetic values for corporate-tax burden, withholding friction, treaty-network quality, insurance regulatory depth, capital fungibility, talent, infrastructure, legal stability, operating cost and the feasibility of maintaining genuine management substance. The tax rates are explicitly illustrative; they must not be interpreted as current statutory rates. The point is to build a reusable optimization grammar, not a tax database.

The cell introduces a crucial variable: `pillar2_floor`. For a group of the assumed scale, a design that derives its attraction from an effective rate materially below the global minimum-tax framework should be treated skeptically. The notebook therefore calculates a simplified “minimum-tax-adjusted” burden and adds a penalty where the synthetic tax advantage would otherwise depend on a sub-floor rate. This is not a GloBE calculator. Real Pillar Two computations are jurisdictional, accounting-intensive and full of detailed adjustments, exclusions, safe harbours and local implementation rules. The simplified variable exists to stop the optimization from learning the wrong lesson.

The compliance gate also requires sufficient legal stability, regulatory depth and substance capacity. These are hard feasibility screens rather than soft preferences. A location can be inexpensive and still be rejected if it cannot credibly host the functions attributed to it.

This separation between **raw economic attractiveness** and **legal feasibility** is one of the most important architectural choices in the notebook. It prevents a weighted-average score from compensating for an unacceptable compliance weakness. In institutional design, some dimensions are not tradeable. A board cannot rationally say that weak substance is acceptable because office costs are low. The code makes that principle computationally explicit.

## Infographic — Code Unit 3

In [ ]:
# CODE UNIT 3 — Synthetic jurisdiction decision attributes and hard compliance gates
countries = [x[0] for x in regulated]
region_map = dict(regulated)
rng = np.random.default_rng(SEED+3)

jur = pd.DataFrame({"country":countries})
jur["region"] = jur.country.map(region_map)
# ILLUSTRATIVE synthetic inputs — NOT current statutory tax data.
jur["synthetic_corp_tax"] = rng.uniform(.12,.32,len(jur)).round(3)
jur["withholding_friction"] = rng.uniform(.02,.14,len(jur)).round(3)
jur["treaty_network"] = rng.uniform(.55,.95,len(jur)).round(3)
jur["regulatory_depth"] = rng.uniform(.55,.98,len(jur)).round(3)
jur["capital_fungibility"] = rng.uniform(.45,.95,len(jur)).round(3)
jur["talent_infrastructure"] = rng.uniform(.55,.98,len(jur)).round(3)
jur["legal_stability"] = rng.uniform(.60,.99,len(jur)).round(3)
jur["substance_capacity"] = rng.uniform(.55,.98,len(jur)).round(3)
jur["operating_cost"] = rng.uniform(.35,.95,len(jur)).round(3)

# Give established international centers plausible synthetic institutional depth.
boost = {
"United Kingdom":(.96,.90,.96,.96),"Ireland":(.90,.87,.90,.91),
"Switzerland":(.95,.90,.93,.94),"Netherlands":(.91,.88,.92,.91),
"United States":(.96,.88,.97,.95),"Canada":(.91,.88,.92,.94),
"Singapore":(.96,.94,.97,.96),"Hong Kong":(.91,.88,.94,.91),
"Japan":(.94,.84,.94,.96),"Australia":(.92,.86,.93,.95)
}
for c,(regd,cap,talent,legal) in boost.items():
    jur.loc[jur.country==c,["regulatory_depth","capital_fungibility","talent_infrastructure","legal_stability"]] = [regd,cap,talent,legal]

PILLAR2_FLOOR = .15
jur["min_tax_adjusted"] = jur.synthetic_corp_tax.clip(lower=PILLAR2_FLOOR)
jur["subfloor_penalty"] = (PILLAR2_FLOOR-jur.synthetic_corp_tax).clip(lower=0)*3
jur["hard_feasible"] = (
    (jur.regulatory_depth>=.70) &
    (jur.legal_stability>=.72) &
    (jur.substance_capacity>=.68)
)
display(jur.sort_values(["hard_feasible","regulatory_depth"],ascending=False).head(12))

,country,region,synthetic_corp_tax,withholding_friction,treaty_network,regulatory_depth,capital_fungibility,talent_infrastructure,legal_stability,substance_capacity,operating_cost,min_tax_adjusted,subfloor_penalty,hard_feasible
15,Panama,Americas,0.146,0.075,0.942,0.963,0.720,0.916,0.777,0.935,0.386,0.150,0.012,True
0,United Kingdom,Europe,0.309,0.099,0.932,0.960,0.900,0.960,0.960,0.887,0.594,0.309,0.000,True
8,United States,Americas,0.161,0.135,0.752,0.960,0.880,0.970,0.950,0.874,0.554,0.161,0.000,True
16,Singapore,Asia-Pacific,0.266,0.134,0.601,0.960,0.940,0.970,0.960,0.895,0.860,0.266,0.000,True
22,Malaysia,Asia-Pacific,0.258,0.088,0.611,0.927,0.645,0.661,0.842,0.773,0.896,0.258,0.000,True
19,Australia,Asia-Pacific,0.223,0.087,0.861,0.920,0.860,0.930,0.950,0.867,0.835,0.223,0.000,True
9,Canada,Americas,0.215,0.064,0.808,0.910,0.880,0.920,0.940,0.800,0.634,0.215,0.000,True
2,France,Europe,0.218,0.088,0.763,0.909,0.620,0.808,0.785,0.828,0.435,0.218,0.000,True
1,Ireland,Europe,0.254,0.106,0.720,0.900,0.870,0.900,0.910,0.911,0.489,0.254,0.000,True
11,Brazil,Americas,0.124,0.055,0.608,0.880,0.454,0.731,0.889,0.721,0.512,0.150,0.078,True
6,Italy,Europe,0.228,0.055,0.944,0.843,0.514,0.820,0.794,0.954,0.653,0.228,0.000,True
5,Spain,Europe,0.207,0.037,0.911,0.832,0.824,0.913,0.790,0.812,0.524,0.207,0.000,True

### Code Unit 4 — Building the multilayer corporate and reinsurance graph

This unit converts the synthetic insurer from a table into a network. Each regulated carrier becomes a node. The London-listed parent is represented as the root owner, and edges capture ownership relationships. Additional directed edges represent synthetic reinsurance cessions among entities. These reinsurance links are weighted by ceded premium, allowing the notebook to distinguish a trivial legal connection from a financially significant dependency.

The graph is intentionally simplified but conceptually powerful. Real insurance groups contain several overlapping networks: legal ownership, cash remittances, capital support, guarantees, reinsurance, service agreements, investment management, data processing and operational dependencies. A single legal organization chart captures only one of them. Network analysis allows us to ask different questions: Which entities are central to risk transfer? Where are the bottlenecks? How concentrated is reinsurance? Which nodes connect otherwise separate regional clusters? What would happen if a proposed hub became unavailable?

The cell calculates degree-based centrality and summarizes the most connected nodes. It also computes a simple complexity measure from the number of entities and edges. Later, the proposed regional architecture can be compared with this legacy baseline.

Students should notice that the graph does not “solve tax.” Instead, it changes the representation of the institution so that tax recommendations can be evaluated in the context of risk and operations. This is a recurring theme in advanced AI systems: better reasoning often begins with a better **state representation**. If the model sees only tax rates, it will optimize tax rates. If it sees a network of policyholder obligations, risk transfers, capital and management functions, it is more likely to reason about an insurer as an insurer rather than as an abstract collection of taxable profits.

## Infographic — Code Unit 4

In [ ]:
# CODE UNIT 4 — Multilayer ownership + reinsurance graph
G = nx.MultiDiGraph()
G.add_node("AGIG_PLC", kind="parent", country="United Kingdom", region="Europe")
for _,r in entities.iterrows():
    G.add_node(r.entity_id, kind="regulated_carrier", country=r.country, region=r.region)
    G.add_edge("AGIG_PLC", r.entity_id, layer="ownership", weight=1.0)

# Synthetic internal reinsurance network: regional + cross-regional diversification.
for _, cedent in entities.iterrows():
    possible = entities[entities.entity_id != cedent.entity_id]
    same_region = possible[possible.region == cedent.region]
    targets = same_region.sample(min(2,len(same_region)), random_state=SEED+int(cedent.entity_id[-2:]))
    if np.random.rand() > .35:
        targets = pd.concat([targets, possible.sample(1, random_state=SEED+100+int(cedent.entity_id[-2:]))]).drop_duplicates("entity_id")
    for _, reinsurer in targets.iterrows():
        ceded = float(cedent.gross_premium_usdm*np.random.uniform(.03,.18))
        G.add_edge(cedent.entity_id, reinsurer.entity_id, layer="reinsurance", weight=round(ceded,1))

simple = nx.DiGraph()
for u,v,d in G.edges(data=True):
    simple.add_edge(u,v,weight=simple.get_edge_data(u,v,{}).get("weight",0)+d["weight"])
centrality = nx.degree_centrality(simple)
top_nodes = sorted(centrality.items(), key=lambda x:x[1], reverse=True)[:8]
legacy_complexity = G.number_of_nodes() + G.number_of_edges()

print("Nodes:",G.number_of_nodes(),"Edges:",G.number_of_edges(),"Legacy complexity index:",legacy_complexity)
print("Most connected nodes:",top_nodes)

plt.figure(figsize=(12,8))
pos = nx.spring_layout(simple, seed=SEED, k=.7)
nx.draw_networkx(simple,pos,with_labels=False,node_size=120,arrows=False)
plt.title("Synthetic AGIG ownership and reinsurance network")
plt.axis("off")
plt.show()

Nodes: 25 Edges: 83 Legacy complexity index: 108
Most connected nodes: [('AGIG_PLC', 1.0), ('AGIG_21', 0.4583333333333333), ('AGIG_16', 0.41666666666666663), ('AGIG_01', 0.3333333333333333), ('AGIG_07', 0.29166666666666663), ('AGIG_08', 0.29166666666666663), ('AGIG_13', 0.29166666666666663), ('AGIG_24', 0.29166666666666663)]

### Code Unit 5 — Generating candidate headquarters and regional architectures

The fifth unit defines the restructuring search space. The listed parent is allowed to remain associated with London while the optimization evaluates a manageable set of plausible headquarters and regional-platform locations. Europe, the Americas and Asia-Pacific each have their own candidate hubs. The code then forms combinations of one headquarters plus one hub per region.

Every architecture receives deterministic scores for tax friction, regulatory quality, capital mobility, substance, operating capability, legal stability and implementation complexity. A synthetic withholding matrix introduces friction when cash or service flows cross borders. Importantly, the tax objective is not “lowest corporate rate.” It combines minimum-tax-adjusted burden with cross-border friction and a penalty for weak substance. This turns the problem from rate shopping into institutional architecture.

The candidate generator also enforces regional logic: a European platform must be located in the European candidate set, and so forth. In a real restructuring, additional constraints would include existing licenses, portfolio-transfer law, employee consultation, regulatory change-of-control approvals, debt covenants, tax attributes, deferred tax, stamp duties, exit taxes and the legal feasibility of moving contracts.

The output is a dataframe in which each row is a complete architecture. This is a critical interface between deterministic optimization and the swarm. The agents will not invent arbitrary jurisdictions from scratch; they will evaluate a bounded, auditable set of alternatives. This reduces hallucination and makes dissent interpretable. The approach is analogous to generating a feasible frontier before asking experts to judge it. Language models are strongest when they reason over explicit alternatives and constraints rather than when they are asked to manufacture an entire transaction structure in unconstrained prose.

## Infographic — Code Unit 5

In [ ]:
# CODE UNIT 5 — Candidate HQ + Europe + Americas + Asia-Pacific architectures
hq_candidates = ["United Kingdom","Ireland","Switzerland","Singapore"]
eu_candidates = ["United Kingdom","Ireland","Netherlands","Switzerland","Germany"]
am_candidates = ["United States","Canada","Mexico","Brazil"]
ap_candidates = ["Singapore","Hong Kong","Japan","Australia"]

J = jur.set_index("country")

def architecture_metrics(hq,eu,am,ap):
    locs=[hq,eu,am,ap]
    x=J.loc[locs]
    tax = x.min_tax_adjusted.mean() + x.subfloor_penalty.mean()
    wh = np.mean([J.loc[a,"withholding_friction"]*0.5 + J.loc[b,"withholding_friction"]*0.5
                  for a,b in [(hq,eu),(hq,am),(hq,ap)]])
    reg = x.regulatory_depth.mean()
    cap = x.capital_fungibility.mean()
    substance = x.substance_capacity.mean()
    talent = x.talent_infrastructure.mean()
    legal = x.legal_stability.mean()
    cost = x.operating_cost.mean()
    feasible = bool(x.hard_feasible.all())
    # Lower is better. Tax matters, but cannot dominate institutional quality.
    score = (
        2.2*tax + 1.2*wh + .55*cost
        -1.35*reg -1.20*cap -1.15*substance -0.85*talent -0.90*legal
    )
    return tax,wh,reg,cap,substance,talent,legal,cost,feasible,score

records=[]
for i,(hq,eu,am,ap) in enumerate(itertools.product(hq_candidates,eu_candidates,am_candidates,ap_candidates),1):
    vals=architecture_metrics(hq,eu,am,ap)
    records.append([f"ARCH_{i:03d}",hq,eu,am,ap,*vals])

cols=["arch_id","hq","europe","americas","asia_pacific","tax_friction","withholding_friction",
      "regulatory_depth","capital_fungibility","substance","talent","legal_stability",
      "operating_cost","hard_feasible","det_score"]
architectures=pd.DataFrame(records,columns=cols)
shortlist=architectures[architectures.hard_feasible].sort_values("det_score").head(12).copy()
display(shortlist)

,arch_id,hq,europe,americas,asia_pacific,tax_friction,withholding_friction,regulatory_depth,capital_fungibility,substance,talent,legal_stability,operating_cost,hard_feasible,det_score
0,ARCH_001,United Kingdom,United Kingdom,United States,Singapore,0.26125,0.110833,0.960,0.9050,0.88575,0.9650,0.9575,0.65050,True,-4.017087
16,ARCH_017,United Kingdom,Ireland,United States,Singapore,0.24750,0.112000,0.945,0.8975,0.89175,0.9500,0.9450,0.62425,True,-4.014025
80,ARCH_081,Ireland,United Kingdom,United States,Singapore,0.24750,0.114333,0.945,0.8975,0.89175,0.9500,0.9450,0.62425,True,-4.011225
96,ARCH_097,Ireland,Ireland,United States,Singapore,0.23375,0.115500,0.930,0.8900,0.89775,0.9350,0.9325,0.59800,True,-4.008163
240,ARCH_241,Singapore,United Kingdom,United States,Singapore,0.25050,0.128333,0.960,0.9150,0.88775,0.9675,0.9575,0.71700,True,-3.999587
3,ARCH_004,United Kingdom,United Kingdom,United States,Australia,0.25050,0.103000,0.950,0.8850,0.87875,0.9550,0.9550,0.64425,True,-3.997275
256,ARCH_257,Singapore,Ireland,United States,Singapore,0.23675,0.129500,0.945,0.9075,0.89375,0.9525,0.9450,0.69075,True,-3.996525
19,ARCH_020,United Kingdom,Ireland,United States,Australia,0.23675,0.104167,0.935,0.8775,0.88475,0.9400,0.9425,0.61800,True,-3.994213
83,ARCH_084,Ireland,United Kingdom,United States,Australia,0.23675,0.106500,0.935,0.8775,0.88475,0.9400,0.9425,0.61800,True,-3.991413
99,ARCH_100,Ireland,Ireland,United States,Australia,0.22300,0.107667,0.920,0.8700,0.89075,0.9250,0.9300,0.59175,True,-3.988350
243,ARCH_244,Singapore,United Kingdom,United States,Australia,0.23975,0.120500,0.950,0.8950,0.88075,0.9575,0.9550,0.71075,True,-3.979775
259,ARCH_260,Singapore,Ireland,United States,Australia,0.22600,0.121667,0.935,0.8875,0.88675,0.9425,0.9425,0.68450,True,-3.976713

### Code Unit 6 — Defining the 50-agent expert institution

This cell creates the swarm itself. Fifty agents are assigned explicit professional roles. The distribution is intentionally heterogeneous: international tax, Pillar Two, transfer pricing, insurance regulation, solvency, actuarial risk, reinsurance, corporate law, securities law, accounting, treasury, capital management, governance, operations, technology, cyber resilience, geopolitical risk, implementation and red-team disciplines are all represented. Several roles appear more than once with different emphases, reflecting the reality that important decisions deserve independent scrutiny.

Each agent receives a mandate that tells it what to protect and what evidence to prioritize. The agents are not asked to “find the lowest tax.” Instead, they are asked to identify feasibility constraints, material risks, trade-offs and preferred architectures from their disciplinary perspective. This makes the swarm closer to an investment committee, supervisory college or multidisciplinary transaction team than to a voting contest among identical bots.

The code also assigns each role a domain weight. These weights do not determine the answer by themselves; they help the synthesis layer understand which objections are particularly material. For example, a regulatory infeasibility flagged by a solvency specialist should not be neutralized by several generic operational preferences.

A major pedagogical point is that **agent count is not intelligence**. Fifty poorly differentiated agents can create fifty correlated errors. Diversity of mandates, structured evidence, adversarial review and deterministic validation are what make the swarm useful. The notebook therefore records agent identity, domain and mandate as first-class data. In production, one would also track prompt versions, model versions, timestamps, token usage, confidence calibration and human reviewer dispositions. Those provenance elements turn an impressive demonstration into a governable decision process.

## Infographic — Code Unit 6

In [ ]:
# CODE UNIT 6 — The 50-agent multidisciplinary institution
roles = [
("International Tax Architect",5),("Pillar Two Specialist",5),("Transfer Pricing Economist",5),
("Insurance Tax Counsel",5),("Treaty & Withholding Specialist",4),("Tax Accounting Specialist",4),
("Deferred Tax Specialist",4),("Indirect Tax Specialist",3),("Tax Controversy Counsel",5),("Anti-Avoidance Red Teamer",5),
("Group Insurance Regulator",5),("European Insurance Regulator",5),("Americas Insurance Regulator",5),
("Asia-Pacific Insurance Regulator",5),("Solvency Capital Expert",5),("Resolution & Recovery Expert",5),
("Actuarial Risk Expert",5),("Life Insurance Actuary",4),("P&C Catastrophe Actuary",4),("Cyber Insurance Expert",4),
("Reinsurance Structuring Expert",5),("Reinsurance Counterparty Expert",4),("Capital Markets Lawyer",5),
("UK Listing & Governance Lawyer",5),("Corporate Reorganization Lawyer",5),("Employment & Mobility Counsel",4),
("Data Privacy Counsel",4),("Sanctions & Financial Crime Counsel",5),("Chief Financial Officer",5),
("Group Treasurer",5),("Capital Allocation Expert",5),("ALM Specialist",4),("Investment Portfolio Expert",4),
("IFRS Accounting Expert",5),("Internal Audit Expert",4),("Enterprise Risk Officer",5),
("Operational Resilience Expert",5),("Cybersecurity Architect",4),("Data Architecture Expert",4),
("AI Governance Expert",4),("Global Operations Executive",4),("Insurance Distribution Expert",4),
("Claims Operations Expert",4),("Underwriting Governance Expert",5),("Talent & Location Strategist",3),
("Geopolitical Risk Analyst",4),("Implementation Program Director",4),("Policyholder Protection Advocate",5),
("Independent Board Director",5),("Synthesis Red Team Chair",5)
]
assert len(roles)==50

agents=[]
for i,(role,weight) in enumerate(roles,1):
    agents.append({
        "agent_id":f"A{i:02d}",
        "role":role,
        "domain_weight":weight,
        "mandate":f"Evaluate the proposed architecture primarily through the lens of {role}; identify hard constraints, second-order effects, and evidence required before implementation."
    })
agents=pd.DataFrame(agents)
display(agents)

,agent_id,role,domain_weight,mandate
0,A01,International Tax Architect,5,Evaluate the proposed architecture primarily t...
1,A02,Pillar Two Specialist,5,Evaluate the proposed architecture primarily t...
2,A03,Transfer Pricing Economist,5,Evaluate the proposed architecture primarily t...
3,A04,Insurance Tax Counsel,5,Evaluate the proposed architecture primarily t...
4,A05,Treaty & Withholding Specialist,4,Evaluate the proposed architecture primarily t...
5,A06,Tax Accounting Specialist,4,Evaluate the proposed architecture primarily t...
6,A07,Deferred Tax Specialist,4,Evaluate the proposed architecture primarily t...
7,A08,Indirect Tax Specialist,3,Evaluate the proposed architecture primarily t...
8,A09,Tax Controversy Counsel,5,Evaluate the proposed architecture primarily t...
9,A10,Anti-Avoidance Red Teamer,5,Evaluate the proposed architecture primarily t...
10,A11,Group Insurance Regulator,5,Evaluate the proposed architecture primarily t...
11,A12,European Insurance Regulator,5,Evaluate the proposed architecture primarily t...
12,A13,Americas Insurance Regulator,5,Evaluate the proposed architecture primarily t...
13,A14,Asia-Pacific Insurance Regulator,5,Evaluate the proposed architecture primarily t...
14,A15,Solvency Capital Expert,5,Evaluate the proposed architecture primarily t...
15,A16,Resolution & Recovery Expert,5,Evaluate the proposed architecture primarily t...
16,A17,Actuarial Risk Expert,5,Evaluate the proposed architecture primarily t...
17,A18,Life Insurance Actuary,4,Evaluate the proposed architecture primarily t...
18,A19,P&C Catastrophe Actuary,4,Evaluate the proposed architecture primarily t...
19,A20,Cyber Insurance Expert,4,Evaluate the proposed architecture primarily t...
20,A21,Reinsurance Structuring Expert,5,Evaluate the proposed architecture primarily t...
21,A22,Reinsurance Counterparty Expert,4,Evaluate the proposed architecture primarily t...
22,A23,Capital Markets Lawyer,5,Evaluate the proposed architecture primarily t...
23,A24,UK Listing & Governance Lawyer,5,Evaluate the proposed architecture primarily t...
24,A25,Corporate Reorganization Lawyer,5,Evaluate the proposed architecture primarily t...
25,A26,Employment & Mobility Counsel,4,Evaluate the proposed architecture primarily t...
26,A27,Data Privacy Counsel,4,Evaluate the proposed architecture primarily t...
27,A28,Sanctions & Financial Crime Counsel,5,Evaluate the proposed architecture primarily t...
28,A29,Chief Financial Officer,5,Evaluate the proposed architecture primarily t...
29,A30,Group Treasurer,5,Evaluate the proposed architecture primarily t...
30,A31,Capital Allocation Expert,5,Evaluate the proposed architecture primarily t...
31,A32,ALM Specialist,4,Evaluate the proposed architecture primarily t...
32,A33,Investment Portfolio Expert,4,Evaluate the proposed architecture primarily t...
33,A34,IFRS Accounting Expert,5,Evaluate the proposed architecture primarily t...
34,A35,Internal Audit Expert,4,Evaluate the proposed architecture primarily t...
35,A36,Enterprise Risk Officer,5,Evaluate the proposed architecture primarily t...
36,A37,Operational Resilience Expert,5,Evaluate the proposed architecture primarily t...
37,A38,Cybersecurity Architect,4,Evaluate the proposed architecture primarily t...
38,A39,Data Architecture Expert,4,Evaluate the proposed architecture primarily t...
39,A40,AI Governance Expert,4,Evaluate the proposed architecture primarily t...
40,A41,Global Operations Executive,4,Evaluate the proposed architecture primarily t...
41,A42,Insurance Distribution Expert,4,Evaluate the proposed architecture primarily t...
42,A43,Claims Operations Expert,4,Evaluate the proposed architecture primarily t...
43,A44,Underwriting Governance Expert,5,Evaluate the proposed architecture primarily t...
44,A45,Talent & Location Strategist,3,Evaluate the proposed architecture primarily t...
45,A46,Geopolitical Risk Analyst,4,Evaluate the proposed architecture primarily t...
46,A47,Implementation Program Director,4,Evaluate the proposed architecture primarily t...
47,A48,Policyholder Protection Advocate,5,Evaluate the proposed architecture primarily t...
48,A49,Independent Board Director,5,Evaluate the proposed architecture primarily t...
49,A50,Synthesis Red Team Chair,5,Evaluate the proposed architecture primarily t...

### Code Unit 7 — Claude Sonnet 5 deliberation with structured outputs

This unit provides the live LLM interface. When `LIVE_LLM=False`, it produces deterministic proxy opinions so that the notebook remains executable without an API key or cost. When live mode is enabled, each of the 50 specialists receives the same compact evidence pack: the synthetic group profile, the leading deterministic architectures, the compliance principles and its own mandate. The Anthropic API is called with the configured Claude Sonnet 5 model.

The prompt requires a JSON object containing the agent’s preferred architecture identifier, confidence, principal rationale, hard constraints, principal risk, and any objection to the deterministic ranking. This is deliberately narrower than a traditional consulting prompt. Structured outputs allow the subsequent code to aggregate results, count objections and preserve dissent.

The system instruction is compliance-first. It prohibits recommendations that depend on concealment, sham substance, artificial profit shifting, false transfer pricing or evasion. It also reminds the agent that local insurance entities may need to remain because the target architecture refers to principal regional platforms rather than the literal disappearance of regulated carriers. These constraints are not cosmetic. They define the legitimate design space.

The deterministic fallback is also pedagogically useful. It demonstrates that the orchestration layer should not collapse when the model is unavailable. The proxy opinions use domain-specific perturbations of the candidate scores, creating disagreement without pretending that the fallback is expert legal advice.

Students can inspect `agent_opinions` to see whether the swarm converges or fragments. A fragmented result is informative: it indicates that the problem contains unresolved trade-offs or insufficient evidence. The notebook does not force unanimity. In complex institutional decisions, visible disagreement can be more valuable than a falsely precise consensus.

## Infographic — Code Unit 7

In [24]:
# ============================================================
# CODE UNIT 7 — LIVE 50-AGENT CLAUDE SONNET 5 DELIBERATION
#
# DESIGN
# ------------------------------------------------------------
# • 50 genuine Claude Sonnet 5 specialist calls
# • Lowest reasoning effort
# • Native JSON-schema structured outputs
# • No deterministic fallback
# • Sequential execution for auditability
# • One production-path canary before launching the swarm
# • Request IDs retained
# • Checkpoint saved after every successful agent
# ============================================================

import time
import json
import pandas as pd
import numpy as np
from datetime import datetime

from anthropic import Anthropic


# ============================================================
# 1. CONFIGURATION
# ============================================================

MODEL = "claude-sonnet-5"

# Lowest reasoning effort.
REASONING_EFFORT = "low"

# This budget covers reasoning + final structured response.
MAX_TOKENS = 6000

if not LIVE_LLM:
    raise RuntimeError(
        "LIVE_LLM=False. "
        "Set LIVE_LLM=True in Code Unit 1."
    )

if not ANTHROPIC_API_KEY:
    raise RuntimeError(
        "ANTHROPIC_API_KEY was not found. "
        "Add it to Google Colab Secrets."
    )

client = Anthropic(
    api_key=ANTHROPIC_API_KEY
)

print("=" * 84)
print("AGIG — LIVE 50-AGENT CLAUDE SONNET 5 INSTITUTION")
print("=" * 84)
print(f"Model:                {MODEL}")
print(f"Reasoning effort:     {REASONING_EFFORT.upper()}")
print(f"Max tokens/call:      {MAX_TOKENS:,}")
print("Structured output:    JSON Schema")
print("Execution:            Sequential")
print("Deterministic fallback: NONE")
print(f"Specialist agents:    {len(agents)}")
print("=" * 84)


# ============================================================
# 2. STRUCTURED OUTPUT SCHEMA
# ============================================================

AGENT_SCHEMA = {

    "type": "object",

    "properties": {

        "preferred_arch_id": {
            "type": "string"
        },

        "confidence": {
            "type": "number"
        },

        "rationale": {
            "type": "string"
        },

        "hard_constraints": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "principal_risk": {
            "type": "string"
        },

        "objection": {
            "type": "string"
        },

        "required_evidence": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "second_order_effect": {
            "type": "string"
        },

        "professional_conclusion": {
            "type": "string"
        }
    },

    "required": [
        "preferred_arch_id",
        "confidence",
        "rationale",
        "hard_constraints",
        "principal_risk",
        "objection",
        "required_evidence",
        "second_order_effect",
        "professional_conclusion"
    ],

    "additionalProperties": False
}


# ============================================================
# 3. RESPONSE HELPERS
# ============================================================

def get_text_block(message):
    """
    Sonnet 5 may return thinking blocks followed by a text block.
    Extract the final visible text block rather than assuming
    content[0] is text.
    """

    text_blocks = []

    for block in message.content:

        if getattr(block, "type", None) == "text":

            text = getattr(
                block,
                "text",
                None
            )

            if text:
                text_blocks.append(
                    text
                )

    if not text_blocks:

        block_types = [
            getattr(
                block,
                "type",
                "?"
            )
            for block in message.content
        ]

        raise RuntimeError(
            "Claude returned no text block. "
            f"Block types={block_types}; "
            f"stop_reason={getattr(message, 'stop_reason', None)}; "
            f"usage={getattr(message, 'usage', None)}"
        )

    return "\n".join(
        text_blocks
    ).strip()


def validate_completion(
    message,
    agent_id
):
    """
    Fail loudly if Claude exhausts its budget or otherwise
    fails to produce a complete response.
    """

    stop_reason = getattr(
        message,
        "stop_reason",
        None
    )

    block_types = [
        getattr(
            block,
            "type",
            "?"
        )
        for block in message.content
    ]

    if stop_reason == "max_tokens":

        raise RuntimeError(
            f"{agent_id}: Claude exhausted MAX_TOKENS "
            f"before completing its answer. "
            f"Blocks={block_types}; "
            f"usage={getattr(message, 'usage', None)}"
        )

    if stop_reason == "refusal":

        raise RuntimeError(
            f"{agent_id}: Claude refused the request."
        )

    if "text" not in block_types:

        raise RuntimeError(
            f"{agent_id}: no final text block. "
            f"Blocks={block_types}; "
            f"stop_reason={stop_reason}"
        )

    return stop_reason


# ============================================================
# 4. STRUCTURED-OUTPUT PREFLIGHT
# ============================================================

PREFLIGHT_SCHEMA = {

    "type": "object",

    "properties": {

        "status": {
            "type": "string"
        },

        "model_test": {
            "type": "string"
        }
    },

    "required": [
        "status",
        "model_test"
    ],

    "additionalProperties": False
}


print()
print("=" * 84)
print("STEP 1 — CLAUDE SONNET 5 STRUCTURED-OUTPUT PREFLIGHT")
print("=" * 84)

preflight_start = time.time()

preflight = client.messages.create(

    model=MODEL,

    max_tokens=1000,

    output_config={

        "effort": "low",

        "format": {

            "type": "json_schema",

            "schema": PREFLIGHT_SCHEMA
        }
    },

    messages=[
        {
            "role": "user",
            "content": (
                "This is an API preflight. "
                "Set status to 'ready' and "
                "model_test to 'successful'."
            )
        }
    ]
)

validate_completion(
    preflight,
    "PREFLIGHT"
)

preflight_text = get_text_block(
    preflight
)

preflight_result = json.loads(
    preflight_text
)

if preflight_result.get(
    "status"
) != "ready":

    raise RuntimeError(
        f"Unexpected preflight response: "
        f"{preflight_result}"
    )

print("✓ REAL CLAUDE API CALL")
print("✓ TEXT OUTPUT RECEIVED")
print("✓ JSON SCHEMA SATISFIED")
print("✓ JSON PARSED SUCCESSFULLY")
print(
    "✓ Request ID:",
    getattr(
        preflight,
        "_request_id",
        None
    )
)
print(
    "✓ Stop reason:",
    getattr(
        preflight,
        "stop_reason",
        None
    )
)
print(
    "✓ Latency:",
    round(
        time.time() -
        preflight_start,
        2
    ),
    "seconds"
)
print(
    "✓ Response:",
    preflight_result
)

print()
print("PREFLIGHT PASSED.")


# ============================================================
# 5. PREPARE THE EIGHT ARCHITECTURES
# ============================================================

top_candidates_df = (
    shortlist
    .head(8)
    .copy()
)

top_candidates = (
    top_candidates_df
    .to_dict("records")
)

VALID_ARCHITECTURES = set(
    top_candidates_df[
        "arch_id"
    ].tolist()
)

print()
print("Candidate architectures:")

for architecture in sorted(
    VALID_ARCHITECTURES
):

    print(
        "  ",
        architecture
    )


# ============================================================
# 6. COMPANY EVIDENCE
# ============================================================

company_summary = {

    "company":
        "Synthetic Atlas Global Insurance Group plc (AGIG)",

    "listing":
        "London-listed synthetic global insurer",

    "regulated_entities":
        int(
            len(
                entities
            )
        ),

    "client_country_footprint":
        int(
            len(
                client_countries
            )
        ),

    "gross_premium_usdm":
        round(
            float(
                entities[
                    "gross_premium_usdm"
                ].sum()
            ),
            1
        ),

    "claims_usdm":
        round(
            float(
                entities[
                    "claims_usdm"
                ].sum()
            ),
            1
        ),

    "reserves_usdm":
        round(
            float(
                entities[
                    "reserves_usdm"
                ].sum()
            ),
            1
        ),

    "regulatory_capital_usdm":
        round(
            float(
                entities[
                    "reg_capital_usdm"
                ].sum()
            ),
            1
        ),

    "employees":
        int(
            entities[
                "employees"
            ].sum()
        ),

    "business_lines":
        sorted(
            entities[
                "primary_line"
            ]
            .unique()
            .tolist()
        ),

    "regions": [
        "Europe",
        "Americas",
        "Asia-Pacific"
    ]
}


# ============================================================
# 7. INSURANCE-RISK EVIDENCE
# ============================================================

risk_summary = {

    "mean_catastrophe_exposure":
        round(
            float(
                entities[
                    "cat_exposure"
                ].mean()
            ),
            3
        ),

    "maximum_catastrophe_exposure":
        round(
            float(
                entities[
                    "cat_exposure"
                ].max()
            ),
            3
        ),

    "mean_duration_risk":
        round(
            float(
                entities[
                    "duration_risk"
                ].mean()
            ),
            3
        ),

    "mean_cyber_concentration":
        round(
            float(
                entities[
                    "cyber_concentration"
                ].mean()
            ),
            3
        )
}


# ============================================================
# 8. NETWORK EVIDENCE
# ============================================================

network_summary = {

    "nodes":
        int(
            G.number_of_nodes()
        ),

    "edges":
        int(
            G.number_of_edges()
        ),

    "legacy_complexity_index":
        int(
            legacy_complexity
        ),

    "most_connected_nodes": [

        {
            "entity":
                str(
                    node
                ),

            "degree_centrality":
                round(
                    float(
                        score
                    ),
                    3
                )
        }

        for node, score
        in top_nodes
    ]
}


# ============================================================
# 9. JURISDICTION EVIDENCE
# ============================================================

jurisdiction_summary = (

    jur[
        [
            "country",
            "region",
            "synthetic_corp_tax",
            "withholding_friction",
            "treaty_network",
            "regulatory_depth",
            "capital_fungibility",
            "talent_infrastructure",
            "legal_stability",
            "substance_capacity",
            "operating_cost",
            "min_tax_adjusted",
            "subfloor_penalty",
            "hard_feasible"
        ]
    ]

    .round(3)

    .to_dict(
        "records"
    )
)


# ============================================================
# 10. GOVERNING PRINCIPLES
# ============================================================

principles = [

    (
        "Compliance with applicable tax, insurance, "
        "securities, corporate and accounting law "
        "is a hard constraint."
    ),

    (
        "No architecture may rely upon tax evasion, "
        "concealment, sham substance, artificial profit "
        "shifting, false transfer pricing or fictitious "
        "insurance risk transfer."
    ),

    (
        "Pillar Two and jurisdictional minimum-tax "
        "consequences are economically material."
    ),

    (
        "Local regulated insurance entities remain where "
        "licensing, policyholder protection, capital "
        "requirements or supervisory expectations make "
        "them necessary."
    ),

    (
        "Risk ownership must align with people, capital, "
        "underwriting authority, actuarial capability, "
        "claims governance, systems and genuine "
        "decision-making."
    ),

    (
        "Tax efficiency cannot override regulatory "
        "feasibility or economic substance."
    ),

    (
        "The architecture should be defensible to tax "
        "authorities, insurance supervisors, auditors, "
        "shareholders and the board."
    ),

    (
        "Jurisdictional tax and regulatory variables "
        "in this experiment are synthetic inputs."
    )
]


# ============================================================
# 11. COMMON EVIDENCE PACK
# ============================================================

evidence = {

    "company_summary":
        company_summary,

    "insurance_risk_summary":
        risk_summary,

    "network_summary":
        network_summary,

    "candidate_architectures":
        top_candidates,

    "jurisdiction_attributes":
        jurisdiction_summary,

    "governing_principles":
        principles
}


# ============================================================
# 12. SPECIALIST PROFESSIONAL LENSES
# ============================================================

def specialist_focus(role):

    r = role.lower()


    if any(
        x in r
        for x in [
            "tax",
            "pillar",
            "transfer",
            "treaty"
        ]
    ):

        return """
Focus on international tax architecture, Pillar Two,
minimum-tax effects, withholding leakage, treaty access,
transfer pricing, functions-assets-risks, economic
substance, intercompany transactions, tax controversy
and durability under tax-authority scrutiny.
"""


    if any(
        x in r
        for x in [
            "regulator",
            "solvency",
            "resolution",
            "policyholder"
        ]
    ):

        return """
Focus on insurance supervision, regulatory capital,
group supervision, local solvency, policyholder
protection, capital fungibility, recovery and resolution,
supervisory colleges and regulatory credibility.
"""


    if any(
        x in r
        for x in [
            "actuary",
            "actuarial",
            "underwriting",
            "claims"
        ]
    ):

        return """
Focus on insurance risk ownership, underwriting
authority, claims volatility, reserves, catastrophe
exposure, duration risk, actuarial governance and the
economics of insurance liabilities.
"""


    if "reinsurance" in r:

        return """
Focus on genuine risk transfer, reinsurance economics,
diversification, counterparty concentration, ceded
premium, capital relief, regulatory recognition and
actual reinsurance decision-making.
"""


    if any(
        x in r
        for x in [
            "lawyer",
            "counsel",
            "legal",
            "listing"
        ]
    ):

        return """
Focus on corporate law, enforceability, governance,
London listing obligations, legal-entity restructuring,
contract and portfolio transfers, employment, privacy,
sanctions, financial crime and execution risk.
"""


    if any(
        x in r
        for x in [
            "financial",
            "treasurer",
            "capital",
            "alm",
            "portfolio",
            "accounting",
            "audit",
            "cfo"
        ]
    ):

        return """
Focus on distributable cash, capital allocation,
liquidity, ALM, trapped capital, IFRS consequences,
treasury flows, financing flexibility, capital
efficiency and shareholder economics.
"""


    if any(
        x in r
        for x in [
            "cyber",
            "data",
            "ai governance"
        ]
    ):

        return """
Focus on technology architecture, data localization,
operational resilience, cybersecurity, AI governance,
systems integration and safe operation of the regional
architecture.
"""


    if any(
        x in r
        for x in [
            "operations",
            "distribution",
            "talent"
        ]
    ):

        return """
Focus on operational feasibility, insurance distribution,
claims servicing, talent availability, management
location, infrastructure and genuine operating substance.
"""


    if any(
        x in r
        for x in [
            "geopolitical",
            "implementation",
            "board",
            "red team",
            "enterprise risk"
        ]
    ):

        return """
Take an enterprise-wide adversarial perspective.
Challenge hidden assumptions, geopolitical risk,
implementation risk, governance weaknesses,
concentration and second-order consequences.
"""


    return """
Evaluate the proposed architectures rigorously from your
professional discipline. Identify material constraints,
trade-offs, failure modes and evidence gaps.
"""


# ============================================================
# 13. LIVE CLAUDE SPECIALIST FUNCTION
# ============================================================

def call_live_agent(
    agent_row
):

    agent_id = str(
        agent_row[
            "agent_id"
        ]
    )

    role = str(
        agent_row[
            "role"
        ]
    )

    mandate = str(
        agent_row[
            "mandate"
        ]
    )

    domain_weight = int(
        agent_row[
            "domain_weight"
        ]
    )

    focus = specialist_focus(
        role
    )


    prompt = f"""
You are specialist agent {agent_id}.

PROFESSIONAL ROLE
{role}

MANDATE
{mandate}

SPECIALIST LENS
{focus}


You are one member of a 50-specialist multidisciplinary
institution advising the board of a synthetic London-listed
global insurance group.

The target institutional architecture consists of:

                 GLOBAL PARENT / HQ
                         |
          --------------------------------
          |              |               |
       EUROPE         AMERICAS      ASIA-PACIFIC
       PLATFORM        PLATFORM        PLATFORM
          |              |               |
       LOCAL REGULATED INSURANCE ENTITIES


COMMON EVIDENCE PACK

{json.dumps(
    evidence,
    indent=2,
    default=str
)}


TASK

Independently evaluate the eight candidate architectures
from your professional perspective.

Do not simply select the architecture with the lowest
deterministic score.

Where relevant, consider:

1. Economic substance.
2. Pillar Two and minimum-tax consequences.
3. Regulatory credibility.
4. Capital fungibility and trapped capital.
5. Insurance risk ownership.
6. Reinsurance architecture.
7. Transfer pricing.
8. Withholding and treaty friction.
9. Operational feasibility.
10. Governance and decision rights.
11. Accounting consequences.
12. Implementation complexity.
13. Policyholder protection.
14. Second-order consequences.
15. Evidence required before implementation.

You may disagree with the deterministic ranking.

A structure with somewhat greater tax friction may be
superior if it materially improves regulation, capital,
substance, governance or operations.

Conversely, an apparently tax-efficient structure must
be rejected if the corresponding functions, people,
capital, decision rights and risk ownership cannot
genuinely exist there.


COMPLIANCE BOUNDARY

Reject any architecture whose advantage depends upon:

- tax evasion;
- concealment;
- sham substance;
- artificial profit shifting;
- false transfer pricing;
- fictitious risk transfer;
- disregard of policyholder obligations;
- disregard of insurance regulation;
- attribution of profits or risks to entities that do not
  perform the corresponding economic functions.

The tax and regulatory variables supplied in the evidence
pack are synthetic experimental inputs.

Select exactly ONE of the eight candidate architecture IDs.

Provide a confidence between 0 and 1.

The strongest objection should be an argument AGAINST
your own preferred architecture.

The required evidence should identify what would need
to be established before a real board could rely upon
the recommendation.
"""


    start = time.time()


    # ========================================================
    # CLAUDE SONNET 5
    #
    # LOWEST REASONING EFFORT
    # NATIVE STRUCTURED OUTPUT
    # ========================================================

    message = client.messages.create(

        model=MODEL,

        max_tokens=MAX_TOKENS,

        output_config={

            "effort":
                REASONING_EFFORT,

            "format": {

                "type":
                    "json_schema",

                "schema":
                    AGENT_SCHEMA
            }
        },

        system=(
            "You are a senior professional adviser "
            "participating in a board-level multidisciplinary "
            "institutional-design exercise. "
            "Reason efficiently. Focus on the material issues "
            "from your assigned professional discipline. "
            "Be precise, skeptical and compliance-first."
        ),

        messages=[
            {
                "role":
                    "user",

                "content":
                    prompt
            }
        ]
    )


    latency = (
        time.time() -
        start
    )


    # ========================================================
    # COMPLETION VALIDATION
    # ========================================================

    stop_reason = validate_completion(
        message,
        agent_id
    )


    # ========================================================
    # STRUCTURED OUTPUT
    # ========================================================

    response_text = get_text_block(
        message
    )

    result = json.loads(
        response_text
    )


    # ========================================================
    # SEMANTIC VALIDATION
    # ========================================================

    preferred = str(
        result[
            "preferred_arch_id"
        ]
    )


    if preferred not in VALID_ARCHITECTURES:

        raise ValueError(
            f"{agent_id} selected invalid architecture "
            f"{preferred}. Valid candidates are "
            f"{sorted(VALID_ARCHITECTURES)}."
        )


    confidence = float(
        result[
            "confidence"
        ]
    )


    if not (
        0.0 <= confidence <= 1.0
    ):

        raise ValueError(
            f"{agent_id} returned invalid confidence "
            f"{confidence}."
        )


    # ========================================================
    # PROVENANCE
    # ========================================================

    result.update({

        "agent_id":
            agent_id,

        "role":
            role,

        "domain_weight":
            domain_weight,

        "latency_seconds":
            round(
                latency,
                2
            ),

        "execution_mode":
            "LIVE_CLAUDE",

        "model":
            MODEL,

        "reasoning_effort":
            REASONING_EFFORT,

        "request_id":
            getattr(
                message,
                "_request_id",
                None
            ),

        "stop_reason":
            stop_reason
    })


    return result


# ============================================================
# 14. PRODUCTION-PATH CANARY
#
# This tests A01 using exactly the same function and API
# configuration that will be used for all 50 agents.
# ============================================================

print()
print()
print("=" * 84)
print("STEP 2 — PRODUCTION CANARY: AGENT A01")
print("=" * 84)

canary_agent = (
    agents.iloc[0]
)

canary_result = call_live_agent(
    canary_agent
)

print()
print("✓ CANARY PASSED")
print(
    "Agent:          ",
    canary_result[
        "agent_id"
    ]
)
print(
    "Role:           ",
    canary_result[
        "role"
    ]
)
print(
    "Architecture:   ",
    canary_result[
        "preferred_arch_id"
    ]
)
print(
    "Confidence:     ",
    round(
        canary_result[
            "confidence"
        ],
        3
    )
)
print(
    "Latency:        ",
    canary_result[
        "latency_seconds"
    ],
    "seconds"
)
print(
    "Stop reason:    ",
    canary_result[
        "stop_reason"
    ]
)
print(
    "Request ID:     ",
    canary_result[
        "request_id"
    ]
)

print()
print(
    "Professional conclusion:"
)

print(
    canary_result[
        "professional_conclusion"
    ]
)

print()
print(
    "✓ Real Claude call"
)
print(
    "✓ Native structured output"
)
print(
    "✓ Valid candidate architecture"
)
print(
    "✓ Valid confidence"
)
print(
    "✓ Complete specialist assessment"
)

print("=" * 84)
print(
    "CANARY SUCCESSFUL — LAUNCHING FULL SWARM"
)
print("=" * 84)


# ============================================================
# 15. RUN THE 50-AGENT INSTITUTION
#
# A01 canary result is reused.
# We DO NOT charge/call A01 a second time.
# ============================================================

opinions = [
    canary_result
]

total_start = time.time()


print()
print(
    "A01 already completed successfully in the canary."
)

print(
    "Beginning A02–A50..."
)


for position in range(
    1,
    len(agents)
):

    agent = (
        agents.iloc[
            position
        ]
    )

    agent_number = (
        position + 1
    )


    print()
    print(
        "-" * 84
    )

    print(
        f"AGENT {agent_number:02d}/50 "
        f"| {agent['agent_id']} "
        f"| {agent['role']}"
    )

    print(
        "Calling Claude Sonnet 5..."
    )


    try:

        result = call_live_agent(
            agent
        )


    except Exception as error:

        print()
        print(
            "✗ LIVE CLAUDE CALL FAILED"
        )

        print(
            f"Agent: "
            f"{agent['agent_id']} — "
            f"{agent['role']}"
        )

        print(
            f"Error type: "
            f"{type(error).__name__}"
        )

        print(
            f"Error: "
            f"{error}"
        )

        print()
        print(
            "SWARM EXECUTION STOPPED."
        )

        print(
            "No deterministic proxy was substituted."
        )

        print(
            f"Successfully completed live agents: "
            f"{len(opinions)}"
        )

        raise


    opinions.append(
        result
    )


    # ========================================================
    # CHECKPOINT AFTER EACH SUCCESS
    # ========================================================

    checkpoint = pd.DataFrame(
        opinions
    )


    checkpoint.to_csv(
        "AGIG_LIVE_SWARM_CHECKPOINT.csv",
        index=False
    )


    with open(
        "AGIG_LIVE_SWARM_CHECKPOINT.json",
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            opinions,
            f,
            indent=2,
            ensure_ascii=False,
            default=str
        )


    print(
        "✓ LIVE CLAUDE RESPONSE"
    )

    print(
        "  Architecture:",
        result[
            "preferred_arch_id"
        ]
    )

    print(
        "  Confidence:",
        f"{result['confidence']:.2f}"
    )

    print(
        "  Latency:",
        f"{result['latency_seconds']:.2f}s"
    )

    print(
        "  Stop reason:",
        result[
            "stop_reason"
        ]
    )

    print(
        "  Request ID:",
        result[
            "request_id"
        ]
    )


    time.sleep(
        0.35
    )


# ============================================================
# 16. FINAL DATASET
# ============================================================

agent_opinions = pd.DataFrame(
    opinions
)

elapsed = (
    time.time() -
    total_start
)


# ============================================================
# 17. EXPERIMENTAL INTEGRITY
# ============================================================

if len(
    agent_opinions
) != 50:

    raise RuntimeError(
        f"Experiment incomplete: "
        f"{len(agent_opinions)}/50 agents."
    )


if not (
    agent_opinions[
        "execution_mode"
    ] == "LIVE_CLAUDE"
).all():

    raise RuntimeError(
        "Experiment contains non-live observations."
    )


if agent_opinions[
    "request_id"
].isna().any():

    raise RuntimeError(
        "At least one specialist response lacks "
        "an Anthropic request ID."
    )


# ============================================================
# 18. WEIGHTED SUPPORT
# ============================================================

agent_opinions[
    "weighted_support"
] = (

    agent_opinions[
        "domain_weight"
    ]

    *

    agent_opinions[
        "confidence"
    ]
)


preference_table = (

    agent_opinions

    .groupby(
        "preferred_arch_id"
    )

    .agg(

        votes=(
            "agent_id",
            "count"
        ),

        weighted_support=(
            "weighted_support",
            "sum"
        ),

        mean_confidence=(
            "confidence",
            "mean"
        ),

        mean_domain_weight=(
            "domain_weight",
            "mean"
        ),

        mean_latency_seconds=(
            "latency_seconds",
            "mean"
        )
    )

    .sort_values(
        [
            "weighted_support",
            "votes"
        ],
        ascending=False
    )
)


# ============================================================
# 19. FINAL AUDIT REPORT
# ============================================================

print()
print()
print("=" * 84)
print("50-AGENT LIVE DELIBERATION COMPLETE")
print("=" * 84)

print(
    f"Total specialist agents:       "
    f"{len(agent_opinions)}"
)

print(
    f"Successful Claude calls:       "
    f"{len(agent_opinions)}"
)

print(
    "Deterministic fallbacks:       0"
)

print(
    f"Reasoning effort:              "
    f"{REASONING_EFFORT.upper()}"
)

print(
    f"Responses with request IDs:    "
    f"{agent_opinions['request_id'].notna().sum()}"
)

print(
    f"Mean specialist confidence:    "
    f"{agent_opinions['confidence'].mean():.3f}"
)

print(
    f"Mean response latency:         "
    f"{agent_opinions['latency_seconds'].mean():.2f} seconds"
)

print(
    f"Execution time A02–A50:        "
    f"{elapsed / 60:.2f} minutes"
)

print("=" * 84)


# ============================================================
# 20. ARCHITECTURE PREFERENCE TABLE
# ============================================================

print()
print(
    "ARCHITECTURE PREFERENCE TABLE"
)
print(
    "-" * 84
)

display(
    preference_table
)


# ============================================================
# 21. SPECIALIST OPINIONS
# ============================================================

print()
print(
    "FIRST 15 SPECIALIST OPINIONS"
)
print(
    "-" * 84
)

display(

    agent_opinions[
        [
            "agent_id",
            "role",
            "preferred_arch_id",
            "confidence",
            "domain_weight",
            "weighted_support",
            "latency_seconds",
            "principal_risk",
            "objection"
        ]
    ]

    .head(
        15
    )
)


# ============================================================
# 22. BOARD-LEVEL CONCLUSIONS
# ============================================================

print()
print(
    "=" * 84
)
print(
    "50 SPECIALIST BOARD CONCLUSIONS"
)
print(
    "=" * 84
)


for _, row in agent_opinions.iterrows():

    print()

    print(
        f"{row['agent_id']} — "
        f"{row['role']}"
    )

    print(
        f"Preferred architecture: "
        f"{row['preferred_arch_id']} "
        f"| Confidence: "
        f"{row['confidence']:.2f}"
    )

    print(
        row[
            "professional_conclusion"
        ]
    )

    print(
        "-" * 84
    )


# ============================================================
# 23. EXPORT
# ============================================================

csv_filename = (
    "AGIG_50_AGENT_LIVE_CLAUDE_OPINIONS.csv"
)

json_filename = (
    "AGIG_50_AGENT_LIVE_CLAUDE_OPINIONS.json"
)

summary_filename = (
    "AGIG_50_AGENT_LIVE_CLAUDE_SUMMARY.csv"
)


agent_opinions.to_csv(
    csv_filename,
    index=False
)


with open(
    json_filename,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        opinions,
        f,
        indent=2,
        ensure_ascii=False,
        default=str
    )


preference_table.to_csv(
    summary_filename
)


print()
print(
    "=" * 84
)
print(
    "EXPERIMENT VALIDATED"
)
print(
    "=" * 84
)

print(
    "50 genuine Claude Sonnet 5 specialist responses."
)

print(
    "0 deterministic substitutions."
)

print(
    f"Reasoning effort: "
    f"{REASONING_EFFORT.upper()}."
)

print()
print(
    "Files created:"
)

print(
    f"  {csv_filename}"
)

print(
    f"  {json_filename}"
)

print(
    f"  {summary_filename}"
)

print()
print(
    "agent_opinions is ready for Code Unit 8."
)

====================================================================================
AGIG — LIVE 50-AGENT CLAUDE SONNET 5 INSTITUTION
====================================================================================
Model:                claude-sonnet-5
Reasoning effort:     LOW
Max tokens/call:      6,000
Structured output:    JSON Schema
Execution:            Sequential
Deterministic fallback: NONE
Specialist agents:    50
====================================================================================

====================================================================================
STEP 1 — CLAUDE SONNET 5 STRUCTURED-OUTPUT PREFLIGHT
====================================================================================
✓ REAL CLAUDE API CALL
✓ TEXT OUTPUT RECEIVED
✓ JSON SCHEMA SATISFIED
✓ JSON PARSED SUCCESSFULLY
✓ Request ID: req_011CfKM5AxushzRGCH971Zz6
✓ Stop reason: end_turn
✓ Latency: 2.11 seconds
✓ Response: {'status': 'ready', 'model_test': 'successful'}

PREFLIGHT PASSED.

Candidate architectures:
   ARCH_001
   ARCH_004
   ARCH_017
   ARCH_020
   ARCH_081
   ARCH_097
   ARCH_241
   ARCH_257


====================================================================================
STEP 2 — PRODUCTION CANARY: AGENT A01
====================================================================================

✓ CANARY PASSED
Agent:           A01
Role:            International Tax Architect
Architecture:    ARCH_001
Confidence:      0.62
Latency:         20.55 seconds
Stop reason:     end_turn
Request ID:      req_011CfKM5KVsNkFP1u89Yq6a5

Professional conclusion:
ARCH_001 is preferred on substance, governance and controversy-durability grounds rather than pure tax efficiency, but the board should commission full Pillar Two and FAR-based transfer pricing modeling before final adoption, and should not dismiss ARCH_097 without a documented comparison of EU regulatory passporting and Ireland-substance considerations.

✓ Real Claude call
✓ Native structured output
✓ Valid candidate architecture
✓ Valid confidence
✓ Complete specialist assessment
====================================================================================
CANARY SUCCESSFUL — LAUNCHING FULL SWARM
====================================================================================

A01 already completed successfully in the canary.
Beginning A02–A50...

------------------------------------------------------------------------------------
AGENT 02/50 | A02 | Pillar Two Specialist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_017
  Confidence: 0.62
  Latency: 22.23s
  Stop reason: end_turn
  Request ID: req_011CfKM6qNzhHadrcg1Ky5Fj

------------------------------------------------------------------------------------
AGENT 03/50 | A03 | Transfer Pricing Economist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_004
  Confidence: 0.62
  Latency: 21.32s
  Stop reason: end_turn
  Request ID: req_011CfKM8W8fK524aCXP5d6Dr

------------------------------------------------------------------------------------
AGENT 04/50 | A04 | Insurance Tax Counsel
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 20.80s
  Stop reason: end_turn
  Request ID: req_011CfKMA6iJwiwEnHE1ZBpca

------------------------------------------------------------------------------------
AGENT 05/50 | A05 | Treaty & Withholding Specialist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 21.60s
  Stop reason: end_turn
  Request ID: req_011CfKMBfDh5sec7Av4rQ5wL

------------------------------------------------------------------------------------
AGENT 06/50 | A06 | Tax Accounting Specialist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_097
  Confidence: 0.62
  Latency: 20.00s
  Stop reason: end_turn
  Request ID: req_011CfKMDH31M5BBVn4mFy9Ly

------------------------------------------------------------------------------------
AGENT 07/50 | A07 | Deferred Tax Specialist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_017
  Confidence: 0.62
  Latency: 23.15s
  Stop reason: end_turn
  Request ID: req_011CfKMEn3YjQMCD2urXPYt1

------------------------------------------------------------------------------------
AGENT 08/50 | A08 | Indirect Tax Specialist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 21.64s
  Stop reason: end_turn
  Request ID: req_011CfKMGWh7sPU4iTT2ESXd2

------------------------------------------------------------------------------------
AGENT 09/50 | A09 | Tax Controversy Counsel
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 23.16s
  Stop reason: end_turn
  Request ID: req_011CfKMJ8beJmwGcWG9jwgrd

------------------------------------------------------------------------------------
AGENT 10/50 | A10 | Anti-Avoidance Red Teamer
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_004
  Confidence: 0.58
  Latency: 20.42s
  Stop reason: end_turn
  Request ID: req_011CfKMKsA1XJQxGW4vK8MeA

------------------------------------------------------------------------------------
AGENT 11/50 | A11 | Group Insurance Regulator
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 20.00s
  Stop reason: end_turn
  Request ID: req_011CfKMMPxhVFXyqhsgNT1ky

------------------------------------------------------------------------------------
AGENT 12/50 | A12 | European Insurance Regulator
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 20.30s
  Stop reason: end_turn
  Request ID: req_011CfKMNtzUXaPgbZygWr3yf

------------------------------------------------------------------------------------
AGENT 13/50 | A13 | Americas Insurance Regulator
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 22.43s
  Stop reason: end_turn
  Request ID: req_011CfKMQRNNSRmAi8MNwnBTw

------------------------------------------------------------------------------------
AGENT 14/50 | A14 | Asia-Pacific Insurance Regulator
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_241
  Confidence: 0.62
  Latency: 21.11s
  Stop reason: end_turn
  Request ID: req_011CfKMS6nyAW5VMdeVbSzCS

------------------------------------------------------------------------------------
AGENT 15/50 | A15 | Solvency Capital Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 23.52s
  Stop reason: end_turn
  Request ID: req_011CfKMTgbF4wXUtthbRcR5y

------------------------------------------------------------------------------------
AGENT 16/50 | A16 | Resolution & Recovery Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 20.96s
  Stop reason: end_turn
  Request ID: req_011CfKMVSiNN6mA6wCMYjEWV

------------------------------------------------------------------------------------
AGENT 17/50 | A17 | Actuarial Risk Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.37s
  Stop reason: end_turn
  Request ID: req_011CfKMX1piZywxcEvftFtk1

------------------------------------------------------------------------------------
AGENT 18/50 | A18 | Life Insurance Actuary
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 18.31s
  Stop reason: end_turn
  Request ID: req_011CfKMYU8HM7ByDfcKQqCmN

------------------------------------------------------------------------------------
AGENT 19/50 | A19 | P&C Catastrophe Actuary
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 24.49s
  Stop reason: end_turn
  Request ID: req_011CfKMZquzSHuqDBP6j77NR

------------------------------------------------------------------------------------
AGENT 20/50 | A20 | Cyber Insurance Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 21.70s
  Stop reason: end_turn
  Request ID: req_011CfKMbgDtKXggHN8jkAdTu

------------------------------------------------------------------------------------
AGENT 21/50 | A21 | Reinsurance Structuring Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 20.00s
  Stop reason: end_turn
  Request ID: req_011CfKMdJUVnGJC9kYtw7WbD

------------------------------------------------------------------------------------
AGENT 22/50 | A22 | Reinsurance Counterparty Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.58
  Latency: 16.25s
  Stop reason: end_turn
  Request ID: req_011CfKMeoYFZTFeELftPEA9U

------------------------------------------------------------------------------------
AGENT 23/50 | A23 | Capital Markets Lawyer
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 17.39s
  Stop reason: end_turn
  Request ID: req_011CfKMg2ZNDgaendr33McuT

------------------------------------------------------------------------------------
AGENT 24/50 | A24 | UK Listing & Governance Lawyer
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.13s
  Stop reason: end_turn
  Request ID: req_011CfKMhLRBwbkDjYgTdrunv

------------------------------------------------------------------------------------
AGENT 25/50 | A25 | Corporate Reorganization Lawyer
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.13s
  Stop reason: end_turn
  Request ID: req_011CfKMimmhvenv4u1bKdnQ3

------------------------------------------------------------------------------------
AGENT 26/50 | A26 | Employment & Mobility Counsel
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 18.54s
  Stop reason: end_turn
  Request ID: req_011CfKMkCvKkJngsycoVg1L4

------------------------------------------------------------------------------------
AGENT 27/50 | A27 | Data Privacy Counsel
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 22.29s
  Stop reason: end_turn
  Request ID: req_011CfKMmbuDLBwdtNAtizszB

------------------------------------------------------------------------------------
AGENT 28/50 | A28 | Sanctions & Financial Crime Counsel
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 25.53s
  Stop reason: end_turn
  Request ID: req_011CfKMoGt2agGhZ8W1xKNRK

------------------------------------------------------------------------------------
AGENT 29/50 | A29 | Chief Financial Officer
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.90s
  Stop reason: end_turn
  Request ID: req_011CfKMqBW8M1sRE3A3Bhs72

------------------------------------------------------------------------------------
AGENT 30/50 | A30 | Group Treasurer
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 17.56s
  Stop reason: end_turn
  Request ID: req_011CfKMrg9LxnQjW2sz1z6U6

------------------------------------------------------------------------------------
AGENT 31/50 | A31 | Capital Allocation Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_241
  Confidence: 0.58
  Latency: 17.27s
  Stop reason: end_turn
  Request ID: req_011CfKMsziKhTexpAuoP5Msg

------------------------------------------------------------------------------------
AGENT 32/50 | A32 | ALM Specialist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 17.97s
  Stop reason: end_turn
  Request ID: req_011CfKMuHyRnN81r6B27d9j7

------------------------------------------------------------------------------------
AGENT 33/50 | A33 | Investment Portfolio Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 18.12s
  Stop reason: end_turn
  Request ID: req_011CfKMveawXyouavz41ws43

------------------------------------------------------------------------------------
AGENT 34/50 | A34 | IFRS Accounting Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.29s
  Stop reason: end_turn
  Request ID: req_011CfKMx1jTKCX8kEgREcPcn

------------------------------------------------------------------------------------
AGENT 35/50 | A35 | Internal Audit Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.03s
  Stop reason: end_turn
  Request ID: req_011CfKMyTjuwcTHzKAyPUbmF

------------------------------------------------------------------------------------
AGENT 36/50 | A36 | Enterprise Risk Officer
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 20.40s
  Stop reason: end_turn
  Request ID: req_011CfKMztirpDkbDHzjtSch6

------------------------------------------------------------------------------------
AGENT 37/50 | A37 | Operational Resilience Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.58
  Latency: 19.77s
  Stop reason: end_turn
  Request ID: req_011CfKN2RU52rRTLdaznorRd

------------------------------------------------------------------------------------
AGENT 38/50 | A38 | Cybersecurity Architect
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 24.53s
  Stop reason: end_turn
  Request ID: req_011CfKN3uY4Do8Yvg3ukqxFp

------------------------------------------------------------------------------------
AGENT 39/50 | A39 | Data Architecture Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.60
  Latency: 19.96s
  Stop reason: end_turn
  Request ID: req_011CfKN5k1sgbiB3XpijyhrN

------------------------------------------------------------------------------------
AGENT 40/50 | A40 | AI Governance Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.60
  Latency: 18.98s
  Stop reason: end_turn
  Request ID: req_011CfKN7Ety4hSEHqGUqHYAd

------------------------------------------------------------------------------------
AGENT 41/50 | A41 | Global Operations Executive
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 21.04s
  Stop reason: end_turn
  Request ID: req_011CfKN8fdXqUpwR4nTfjrot

------------------------------------------------------------------------------------
AGENT 42/50 | A42 | Insurance Distribution Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 21.53s
  Stop reason: end_turn
  Request ID: req_011CfKNAFCf9H6tYrpyGFWRx

------------------------------------------------------------------------------------
AGENT 43/50 | A43 | Claims Operations Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 17.77s
  Stop reason: end_turn
  Request ID: req_011CfKNBrj7QZSSrqXUSfvKE

------------------------------------------------------------------------------------
AGENT 44/50 | A44 | Underwriting Governance Expert
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.70s
  Stop reason: end_turn
  Request ID: req_011CfKNDCFPbCjhhDQqKz6GX

------------------------------------------------------------------------------------
AGENT 45/50 | A45 | Talent & Location Strategist
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.68
  Latency: 18.73s
  Stop reason: end_turn
  Request ID: req_011CfKNEg8DDsYNrC75hUdcu

------------------------------------------------------------------------------------
AGENT 46/50 | A46 | Geopolitical Risk Analyst
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.17s
  Stop reason: end_turn
  Request ID: req_011CfKNG5mJ6Ze1MS34uiXLy

------------------------------------------------------------------------------------
AGENT 47/50 | A47 | Implementation Program Director
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.58
  Latency: 20.22s
  Stop reason: end_turn
  Request ID: req_011CfKNHXGzGeCg3rHaNcz7f

------------------------------------------------------------------------------------
AGENT 48/50 | A48 | Policyholder Protection Advocate
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 19.77s
  Stop reason: end_turn
  Request ID: req_011CfKNK3CquDdfBDAwbzBkg

------------------------------------------------------------------------------------
AGENT 49/50 | A49 | Independent Board Director
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.62
  Latency: 20.29s
  Stop reason: end_turn
  Request ID: req_011CfKNLXRkVFWS1GeegYfZ1

------------------------------------------------------------------------------------
AGENT 50/50 | A50 | Synthesis Red Team Chair
Calling Claude Sonnet 5...
✓ LIVE CLAUDE RESPONSE
  Architecture: ARCH_001
  Confidence: 0.58
  Latency: 22.29s
  Stop reason: end_turn
  Request ID: req_011CfKNN3dEKEGeiGHYhMaLP


====================================================================================
50-AGENT LIVE DELIBERATION COMPLETE
====================================================================================
Total specialist agents:       50
Successful Claude calls:       50
Deterministic fallbacks:       0
Reasoning effort:              LOW
Responses with request IDs:    50
Mean specialist confidence:    0.616
Mean response latency:         20.37 seconds
Execution time A02–A50:        16.93 minutes
====================================================================================

ARCHITECTURE PREFERENCE TABLE
------------------------------------------------------------------------------------

,votes,weighted_support,mean_confidence,mean_domain_weight,mean_latency_seconds
preferred_arch_id,,,,,
ARCH_001,43,118.96,0.616744,4.488372,20.304884
ARCH_004,2,6.00,0.600000,5.000000,20.870000
ARCH_241,2,6.00,0.600000,5.000000,19.190000
ARCH_017,2,5.58,0.620000,4.500000,22.690000
ARCH_097,1,2.48,0.620000,4.000000,20.000000

FIRST 15 SPECIALIST OPINIONS
------------------------------------------------------------------------------------

,agent_id,role,preferred_arch_id,confidence,domain_weight,weighted_support,latency_seconds,principal_risk,objection
0,A01,International Tax Architect,ARCH_001,0.62,5,3.10,20.55,Locating HQ and Europe platform both in the UK...,A rigorous tax architect could argue ARCH_097 ...
1,A02,Pillar Two Specialist,ARCH_017,0.62,5,3.10,22.23,Using Ireland as the European hub while UK rem...,"An objector could argue ARCH_001 (UK HQ, UK Eu..."
2,A03,Transfer Pricing Economist,ARCH_004,0.62,5,3.10,21.32,The det_score differentials across all eight c...,ARCH_004's reliance on Australia as APAC platf...
3,A04,Insurance Tax Counsel,ARCH_001,0.62,5,3.10,20.80,"A UK-headquartered, London-listed group delibe...",ARCH_001 is not the lowest deterministic-frict...
4,A05,Treaty & Withholding Specialist,ARCH_001,0.62,4,2.48,21.60,"That the UK/US/Singapore platform structure, w...",An informed colleague could argue ARCH_017 or ...
5,A06,Tax Accounting Specialist,ARCH_097,0.62,4,2.48,20.00,Moving group HQ to Ireland while retaining a U...,ARCH_097's tax friction advantage may not surv...
6,A07,Deferred Tax Specialist,ARCH_017,0.62,4,2.48,23.15,That the Ireland-Europe/UK-HQ split is challen...,A rigorous critic would argue ARCH_017 is a co...
7,A08,Indirect Tax Specialist,ARCH_001,0.62,3,1.86,21.64,UK's relatively higher headline corporate tax ...,"ARCH_017 (UK HQ, Ireland Europe platform) achi..."
8,A09,Tax Controversy Counsel,ARCH_001,0.62,5,3.10,23.16,"Under Pillar Two, UK top-up taxation combined ...",A rigorous transfer pricing challenge could ar...
9,A10,Anti-Avoidance Red Teamer,ARCH_004,0.58,5,2.90,20.42,A structure combining a UK/Ireland double-hop ...,ARCH_004's selection of Australia over Singapo...
10,A11,Group Insurance Regulator,ARCH_001,0.62,5,3.10,20.00,Regional platform structures (Europe/Americas/...,ARCH_001's reliance on a UK HQ construct assum...
11,A12,European Insurance Regulator,ARCH_001,0.62,5,3.10,20.30,Introducing a regional 'platform' layer betwee...,ARCH_001 retains UK as both HQ and European pl...
12,A13,Americas Insurance Regulator,ARCH_001,0.62,5,3.10,22.43,Placing a Europe/HQ-led group structure with a...,A regulator could argue ARCH_001's marginal ca...
13,A14,Asia-Pacific Insurance Regulator,ARCH_241,0.62,5,3.10,21.11,Relocating group HQ to Singapore (ARCH_241) cr...,A Singapore HQ is a major structural change re...
14,A15,Solvency Capital Expert,ARCH_001,0.62,5,3.10,23.52,Consolidating group capital management functio...,The strongest objection to ARCH_001 is that co...

====================================================================================
50 SPECIALIST BOARD CONCLUSIONS
====================================================================================

A01 — International Tax Architect
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is preferred on substance, governance and controversy-durability grounds rather than pure tax efficiency, but the board should commission full Pillar Two and FAR-based transfer pricing modeling before final adoption, and should not dismiss ARCH_097 without a documented comparison of EU regulatory passporting and Ireland-substance considerations.
------------------------------------------------------------------------------------

A02 — Pillar Two Specialist
Preferred architecture: ARCH_017 | Confidence: 0.62
ARCH_017 is an acceptable and reasonably defensible architecture from a Pillar Two and international tax perspective provided genuine, auditable economic substance is built and maintained in the Irish hub commensurate with profits booked there; however the board should commission independent functional and Pillar Two impact studies before finalizing, and should retain ARCH_001 as a lower-complexity fallback if Irish substance cannot be robustly evidenced.
------------------------------------------------------------------------------------

A03 — Transfer Pricing Economist
Preferred architecture: ARCH_004 | Confidence: 0.62
ARCH_004 is preferable not because it minimizes a composite score but because it aligns platform jurisdictions with genuinely available substance, robust treaty networks and manageable Pillar Two exposure without introducing incremental holding-company layers (Ireland/Singapore HQ variants) whose primary appeal is tax friction reduction unsupported by proportionate functional relocation; however, this recommendation is contingent on the required evidence being obtained, particularly functional substance verification in Australia versus Singapore for APAC risk ownership, before the board can rely on it.
------------------------------------------------------------------------------------

A04 — Insurance Tax Counsel
Preferred architecture: ARCH_001 | Confidence: 0.62
From an insurance tax counsel perspective, ARCH_001 is the most defensible architecture given it aligns HQ tax residence with the group's actual UK-centered governance and listing, minimizes controversy risk versus alternatives that appear tax-efficient only by relocating headline entities, and satisfies economic substance and Pillar Two durability tests better than marginally cheaper alternatives — subject to full transfer pricing, substance and treaty documentation before board reliance.
------------------------------------------------------------------------------------

A05 — Treaty & Withholding Specialist
Preferred architecture: ARCH_001 | Confidence: 0.62
From a treaty and withholding perspective, ARCH_001 is preferred not because it minimizes tax friction but because it best aligns economic substance, treaty access and regulatory credibility with real decision rights, subject to mandatory transfer pricing, Pillar Two and FAR documentation being completed before implementation; the board should not rely on the deterministic score differential of roughly 2-4 percentage points of friction against Ireland-based alternatives as decisive without this evidence.
------------------------------------------------------------------------------------

A06 — Tax Accounting Specialist
Preferred architecture: ARCH_097 | Confidence: 0.62
From a tax accounting perspective, ARCH_097 is the most defensible of the eight on pure friction and substance-capacity metrics, but its net benefit over ARCH_001 is marginal and contingent on the group being able to demonstrate genuine relocation of central management and control and decision rights to Ireland; absent that proof, the board should prefer the UK-HQ variant (ARCH_001) to avoid residency and controversy risk exceeding the tax savings.
------------------------------------------------------------------------------------

A07 — Deferred Tax Specialist
Preferred architecture: ARCH_017 | Confidence: 0.62
From a deferred tax and international tax architecture perspective, ARCH_017 is defensible only if substance is genuinely built and maintained in Ireland commensurate with the profit allocation, and if the board commits to entity-level Pillar Two modelling before implementation; absent that, ARCH_001 (UK-only Europe platform) is a safer, marginally less tax-efficient but structurally simpler alternative that should be kept as fallback.
------------------------------------------------------------------------------------

A08 — Indirect Tax Specialist
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is an acceptable and defensible base case from an indirect tax and international tax controversy standpoint due to its treaty strength, substance and regulatory credibility, but the board should commission a comparative real-cost Pillar Two and withholding-corridor study against ARCH_017 before finalizing, since the tax friction differential may not be justified once genuine Irish substance capacity for the European platform is verified.
------------------------------------------------------------------------------------

A09 — Tax Controversy Counsel
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is preferable from a tax controversy standpoint primarily because UK's superior treaty network and regulatory credibility reduce withholding leakage and audit risk relative to Ireland-HQ alternatives, but board reliance is conditional on completing FAR analysis, Pillar Two modelling and TP documentation before implementation; absent that evidence, no architecture in this set can be certified durable under tax-authority scrutiny.
------------------------------------------------------------------------------------

A10 — Anti-Avoidance Red Teamer
Preferred architecture: ARCH_004 | Confidence: 0.58
Reject the lowest-friction architectures (ARCH_097, ARCH_081, ARCH_017) as presenting unacceptable optics and audit risk from an Ireland-heavy, multi-hop treaty topology; recommend ARCH_004 as the most defensible structure balancing tax efficiency against anti-avoidance scrutiny, subject to the evidence pack above being independently verified before board sign-off.
------------------------------------------------------------------------------------

A11 — Group Insurance Regulator
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is defensible as the strongest starting point for group insurance supervision purposes given its superior regulatory depth, capital fungibility and legal stability scores, but board reliance is conditional on obtaining explicit supervisory college consensus and legal-entity-level solvency validation across all 24 regulated entities before implementation; absent this evidence, the modeled capital fungibility advantage should be treated as unproven rather than assured.
------------------------------------------------------------------------------------

A12 — European Insurance Regulator
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is acceptable as a starting architecture given its superior regulatory depth and capital fungibility scores, but the board should treat EU group-supervision recognition, capital fungibility validation, and RRP self-sufficiency as pre-conditions rather than assumptions, and should monitor for near-term supervisory pressure toward an EU-domiciled intermediate platform.
------------------------------------------------------------------------------------

A13 — Americas Insurance Regulator
Preferred architecture: ARCH_001 | Confidence: 0.62
From an Americas insurance regulatory standpoint, ARCH_001 is acceptable only if the group can evidence robust, independently verifiable US-entity capital adequacy, genuine local risk ownership, and a workable supervisory college arrangement between UK/Irish and US regulators; absent that evidence, none of the eight architectures should be treated as materially differentiated on tax-efficiency grounds alone, since Americas policyholder protection outcomes hinge on local substance, not on HQ or Europe/APAC domicile choices.
------------------------------------------------------------------------------------

A14 — Asia-Pacific Insurance Regulator
Preferred architecture: ARCH_241 | Confidence: 0.62
ARCH_241 is defensible on APAC-specific supervisory coherence grounds but carries material, poorly-evidenced group-supervision transition risk; I would only endorse it conditional on documented pre-clearance from the primary home supervisor and MAS on lead-supervisor status, absent which ARCH_001 (UK HQ, Singapore APAC platform) is the safer default that still secures adequate APAC regulatory outcomes.
------------------------------------------------------------------------------------

A15 — Solvency Capital Expert
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is provisionally acceptable on solvency-capital grounds due to superior regulatory depth, capital fungibility and legal stability, but board reliance must be conditioned on obtaining supervisory equivalence confirmations and local capital adequacy stress-testing per entity; absent this evidence, ARCH_097 (Ireland HQ/Europe) should be held as a credible EU-supervisory-recognition contingency given its comparable metrics and improved EU passporting posture.
------------------------------------------------------------------------------------

A16 — Resolution & Recovery Expert
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is the preferred candidate on resolution and recovery grounds due to its combination of highest capital fungibility, regulatory depth and substance scores among feasible candidates, anchored in three jurisdictions with mature insurance resolution regimes, but the board must not treat the deterministic score differential as material; a full legal-entity capital and RRP mapping exercise plus explicit host-supervisor engagement is required before implementation, and the architecture should be revisited if local supervisors indicate this design will trigger material local capital add-ons or subsidiarisation demands.
------------------------------------------------------------------------------------

A17 — Actuarial Risk Expert
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is actuarially preferable primarily on regulatory depth, legal stability and talent proximity to real underwriting/claims/actuarial functions, but the recommendation should be treated as provisional pending granular reserve, reinsurance-treaty and capital-fungibility evidence; the tax-friction differential versus ARCH_097 is not decisive from a pure insurance-risk perspective and should be resolved jointly with tax and regulatory specialists before board sign-off.
------------------------------------------------------------------------------------

A18 — Life Insurance Actuary
Preferred architecture: ARCH_001 | Confidence: 0.62
From an actuarial risk-ownership and capital adequacy standpoint, ARCH_001 provides the most credible foundation for genuine group actuarial governance, catastrophe capital pooling and reserve oversight, but implementation must be conditioned on demonstrable real risk transfer, local solvency compliance and stress-tested capital fungibility before board reliance.
------------------------------------------------------------------------------------

A19 — P&C Catastrophe Actuary
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is an acceptable, actuarially defensible choice given its superior regulatory depth, legal stability and capital fungibility supporting group-wide catastrophe risk governance, but the board should not treat the deterministic score as decisive; it must commission peril-level cat modelling, reserve adequacy testing and capital fungibility stress tests across all candidates before final selection, and should probe whether Ireland-anchored alternatives (ARCH_097) could deliver equivalent substance at lower friction without compromising policyholder protection.
------------------------------------------------------------------------------------

A20 — Cyber Insurance Expert
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is acceptable as a jurisdictional shell from a cyber-resilience perspective given its concentration in mature regulatory/talent environments, but the architecture cannot be approved on jurisdictional choice alone — board sign-off must be conditioned on independent verification of network segmentation, data localization compliance, and a remediation plan addressing the extreme centrality/legacy-complexity risk evident in the network data, none of which the deterministic score captures.
------------------------------------------------------------------------------------

A21 — Reinsurance Structuring Expert
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is the preferred architecture on reinsurance-structuring grounds due to superior regulatory depth, capital fungibility, and treaty-network access supporting credible internal reinsurance pooling, but the board must commission independent risk-transfer testing, counterparty concentration analysis, and multi-jurisdictional regulatory pre-clearance before implementation, as the deterministic score differential versus Ireland/Singapore-hub alternatives is too narrow to be decisive without this qualitative evidence.
------------------------------------------------------------------------------------

A22 — Reinsurance Counterparty Expert
Preferred architecture: ARCH_001 | Confidence: 0.58
ARCH_001 is preferred on reinsurance counterparty grounds due to superior regulatory credibility, capital fungibility and market recognition supporting genuine risk transfer, but the board must obtain detailed treaty-level evidence and regulatory capital relief confirmation before relying on this structure, and should reassess if UK-EU reinsurance equivalence deteriorates.
------------------------------------------------------------------------------------

A23 — Capital Markets Lawyer
Preferred architecture: ARCH_001 | Confidence: 0.62
From a capital markets and corporate law perspective, ARCH_001 is the most defensible architecture because it preserves the integrity of the existing London listing and regulatory relationships while supporting genuine regional decision-making, but implementation must be preceded by entity-by-entity legal, regulatory and portfolio-transfer feasibility analysis before the board can rely on it.
------------------------------------------------------------------------------------

A24 — UK Listing & Governance Lawyer
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is the most defensible architecture from a UK listing and governance perspective because it minimises redomiciliation risk to the London listing while allowing genuine regional substance to be built in the US and Singapore, subject to rigorous evidence on regulatory pre-clearance, policyholder protection and Pillar Two compliance being obtained before implementation.
------------------------------------------------------------------------------------

A25 — Corporate Reorganization Lawyer
Preferred architecture: ARCH_001 | Confidence: 0.62
From a corporate reorganization and enforceability perspective, ARCH_001 is the most defensible baseline because it preserves the listed parent's legal seat and regulatory relationships while allocating regional platforms to jurisdictions with genuine existing substance; however, board approval should be conditioned on a full legal-entity rationalization plan, Part VII/local transfer feasibility studies, and Pillar Two impact modelling before implementation.”}}
------------------------------------------------------------------------------------

A26 — Employment & Mobility Counsel
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is preferred on employment and mobility grounds because it preserves the existing UK-anchored employment and governance base, minimizing transfer, consultation, and re-authorisation burdens, but this preference is conditional on further evidence that the UK Europe platform can sustainably support the group's EU-facing regulated entities without a future forced relocation.
------------------------------------------------------------------------------------

A27 — Data Privacy Counsel
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is acceptable from a data privacy standpoint provided that regional platform consolidation is implemented with clear controller/processor delineation, validated cross-border transfer mechanisms for EU-to-US flows, and jurisdiction-specific data residency compliance; however, board approval should be conditioned on completion of a full pre-implementation data protection impact assessment (DPIA) covering all three regional hubs before any centralization of underwriting, claims or cyber-risk data processing occurs.
------------------------------------------------------------------------------------

A28 — Sanctions & Financial Crime Counsel
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is acceptable from a sanctions and financial crime standpoint, but the architecture question is necessary rather than sufficient: platform jurisdiction selection does not itself resolve the group's sanctions and financial-crime risk, which is a function of business-line exposure (Marine, Cyber, Specialty), 150-country client footprint and intragroup reinsurance flows. Board approval should be conditioned on completion of the group-wide financial crime risk assessment and confirmation of adequately resourced, independent compliance functions at each hub before implementation proceeds.
------------------------------------------------------------------------------------

A29 — Chief Financial Officer
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is preferred on capital efficiency, distributable cash and regulatory credibility grounds despite not being the deterministic top scorer; however, the board should commission a full trapped-capital and Pillar Two sensitivity analysis before final commitment, and treasury should retain optionality to revisit HQ domicile if fungibility assumptions prove materially inaccurate post-implementation.
------------------------------------------------------------------------------------

A30 — Group Treasurer
Preferred architecture: ARCH_001 | Confidence: 0.62
ARCH_001 is preferred on treasury and capital efficiency grounds due to its superior capital fungibility, regulatory depth and operational simplicity, but the board must commission jurisdiction-specific solvency, dividend capacity and Pillar Two cash-tax analysis before reliance, and should preserve optionality to revisit the Ireland-hub alternatives if EU regulatory friction on cross-border capital flows increases materially.
------------------------------------------------------------------------------------

A31 — Capital Allocation Expert
Preferred architecture: ARCH_241 | Confidence: 0.58
ARCH_241 is preferred on pure capital fungibility and regulatory depth grounds, but only if quantitative treasury modelling confirms the fungibility benefit exceeds the incremental tax, withholding, operating cost and redomiciliation transition costs; absent that evidence, ARCH_001 (UK HQ) remains a credible fallback given lower disruption to capital markets access and shareholder base.
------------------------------------------------------------------------------------

A32 — ALM Specialist
Preferred architecture: ARCH_001 | Confidence: 0.62

### Code Unit 8 — Aggregation, dissent and red-team challenge

The eighth unit converts fifty individual judgments into an institutional view. It counts architecture preferences, weights them by agent confidence and domain materiality, and merges this signal with the deterministic candidate table. The result is not simple majority rule. An architecture can attract many votes yet still fail if it violates a hard feasibility gate or accumulates severe objections from regulation, solvency, legal or tax-compliance specialists.

The red-team layer searches for characteristic failure modes: excessive reliance on a low synthetic tax rate, weak management substance, poor capital fungibility, low regulatory depth, high withholding friction, excessive implementation complexity and concentration of critical functions. Each candidate receives a red-team penalty and an explicit list of flags. This is important because optimization systems are often better at finding loopholes in their objective function than at understanding institutional intent. Red teaming asks, in effect, “How could this score look good while the real-world structure is bad?”

The aggregation code preserves dissent. It reports both the leading consensus and the number of material flags. A board should be able to see that a recommendation was selected despite a particular objection and then decide whether additional evidence is required.

This cell illustrates a general pattern for autonomous finance: **proposal and criticism should be separate computational roles**. The same mechanism that generates an idea should not be the only mechanism that validates it. Independent deterministic tests, specialist objections and red-team prompts reduce common-mode failure.

In a real tax restructuring, the red-team stage would be far more extensive. It would include jurisdiction-specific anti-avoidance rules, controlled foreign company rules, transfer-pricing documentation, permanent-establishment analysis, beneficial ownership, treaty entitlement, exit taxation, insurance premium taxes, VAT/GST, deferred tax, accounting impacts, sanctions, regulatory approvals, policyholder communications and implementation sequencing. Here, those complexities are represented as categories rather than legal conclusions.

## Infographic — Code Unit 8

In [25]:
# CODE UNIT 8 — Weighted consensus, dissent and deterministic red-team penalties
weights = agents.set_index("agent_id").domain_weight.to_dict()
agent_opinions["weight"] = agent_opinions.agent_id.map(weights)
agent_opinions["weighted_support"] = agent_opinions["weight"] * agent_opinions["confidence"].astype(float)

support = agent_opinions.groupby("preferred_arch_id").agg(
    votes=("agent_id","count"),
    weighted_support=("weighted_support","sum"),
    mean_confidence=("confidence","mean")
).reset_index()

evaluated = shortlist.merge(support,left_on="arch_id",right_on="preferred_arch_id",how="left")
evaluated[["votes","weighted_support","mean_confidence"]] = evaluated[["votes","weighted_support","mean_confidence"]].fillna(0)

def red_team(row):
    flags=[]
    if row["substance"] < .75: flags.append("substance")
    if row["capital_fungibility"] < .68: flags.append("capital_fungibility")
    if row["regulatory_depth"] < .78: flags.append("regulatory_depth")
    if row["withholding_friction"] > .10: flags.append("cross_border_friction")
    if row["tax_friction"] < .15: flags.append("minimum_tax_dependency")
    if row["legal_stability"] < .80: flags.append("legal_stability")
    return flags

evaluated["red_flags"]=evaluated.apply(red_team,axis=1)
evaluated["red_penalty"]=evaluated.red_flags.map(lambda x:.18*len(x))
maxsup=max(evaluated.weighted_support.max(),1)
evaluated["consensus_bonus"]=evaluated.weighted_support/maxsup
evaluated["final_score"]=evaluated.det_score + evaluated.red_penalty - .35*evaluated.consensus_bonus
evaluated=evaluated.sort_values("final_score")
display(evaluated[["arch_id","hq","europe","americas","asia_pacific","votes","weighted_support","red_flags","final_score"]])

,arch_id,hq,europe,americas,asia_pacific,votes,weighted_support,red_flags,final_score
0,ARCH_001,United Kingdom,United Kingdom,United States,Singapore,43.0,118.96,[cross_border_friction],-4.187087
1,ARCH_017,United Kingdom,Ireland,United States,Singapore,2.0,5.58,[cross_border_friction],-3.850442
4,ARCH_241,Singapore,United Kingdom,United States,Singapore,2.0,6.00,[cross_border_friction],-3.837240
3,ARCH_097,Ireland,Ireland,United States,Singapore,1.0,2.48,[cross_border_friction],-3.835459
5,ARCH_004,United Kingdom,United Kingdom,United States,Australia,2.0,6.00,[cross_border_friction],-3.834928
2,ARCH_081,Ireland,United Kingdom,United States,Singapore,0.0,0.00,[cross_border_friction],-3.831225
6,ARCH_257,Singapore,Ireland,United States,Singapore,0.0,0.00,[cross_border_friction],-3.816525
7,ARCH_020,United Kingdom,Ireland,United States,Australia,0.0,0.00,[cross_border_friction],-3.814213
8,ARCH_084,Ireland,United Kingdom,United States,Australia,0.0,0.00,[cross_border_friction],-3.811412
9,ARCH_100,Ireland,Ireland,United States,Australia,0.0,0.00,[cross_border_friction],-3.808350
10,ARCH_244,Singapore,United Kingdom,United States,Australia,0.0,0.00,[cross_border_friction],-3.799775
11,ARCH_260,Singapore,Ireland,United States,Australia,0.0,0.00,[cross_border_friction],-3.796712

### Code Unit 9 — Selecting the constrained architecture and designing the operating model

This unit selects the highest-ranked architecture that survives the hard compliance gates and red-team threshold. It then translates a row of scores into a proposed organizational pattern: a listed parent and group headquarters, three regional platforms, retained local regulated carriers where legally required, regional reinsurance coordination, shared-service boundaries and explicit substance requirements.

The key concept is **functional alignment**. If a regional platform is described as the risk owner, it must have the people, board authority, actuarial capability, underwriting governance, claims oversight, capital and systems necessary to own that risk. If a service center performs routine functions, its remuneration should be designed consistently with arm’s-length principles. If a reinsurance center assumes material insurance risk, its capital and decision-making must correspond to that risk. The notebook therefore emits an “architecture contract” describing what must be true for the recommendation to remain valid.

The cell also estimates the change in synthetic structural friction relative to the legacy network. This is not a forecast of tax savings. It is an index combining entity complexity, cross-border friction and administrative duplication. The distinction is intentional: for a modern multinational subject to minimum-tax regimes, the board may obtain more durable value from simplification, capital mobility and governance than from chasing headline tax-rate differentials.

The recommended design is consequently a **hypothesis for professional validation**, not an executable transaction plan. The output includes explicit conditions precedent: current local tax opinions, Pillar Two modeling, transfer-pricing functional analysis, actuarial and solvency work, regulator engagement, securities-law review and board approval. This makes the final answer useful without pretending that synthetic data can replace legal facts.

## Infographic — Code Unit 9

In [26]:
# CODE UNIT 9 — Select architecture and translate it into an institutional operating model
eligible = evaluated[
    evaluated.hard_feasible &
    (evaluated.red_penalty <= .36)
].copy()
if eligible.empty:
    eligible = evaluated[evaluated.hard_feasible].copy()

winner = eligible.iloc[0]
architecture_contract = {
    "listed_parent_and_group_hq": winner.hq,
    "europe_platform": winner.europe,
    "americas_platform": winner.americas,
    "asia_pacific_platform": winner.asia_pacific,
    "local_carriers":"Retain wherever licensing, policyholder protection, tax, capital or supervisory requirements make them necessary.",
    "reinsurance":"Coordinate regionally; centralize only where risk ownership, capital, governance and regulatory permissions genuinely support it.",
    "shared_services":"Place routine services under documented arm's-length arrangements; keep key risk-taking decisions with the entities that economically own the risks.",
    "substance_rule":"Boards, senior management, underwriting/actuarial authority, capital and systems must align with attributed functions and risks.",
    "tax_rule":"Optimize lawful friction and simplification, not sub-minimum-tax profit parking.",
    "conditions_precedent":[
        "jurisdiction-specific legal and tax opinions",
        "full OECD/GloBE Pillar Two model using verified accounting data",
        "transfer-pricing functional and financial-transactions analysis",
        "actuarial, solvency and capital fungibility analysis",
        "supervisory engagement and required approvals",
        "UK listing, shareholder and corporate-governance review",
        "implementation tax, exit tax, stamp duty, VAT/GST and policyholder impact analysis"
    ]
}
legacy_index = legacy_complexity + len(entities)*1.5
target_index = 4 + len(entities)*0.75 + 12  # parent + regional platforms + retained local complexity proxy
simplification = 1-target_index/legacy_index

print("SELECTED SYNTHETIC ARCHITECTURE")
print(json.dumps(architecture_contract,indent=2))
print("\nSynthetic structural-complexity reduction:",f"{simplification:.1%}")
print("Deterministic score:",round(float(winner.det_score),4),
      "Final score:",round(float(winner.final_score),4),
      "Red flags:",winner.red_flags)

SELECTED SYNTHETIC ARCHITECTURE
{
  "listed_parent_and_group_hq": "United Kingdom",
  "europe_platform": "United Kingdom",
  "americas_platform": "United States",
  "asia_pacific_platform": "Singapore",
  "local_carriers": "Retain wherever licensing, policyholder protection, tax, capital or supervisory requirements make them necessary.",
  "reinsurance": "Coordinate regionally; centralize only where risk ownership, capital, governance and regulatory permissions genuinely support it.",
  "shared_services": "Place routine services under documented arm's-length arrangements; keep key risk-taking decisions with the entities that economically own the risks.",
  "substance_rule": "Boards, senior management, underwriting/actuarial authority, capital and systems must align with attributed functions and risks.",
  "tax_rule": "Optimize lawful friction and simplification, not sub-minimum-tax profit parking.",
  "conditions_precedent": [
    "jurisdiction-specific legal and tax opinions",
    "full OECD/GloBE Pillar Two model using verified accounting data",
    "transfer-pricing functional and financial-transactions analysis",
    "actuarial, solvency and capital fungibility analysis",
    "supervisory engagement and required approvals",
    "UK listing, shareholder and corporate-governance review",
    "implementation tax, exit tax, stamp duty, VAT/GST and policyholder impact analysis"
  ]
}

Synthetic structural-complexity reduction: 76.4%
Deterministic score: -4.0171 Final score: -4.1871 Red flags: ['cross_border_friction']

### Code Unit 10 — Board report, provenance and references-ready export

The final computational unit assembles the experiment into a board-style report. It records the synthetic company profile, selected architecture, quantitative scores, swarm consensus, dissent, red-team flags, required safeguards and implementation phases. It also creates machine-readable CSV and JSON artifacts that can be downloaded from Colab and inspected independently of the notebook.

The implementation roadmap is staged. Phase 1 is evidence: legal-entity inventory, tax attributes, regulatory licenses, capital, contracts and reinsurance. Phase 2 is design validation: jurisdiction-specific legal and tax opinions, Pillar Two calculations, transfer-pricing functional analysis and supervisory engagement. Phase 3 is sequencing: establish or strengthen regional platforms, migrate functions and people, amend reinsurance, obtain approvals, and only then transfer contracts or entities where feasible. Phase 4 is stabilization: monitor effective tax rates, capital, solvency, service quality, claims performance, transfer-pricing outcomes and regulatory commitments.

Provenance is part of the deliverable. The report records the random seed, model identifier, whether live LLM mode was used, the number of agents and the candidate universe. A real system would add prompt hashes, source-document versions and human approvals.

The notebook closes by emphasizing that a sophisticated swarm should make the decision process **more inspectable**, not less. The value of the 50 agents lies in surfacing specialist conflicts and hidden constraints. The final recommendation is accepted only after deterministic validation. This is a useful model for financial institutions adopting autonomous systems: AI can broaden the range of hypotheses and accelerate multidisciplinary analysis, while governance, evidence and accountable human judgment remain the mechanisms that authorize real-world action.

## Infographic — Code Unit 10

In [27]:
# CODE UNIT 10 — Board report, implementation roadmap and provenance export
board_report = {
    "status":"SYNTHETIC EDUCATIONAL DECISION-SUPPORT OUTPUT — NOT TAX OR LEGAL ADVICE",
    "company":"Atlas Global Insurance Group plc (synthetic)",
    "problem":"Reorganize a highly complex global insurer around one headquarters and three principal regional platforms.",
    "selected_architecture":architecture_contract,
    "swarm":{
        "agents":len(agents),
        "model":MODEL,
        "live_llm":LIVE_LLM,
        "top_preference_counts":agent_opinions.preferred_arch_id.value_counts().head(5).to_dict()
    },
    "selected_metrics":{
        k:(bool(winner[k]) if isinstance(winner[k],(np.bool_,bool)) else
           float(winner[k]) if isinstance(winner[k],(np.floating,float)) else winner[k])
        for k in ["tax_friction","withholding_friction","regulatory_depth","capital_fungibility",
                  "substance","talent","legal_stability","operating_cost","hard_feasible","final_score"]
    },
    "implementation":[
        "Phase 1 — Evidence: reconcile legal entities, licenses, contracts, tax attributes, capital, reinsurance and intercompany flows.",
        "Phase 2 — Validation: current local opinions, Pillar Two model, transfer pricing, solvency, accounting and supervisory pre-consultation.",
        "Phase 3 — Build: establish/strengthen regional platforms, move genuine functions and people, redesign governance and reinsurance.",
        "Phase 4 — Execute: obtain approvals, sequence entity/portfolio transfers, amend contracts, funding and service arrangements.",
        "Phase 5 — Stabilize: monitor ETR, solvency, capital mobility, claims, service quality, TP outcomes and regulatory commitments."
    ],
    "provenance":{"seed":SEED,"candidate_architectures":len(architectures),"shortlist":len(shortlist)}
}

with open("AGIG_board_report.json","w") as f:
    json.dump(board_report,f,indent=2,default=str)
evaluated.to_csv("AGIG_architecture_shortlist.csv",index=False)
agent_opinions.to_csv("AGIG_50_agent_opinions.csv",index=False)

print(json.dumps(board_report,indent=2,default=str))
print("\nExports created: AGIG_board_report.json, AGIG_architecture_shortlist.csv, AGIG_50_agent_opinions.csv")

{
  "status": "SYNTHETIC EDUCATIONAL DECISION-SUPPORT OUTPUT \u2014 NOT TAX OR LEGAL ADVICE",
  "company": "Atlas Global Insurance Group plc (synthetic)",
  "problem": "Reorganize a highly complex global insurer around one headquarters and three principal regional platforms.",
  "selected_architecture": {
    "listed_parent_and_group_hq": "United Kingdom",
    "europe_platform": "United Kingdom",
    "americas_platform": "United States",
    "asia_pacific_platform": "Singapore",
    "local_carriers": "Retain wherever licensing, policyholder protection, tax, capital or supervisory requirements make them necessary.",
    "reinsurance": "Coordinate regionally; centralize only where risk ownership, capital, governance and regulatory permissions genuinely support it.",
    "shared_services": "Place routine services under documented arm's-length arrangements; keep key risk-taking decisions with the entities that economically own the risks.",
    "substance_rule": "Boards, senior management, underwriting/actuarial authority, capital and systems must align with attributed functions and risks.",
    "tax_rule": "Optimize lawful friction and simplification, not sub-minimum-tax profit parking.",
    "conditions_precedent": [
      "jurisdiction-specific legal and tax opinions",
      "full OECD/GloBE Pillar Two model using verified accounting data",
      "transfer-pricing functional and financial-transactions analysis",
      "actuarial, solvency and capital fungibility analysis",
      "supervisory engagement and required approvals",
      "UK listing, shareholder and corporate-governance review",
      "implementation tax, exit tax, stamp duty, VAT/GST and policyholder impact analysis"
    ]
  },
  "swarm": {
    "agents": 50,
    "model": "claude-sonnet-5",
    "live_llm": true,
    "top_preference_counts": {
      "ARCH_001": 43,
      "ARCH_017": 2,
      "ARCH_004": 2,
      "ARCH_241": 2,
      "ARCH_097": 1
    }
  },
  "selected_metrics": {
    "tax_friction": 0.26125,
    "withholding_friction": 0.11083333333333334,
    "regulatory_depth": 0.96,
    "capital_fungibility": 0.905,
    "substance": 0.88575,
    "talent": 0.9649999999999999,
    "legal_stability": 0.9575,
    "operating_cost": 0.6505,
    "hard_feasible": true,
    "final_score": -4.1870875
  },
  "implementation": [
    "Phase 1 \u2014 Evidence: reconcile legal entities, licenses, contracts, tax attributes, capital, reinsurance and intercompany flows.",
    "Phase 2 \u2014 Validation: current local opinions, Pillar Two model, transfer pricing, solvency, accounting and supervisory pre-consultation.",
    "Phase 3 \u2014 Build: establish/strengthen regional platforms, move genuine functions and people, redesign governance and reinsurance.",
    "Phase 4 \u2014 Execute: obtain approvals, sequence entity/portfolio transfers, amend contracts, funding and service arrangements.",
    "Phase 5 \u2014 Stabilize: monitor ETR, solvency, capital mobility, claims, service quality, TP outcomes and regulatory commitments."
  ],
  "provenance": {
    "seed": 766,
    "candidate_architectures": 320,
    "shortlist": 12
  }
}

Exports created: AGIG_board_report.json, AGIG_architecture_shortlist.csv, AGIG_50_agent_opinions.csv

## References and further reading

The notebook uses synthetic tax and jurisdictional inputs. The sources below define the **real conceptual and regulatory frameworks** that a professional team would consult and then supplement with current jurisdiction-specific law and advice.

1. OECD. *Global Anti-Base Erosion Model Rules (Pillar Two).* OECD/G20 Inclusive Framework on BEPS. https://www.oecd.org/tax/beps/tax-challenges-arising-from-the-digitalisation-of-the-economy-global-anti-base-erosion-model-rules-pillar-two.htm  
2. OECD. *OECD Transfer Pricing Guidelines for Multinational Enterprises and Tax Administrations 2022.* https://doi.org/10.1787/0e655865-en  
3. OECD. *Transfer Pricing.* https://www.oecd.org/en/topics/transfer-pricing.html  
4. HM Revenue & Customs. *Multinational Top-up Tax and Domestic Top-up Tax — Overview.* https://www.gov.uk/hmrc-internal-manuals/multinational-top-up-tax-and-domestic-top-up-tax/mtt01010  
5. HM Revenue & Customs. *Calculating Pillar Two top-up amounts — Overview.* https://www.gov.uk/hmrc-internal-manuals/multinational-top-up-tax-and-domestic-top-up-tax/mtt30010  
6. HM Revenue & Customs. *How to report Pillar 2 Top-up Taxes.* https://www.gov.uk/guidance/how-to-report-pillar-2-top-up-taxes  
7. HM Revenue & Customs. *Pillar 2: adoption of the undertaxed profits rule.* https://www.gov.uk/government/publications/pillar-2-adoption-of-the-undertaxed-profits-rule  
8. International Association of Insurance Supervisors (IAIS). *Insurance Core Principles and Common Framework for the Supervision of Internationally Active Insurance Groups (ComFrame).* https://www.iaisweb.org/activities-topics/standard-setting/icps-and-comframe/  
9. International Association of Insurance Supervisors (IAIS). *Insurance Capital Standard (ICS).* https://www.iaisweb.org/activities-topics/standard-setting/insurance-capital-standard/  
10. IFRS Foundation. *IFRS 17 Insurance Contracts.* https://www.ifrs.org/issued-standards/list-of-standards/ifrs-17-insurance-contracts/  
11. UK Prudential Regulation Authority. *Insurance supervision.* https://www.bankofengland.co.uk/prudential-regulation  
12. Financial Conduct Authority. *Insurance.* https://www.fca.org.uk/firms/insurance  
13. European Insurance and Occupational Pensions Authority (EIOPA). *Solvency II.* https://www.eiopa.europa.eu/browse/regulation-and-policy/solvency-ii_en  
14. National Association of Insurance Commissioners (NAIC). *International Insurance Relations.* https://content.naic.org/insurance-topics/international-insurance-relations  
15. Anthropic. *API documentation.* https://docs.anthropic.com/

### Final methodological note

The notebook should be read as a **research architecture**. Before any real transaction, synthetic inputs must be replaced by verified entity-level data and current law. The output should then be reviewed by qualified tax counsel, insurance regulatory counsel, transfer-pricing specialists, actuaries, accountants, treasury professionals, local management, supervisors and the board. A 50-agent swarm can expand analytical coverage; it cannot convert an illustrative dataset into a legally executable restructuring.