# Caso práctico — Enjambre de 50 agentes para una iniciativa de reforma de la Ley del Mercado de Valores

## Introducción

Este cuaderno presenta un experimento institucional: utilizar un enjambre de cincuenta agentes especializados para estudiar la Ley del Mercado de Valores mexicana y producir, al final del proceso, un **anteproyecto de iniciativa de reforma limitado exactamente a veinte artículos**. El objetivo no es pedir a un modelo de lenguaje que “reescriba la ley”. El objetivo es construir una arquitectura deliberativa que haga visibles intereses, especialidades, desacuerdos, evidencia, restricciones jurídicas y consecuencias operativas antes de redactar una propuesta legislativa.

La hipótesis de trabajo es sencilla. Una reforma bursátil rara vez tiene una sola perspectiva correcta. El regulador puede privilegiar integridad de mercado y protección al inversionista; una emisora puede observar costos de acceso, tiempos y cargas de revelación; una bolsa puede identificar fricciones de listado y liquidez; una casa de bolsa puede advertir problemas de colocación, intermediación y responsabilidad; un inversionista institucional puede exigir mejor información, gobierno corporativo y mecanismos de salida. A estas perspectivas se agregan abogados practicantes, especialistas legislativos y expertos en derecho comparado. Ninguno debe dominar por construcción. La riqueza del ejercicio surge precisamente de conservar diferencias y obligar al sistema a convertirlas en una propuesta jurídicamente coherente.

El corpus normativo primario será la **Ley del Mercado de Valores vigente que el usuario proporcione o descargue desde una fuente oficial**. El notebook no debe inventar el texto de artículos ausentes. Cada propuesta legislativa deberá citar el artículo fuente y conservar evidencia suficiente para reconstruir por qué fue seleccionado. Como contexto secundario pueden incorporarse la reforma publicada el 28 de diciembre de 2023, las disposiciones de emisoras simplificadas y otros documentos oficiales o comparados que el usuario cargue. La regla metodológica es estricta: el corpus mexicano manda; el derecho comparado sirve para generar alternativas y preguntas, no para trasplantar instituciones de manera automática.

Los cincuenta agentes utilizarán el mismo modelo —Claude Haiku 4.5— pero no serán clones. Cada uno tendrá una identidad institucional, una especialidad, un mandato, objetivos, sesgos declarados y criterios de evaluación. El sesgo no se oculta: se modela. Un agente que representa a una emisora puede asignar mayor peso al costo de cumplimiento; uno que representa a un inversionista institucional puede ponderar más la revelación y la protección de minorías. Un regulador puede ser más conservador respecto de conflictos de interés. Hacer explícitas estas inclinaciones permite tratarlas como información del proceso, en lugar de confundirlas con una supuesta neutralidad del modelo.

La arquitectura tendrá dos niveles. En el **inner loop**, los agentes leen el corpus, diagnostican fricciones, proponen temas y critican propuestas. En el **outer loop**, una capa de gobernanza evalúa la calidad del proceso: cobertura de perspectivas, soporte normativo, duplicidades, contradicciones, concentración de influencia y calidad de la evidencia. El sistema podrá reorganizar grupos de trabajo, pero no podrá modificar por sí mismo la ley ni declarar ganadora una propuesta. Se mantiene así el principio que guía todo el caso: **quien propone no debe ser quien evalúa y quien evalúa no debe ser quien autoriza**.

El flujo deliberativo se divide en constelaciones. Primero se construye el corpus y se segmenta la ley por artículos. Después los cincuenta agentes producen diagnósticos independientes. Esos diagnósticos se agrupan por problemas: acceso al mercado, emisoras y revelación, gobierno corporativo, intermediarios, infraestructura de mercado, inversionistas, supervisión, sanciones, innovación y otros temas que emerjan de la evidencia. A continuación se forman coaliciones temporales de agentes con perspectivas distintas. Cada coalición formula alternativas y recibe críticas de una coalición adversarial. El sistema registra apoyos y objeciones, pero no utiliza una simple mayoría como sustituto de juicio legislativo.

El resultado final deberá contener exactamente veinte artículos afectados. Para cada artículo se identificará la operación legislativa —reforma, adición o derogación—, el problema que se intenta resolver, la evidencia proveniente del corpus, los grupos que apoyan y objetan la medida, los riesgos de implementación, una comparación internacional cuando exista soporte suficiente y una propuesta de redacción. Posteriormente, un agente legislativo integrador elaborará una exposición de motivos y un texto articulado. Una capa independiente de validación verificará que ningún artículo citado sea inventado, que las referencias existan en el corpus, que la propuesta no exceda veinte artículos y que las contradicciones pendientes sean visibles.

Este notebook es deliberadamente un **laboratorio pedagógico y de investigación**, no una iniciativa lista para presentarse al Congreso. Una iniciativa real requeriría revisión jurídica humana exhaustiva, técnica legislativa formal, análisis constitucional, impacto regulatorio, consistencia con legislación secundaria y otras leyes, consulta con autoridades y participantes del mercado, y validación política. El sistema ayuda a ampliar la capacidad de análisis; no recibe autoridad legislativa.

Desde la perspectiva de la conferencia, el caso materializa varias ideas centrales. El conocimiento jurídico se convierte en corpus estructurado; la memoria conserva procedencia; la especialización se integra mediante múltiples agentes; el arnés limita fuentes y acciones; la autoridad permanece fuera del modelo; y el enjambre permite que la organización del análisis se adapte al problema. La pregunta ya no es si Claude puede redactar veinte reformas. La pregunta es si podemos diseñar una institución artificial de deliberación que produzca una propuesta mejor documentada, más plural, más trazable y más fácil de cuestionar que una única conversación con un modelo.

Finalmente, el diseño busca hacer visible una tensión esencial. Los mercados de valores necesitan simultáneamente acceso, competencia, liquidez, innovación, transparencia, integridad y protección al inversionista. Esos objetivos pueden entrar en conflicto. Un buen enjambre no elimina el conflicto ni fabrica consenso. Lo estructura. Su éxito no consiste en que cincuenta agentes estén de acuerdo, sino en que el desacuerdo relevante llegue a la decisión final acompañado de evidencia, alternativas y responsabilidad claramente asignada.

Hay además una razón para escoger la Ley del Mercado de Valores como laboratorio. Es una ley en la que confluyen derecho corporativo, regulación prudencial y de conducta, infraestructura, gobierno corporativo, información, intermediación y protección al inversionista. Una modificación aparentemente localizada puede alterar incentivos en varios nodos del mercado. Esa interdependencia permite observar con claridad por qué la especialización es necesaria y, al mismo tiempo, por qué una reforma exige reconstruir una visión de conjunto. El enjambre no pretende reemplazar esa integración humana; pretende hacerla más explícita, sistemática y auditable.

## Cell 1 — Configuración y dependencias

Esta primera celda establece el entorno de ejecución y las reglas que no deben quedar dispersas por el cuaderno. Se instalan o importan las bibliotecas necesarias, se fija una semilla para reproducibilidad y se declara el modelo `claude-haiku-4-5-20251001`. La clave de Anthropic se obtiene exclusivamente desde `google.colab.userdata` utilizando el nombre exacto `ANTHROPIC_API_KEY`; nunca se imprime ni se guarda en el notebook. También se define un interruptor `LIVE_LLM`. Cuando está apagado, el cuaderno puede recorrerse sin consumir API y utiliza resultados deterministas de demostración; cuando está encendido, las llamadas pasan por una única puerta de enlace.

Centralizar la llamada al modelo es una decisión de gobernanza. En lugar de permitir que cada agente construya parámetros distintos, todos utilizan la misma función, con límites de tokens, reintentos y registro. No se fija `temperature=0`; el ejemplo usa la configuración soportada por el proveedor y mantiene la variación controlada mediante prompts y validación posterior. El propósito no es maximizar creatividad, sino permitir diversidad argumentativa sin perder trazabilidad.

La celda también crea estructuras para el registro de auditoría. Cada llamada tendrá agente, propósito, modelo, instante, hash del prompt y estado. Esto permite reconstruir qué parte del resultado provino de qué agente. En un experimento legislativo, esa procedencia es tan importante como el texto final: una redacción convincente no debe ocultar el camino que la produjo.

Al ejecutar esta celda, el usuario debe comprobar tres cosas: que la biblioteca `anthropic` esté disponible, que el secreto exista en Colab y que el modelo declarado sea exactamente el deseado. Si la clave no existe, el cuaderno no falla de manera opaca: cambia a modo demostración y explica qué falta. Esa conducta es deliberada. El sistema debe degradarse de manera segura, no improvisar credenciales ni sustituir silenciosamente el modelo.

Una consideración adicional es el costo. Cincuenta agentes multiplicados por varias rondas pueden generar muchas llamadas. Por eso la arquitectura permite probar primero con pocos agentes, inspeccionar formatos y sólo después activar la ejecución completa. Esta práctica evita gastar tokens en un pipeline mal configurado y refleja una regla institucional más general: antes de ampliar autonomía o escala, conviene validar el arnés en un entorno acotado.

In [ ]:
# @title
# Cell 1 — configuration and dependencies
!pip -q install "anthropic>=0.40.0" pypdf pandas numpy scikit-learn

import os, re, json, time, hashlib, random, threading
from pathlib import Path
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed

import numpy as np
import pandas as pd

SEED = 766
random.seed(SEED)
np.random.seed(SEED)

MODEL = "claude-haiku-4-5-20251001"
LIVE_LLM = True

# Bounded concurrency. Increase cautiously only after a clean run.
MAX_AGENT_WORKERS = 8
MAX_CONSTELLATION_WORKERS = 5
MAX_REVIEW_WORKERS = 8
MAX_DRAFT_WORKERS = 6

# Portfolio design targets.
TARGET_FINAL_ARTICLES = 20
MIN_DIAGNOSED_ARTICLES = 30
MIN_CANDIDATE_ARTICLES = 28

try:
    from google.colab import userdata
    ANTHROPIC_API_KEY = userdata.get("ANTHROPIC_API_KEY")
except Exception:
    ANTHROPIC_API_KEY = None

from anthropic import Anthropic
client = Anthropic(api_key=ANTHROPIC_API_KEY) if ANTHROPIC_API_KEY else None
CLAUDE_ENABLED = bool(client and LIVE_LLM)

audit_log = []
audit_lock = threading.Lock()

print("Model:", MODEL)
print("Claude enabled:", CLAUDE_ENABLED)
print("Target final articles:", TARGET_FINAL_ARTICLES)
if not ANTHROPIC_API_KEY:
    print("Add the Colab secret ANTHROPIC_API_KEY before running live calls.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 25.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 23.3 MB/s eta 0:00:00
Model: claude-haiku-4-5-20251001
Claude enabled: True
Target final articles: 20

## Cell 2 — Carga del corpus oficial

La segunda celda construye la frontera epistemológica del experimento: qué documentos pueden considerarse evidencia. El notebook busca primero archivos cargados por el usuario en `/content` y permite incorporar la Ley del Mercado de Valores en PDF o texto. Para facilitar la demostración, también ofrece una función explícita para descargar la versión oficial desde la Cámara de Diputados cuando el usuario decida hacerlo. El diseño evita depender de páginas no oficiales o de resúmenes de terceros.

La Ley del Mercado de Valores es el corpus primario. Documentos adicionales —decretos de reforma, disposiciones de carácter general, regulación de emisoras simplificadas, materiales comparados— se etiquetan como corpus secundario. Esa distinción importa: un agente puede utilizar derecho comparado para sugerir una alternativa, pero no puede presentarlo como si fuera derecho mexicano vigente. Cada documento recibe identificador, fuente, fecha de carga y hash.

El cuaderno no presupone que el PDF pueda extraerse perfectamente. La función de ingestión valida que haya texto suficiente y, si la extracción es deficiente, detiene la fase legislativa. Esto evita el error más peligroso del ejercicio: redactar sobre artículos que el sistema nunca leyó. En una versión de producción podrían añadirse conectores a fuentes oficiales, control de versiones y firma de documentos.

Esta celda representa el equivalente del “arnés de fuentes” del discurso. Los agentes pueden ser muy capaces, pero no pueden decidir libremente qué texto cuenta como Ley. El usuario controla el corpus autorizado. Si se agrega material internacional, debe etiquetarse con jurisdicción y función. El resultado de la celda es un inventario verificable de documentos, no todavía una interpretación jurídica.

También conviene conservar versiones. Si el usuario vuelve a ejecutar el ejercicio con una LMV reformada, los hashes permiten distinguir resultados producidos con corpus distintos. Dos propuestas aparentemente iguales pueden tener significado diferente si cambió el texto vigente. La versión del conocimiento es parte del conocimiento; por ello el inventario del corpus debe acompañar cualquier resultado que se exporte.

In [ ]:
# @title
# Cell 2 — authorized corpus
from pypdf import PdfReader
import urllib.request

OFFICIAL_LMV_URL = "https://www.diputados.gob.mx/LeyesBiblio/pdf/LMV.pdf"
CORPUS_DIR = Path("/content/lmv_corpus")
CORPUS_DIR.mkdir(exist_ok=True)

def sha256_bytes(b):
    return hashlib.sha256(b).hexdigest()

def download_official_lmv(force=False):
    target = CORPUS_DIR / "LMV_oficial.pdf"
    if force or not target.exists():
        urllib.request.urlretrieve(OFFICIAL_LMV_URL, target)
    return target

def pdf_to_text(path):
    reader = PdfReader(str(path))
    return "\n".join((p.extract_text() or "") for p in reader.pages)

def load_corpus(download_lmv=True):
    if download_lmv:
        try:
            download_official_lmv()
        except Exception as e:
            print("Official LMV download failed:", e)

    candidates = list(CORPUS_DIR.glob("*")) + list(Path("/content").glob("*.pdf")) + list(Path("/content").glob("*.txt"))
    docs, seen = [], set()

    for p in candidates:
        rp = str(p.resolve())
        if rp in seen or not p.is_file():
            continue
        seen.add(rp)

        try:
            text = pdf_to_text(p) if p.suffix.lower() == ".pdf" else p.read_text(errors="ignore")
            docs.append({
                "name": p.name,
                "path": str(p),
                "text": text,
                "sha256": sha256_bytes(p.read_bytes())
            })
        except Exception as e:
            print(f"Skipped {p.name}: {e}")

    return docs

corpus = load_corpus(download_lmv=True)

inventory = pd.DataFrame([
    {k: v for k, v in d.items() if k != "text"}
    for d in corpus
])
display(inventory)

lmv_doc = next((d for d in corpus if "LMV" in d["name"].upper()), None)
if not lmv_doc:
    raise RuntimeError("No LMV document found. Upload the official LMV PDF to /content.")

if len(lmv_doc["text"]) < 10000:
    raise RuntimeError("LMV extraction appears too short. Check the PDF before continuing.")

print("✓ Authorized LMV corpus loaded.")
print("LMV SHA256:", lmv_doc["sha256"][:20], "...")

,name,path,sha256
0,LMV_oficial.pdf,/content/lmv_corpus/LMV_oficial.pdf,cc72fd6a12721826b6be40a77e3bb8bc297e5ce7b8794a...

✓ Authorized LMV corpus loaded.
LMV SHA256: cc72fd6a12721826b6be ...

## Cell 3 — Segmentación de la Ley por artículos

La tercera celda transforma el documento legislativo en una estructura utilizable por cincuenta agentes. En vez de enviar cientos de páginas completas en cada llamada, intenta identificar encabezados de artículos y construir registros separados con número, texto, documento fuente y hash. Esta segmentación permite recuperar únicamente las disposiciones pertinentes y, sobre todo, comprobar posteriormente que un artículo propuesto existe en el corpus.

La extracción legislativa nunca es perfecta. Artículos Bis, Ter, fracciones, transitorios y formatos PDF pueden producir casos difíciles. Por eso la celda incluye diagnósticos: número de artículos detectados, ejemplos iniciales y advertencias cuando la cobertura parece anormal. El usuario puede inspeccionar el resultado antes de continuar. La intención pedagógica es mostrar que el “conocimiento” de un sistema no aparece mágicamente; requiere una representación.

A partir de esta estructura se construye un índice ligero de palabras y temas. No pretende sustituir un motor semántico profesional. Su función es ofrecer recuperación determinista para que los prompts de los agentes reciban fragmentos relevantes del corpus. Más adelante, las propuestas sólo podrán referirse a artículos presentes en este diccionario, salvo que se trate expresamente de una adición nueva cuya ubicación deba ser validada por técnica legislativa.

La celda también prepara una función `retrieve_articles` que devuelve artículos por términos y limita el volumen de contexto. Con ello reducimos costo, evitamos enviar información irrelevante y preservamos trazabilidad. Si un agente afirma que cierto problema está en el artículo 85, la validación final puede recuperar exactamente el texto que ese artículo tenía en el corpus utilizado. Esa capacidad de reconstrucción es esencial para diferenciar una simulación seria de una conversación generativa.

En una implementación más robusta, la segmentación debería reconocer no sólo artículos, sino párrafos, fracciones, incisos y referencias cruzadas. Para el caso pedagógico se mantiene el artículo como unidad principal porque coincide con la restricción final de veinte artículos. Esta simplificación es visible y, por tanto, puede ser cuestionada. Un buen sistema no oculta sus aproximaciones: las declara para que el usuario sepa dónde necesita mayor revisión.

In [ ]:
# @title
# Cell 3 — segment LMV into articles and build retrieval helpers
def normalize_text(s):
    return re.sub(r"\s+", " ", str(s)).strip()

def normalize_article_ref(value):
    if value is None:
        return ""
    x = str(value).strip()
    x = re.sub(r"(?i)^(art[ií]culo|art\.)\s*", "", x).strip()
    return re.sub(r"\s+", " ", x)

def segment_articles(text):
    # Supports forms such as 2, 9 Bis, 225 Bis 1, 391 Ter.
    pat = re.compile(
        r"(?im)(Artículo\s+\d+(?:\s+Bis(?:\s+\d+)?|\s+Ter(?:\s+\d+)?)?\s*[.\-–—]?)"
    )
    hits = list(pat.finditer(text))
    out = {}

    for i, m in enumerate(hits):
        start = m.start()
        end = hits[i+1].start() if i+1 < len(hits) else len(text)
        chunk = text[start:end].strip()

        label = re.search(
            r"(?i)Artículo\s+([0-9]+(?:\s+Bis(?:\s+\d+)?|\s+Ter(?:\s+\d+)?)?)",
            chunk
        )
        if label:
            key = normalize_article_ref(label.group(1))
            out[key] = chunk

    return out

articles = segment_articles(lmv_doc["text"])

if len(articles) < 100:
    raise RuntimeError(
        f"Only {len(articles)} articles were detected. "
        "The LMV parsing is probably incomplete; inspect the source PDF."
    )

article_keys = list(articles.keys())

def article_sort_key(x):
    m = re.match(r"(\d+)", str(x))
    return int(m.group(1)) if m else 10**9

article_keys = sorted(article_keys, key=article_sort_key)

def retrieve_articles(query, k=12):
    terms = set(re.findall(r"[A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9]+", str(query).lower()))
    scored = []

    for n, t in articles.items():
        words = set(re.findall(r"[A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9]+", t.lower()))
        score = len(terms & words)
        if score:
            scored.append((score, n, t))

    return sorted(scored, key=lambda z: (z[0], -article_sort_key(z[1])), reverse=True)[:k]

def rotating_article_pack(agent_number, pack_size=8):
    # Deterministic coverage across the statute so the 50 agents do not all see
    # only the same high-frequency provisions.
    if not article_keys:
        return []
    start = ((agent_number - 1) * pack_size) % len(article_keys)
    idxs = [(start + j) % len(article_keys) for j in range(pack_size)]
    return [article_keys[i] for i in idxs]

print("✓ Articles detected:", len(articles))
print("First 15:", article_keys[:15])

✓ Articles detected: 468
First 15: ['1', '2', '3', '4', '5', '6', '7', '8', '8 Bis', '9', '9 Bis', '10', '11', '12', '13']

## Cell 4 — Diseño de los 50 agentes

La cuarta celda crea el enjambre. Los cincuenta agentes se distribuyen entre ocho familias: abogados practicantes; especialistas legislativos y de política pública; reguladores y supervisores; emisoras; bolsas e infraestructura; casas de bolsa e intermediarios; inversionistas institucionales; y especialistas de derecho comparado y academia. La distribución no pretende afirmar que ésas sean las únicas voces legítimas. Es un diseño experimental que puede modificarse y que hace explícita la composición del grupo.

Cada agente recibe cinco atributos: rol, especialidad, objetivos, sesgos declarados y criterio de éxito. Por ejemplo, un representante de emisoras puede priorizar acceso y proporcionalidad de costos; un inversionista institucional puede ponderar revelación, gobierno y remedios; un regulador puede privilegiar integridad, supervisabilidad y protección del público. Un abogado de mercado puede enfocarse en coherencia normativa y ejecutabilidad. Los agentes comparados deben distinguir cuidadosamente equivalencia funcional de similitud terminológica.

Todos comparten un núcleo común de instrucciones: Derecho mexicano como marco primario, obligación de citar artículos del corpus, prohibición de inventar fuentes, deber de declarar incertidumbre y separación entre diagnóstico y autorización. Lo que cambia es la lente. Así obtenemos diversidad sin cambiar de modelo.

La celda muestra una tabla resumen para comprobar que hay exactamente cincuenta identidades y que ninguna familia domina accidentalmente. También asigna un peso inicial uniforme. Más adelante, la influencia puede ajustarse por calidad de evidencia, pero nunca por “prestigio” inventado. El punto metodológico es central: un enjambre útil no es cincuenta copias de Claude preguntadas cincuenta veces. Es una institución sintética con división de trabajo, incentivos y perspectivas explícitas.

Los nombres de los agentes son funcionales y no simulan personas reales. Esto evita atribuir a participantes concretos posiciones que nunca expresaron. Si en una fase posterior se incorporaran entrevistas o consultas reales, deberían entrar como una capa de evidencia separada, con consentimiento y procedencia, y no confundirse con las preferencias sintéticas de los agentes.

In [ ]:
# @title
# Cell 4 — 50-agent swarm
families = {
    "Practicing lawyers": 8,
    "Legislative & policy": 6,
    "Regulators": 7,
    "Issuers": 7,
    "Exchanges & infrastructure": 5,
    "Broker-dealers": 6,
    "Institutional investors": 6,
    "Comparative law & academia": 5
}

lenses = {
    "Practicing lawyers": (
        "coherence, enforceability, transaction practice",
        "reduce ambiguity and legal friction"
    ),
    "Legislative & policy": (
        "legislative technique, constitutional fit, public policy",
        "clear and implementable statute"
    ),
    "Regulators": (
        "market integrity, supervision, investor protection",
        "supervisable and resilient market"
    ),
    "Issuers": (
        "access, proportionality, disclosure cost, governance",
        "lower justified frictions without weakening trust"
    ),
    "Exchanges & infrastructure": (
        "listing, liquidity, price formation, infrastructure",
        "deeper and more efficient markets"
    ),
    "Broker-dealers": (
        "placement, intermediation, suitability, liability",
        "workable intermediation rules"
    ),
    "Institutional investors": (
        "disclosure, governance, minority protection, liquidity",
        "investable securities and credible protection"
    ),
    "Comparative law & academia": (
        "functional comparison, evidence, institutional design",
        "adaptable lessons, not legal transplants"
    )
}

agents = []
idx = 1

for family, n in families.items():
    for _ in range(n):
        agents.append({
            "id": f"A{idx:02d}",
            "agent_number": idx,
            "family": family,
            "specialty": lenses[family][0],
            "declared_bias": lenses[family][1],
            "weight": 1.0
        })
        idx += 1

assert len(agents) == 50
agent_by_id = {a["id"]: a for a in agents}
agents_df = pd.DataFrame(agents)

display(agents_df.groupby("family").size().rename("agents").to_frame())
display(agents_df.head())
print("✓ 50 distinct institutional agents created.")

                            agents
family
Broker-dealers                   6
Comparative law & academia       5
Exchanges & infrastructure       5
Institutional investors          6
Issuers                          7
Legislative & policy             6
Practicing lawyers               8
Regulators                       7

,id,agent_number,family,specialty,declared_bias,weight
0,A01,1,Practicing lawyers,"coherence, enforceability, transaction practice",reduce ambiguity and legal friction,1.0
1,A02,2,Practicing lawyers,"coherence, enforceability, transaction practice",reduce ambiguity and legal friction,1.0
2,A03,3,Practicing lawyers,"coherence, enforceability, transaction practice",reduce ambiguity and legal friction,1.0
3,A04,4,Practicing lawyers,"coherence, enforceability, transaction practice",reduce ambiguity and legal friction,1.0
4,A05,5,Practicing lawyers,"coherence, enforceability, transaction practice",reduce ambiguity and legal friction,1.0

✓ 50 distinct institutional agents created.

## Cell 5 — Puerta de enlace a Claude y contrato de salida

La quinta celda implementa la única función autorizada para llamar a Claude. El prompt del sistema combina las reglas comunes del enjambre con la identidad particular del agente. El prompt de usuario contiene la tarea, los artículos recuperados y un contrato JSON. Pedir salida estructurada facilita comparar cincuenta respuestas y detectar fallas, pero la celda no confía ciegamente en que el modelo obedecerá: limpia bloques de código, intenta parsear JSON y, si falla, registra el error y devuelve una estructura segura.

La función incorpora reintentos limitados para errores transitorios y no modifica silenciosamente los parámetros entre intentos. El modelo es Haiku 4.5 para todos los agentes, como requiere el diseño. Se evita `temperature=0`; el notebook no depende de ese parámetro para producir consistencia. La disciplina proviene del contrato de salida, del corpus y de la validación.

Cada llamada se registra en `audit_log` con agente, tarea, hash del prompt y éxito. No se almacena la API key. Tampoco se permite que los agentes llamen herramientas externas de manera autónoma. En este caso práctico, Claude razona sobre contexto autorizado; las operaciones deterministas —conteos, clustering, selección y validación— quedan en Python.

Esta separación es deliberada. El LLM es bueno generando diagnósticos, comparaciones y lenguaje jurídico preliminar; Python es mejor verificando que haya cincuenta agentes, veinte artículos, identificadores válidos y restricciones cuantitativas. La arquitectura combina ambos. Al final de la celda se ejecuta una prueba mínima sólo si `LIVE_LLM=True`, de modo que el usuario pueda comprobar la conexión antes de lanzar cincuenta o más llamadas.

El contrato JSON también permite imponer campos obligatorios de evidencia y riesgo. Si un agente entrega una prosa brillante pero omite el artículo, la objeción o el nivel de incertidumbre, la salida puede rechazarse mecánicamente. Éste es un ejemplo concreto de cómo un arnés transforma una capacidad lingüística general en una tarea institucional con requisitos verificables.

## Cell 6 — Ronda 1: diagnóstico independiente

La primera ronda utiliza a los 50 agentes **en paralelo** y con salida estructurada nativa de Anthropic. Cada agente recibe tanto artículos recuperados por afinidad temática como un paquete rotatorio de artículos de la LMV, de manera que el enjambre no concentre toda su atención en unas pocas disposiciones. Si la primera ronda no cubre suficientes artículos, el sistema ejecuta automáticamente una segunda pasada de cobertura. La ronda no redacta reformas: sólo diagnostica problemas y conserva su fundamento normativo.

In [ ]:
# Cell 6 — Round 1: parallel independent diagnosis + coverage pass
DIAG_TOOL = {
    "type": "object",
    "properties": {
        "issues": {
            "type": "array",
            "minItems": 1,
            "maxItems": 5,
            "items": {
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "problem": {"type": "string"},
                    "article_numbers": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "evidence": {"type": "string"},
                    "policy_objective": {"type": "string"},
                    "beneficiaries": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "risks": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "priority": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 5
                    }
                },
                "required": [
                    "title", "problem", "article_numbers", "evidence",
                    "policy_objective", "beneficiaries", "risks", "priority"
                ],
                "additionalProperties": False
            }
        }
    },
    "required": ["issues"],
    "additionalProperties": False
}

def diagnosis_context(agent, extra_articles=None):
    q = agent["specialty"] + " " + agent["declared_bias"]
    targeted = [n for _, n, _ in retrieve_articles(q, k=12)]
    rotation = rotating_article_pack(agent["agent_number"], pack_size=8)
    extra_articles = extra_articles or []

    selected = []
    for n in targeted + rotation + extra_articles:
        n = normalize_article_ref(n)
        if n in articles and n not in selected:
            selected.append(n)

    return "\n\n".join(
        f"[ARTICLE {n}]\n{articles[n][:3500]}"
        for n in selected[:24]
    )

def clean_issue(issue):
    if not isinstance(issue, dict):
        return None

    nums = []
    for x in issue.get("article_numbers", []):
        n = normalize_article_ref(x)
        if n in articles and n not in nums:
            nums.append(n)

    if not nums:
        return None

    title = str(issue.get("title", "")).strip()
    problem = str(issue.get("problem", "")).strip()
    if not title or not problem:
        return None

    priority = issue.get("priority", 3)
    try:
        priority = max(1, min(5, int(priority)))
    except Exception:
        priority = 3

    return {
        "title": title,
        "problem": problem,
        "article_numbers": nums,
        "evidence": str(issue.get("evidence", "")).strip(),
        "policy_objective": str(issue.get("policy_objective", "")).strip(),
        "beneficiaries": issue.get("beneficiaries", []) if isinstance(issue.get("beneficiaries", []), list) else [],
        "risks": issue.get("risks", []) if isinstance(issue.get("risks", []), list) else [],
        "priority": priority
    }

def diagnose_agent(agent, extra_articles=None, purpose="round1_diagnosis"):
    task = """ROUND 1 — DIAGNOSIS ONLY.
Identify 2 to 5 concrete frictions, obsolete provisions, ambiguities, proportionality problems,
market-development obstacles, investor-protection weaknesses, governance issues, or implementation
problems in the supplied LMV articles from your institutional perspective.
Do NOT draft amendments yet.
Every issue must cite at least one article that is actually present in the authorized context.
Prefer distinct substantive issues rather than variants of the same point."""
    result = structured_claude_call(
        agent=agent,
        purpose=purpose,
        task=task,
        context=diagnosis_context(agent, extra_articles),
        tool_name="submit_diagnosis",
        tool_description="Submit supported LMV diagnostic issues.",
        input_schema=DIAG_TOOL,
        max_tokens=2600
    )
    return agent, result

def run_diagnosis_batch(agent_jobs):
    rows, status = [], []
    with ThreadPoolExecutor(max_workers=MAX_AGENT_WORKERS) as ex:
        futures = {
            ex.submit(diagnose_agent, agent, extra, purpose): (agent, purpose)
            for agent, extra, purpose in agent_jobs
        }

        done = 0
        for f in as_completed(futures):
            agent, purpose = futures[f]
            try:
                _, result = f.result()
                valid = 0
                for issue in result.get("issues", []):
                    cleaned = clean_issue(issue)
                    if cleaned:
                        rows.append({
                            "agent": agent["id"],
                            "family": agent["family"],
                            "diagnosis_pass": purpose,
                            **cleaned
                        })
                        valid += 1
                status.append({"agent": agent["id"], "pass": purpose, "status": "OK" if valid else "NO_VALID_ISSUES", "issues": valid, "error": ""})
            except Exception as e:
                status.append({"agent": agent["id"], "pass": purpose, "status": "ERROR", "issues": 0, "error": str(e)[:500]})

            done += 1
            print(f"[{done:02d}/{len(agent_jobs):02d}] {agent['id']} {purpose}")

    return rows, status

print("=" * 72)
print("ROUND 1A — 50 INDEPENDENT DIAGNOSES")
print("=" * 72)

jobs = [(a, None, "round1_primary") for a in agents]
diagnoses, diagnosis_status = run_diagnosis_batch(jobs)
diagnoses_df = pd.DataFrame(diagnoses)
diagnosis_status_df = pd.DataFrame(diagnosis_status)

def distinct_diagnosed_articles(df):
    s = set()
    if df.empty:
        return s
    for xs in df["article_numbers"]:
        if isinstance(xs, list):
            s.update(x for x in xs if x in articles)
    return s

covered = distinct_diagnosed_articles(diagnoses_df)
print("\nPrimary findings:", len(diagnoses_df))
print("Agents contributing:", diagnoses_df["agent"].nunique() if not diagnoses_df.empty else 0)
print("Distinct diagnosed articles:", len(covered))

# Automatic coverage pass if the first sweep is too narrow.
if len(covered) < MIN_DIAGNOSED_ARTICLES:
    print("\nROUND 1B — COVERAGE EXPANSION")
    uncovered = [n for n in article_keys if n not in covered]
    if uncovered:
        # Give each agent a deterministic small batch of undercovered provisions.
        expansion_jobs = []
        chunk = max(1, min(6, int(np.ceil(len(uncovered) / len(agents)))))
        for i, agent in enumerate(agents):
            start = (i * chunk) % len(uncovered)
            pack = [uncovered[(start + j) % len(uncovered)] for j in range(chunk)]
            expansion_jobs.append((agent, pack, "round1_coverage"))

        extra_rows, extra_status = run_diagnosis_batch(expansion_jobs)
        if extra_rows:
            diagnoses_df = pd.concat([diagnoses_df, pd.DataFrame(extra_rows)], ignore_index=True)
        diagnosis_status_df = pd.concat([diagnosis_status_df, pd.DataFrame(extra_status)], ignore_index=True)

covered = distinct_diagnosed_articles(diagnoses_df)

print("\n" + "=" * 72)
print("ROUND 1 COMPLETE")
print("=" * 72)
print("Usable findings:", len(diagnoses_df))
print("Agents contributing:", diagnoses_df["agent"].nunique() if not diagnoses_df.empty else 0)
print("Families represented:", diagnoses_df["family"].nunique() if not diagnoses_df.empty else 0)
print("Distinct diagnosed LMV articles:", len(covered))

display(diagnosis_status_df.groupby(["pass", "status"]).size().rename("agents").to_frame())
display(diagnoses_df.head(20))

if diagnoses_df.empty or diagnoses_df["agent"].nunique() < 20:
    raise RuntimeError("Round 1 is too thin: fewer than 20 agents produced usable diagnoses.")
if len(covered) < TARGET_FINAL_ARTICLES:
    raise RuntimeError(
        f"Only {len(covered)} distinct LMV articles were diagnosed. "
        f"At least {TARGET_FINAL_ARTICLES} are required before continuing."
    )

print("✓ Round 1 has sufficient breadth for the reform funnel.")

========================================================================
ROUND 1A — 50 INDEPENDENT DIAGNOSES
========================================================================
[01/50] A06 round1_primary
[02/50] A03 round1_primary
[03/50] A04 round1_primary
[04/50] A08 round1_primary
[05/50] A01 round1_primary
[06/50] A07 round1_primary
[07/50] A05 round1_primary
[08/50] A02 round1_primary
[09/50] A15 round1_primary
[10/50] A09 round1_primary
[11/50] A10 round1_primary
[12/50] A12 round1_primary
[13/50] A11 round1_primary
[14/50] A16 round1_primary
[15/50] A13 round1_primary
[16/50] A14 round1_primary
[17/50] A18 round1_primary
[18/50] A17 round1_primary
[19/50] A21 round1_primary
[20/50] A23 round1_primary
[21/50] A22 round1_primary
[22/50] A19 round1_primary
[23/50] A20 round1_primary
[24/50] A24 round1_primary
[25/50] A25 round1_primary
[26/50] A28 round1_primary
[27/50] A26 round1_primary
[28/50] A27 round1_primary
[29/50] A31 round1_primary
[30/50] A30 round1_primary
[31/50] A29 round1_primary
[32/50] A32 round1_primary
[33/50] A33 round1_primary
[34/50] A34 round1_primary
[35/50] A37 round1_primary
[36/50] A36 round1_primary
[37/50] A35 round1_primary
[38/50] A38 round1_primary
[39/50] A39 round1_primary
[40/50] A41 round1_primary
[41/50] A40 round1_primary
[42/50] A44 round1_primary
[43/50] A42 round1_primary
[44/50] A43 round1_primary
[45/50] A45 round1_primary
[46/50] A46 round1_primary
[47/50] A48 round1_primary
[48/50] A49 round1_primary
[49/50] A47 round1_primary
[50/50] A50 round1_primary

Primary findings: 176
Agents contributing: 37
Distinct diagnosed articles: 169

========================================================================
ROUND 1 COMPLETE
========================================================================
Usable findings: 176
Agents contributing: 37
Families represented: 7
Distinct diagnosed LMV articles: 169

                                agents
pass           status
round1_primary NO_VALID_ISSUES      13
               OK                   37

,agent,family,diagnosis_pass,title,problem,article_numbers,evidence,policy_objective,beneficiaries,risks,priority
0,A06,Practicing lawyers,round1_primary,Ambiguity in Article 4: Good-Faith Third-Party...,Article 4 provides that breaches of the LMV 's...,[4],Article 4 states acts 'darán lugar...al pago d...,Clarify the interplay between regulatory compl...,"[Issuers, Investors, Intermediaries, Courts]",[Inconsistent judicial application of good-fai...,4
1,A06,Practicing lawyers,round1_primary,Article 12: Silent Gap on Governance Transitio...,Article 12 permits SAB (Sociedades Anónimas Bu...,"[12, 35, 36]",Article 12 states 'Las sociedades anónimas...p...,Ensure governance continuity and clarity durin...,"[Board members, Shareholders, Audit committees...",[Directors face uncertain fiduciary duty scope...,4
2,A06,Practicing lawyers,round1_primary,Article 29 & 36: Overly Broad Proxy for False-...,Article 29 makes the general director and 'rel...,"[29, 36]",Article 29 states directors are liable for 'La...,Balance director accountability for material d...,"[Issuers, Investors, Directors, Market partici...",[Over-deterrence of legitimate business commun...,4
3,A06,Practicing lawyers,round1_primary,Article 64 Bis 1 & Article 71: Procedural and ...,Article 64 Bis 1 grants certificate-holder ass...,"[64 Bis 1, 71]",Article 64 Bis 1(II)(b) grants power to 'Deter...,Clarify fiduciary accountability mechanisms an...,"[Trust administrators, Certificate-holders, Is...",[Conflicting remedies create litigation uncert...,3
4,A06,Practicing lawyers,round1_primary,Article 45: Incomplete Delegation Framework fo...,Article 45 permits the general director (Direc...,"[45, 29, 36, 44]",Article 45 states 'El director general...se au...,Establish clear delegation rules and liability...,"[Directors, Controlled entities, Compliance of...",[Directors unable to delegate risk-critical fu...,4
5,A03,Practicing lawyers,round1_primary,Conflicting Safe Harbor and Validity Doctrine ...,Article 4 creates internal logical tension by ...,[4],Article 4 states acts in contravention 'sin qu...,Clarify conditions under which regulatory brea...,"[securities market participants, investors, co...",[unpredictable judicial nullification of other...,4
6,A03,Practicing lawyers,round1_primary,Fiduciary Duty Ambiguity: 'Legitimate Cause' S...,Article 35's opening paragraph punishes board ...,[35],"Article 35, first paragraph, makes board membe...",Establish objective safe harbors (such as appr...,"[board members and executive officers, investm...",[personal liability exposure chilling independ...,4
7,A03,Practicing lawyers,round1_primary,Conflict-of-Interest Disclosure Scope Ambiguit...,"Article 35, Fraction II, requires directors to...",[35],Article 35(II) states directors must reveal co...,Define the materiality threshold for conflict ...,"[directors and board secretaries, companies ma...",[over-disclosure chilling legitimate board con...,3
8,A03,Practicing lawyers,round1_primary,Absence of Proportionality Calibration for Fid...,"Articles 29, 35, and 36 establish strict fiduc...","[29, 35, 36]",Article 29 imposes liability on 'the director ...,Introduce proportionality-based liability cali...,"[directors and officers, companies recruiting ...",[excessive personal liability chilling entrepr...,4
9,A03,Practicing lawyers,round1_primary,Temporal and Procedural Gaps in Article 64 Bis...,Article 64 Bis 1(II)(a) permits certificate ho...,[64 Bis 1],Article 64 Bis 1(II)(a) requires opposition to...,"Clarify remedy scope, procedural timing flexib...","[minority certificate holders, fiduciary admin...",[unenforceability of minority challenges due t...,3
10,A04,Practicing lawyers,round1_primary,Ambiguity in Article 4: Scope of Permitted Act...,Article 4 establishes that legal acts performe...,[4],Article 4 explicitly preserves contractual val...,Reduce transaction friction and predictability...,"[practicing lawyers, transaction parties, thir...",[enforceability uncertainty leading to delayed...,4
11,A04,Practicing lawyers,round1_primary,Unresolved Temporal and Procedural Gaps in Ind...,Article 26 establishes disqualification criter...,[26],Article 26 states: 'La Comisión tendrá un plaz...,"Clarify timing, procedure, and consequences fo...","[issuers, independent directors, investors, au...",[retroactive disqualification creating governa...,4
12,A04,Practicing lawyers,round1_primary,Inconsistent Responsibility Framework and Evid...,Articles 29 (director and key management respo...,"[29, 36, 44]","Article 36(iv): 'Se presumirá, salvo prueba en...",Harmonize liability standards; clarify evident...,"[finance officers, legal officers, chief execu...",[excessive liability exposure discouraging qua...,4
13,A04,Practicing lawyers,round1_primary,Structural Lacuna: Duty-Conflict Waiver and Ap...,Article 35 prohibits directors from voting on ...,"[35, 36]",Article 35(iv) prohibits directors from 'Aprue...,"Establish clear, predictable standards for rel...","[issuers, connected party counterparties, mino...",[chilling of legitimate related-party transact...,5
14,A04,Practicing lawyers,round1_primary,Inadequate Cure and Remediation Framework for ...,"Articles 36(ii), (v), and (vi) criminalize or ...",[36],"Article 36(v) prohibits 'Destruir, modificar u...",Balance investor protection against record des...,"[issuers, compliance officers, IT service prov...",[over-deterrence of legitimate records managem...,4
15,A08,Practicing lawyers,round1_primary,Contradiction between Act Validity and Fault-B...,Article 4 simultaneously permits damages and a...,[4],Article 4 states acts 'darán lugar...al pago d...,Reduce ambiguity in transaction enforceability...,"[transaction participants, third parties in go...",[Repeated litigation over whether specific vio...,4
16,A08,Practicing lawyers,round1_primary,Ambiguity in Conversion of Existing Sociedades...,Article 12 permits existing sociedades anónima...,[12],Article 12 states dissenting shareholders 'pod...,Facilitate orderly transition to SAPI status; ...,"[dissenting minority shareholders, continuing ...",[Valuation disputes between exiting and contin...,4
17,A08,Practicing lawyers,round1_primary,Duty of Care and Information Gaps in Director ...,"Articles 29, 35, and 36 impose fiduciary dutie...","[29, 35, 36]",Article 29 refers to 'falta de atención oportu...,Clarify directorial duty standards to reduce e...,"[board members and directors, bursátil societi...",[Directors exposed to unpredictable liability ...,5
18,A08,Practicing lawyers,round1_primary,Incomplete Frameworkfor Fiduciary and Administ...,Article 64 Bis 1 establishes holder assembly r...,[64 Bis 1],Article 64 Bis 1(II.b) permits holders represe...,Enable effective holder enforcement against fu...,"[certificate holders, administering societies,...",[Uncertainty over duty standard discourages ho...,3
19,A08,Practicing lawyers,round1_primary,Incomplete Scope of Foreign Issuer Exemption a...,Article 59 exempts foreign societies from Arti...,"[58, 59]",Article 58 requires foreign societies to demon...,Establish clear equivalence benchmarks for for...,"[domestic and foreign issuers, investors in fo...",[Selective enforcement of equivalence standard...,4

✓ Round 1 has sufficient breadth for the reform funnel.

## Cell 7 — Mapa de problemas y formación de constelaciones

Esta celda es una barrera de sincronización determinista. Sólo después de que termina la Ronda 1 clasifica los diagnósticos por tema, mide la amplitud institucional, identifica los artículos más citados y forma constelaciones temporales con diversidad de familias. Aquí no se llama al LLM: Python organiza la evidencia ya generada.

In [ ]:
# Cell 7 — deterministic problem map and diversified temporary constellations
THEMES = {
    "Access & offerings": ["inscripción","oferta","acceso","simplificada","capital","emisión","listado"],
    "Disclosure & governance": ["información","revelación","consejo","gobierno","minoría","accionista","conflicto"],
    "Intermediation": ["casa de bolsa","intermediación","intermediario","colocación","cliente","asesoría","distribución"],
    "Infrastructure & liquidity": ["bolsa","liquidez","depósito","contraparte","precio","negociación","compensación","liquidación"],
    "Supervision & enforcement": ["comisión","cnbv","supervisión","sanción","multa","inspección","vigilancia","infracción"],
    "Innovation": ["tecnología","digital","electrónico","innovación","automatización","token","plataforma"],
    "Investor protection": ["inversionista","protección","abuso","fraude","minoría","transparencia","idoneidad"]
}

def classify_theme(row):
    text = " ".join(str(row.get(c, "")) for c in ["title","problem","policy_objective","evidence"]).lower()
    scores = {theme: sum(text.count(k.lower()) for k in kws) for theme, kws in THEMES.items()}
    best = max(scores, key=scores.get)
    return best if scores[best] > 0 else "Other"

diagnoses_df = diagnoses_df.copy()
diagnoses_df["theme"] = diagnoses_df.apply(classify_theme, axis=1)

theme_summary = (
    diagnoses_df.groupby("theme")
    .agg(
        issues=("theme","size"),
        agents=("agent","nunique"),
        families=("family","nunique")
    )
    .sort_values(["issues","families"], ascending=[False,False])
)
theme_summary["share"] = theme_summary["issues"] / theme_summary["issues"].sum()
display(theme_summary)

article_rows = []
for _, row in diagnoses_df.iterrows():
    for article in row["article_numbers"]:
        article_rows.append({
            "article": article,
            "agent": row["agent"],
            "family": row["family"],
            "theme": row["theme"],
            "priority": row["priority"]
        })

article_mentions_df = pd.DataFrame(article_rows)
article_summary = (
    article_mentions_df.groupby("article")
    .agg(
        mentions=("article","size"),
        agents=("agent","nunique"),
        families=("family","nunique"),
        themes=("theme","nunique"),
        best_priority=("priority","min")
    )
    .sort_values(["families","mentions"], ascending=False)
)
display(article_summary.head(40))

# Up to 7 members per constellation, maximizing family diversity first.
MAX_CONSTELLATION_SIZE = 7
constellations = {}

for theme in theme_summary.index:
    pool = (
        diagnoses_df[diagnoses_df["theme"] == theme][["agent","family"]]
        .drop_duplicates()
    )
    activity = (
        diagnoses_df[diagnoses_df["theme"] == theme]
        .groupby("agent")
        .size()
        .rename("issue_count")
    )
    pool = pool.merge(activity, left_on="agent", right_index=True, how="left")
    pool = pool.sort_values("issue_count", ascending=False)

    chosen, families_seen = [], set()

    for _, r in pool.iterrows():
        if r["family"] not in families_seen:
            chosen.append(r["agent"])
            families_seen.add(r["family"])
        if len(chosen) >= MAX_CONSTELLATION_SIZE:
            break

    for _, r in pool.iterrows():
        if len(chosen) >= MAX_CONSTELLATION_SIZE:
            break
        if r["agent"] not in chosen:
            chosen.append(r["agent"])

    constellations[theme] = chosen

constellation_rows = []
for theme, members in constellations.items():
    for aid in members:
        constellation_rows.append({
            "theme": theme,
            "agent": aid,
            "family": agent_by_id[aid]["family"]
        })

constellations_df = pd.DataFrame(constellation_rows)
constellation_summary = (
    constellations_df.groupby("theme")
    .agg(members=("agent","count"), families=("family","nunique"))
)
display(constellation_summary)

warnings = [
    f"{theme}: only {row['families']} families"
    for theme, row in constellation_summary.iterrows()
    if row["families"] < 3
]
if warnings:
    print("Governance warnings:", warnings)
else:
    print("✓ Every constellation contains at least three institutional families.")

print("✓ Cell 7 complete: synchronized map and constellations ready.")

                            issues  agents  families     share
theme
Supervision & enforcement       45      29         7  0.255682
Other                           41      18         6  0.232955
Infrastructure & liquidity      37      20         5  0.210227
Access & offerings              30      19         7  0.170455
Disclosure & governance         10       9         6  0.056818
Intermediation                   7       5         4  0.039773
Innovation                       3       3         2  0.017045
Investor protection              3       3         1  0.017045

           mentions  agents  families  themes  best_priority
article
35                8       6         2       4              3
71                3       3         2       3              3
36                9       5         1       4              4
275               5       1         1       3              2
29                5       4         1       2              4
4                 5       5         1       3              4
226               4       1         1       3              3
64 Bis 1          4       4         1       2              3
112               3       1         1       3              3
12                3       3         1       1              4
144               3       1         1       1              3
190 Bis           3       1         1       2              4
305               3       1         1       2              3
96                3       1         1       2              4
103               2       1         1       1              4
108               2       1         1       2              4
108 Bis           2       1         1       1              3
118               2       1         1       1              3
123               2       1         1       2              3
125               2       1         1       2              4
126               2       1         1       1              3
128               2       1         1       2              3
145               2       1         1       1              3
146               2       1         1       2              4
160               2       1         1       2              3
164               2       1         1       1              4
171               2       1         1       2              3
173 Bis           2       1         1       2              3
177               2       1         1       2              3
177 Bis           2       1         1       2              4
180               2       1         1       2              3
181               2       1         1       2              4
183               2       1         1       1              3
189               2       1         1       2              4
190 Bis 1         2       1         1       1              4
201               2       1         1       2              3
202               2       1         1       2              3
204               2       1         1       2              3
217               2       1         1       1              2
219               2       1         1       1              2

                            members  families
theme
Access & offerings                7         7
Disclosure & governance           7         6
Infrastructure & liquidity        7         5
Innovation                        3         2
Intermediation                    5         4
Investor protection               3         1
Other                             7         6
Supervision & enforcement         7         7

Governance warnings: ['Innovation: only 2 families', 'Investor protection: only 1 families']
✓ Cell 7 complete: synchronized map and constellations ready.

## Cell 8 — Ronda 2: propuestas de reforma

Las constelaciones trabajan **en paralelo** y convierten diagnósticos en propuestas preliminares. La salida se obtiene mediante herramientas estructuradas, no mediante JSON escrito como texto. Además, la celda contiene un mecanismo de expansión: si la ronda temática no produce un universo suficientemente amplio, toma artículos diagnosticados pero todavía no cubiertos y solicita propuestas artículo por artículo. El objetivo es llegar a un conjunto de candidatos claramente mayor a veinte antes de la crítica adversarial.

In [ ]:
# @title
# ================================================================
# CELL 8 — ROUND 2: REFORM PROPOSALS
# PARALLEL CONSTELLATIONS + ITERATIVE ARTICLE COVERAGE EXPANSION
# ================================================================

from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd
import json


# ================================================================
# 0. PRECONDITIONS
# ================================================================

if "constellations" not in globals() or not constellations:
    raise RuntimeError("No constellations found. Run Cell 7 first.")

if "diagnoses_df" not in globals() or diagnoses_df.empty:
    raise RuntimeError("diagnoses_df is missing or empty. Run Cells 6 and 7 first.")

if "articles" not in globals() or not articles:
    raise RuntimeError("LMV articles are missing. Run Cell 3 first.")

if "agent_by_id" not in globals():
    agent_by_id = {a["id"]: a for a in agents}


TARGET_FINAL_ARTICLES = 20
PREFERRED_CANDIDATE_ARTICLES = 28


# ================================================================
# 1. STRUCTURED PROPOSAL TOOL
# ================================================================

PROP_TOOL = {
    "type": "object",
    "properties": {
        "proposals": {
            "type": "array",
            "minItems": 1,
            "maxItems": 5,
            "items": {
                "type": "object",
                "properties": {
                    "article": {"type": "string"},
                    "operation": {
                        "type": "string",
                        "enum": ["REFORM", "ADD", "REPEAL"]
                    },
                    "problem": {"type": "string"},
                    "policy_objective": {"type": "string"},
                    "draft_text": {"type": "string"},
                    "legal_rationale": {"type": "string"},
                    "expected_effects": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "implementation_risks": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "dependencies": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "supporting_roles": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "opposing_roles": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "unresolved_questions": {
                        "type": "array",
                        "items": {"type": "string"}
                    }
                },
                "required": [
                    "article",
                    "operation",
                    "problem",
                    "policy_objective",
                    "draft_text",
                    "legal_rationale",
                    "expected_effects",
                    "implementation_risks",
                    "dependencies",
                    "supporting_roles",
                    "opposing_roles",
                    "unresolved_questions"
                ],
                "additionalProperties": False
            }
        }
    },
    "required": ["proposals"],
    "additionalProperties": False
}


# ================================================================
# 2. CLEANING HELPERS
# ================================================================

def clean_proposal(p):

    if not isinstance(p, dict):
        return None

    article = normalize_article_ref(
        p.get("article", "")
    )

    if article != "NEW_PROVISION" and article not in articles:
        return None

    operation = str(
        p.get("operation", "")
    ).strip().upper()

    if operation not in {
        "REFORM",
        "ADD",
        "REPEAL"
    }:
        return None

    problem = str(
        p.get("problem", "")
    ).strip()

    policy_objective = str(
        p.get("policy_objective", "")
    ).strip()

    if not problem or not policy_objective:
        return None

    def as_list(v):
        if v is None:
            return []
        return v if isinstance(v, list) else [v]

    return {
        "article": article,
        "operation": operation,
        "problem": problem,
        "policy_objective": policy_objective,
        "draft_text": str(
            p.get("draft_text", "")
        ).strip(),
        "legal_rationale": str(
            p.get("legal_rationale", "")
        ).strip(),
        "expected_effects": as_list(
            p.get("expected_effects")
        ),
        "implementation_risks": as_list(
            p.get("implementation_risks")
        ),
        "dependencies": as_list(
            p.get("dependencies")
        ),
        "supporting_roles": as_list(
            p.get("supporting_roles")
        ),
        "opposing_roles": as_list(
            p.get("opposing_roles")
        ),
        "unresolved_questions": as_list(
            p.get("unresolved_questions")
        )
    }


def distinct_existing_candidates(df):

    if df is None or df.empty:
        return set()

    return {
        str(x)
        for x in df["article"]
        if str(x) in articles
    }


# ================================================================
# 3. ARTICLES RELEVANT TO EACH THEME
# ================================================================

def theme_article_set(theme, limit=20):

    rows = diagnoses_df[
        diagnoses_df["theme"] == theme
    ]

    counts = {}

    for xs in rows["article_numbers"]:

        if not isinstance(xs, list):
            continue

        for n in xs:

            n = normalize_article_ref(n)

            if n in articles:
                counts[n] = counts.get(n, 0) + 1

    ranked = sorted(
        counts.items(),
        key=lambda kv: kv[1],
        reverse=True
    )

    return [
        n
        for n, _ in ranked[:limit]
    ]


# ================================================================
# 4. CONSTELLATION ROUND
# ================================================================

def run_constellation(theme, members):

    lead = agent_by_id[
        members[0]
    ]

    issue_records = (
        diagnoses_df[
            diagnoses_df["theme"] == theme
        ]
        .sort_values(
            "priority",
            ascending=True
        )
        .head(18)
        .to_dict(
            orient="records"
        )
    )

    nums = theme_article_set(
        theme,
        limit=20
    )

    legal_context = "\n\n".join(
        f"[ARTICLE {n}]\n{articles[n][:4500]}"
        for n in nums
    )

    task = f"""
ROUND 2 — REFORM PROPOSALS

THEME
=====
{theme}

CONSTELLATION
=============
{json.dumps(
    [agent_by_id[m] for m in members],
    ensure_ascii=False,
    default=str
)}

ROUND 1 DIAGNOSES
=================
{json.dumps(
    issue_records,
    ensure_ascii=False,
    default=str
)}

TASK
====
Generate 3 to 5 DISTINCT preliminary proposals for reform
of the Mexican Ley del Mercado de Valores.

IMPORTANT:

1. Prefer DIFFERENT article numbers.

2. Every existing article proposed must appear in the
   authorized legal context.

3. Do not invent articles.

4. Each proposal must respond to an actual Round 1 diagnosis.

5. Preserve disagreements and implementation risks.

6. The objective is not simply more regulation or less regulation.
   It is a better securities-market framework.

7. Use NEW_PROVISION only if a genuinely new provision is needed.

This is preliminary legislative analysis, not final drafting.
"""

    result = structured_claude_call(
        agent=lead,
        purpose="round2_constellation",
        task=task,
        context=legal_context,
        tool_name="submit_reform_proposals",
        tool_description="Submit preliminary LMV reform proposals.",
        input_schema=PROP_TOOL,
        max_tokens=5000
    )

    return {
        "theme": theme,
        "lead": lead["id"],
        "members": members,
        "result": result
    }


# ================================================================
# 5. RUN CONSTELLATIONS IN PARALLEL
# ================================================================

proposals = []
constellation_status = []

print("=" * 76)
print("ROUND 2A — PARALLEL CONSTELLATION PROPOSALS")
print("=" * 76)

workers = min(
    MAX_CONSTELLATION_WORKERS,
    len(constellations)
)

with ThreadPoolExecutor(
    max_workers=workers
) as executor:

    future_map = {

        executor.submit(
            run_constellation,
            theme,
            members
        ): theme

        for theme, members
        in constellations.items()

        if members
    }

    for i, future in enumerate(
        as_completed(future_map),
        start=1
    ):

        theme = future_map[
            future
        ]

        try:

            outcome = future.result()

            valid = 0

            for raw in outcome[
                "result"
            ].get(
                "proposals",
                []
            ):

                cp = clean_proposal(
                    raw
                )

                if cp is None:
                    continue

                proposals.append({
                    "theme":
                        outcome["theme"],
                    "lead":
                        outcome["lead"],
                    "members":
                        outcome["members"],
                    "proposal_pass":
                        "constellation",
                    **cp
                })

                valid += 1

            constellation_status.append({
                "theme": theme,
                "status":
                    "OK"
                    if valid
                    else "NO_VALID_PROPOSALS",
                "valid": valid,
                "error": ""
            })

        except Exception as e:

            constellation_status.append({
                "theme": theme,
                "status": "ERROR",
                "valid": 0,
                "error": str(e)[:500]
            })

        print(
            f"[{i:02d}/{len(future_map):02d}] "
            f"{theme}"
        )


proposals_df = pd.DataFrame(
    proposals
)

constellation_status_df = pd.DataFrame(
    constellation_status
)


# ================================================================
# 6. INITIAL CANDIDATE COUNT
# ================================================================

candidate_articles = (
    distinct_existing_candidates(
        proposals_df
    )
)

print()
print(
    "Initial usable proposals:",
    len(proposals_df)
)

print(
    "Initial distinct existing article candidates:",
    len(candidate_articles)
)


# ================================================================
# 7. RANK ALL DIAGNOSED ARTICLES
# ================================================================

article_support = {}

for _, row in diagnoses_df.iterrows():

    for n in row[
        "article_numbers"
    ]:

        n = normalize_article_ref(
            n
        )

        if n not in articles:
            continue

        if n not in article_support:

            article_support[n] = {
                "mentions": 0,
                "agents": set(),
                "families": set(),
                "best_priority": 99
            }

        article_support[n][
            "mentions"
        ] += 1

        article_support[n][
            "agents"
        ].add(
            row["agent"]
        )

        article_support[n][
            "families"
        ].add(
            row["family"]
        )

        article_support[n][
            "best_priority"
        ] = min(
            article_support[n][
                "best_priority"
            ],
            int(
                row.get(
                    "priority",
                    5
                )
            )
        )


ranked_diagnosed_articles = sorted(

    article_support.keys(),

    key=lambda n: (

        len(
            article_support[n][
                "families"
            ]
        ),

        len(
            article_support[n][
                "agents"
            ]
        ),

        article_support[n][
            "mentions"
        ],

        -article_support[n][
            "best_priority"
        ]

    ),

    reverse=True
)


print(
    "Distinct diagnosed LMV articles:",
    len(ranked_diagnosed_articles)
)


# ================================================================
# 8. ARTICLE-SPECIFIC STRUCTURED TOOL
# ================================================================

ARTICLE_PROPOSAL_TOOL = {

    "type": "object",

    "properties": {

        "decision": {
            "type": "string",
            "enum": [
                "PROPOSE",
                "SKIP"
            ]
        },

        "reason": {
            "type": "string"
        },

        "proposal": {
            "type": "object",

            "properties": {

                "article": {
                    "type": "string"
                },

                "operation": {
                    "type": "string",
                    "enum": [
                        "REFORM",
                        "ADD",
                        "REPEAL"
                    ]
                },

                "problem": {
                    "type": "string"
                },

                "policy_objective": {
                    "type": "string"
                },

                "draft_text": {
                    "type": "string"
                },

                "legal_rationale": {
                    "type": "string"
                },

                "expected_effects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },

                "implementation_risks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },

                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },

                "supporting_roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },

                "opposing_roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },

                "unresolved_questions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },

            "required": [
                "article",
                "operation",
                "problem",
                "policy_objective",
                "draft_text",
                "legal_rationale",
                "expected_effects",
                "implementation_risks",
                "dependencies",
                "supporting_roles",
                "opposing_roles",
                "unresolved_questions"
            ],

            "additionalProperties":
                False
        }
    },

    "required": [
        "decision",
        "reason"
    ],

    "additionalProperties":
        False
}


# ================================================================
# 9. ARTICLE-SPECIFIC PROPOSAL FUNCTION
# ================================================================

def propose_specific_article(
    article,
    attempt_number=0
):

    related = diagnoses_df[
        diagnoses_df[
            "article_numbers"
        ].apply(
            lambda xs:
                isinstance(xs, list)
                and article in xs
        )
    ].copy()

    related = (
        related
        .sort_values(
            "priority",
            ascending=True
        )
        .head(15)
    )

    # Different institutional lens on retry
    agent_index = (
        article_sort_key(article)
        + attempt_number * 11
    ) % len(agents)

    agent = agents[
        agent_index
    ]

    task = f"""
ARTICLE-SPECIFIC REFORM ASSESSMENT

TARGET ARTICLE
==============
{article}

ROUND 1 DIAGNOSES
=================
{json.dumps(
    related.to_dict(
        orient="records"
    ),
    ensure_ascii=False,
    default=str
)}

TASK
====
Determine whether Article {article} presents a sufficiently
important and supportable opportunity for reform in the context
of this exercise.

Remember that the overall project must ultimately identify
20 distinct LMV articles for a reform initiative.

This does NOT mean that you should invent a problem.

If the evidence supports a meaningful improvement:
    decision = PROPOSE

and produce ONE concrete proposal for Article {article}.

If the evidence genuinely does not justify reform:
    decision = SKIP

The article number MUST remain exactly {article}.

Possible operations:
REFORM
ADD
REPEAL

Do not invent legal text or external evidence.
"""

    result = structured_claude_call(

        agent=agent,

        purpose=f"round2_article_{article}",

        task=task,

        context=(
            f"[CURRENT ARTICLE {article}]\n"
            f"{articles[article][:7000]}"
        ),

        tool_name=
            "submit_article_assessment",

        tool_description=(
            "Assess and, when supported, propose "
            "one reform for a specified LMV article."
        ),

        input_schema=
            ARTICLE_PROPOSAL_TOOL,

        max_tokens=3000
    )

    return {
        "agent": agent,
        "article": article,
        "result": result
    }


# ================================================================
# 10. ITERATIVE COVERAGE EXPANSION
# ================================================================
#
# This is the key repair.
#
# We continue through diagnosed articles in waves until:
#
#   a) we reach the preferred 28 candidates, or
#   b) we exhaust the diagnosed article universe.
#
# ================================================================

attempted_articles = set()
skipped_articles = set()

MAX_EXPANSION_ROUNDS = 6
BATCH_SIZE = 8


for expansion_round in range(
    1,
    MAX_EXPANSION_ROUNDS + 1
):

    candidate_articles = (
        distinct_existing_candidates(
            proposals_df
        )
    )

    if len(
        candidate_articles
    ) >= PREFERRED_CANDIDATE_ARTICLES:

        print(
            "\n✓ Preferred candidate universe reached."
        )

        break


    available = [

        n
        for n
        in ranked_diagnosed_articles

        if n not in candidate_articles
        and n not in attempted_articles
    ]


    if not available:

        print(
            "\nNo additional diagnosed articles remain."
        )

        break


    batch = available[
        :BATCH_SIZE
    ]


    print()
    print(
        "=" * 76
    )

    print(
        f"ROUND 2B.{expansion_round} — "
        f"ARTICLE COVERAGE EXPANSION"
    )

    print(
        "=" * 76
    )

    print(
        "Current distinct candidates:",
        len(candidate_articles)
    )

    print(
        "Articles in this batch:",
        batch
    )


    expansion_rows = []


    with ThreadPoolExecutor(
        max_workers=min(
            MAX_REVIEW_WORKERS,
            len(batch)
        )
    ) as executor:

        future_map = {

            executor.submit(
                propose_specific_article,
                article,
                expansion_round - 1
            ): article

            for article in batch
        }


        for i, future in enumerate(
            as_completed(
                future_map
            ),
            start=1
        ):

            article = future_map[
                future
            ]

            attempted_articles.add(
                article
            )

            try:

                outcome = future.result()

                result = outcome[
                    "result"
                ]

                decision = result.get(
                    "decision",
                    "SKIP"
                )

                if decision == "PROPOSE":

                    raw = result.get(
                        "proposal"
                    )

                    cp = clean_proposal(
                        raw
                    )

                    if (
                        cp
                        and cp[
                            "article"
                        ] == article
                    ):

                        expansion_rows.append({

                            "theme":
                                classify_theme({
                                    "title":
                                        cp["problem"],
                                    "problem":
                                        cp["problem"],
                                    "policy_objective":
                                        cp[
                                            "policy_objective"
                                        ],
                                    "evidence":
                                        ""
                                }),

                            "lead":
                                outcome[
                                    "agent"
                                ][
                                    "id"
                                ],

                            "members": [
                                outcome[
                                    "agent"
                                ][
                                    "id"
                                ]
                            ],

                            "proposal_pass":
                                f"coverage_{expansion_round}",

                            **cp
                        })

                    else:

                        print(
                            f"Article {article}: "
                            f"invalid structured proposal."
                        )

                else:

                    skipped_articles.add(
                        article
                    )

            except Exception as e:

                print(
                    f"Article {article} failed: {e}"
                )

            print(
                f"[{i:02d}/{len(batch):02d}] "
                f"Article {article}"
            )


    if expansion_rows:

        proposals_df = pd.concat(
            [
                proposals_df,
                pd.DataFrame(
                    expansion_rows
                )
            ],
            ignore_index=True
        )


    # ------------------------------------------------------------
    # Deduplicate exact conceptual duplicates
    # ------------------------------------------------------------

    if not proposals_df.empty:

        proposals_df[
            "problem_key"
        ] = (
            proposals_df[
                "problem"
            ]
            .astype(str)
            .str.lower()
            .str.replace(
                r"\s+",
                " ",
                regex=True
            )
            .str[:180]
        )

        proposals_df = (
            proposals_df
            .drop_duplicates(
                [
                    "article",
                    "operation",
                    "problem_key"
                ]
            )
            .drop(
                columns=[
                    "problem_key"
                ]
            )
            .reset_index(
                drop=True
            )
        )


    candidate_articles = (
        distinct_existing_candidates(
            proposals_df
        )
    )


    print(
        "Distinct candidates after this round:",
        len(candidate_articles)
    )


# ================================================================
# 11. EMERGENCY RETRY FOR FAILED / UNPROPOSED ARTICLES
# ================================================================
#
# If we are still below 20, retry the strongest remaining
# diagnosed articles with a DIFFERENT institutional lens.
# ================================================================

candidate_articles = (
    distinct_existing_candidates(
        proposals_df
    )
)


if len(
    candidate_articles
) < TARGET_FINAL_ARTICLES:

    print()
    print(
        "=" * 76
    )

    print(
        "ROUND 2C — FINAL RECOVERY PASS"
    )

    print(
        "=" * 76
    )


    remaining = [

        n
        for n
        in ranked_diagnosed_articles

        if n not in candidate_articles
    ]


    needed = (
        TARGET_FINAL_ARTICLES
        -
        len(candidate_articles)
    )


    # Ask more than strictly needed
    recovery_batch = remaining[
        :max(
            needed * 3,
            10
        )
    ]


    recovery_rows = []


    with ThreadPoolExecutor(
        max_workers=min(
            MAX_REVIEW_WORKERS,
            len(recovery_batch)
        )
    ) as executor:

        future_map = {

            executor.submit(
                propose_specific_article,
                article,
                99
            ): article

            for article
            in recovery_batch
        }


        for future in as_completed(
            future_map
        ):

            article = future_map[
                future
            ]

            try:

                outcome = future.result()

                result = outcome[
                    "result"
                ]

                if result.get(
                    "decision"
                ) != "PROPOSE":

                    continue


                cp = clean_proposal(
                    result.get(
                        "proposal"
                    )
                )


                if not cp:
                    continue


                if cp[
                    "article"
                ] != article:
                    continue


                recovery_rows.append({

                    "theme":
                        classify_theme({
                            "title":
                                cp["problem"],
                            "problem":
                                cp["problem"],
                            "policy_objective":
                                cp[
                                    "policy_objective"
                                ],
                            "evidence":
                                ""
                        }),

                    "lead":
                        outcome[
                            "agent"
                        ][
                            "id"
                        ],

                    "members": [
                        outcome[
                            "agent"
                        ][
                            "id"
                        ]
                    ],

                    "proposal_pass":
                        "recovery",

                    **cp
                })

            except Exception as e:

                print(
                    f"Recovery failed for "
                    f"Article {article}: {e}"
                )


    if recovery_rows:

        proposals_df = pd.concat(
            [
                proposals_df,
                pd.DataFrame(
                    recovery_rows
                )
            ],
            ignore_index=True
        )


# ================================================================
# 12. FINAL DEDUPLICATION
# ================================================================

if not proposals_df.empty:

    proposals_df[
        "problem_key"
    ] = (
        proposals_df[
            "problem"
        ]
        .astype(str)
        .str.lower()
        .str.replace(
            r"\s+",
            " ",
            regex=True
        )
        .str[:180]
    )

    proposals_df = (
        proposals_df
        .drop_duplicates(
            [
                "article",
                "operation",
                "problem_key"
            ]
        )
        .drop(
            columns=[
                "problem_key"
            ]
        )
        .reset_index(
            drop=True
        )
    )


candidate_articles = (
    distinct_existing_candidates(
        proposals_df
    )
)


# ================================================================
# 13. FINAL REPORT
# ================================================================

print()
print(
    "=" * 76
)

print(
    "ROUND 2 COMPLETE"
)

print(
    "=" * 76
)

print(
    "Usable proposals:",
    len(proposals_df)
)

print(
    "Distinct existing LMV article candidates:",
    len(candidate_articles)
)

print(
    "Target final articles:",
    TARGET_FINAL_ARTICLES
)

print(
    "Preferred candidate universe:",
    PREFERRED_CANDIDATE_ARTICLES
)


display(
    constellation_status_df
)


if not proposals_df.empty:

    display(
        proposals_df[
            [
                "theme",
                "lead",
                "article",
                "operation",
                "proposal_pass",
                "problem",
                "policy_objective"
            ]
        ]
        .sort_values(
            [
                "article",
                "proposal_pass"
            ]
        )
    )


# ================================================================
# 14. HARD GATE
# ================================================================

if len(
    candidate_articles
) < TARGET_FINAL_ARTICLES:

    missing = (
        TARGET_FINAL_ARTICLES
        -
        len(candidate_articles)
    )

    raise RuntimeError(
        f"Round 2 still produced only "
        f"{len(candidate_articles)} distinct existing article candidates. "
        f"We need {TARGET_FINAL_ARTICLES}; shortage = {missing}. "
        f"This now means the diagnosed corpus itself did not support "
        f"enough additional reforms, rather than merely a one-pass "
        f"coverage failure."
    )


if len(
    candidate_articles
) < PREFERRED_CANDIDATE_ARTICLES:

    print()
    print(
        "⚠ Candidate universe is sufficient for the "
        "20-article mandate but smaller than the preferred "
        f"{PREFERRED_CANDIDATE_ARTICLES}-article competition set."
    )

else:

    print()
    print(
        "✓ Preferred candidate universe achieved."
    )


print()
print(
    f"✓ {len(candidate_articles)} distinct LMV "
    "article candidates available."
)

print(
    "✓ Ready for Cell 9 — adversarial review."
)

============================================================================
ROUND 2A — PARALLEL CONSTELLATION PROPOSALS
============================================================================
[01/08] Other
[02/08] Supervision & enforcement
[03/08] Infrastructure & liquidity
[04/08] Disclosure & governance
[05/08] Access & offerings
[06/08] Investor protection
[07/08] Innovation
[08/08] Intermediation

Initial usable proposals: 0
Initial distinct existing article candidates: 0
Distinct diagnosed LMV articles: 169

============================================================================
ROUND 2B.1 — ARTICLE COVERAGE EXPANSION
============================================================================
Current distinct candidates: 0
Articles in this batch: ['35', '71', '36', '4', '29', '64 Bis 1', '12', '44']
[01/08] Article 44
[02/08] Article 29
[03/08] Article 71
[04/08] Article 12
[05/08] Article 4
Article 36: invalid structured proposal.
[06/08] Article 36
Article 35: invalid structured proposal.
[07/08] Article 35
Article 64 Bis 1: invalid structured proposal.
[08/08] Article 64 Bis 1
Distinct candidates after this round: 5

============================================================================
ROUND 2B.2 — ARTICLE COVERAGE EXPANSION
============================================================================
Current distinct candidates: 5
Articles in this batch: ['275', '226', '112', '144', '305', '96', '190 Bis', '217']
[01/08] Article 144
[02/08] Article 112
[03/08] Article 96
[04/08] Article 275
[05/08] Article 190 Bis
[06/08] Article 305
[07/08] Article 217
Article 226: invalid structured proposal.
[08/08] Article 226
Distinct candidates after this round: 12

============================================================================
ROUND 2B.3 — ARTICLE COVERAGE EXPANSION
============================================================================
Current distinct candidates: 12
Articles in this batch: ['219', '64 Bis 2', '66', '67', '70 Bis', '108 Bis', '87', '88']
[01/08] Article 66
[02/08] Article 108 Bis
Article 219: invalid structured proposal.
[03/08] Article 219
Article 87: invalid structured proposal.
[04/08] Article 87
Article 67: invalid structured proposal.
[05/08] Article 67
Article 88: invalid structured proposal.
[06/08] Article 88
Article 70 Bis: invalid structured proposal.
[07/08] Article 70 Bis
[08/08] Article 64 Bis 2
Distinct candidates after this round: 15

============================================================================
ROUND 2B.4 — ARTICLE COVERAGE EXPANSION
============================================================================
Current distinct candidates: 15
Articles in this batch: ['123', '126', '118', '145', '160', '128', '171', '173 Bis']
[01/08] Article 173 Bis
[02/08] Article 160
[03/08] Article 126
[04/08] Article 123
[05/08] Article 171
Article 118: invalid structured proposal.
[06/08] Article 118
Article 145: invalid structured proposal.
[07/08] Article 145
Article 128: invalid structured proposal.
[08/08] Article 128
Distinct candidates after this round: 20

============================================================================
ROUND 2B.5 — ARTICLE COVERAGE EXPANSION
============================================================================
Current distinct candidates: 20
Articles in this batch: ['177', '183', '180', '202', '201', '204', '229', '237']
[01/08] Article 237
[02/08] Article 202
[03/08] Article 177
[04/08] Article 180
[05/08] Article 183
Article 229: invalid structured proposal.
[06/08] Article 229
[07/08] Article 204
[08/08] Article 201
Distinct candidates after this round: 27

============================================================================
ROUND 2B.6 — ARTICLE COVERAGE EXPANSION
============================================================================
Current distinct candidates: 27
Articles in this batch: ['236', '255', '266', '267', '103', '108', '125', '146']
[01/08] Article 255
[02/08] Article 103
[03/08] Article 236
[04/08] Article 125
[05/08] Article 267
[06/08] Article 108
[07/08] Article 146
Article 266: invalid structured proposal.
[08/08] Article 266
Distinct candidates after this round: 33

============================================================================
ROUND 2 COMPLETE
============================================================================
Usable proposals: 33
Distinct existing LMV article candidates: 33
Target final articles: 20
Preferred candidate universe: 28

                        theme              status  valid error
0                       Other  NO_VALID_PROPOSALS      0
1   Supervision & enforcement  NO_VALID_PROPOSALS      0
2  Infrastructure & liquidity  NO_VALID_PROPOSALS      0
3     Disclosure & governance  NO_VALID_PROPOSALS      0
4          Access & offerings  NO_VALID_PROPOSALS      0
5         Investor protection  NO_VALID_PROPOSALS      0
6                  Innovation  NO_VALID_PROPOSALS      0
7              Intermediation  NO_VALID_PROPOSALS      0

,theme,lead,article,operation,proposal_pass,problem,policy_objective
27,Other,A09,103,REFORM,coverage_6,Article 103 obligates persons to conduct a man...,"Establish clear, bright-line thresholds for 'c..."
31,Disclosure & governance,A14,108,REFORM,coverage_6,Article 108.I.b establishes a mandatory buybac...,"Establish clear, objectively-verifiable valuat..."
13,Supervision & enforcement,A31,108 Bis,REFORM,coverage_3,Article 108 Bis creates three distinct procedu...,"Establish transparent, supervisable cancellati..."
6,Supervision & enforcement,A24,112,REFORM,coverage_2,Article 112 delegates computation mechanics fo...,"Establish clear, verifiable, and proportionate..."
3,Other,A13,12,REFORM,coverage_1,Article 12 permits conversion of ordinary soci...,"Establish transparent, time-bound procedures f..."
18,Infrastructure & liquidity,A07,123,REFORM,coverage_4,Article 123 mandates that at least 25% of boar...,"Establish clear, supervisable statutory standa..."
29,Access & offerings,A31,125,REFORM,coverage_6,Article 125 establishes proportional appointme...,Decouple independent director selection from p...
17,Supervision & enforcement,A10,126,REFORM,coverage_4,Article 126 mandates an audit committee but de...,Embed minimum audit committee requirements in ...
5,Other,A06,144,REFORM,coverage_2,Article 144 vests plenos poderes in an interve...,"Establish transparent, time-bound, and account..."
32,Other,A02,146,REFORM,coverage_6,Article 146 authorizes the Commission to estab...,"Establish binding, transparent, and proportion..."
16,Access & offerings,A44,160,REFORM,coverage_4,Article 160 imposes two regulatory burdens wit...,Maintain prudential authorization control whil...
19,Access & offerings,A05,171,REFORM,coverage_4,Article 171(I) and 171(VII) authorize simplifi...,Establish a statutory foundation for proportio...
15,Supervision & enforcement,A07,173 Bis,REFORM,coverage_4,Article 173 Bis mandates uniform annual capita...,Embed proportionality and statutory transparen...
22,Supervision & enforcement,A22,177,REFORM,coverage_5,Article 177 grants CNBV unconstrained discreti...,Establish statutory guardrails on auditor rota...
23,Infrastructure & liquidity,A25,180,REFORM,coverage_5,Article 180(p) imposes categorical sanctions f...,"Introduce proportional, tiered enforcement arc..."
24,Infrastructure & liquidity,A28,183,REFORM,coverage_5,Article 183 authorizes casas de bolsa to hold ...,Require casas de bolsa to disclose (at publica...
9,Supervision & enforcement,A02,190 Bis,REFORM,coverage_2,Article 190 Bis mandates product analysis comm...,Establish minimum statutory guardrails for pro...
26,Access & offerings,A46,201,REFORM,coverage_5,Article 201 requires brokerages to deliver ass...,Enhance market infrastructure efficiency and i...
21,Supervision & enforcement,A47,202,REFORM,coverage_5,Article 202 permits unilateral contract modifi...,Strengthen investor protection through enhance...
25,Infrastructure & liquidity,A49,204,REFORM,coverage_5,Article 204 establishes a private extra-judici...,Strengthen market integrity and price discover...
11,Supervision & enforcement,A29,217,REFORM,coverage_2,Article 217 permits CNBV to order clausura (of...,"Establish a graduated, proportionate enforceme..."
28,Supervision & enforcement,A42,236,REFORM,coverage_6,Article 236 requires exchanges to demonstrate ...,Establish a mandatory operational transition a...
20,Access & offerings,A32,237,REFORM,coverage_5,"Article 237, paragraph 5 restricts exchange-ca...",Clarify and rationalize Article 237 to (a) ena...
30,Other,A23,267,REFORM,coverage_6,Article 267 mandates five-year retention of tr...,Extend and clarify record-retention requiremen...
8,Supervision & enforcement,A37,275,REFORM,coverage_2,Article 275 grants CNBV open-ended discretion ...,"Establish a transparent, criteria-based author..."
1,Access & offerings,A30,29,REFORM,coverage_1,Article 29(II) imposes liability on directors ...,"Balance director accountability for material, ..."
10,Supervision & enforcement,A17,305,REFORM,coverage_2,Article 305 contains two structural deficienci...,Eliminate circular cross-references and define...
4,Other,A05,4,REFORM,coverage_1,Article 4 preserves acts in breach of the LMV ...,Operationalize Article 4's protective intent b...
0,Other,A45,44,REFORM,coverage_1,Article 44 requires finance and legal area hea...,Clarify the scope and standard of review oblig...
14,Access & offerings,A37,64 Bis 2,REFORM,coverage_3,"Article 64 Bis 2, Fraction IV requires issuers...",Establish statutory proportionality constraint...
12,Supervision & enforcement,A39,66,REFORM,coverage_3,Article 66 permits optional titles to referenc...,"Establish a transparent, predictable mechanism..."
2,Access & offerings,A22,71,REFORM,coverage_1,Article 71 provides that registered securities...,Define 'efectivamente colocados' by reference ...
7,Supervision & enforcement,A08,96,REFORM,coverage_2,Article 96.II.c permits disclosure of prior ag...,"Establish clear, enforceable standards for pri..."

✓ Preferred candidate universe achieved.

✓ 33 distinct LMV article candidates available.
✓ Ready for Cell 9 — adversarial review.

## Cell 9 — Ronda 3: crítica adversarial

Cada propuesta recibe una revisión independiente por un agente de una familia distinta a la del proponente. Las revisiones se ejecutan en paralelo y utilizan salida estructurada. El artículo y la identidad de la propuesta permanecen bajo control determinista de Python; el modelo sólo evalúa. La ronda puntúa coherencia, protección al inversionista, proporcionalidad, implementabilidad, claridad, evidencia, impacto de mercado y riesgo regulatorio, y conserva la objeción más fuerte.

In [ ]:
# @title
# Cell 9 — Round 3: parallel adversarial review with deterministic proposal identity
ADVERSARIAL_REVIEW_TOOL = {
    "type": "object",
    "properties": {
        "overall_assessment": {"type": "string"},
        "coherence": {"type": "integer", "minimum": 1, "maximum": 5},
        "investor_protection": {"type": "integer", "minimum": 1, "maximum": 5},
        "proportionality": {"type": "integer", "minimum": 1, "maximum": 5},
        "implementability": {"type": "integer", "minimum": 1, "maximum": 5},
        "legislative_clarity": {"type": "integer", "minimum": 1, "maximum": 5},
        "evidence_quality": {"type": "integer", "minimum": 1, "maximum": 5},
        "market_impact": {"type": "integer", "minimum": 1, "maximum": 5},
        "regulatory_risk": {"type": "integer", "minimum": 1, "maximum": 5},
        "strongest_objection": {"type": "string"},
        "possible_unintended_consequences": {"type": "array", "items": {"type": "string"}},
        "missing_dependencies": {"type": "array", "items": {"type": "string"}},
        "comparative_note": {"type": "string"},
        "comparative_source_status": {"type": "string", "enum": ["VERIFIED","HYPOTHESIS","NONE"]},
        "recommended_action": {"type": "string", "enum": ["KEEP","REVISE","DROP"]},
        "revision_needed": {"type": "string"}
    },
    "required": [
        "overall_assessment","coherence","investor_protection","proportionality","implementability",
        "legislative_clarity","evidence_quality","market_impact","regulatory_risk",
        "strongest_objection","possible_unintended_consequences","missing_dependencies",
        "comparative_note","comparative_source_status","recommended_action","revision_needed"
    ],
    "additionalProperties": False
}

PREFERRED_REVIEWERS = {
    "Access & offerings": ["Institutional investors","Regulators","Practicing lawyers"],
    "Disclosure & governance": ["Issuers","Institutional investors","Regulators"],
    "Intermediation": ["Institutional investors","Regulators","Practicing lawyers"],
    "Infrastructure & liquidity": ["Regulators","Institutional investors","Practicing lawyers"],
    "Supervision & enforcement": ["Practicing lawyers","Issuers","Broker-dealers"],
    "Innovation": ["Regulators","Institutional investors","Comparative law & academia"],
    "Investor protection": ["Issuers","Broker-dealers","Practicing lawyers"],
    "Other": ["Comparative law & academia","Regulators","Practicing lawyers"]
}

reviewer_use_count = {a["id"]: 0 for a in agents}
reviewer_lock = threading.Lock()

def choose_reviewer(row):
    lead = agent_by_id[row["lead"]]
    preferred = PREFERRED_REVIEWERS.get(row.get("theme","Other"), PREFERRED_REVIEWERS["Other"])
    candidates = [a for a in agents if a["family"] != lead["family"]]

    # Prefer counter-perspective, then least-used reviewer for diversity.
    ranked = []
    for a in candidates:
        pref_rank = preferred.index(a["family"]) if a["family"] in preferred else 99
        ranked.append((pref_rank, reviewer_use_count[a["id"]], a["agent_number"], a))
    ranked.sort(key=lambda x: (x[0], x[1], x[2]))
    chosen = ranked[0][3]

    with reviewer_lock:
        reviewer_use_count[chosen["id"]] += 1

    return chosen

def review_one(proposal_index, row):
    reviewer = choose_reviewer(row)
    article = str(row["article"])
    current = (
        f"[ARTICLE {article}]\n{articles[article][:6000]}"
        if article in articles else
        "NEW_PROVISION — no current article text."
    )

    payload = {
        k: row.get(k, "")
        for k in [
            "theme","lead","article","operation","problem","policy_objective","draft_text",
            "legal_rationale","expected_effects","implementation_risks","dependencies",
            "supporting_roles","opposing_roles","unresolved_questions"
        ]
    }

    task = f"""ROUND 3 — ADVERSARIAL REVIEW.
You did not author this proposal. Challenge it independently.
Proposal:
{json.dumps(payload, ensure_ascii=False, default=str)}

Evaluate legal coherence, investor protection, proportionality, implementability,
legislative clarity, evidence quality, likely market impact and regulatory risk.
For regulatory_risk, 5 means LOW/MANAGEABLE risk and 1 means SEVERE risk,
so higher is better for every score.
Identify the strongest objection even if you recommend KEEP.
Do not rewrite the proposal. Comparative claims are VERIFIED only if the authorized context supports them."""

    result = structured_claude_call(
        reviewer, "round3_review", task, current,
        "submit_adversarial_review",
        "Submit an independent adversarial review.",
        ADVERSARIAL_REVIEW_TOOL,
        max_tokens=3000
    )

    return {
        "proposal_index": proposal_index,
        "article": article,  # deterministic; not supplied by the model
        "reviewer": reviewer["id"],
        "reviewer_family": reviewer["family"],
        **result
    }

reviews, review_status = [], []

print("=" * 72)
print("ROUND 3 — ADVERSARIAL REVIEWS IN PARALLEL")
print("=" * 72)

with ThreadPoolExecutor(max_workers=MAX_REVIEW_WORKERS) as ex:
    futures = {
        ex.submit(review_one, idx, row): idx
        for idx, row in proposals_df.iterrows()
    }

    for i, f in enumerate(as_completed(futures), 1):
        idx = futures[f]
        try:
            reviews.append(f.result())
            review_status.append({"proposal_index": idx, "status": "OK", "error": ""})
        except Exception as e:
            review_status.append({"proposal_index": idx, "status": "ERROR", "error": str(e)[:500]})
        print(f"[{i:02d}/{len(futures):02d}] proposal {idx}")

reviews_df = pd.DataFrame(reviews)
review_status_df = pd.DataFrame(review_status)

if reviews_df.empty:
    raise RuntimeError("Round 3 produced no usable reviews.")

SCORE_COLS = [
    "coherence","investor_protection","proportionality","implementability",
    "legislative_clarity","evidence_quality","market_impact","regulatory_risk"
]
for c in SCORE_COLS:
    reviews_df[c] = pd.to_numeric(reviews_df[c], errors="coerce")

reviews_df["review_score"] = reviews_df[SCORE_COLS].mean(axis=1)

# Merge metadata WITHOUT article to avoid article_x/article_y.
proposal_meta = proposals_df[
    ["theme","operation","lead","problem","policy_objective"]
].copy()
proposal_meta["proposal_index"] = proposal_meta.index

reviews_df = reviews_df.merge(
    proposal_meta,
    on="proposal_index",
    how="left",
    validate="one_to_one"
)

print("\nADVERSARIAL REVIEW SUMMARY")
display(
    reviews_df[
        [
            "proposal_index","theme","article","operation","lead","reviewer",
            "reviewer_family","review_score","recommended_action","strongest_objection"
        ]
    ].sort_values("review_score", ascending=False)
)

display(reviews_df["recommended_action"].value_counts().rename("proposals").to_frame())

missing = sorted(set(proposals_df.index) - set(reviews_df["proposal_index"]))
if missing:
    print("⚠ Proposals without a successful review:", missing)
else:
    print("✓ Every proposal received an adversarial review.")

same_family = []
for _, r in reviews_df.iterrows():
    if agent_by_id[r["lead"]]["family"] == r["reviewer_family"]:
        same_family.append(r["proposal_index"])
if same_family:
    raise RuntimeError(f"Reviewer independence failed for proposals: {same_family}")

print("✓ Round 3 complete and reviewer independence verified.")

========================================================================
ROUND 3 — ADVERSARIAL REVIEWS IN PARALLEL
========================================================================
[01/33] proposal 4
[02/33] proposal 0
[03/33] proposal 7
[04/33] proposal 5
[05/33] proposal 1
[06/33] proposal 3
[07/33] proposal 6
[08/33] proposal 2
[09/33] proposal 10
[10/33] proposal 12
[11/33] proposal 13
[12/33] proposal 8
[13/33] proposal 11
[14/33] proposal 9
[15/33] proposal 15
[16/33] proposal 14
[17/33] proposal 17
[18/33] proposal 16
[19/33] proposal 19
[20/33] proposal 18
[21/33] proposal 21
[22/33] proposal 22
[23/33] proposal 23
[24/33] proposal 20
[25/33] proposal 24
[26/33] proposal 26
[27/33] proposal 27
[28/33] proposal 28
[29/33] proposal 25
[30/33] proposal 29
[31/33] proposal 30
[32/33] proposal 31
[33/33] proposal 32

ADVERSARIAL REVIEW SUMMARY

,proposal_index,theme,article,operation,lead,reviewer,reviewer_family,review_score,recommended_action,strongest_objection
16,17,Supervision & enforcement,126,REFORM,A10,A07,Practicing lawyers,3.750,REVISE,"The draft delegates the definition of ""hallazg..."
4,1,Access & offerings,29,REFORM,A30,A40,Institutional investors,3.625,REVISE,"The proposal's safe harbor for reliance on ""pr..."
12,11,Supervision & enforcement,217,REFORM,A29,A04,Practicing lawyers,3.375,KEEP,The proposal mandates a 90% client notificatio...
9,12,Supervision & enforcement,66,REFORM,A39,A05,Practicing lawyers,3.375,REVISE,The proposal assigns substantive authorization...
14,15,Supervision & enforcement,173 Bis,REFORM,A07,A24,Issuers,3.375,REVISE,"The statutory delegation to define 'size,' 'co..."
19,18,Infrastructure & liquidity,123,REFORM,A07,A16,Regulators,3.375,REVISE,The proposal defines 'participación significat...
13,9,Supervision & enforcement,190 Bis,REFORM,A02,A23,Issuers,3.250,KEEP,The 'reasonableness' definition in subsection ...
7,2,Access & offerings,71,REFORM,A22,A41,Institutional investors,3.250,REVISE,The proposal delegates to CNBV the maintenance...
2,7,Supervision & enforcement,96,REFORM,A08,A22,Issuers,3.250,REVISE,"The ""completeness certification"" requirement f..."
5,3,Other,12,REFORM,A13,A47,Comparative law & academia,3.250,REVISE,"The 30-day payment obligation, while aligned w..."
10,13,Supervision & enforcement,108 Bis,REFORM,A31,A06,Practicing lawyers,3.250,REVISE,The proposal's diagnosis of Fraction I interna...
8,10,Supervision & enforcement,305,REFORM,A17,A03,Practicing lawyers,3.125,REVISE,The proposal replaces one set of circular refe...
3,5,Other,144,REFORM,A06,A49,Comparative law & academia,3.125,REVISE,The 12-month initial ceiling with mandatory qu...
17,16,Access & offerings,160,REFORM,A44,A15,Regulators,3.000,REVISE,"Section II(b) permits authorization ""continuit..."
15,14,Access & offerings,64 Bis 2,REFORM,A37,A42,Institutional investors,3.000,REVISE,The 20% annual statutory penalty ceiling lacks...
25,26,Access & offerings,201,REFORM,A46,A45,Institutional investors,3.000,REVISE,The 10-day settlement timeline is mechanistica...
0,4,Other,4,REFORM,A05,A48,Comparative law & academia,2.750,REVISE,"The proposal references undefined articles [x,..."
21,22,Supervision & enforcement,177,REFORM,A22,A01,Practicing lawyers,2.750,REVISE,The proposal's core error is treating discreti...
22,23,Infrastructure & liquidity,180,REFORM,A25,A17,Regulators,2.750,REVISE,The proposal's central implementability flaw i...
27,28,Supervision & enforcement,236,REFORM,A42,A02,Practicing lawyers,2.625,REVISE,The proposal mandates insurance or guarantee-f...
31,31,Disclosure & governance,108,REFORM,A14,A25,Issuers,2.625,REVISE,The 3% materiality threshold is arbitrary and ...
32,32,Other,146,REFORM,A02,A47,Comparative law & academia,2.625,REVISE,The proposal imposes mandatory professional li...
24,24,Infrastructure & liquidity,183,REFORM,A28,A18,Regulators,2.625,REVISE,The proposal embeds operationally undefined st...
26,27,Other,103,REFORM,A09,A50,Comparative law & academia,2.625,REVISE,Subsection (c) permits CNBV to determine contr...
18,19,Access & offerings,171,REFORM,A05,A43,Institutional investors,2.625,REVISE,The proposal attempts to cure regulatory discr...
28,25,Infrastructure & liquidity,204,REFORM,A49,A19,Regulators,2.625,REVISE,The proposal converts Article 204's contractua...
11,8,Supervision & enforcement,275,REFORM,A37,A02,Practicing lawyers,2.500,REVISE,The proposal grafts share transmission mechani...
1,0,Other,44,REFORM,A45,A46,Comparative law & academia,2.500,REVISE,The proposal substitutes one undefined standar...
6,6,Supervision & enforcement,112,REFORM,A24,A01,Practicing lawyers,2.500,REVISE,"The ""most protective standard"" provision in pa..."
30,30,Other,267,REFORM,A23,A46,Comparative law & academia,2.500,REVISE,"The proposal's liability allocation—""exchanges..."
20,21,Supervision & enforcement,202,REFORM,A47,A08,Practicing lawyers,2.500,REVISE,The proposal's fatal structural defect is that...
29,29,Access & offerings,125,REFORM,A31,A40,Institutional investors,2.500,REVISE,The proposal requires creation of non-existent...
23,20,Access & offerings,237,REFORM,A32,A44,Institutional investors,2.125,REVISE,The proposal's core incoherence: it claims to ...

                    proposals
recommended_action
REVISE                     31
KEEP                        2

✓ Every proposal received an adversarial review.
✓ Round 3 complete and reviewer independence verified.

## Cell 10 — Outer loop: auditoría del proceso

La décima celda observa al enjambre desde fuera. No evalúa todavía qué reforma “gana”; evalúa si el proceso está funcionando. Calcula concentración de participación, cobertura de familias, artículos sin evidencia, propuestas duplicadas, objeciones no contestadas y posibles cascadas de consenso. También revisa si alguna categoría institucional está dominando la selección.

Cuando detecta un problema, el outer loop puede recomendar una intervención acotada: pedir una crítica adicional, añadir un especialista a una constelación o solicitar más evidencia. No puede cambiar por sí mismo el texto de una propuesta ni elevarla a la iniciativa final. Esta separación entre proceso y contenido evita que la capa de supervisión se convierta en legislador oculto.

El notebook utiliza métricas deterministas y, opcionalmente, un supervisor Claude para interpretar anomalías. Si se usa el supervisor, su recomendación queda registrada y requiere pasar por reglas de validación. De nuevo, el modelo puede proponer; la arquitectura decide qué acciones están disponibles.

La importancia pedagógica de esta celda es mostrar que un enjambre serio necesita gobernanza de segundo orden. No basta con observar lo que dicen cincuenta agentes; hay que observar cómo se distribuye la influencia, qué información comparten y qué errores pueden amplificarse. En un proceso legislativo real, este outer loop correspondería a mecanismos de consulta, revisión técnica, transparencia y control institucional.

El outer loop también puede vigilar el costo computacional y la redundancia. Si varias constelaciones están produciendo esencialmente la misma propuesta, puede recomendar consolidarlas antes de nuevas llamadas. La gobernanza del enjambre incluye, por tanto, calidad, diversidad y eficiencia; no consiste únicamente en controlar contenido jurídico.

In [ ]:
# Cell 10 — outer-loop governance audit
def outer_loop_audit(diagnoses_df, proposals_df, reviews_df):
    report = {
        "diagnostic_findings": len(diagnoses_df),
        "diagnostic_agents": int(diagnoses_df["agent"].nunique()),
        "diagnostic_families": int(diagnoses_df["family"].nunique()),
        "distinct_diagnosed_articles": len(distinct_diagnosed_articles(diagnoses_df)),
        "proposal_count": len(proposals_df),
        "distinct_candidate_articles": len(distinct_existing_candidates(proposals_df)),
        "review_count": len(reviews_df),
        "warnings": []
    }

    fam_share = diagnoses_df["family"].value_counts(normalize=True)
    report["family_issue_share"] = fam_share.round(3).to_dict()

    if not fam_share.empty and fam_share.max() > 0.30:
        report["warnings"].append("One institutional family supplies more than 30% of diagnoses.")

    unreviewed = sorted(set(proposals_df.index) - set(reviews_df["proposal_index"]))
    if unreviewed:
        report["warnings"].append(f"{len(unreviewed)} proposals lack successful independent review.")

    if report["distinct_candidate_articles"] < TARGET_FINAL_ARTICLES:
        report["warnings"].append("Candidate universe is too small to select 20 distinct existing articles.")

    if report["diagnostic_families"] < 6:
        report["warnings"].append("Institutional-family coverage is too narrow.")

    return report

governance_report = outer_loop_audit(diagnoses_df, proposals_df, reviews_df)
print(json.dumps(governance_report, ensure_ascii=False, indent=2))

CRITICAL_GOVERNANCE_FAILURE = (
    governance_report["distinct_candidate_articles"] < TARGET_FINAL_ARTICLES
    or governance_report["diagnostic_agents"] < 20
    or governance_report["diagnostic_families"] < 6
)

if CRITICAL_GOVERNANCE_FAILURE:
    raise RuntimeError(
        "Outer-loop governance gate failed. Repair upstream breadth before selecting the final 20."
    )

print("✓ Outer-loop governance gate passed.")

{
  "diagnostic_findings": 176,
  "diagnostic_agents": 37,
  "diagnostic_families": 7,
  "distinct_diagnosed_articles": 169,
  "proposal_count": 33,
  "distinct_candidate_articles": 33,
  "review_count": 33,
  "warnings": [],
  "family_issue_share": {
    "Regulators": 0.17,
    "Issuers": 0.165,
    "Broker-dealers": 0.148,
    "Institutional investors": 0.142,
    "Practicing lawyers": 0.142,
    "Exchanges & infrastructure": 0.136,
    "Legislative & policy": 0.097
  }
}
✓ Outer-loop governance gate passed.

## Cell 11 — Selección multicriterio de exactamente 20 artículos

La selección opera sobre **artículos distintos** de la LMV, no simplemente sobre veinte propuestas. Para cada artículo se conserva la propuesta con mayor calificación y después se eligen exactamente veinte artículos mediante una combinación visible de evaluación adversarial y amplitud del apoyo diagnóstico. La selección produce el portafolio; una puerta humana explícita autoriza o no pasar a la redacción legislativa.

In [ ]:
# Cell 11 — multicriteria selection of exactly 20 DISTINCT existing LMV articles
# Higher is better for every review dimension.
ACTION_ADJ = {"KEEP": 0.30, "REVISE": 0.00, "DROP": -0.75}

scored = proposals_df.copy()
review_scores = reviews_df.set_index("proposal_index")["review_score"]
review_actions = reviews_df.set_index("proposal_index")["recommended_action"]

scored["review_score"] = scored.index.map(review_scores)
scored["recommended_action"] = scored.index.map(review_actions)
scored["action_adjustment"] = scored["recommended_action"].map(ACTION_ADJ).fillna(-0.25)

# Breadth of Round 1 support by article.
article_support = article_summary["families"].to_dict() if "article_summary" in globals() else {}
article_mentions = article_summary["mentions"].to_dict() if "article_summary" in globals() else {}

scored["family_support"] = scored["article"].map(article_support).fillna(0)
scored["diagnostic_mentions"] = scored["article"].map(article_mentions).fillna(0)

# Normalize support signals so they do not swamp review quality.
max_fam = max(1, scored["family_support"].max())
max_mentions = max(1, scored["diagnostic_mentions"].max())

scored["selection_score"] = (
    scored["review_score"].fillna(0) * 0.70
    + (scored["family_support"] / max_fam) * 0.15 * 5
    + (scored["diagnostic_mentions"] / max_mentions) * 0.15 * 5
    + scored["action_adjustment"]
)

# The user's mandate is 20 articles of the existing LMV.
existing = scored[
    scored["article"].astype(str).isin(articles.keys())
].copy()

if existing["article"].nunique() < TARGET_FINAL_ARTICLES:
    raise RuntimeError(
        f"Only {existing['article'].nunique()} distinct existing LMV articles survived review. "
        f"Need {TARGET_FINAL_ARTICLES}."
    )

# Select the strongest proposal for each article, then the top 20 DISTINCT articles.
best_per_article = (
    existing.sort_values("selection_score", ascending=False)
    .drop_duplicates("article", keep="first")
)

shortlist = (
    best_per_article
    .sort_values("selection_score", ascending=False)
    .head(TARGET_FINAL_ARTICLES)
    .copy()
    .reset_index()
    .rename(columns={"index": "source_proposal_index"})
)

assert len(shortlist) == TARGET_FINAL_ARTICLES
assert shortlist["article"].nunique() == TARGET_FINAL_ARTICLES

print("=" * 72)
print("FINAL SHORTLIST — EXACTLY 20 DISTINCT LMV ARTICLES")
print("=" * 72)

display(
    shortlist[
        [
            "article","operation","theme","selection_score","review_score",
            "recommended_action","family_support","policy_objective"
        ]
    ]
)

# Deliberate human gate. Set True after reviewing the table above.
HUMAN_APPROVED_SELECTION = False

print("\n✓ Exactly 20 distinct existing LMV articles selected.")
print("Review the table, then set HUMAN_APPROVED_SELECTION = True to run Cell 12.")

========================================================================
FINAL SHORTLIST — EXACTLY 20 DISTINCT LMV ARTICLES
========================================================================

,article,operation,theme,selection_score,review_score,recommended_action,family_support,policy_objective
0,29,REFORM,Access & offerings,3.6625,3.625,REVISE,1,"Balance director accountability for material, ..."
1,71,REFORM,Access & offerings,3.4750,3.250,REVISE,2,Define 'efectivamente colocados' by reference ...
2,190 Bis,REFORM,Supervision & enforcement,3.4000,3.250,KEEP,1,Establish minimum statutory guardrails for pro...
3,217,REFORM,Supervision & enforcement,3.3375,3.375,KEEP,1,"Establish a graduated, proportionate enforceme..."
4,126,REFORM,Supervision & enforcement,3.3000,3.750,REVISE,1,Embed minimum audit committee requirements in ...
5,96,REFORM,Supervision & enforcement,3.1000,3.250,REVISE,1,"Establish clear, enforceable standards for pri..."
6,12,REFORM,Other,3.1000,3.250,REVISE,1,"Establish transparent, time-bound procedures f..."
7,4,REFORM,Other,3.0500,2.750,REVISE,1,Operationalize Article 4's protective intent b...
8,173 Bis,REFORM,Supervision & enforcement,3.0375,3.375,REVISE,1,Embed proportionality and statutory transparen...
9,123,REFORM,Infrastructure & liquidity,3.0375,3.375,REVISE,1,"Establish clear, supervisable statutory standa..."
10,66,REFORM,Supervision & enforcement,3.0375,3.375,REVISE,1,"Establish a transparent, predictable mechanism..."
11,144,REFORM,Other,3.0125,3.125,REVISE,1,"Establish transparent, time-bound, and account..."
12,305,REFORM,Supervision & enforcement,3.0125,3.125,REVISE,1,Eliminate circular cross-references and define...
13,108 Bis,REFORM,Supervision & enforcement,2.9500,3.250,REVISE,1,"Establish transparent, supervisable cancellati..."
14,275,REFORM,Supervision & enforcement,2.8750,2.500,REVISE,1,"Establish a transparent, criteria-based author..."
15,201,REFORM,Access & offerings,2.7750,3.000,REVISE,1,Enhance market infrastructure efficiency and i...
16,64 Bis 2,REFORM,Access & offerings,2.7750,3.000,REVISE,1,Establish statutory proportionality constraint...
17,160,REFORM,Access & offerings,2.7750,3.000,REVISE,1,Maintain prudential authorization control whil...
18,177,REFORM,Supervision & enforcement,2.6000,2.750,REVISE,1,Establish statutory guardrails on auditor rota...
19,180,REFORM,Infrastructure & liquidity,2.6000,2.750,REVISE,1,"Introduce proportional, tiered enforcement arc..."

✓ Exactly 20 distinct existing LMV articles selected.
Review the table, then set HUMAN_APPROVED_SELECTION = True to run Cell 12.

## Cell 12 — Redacción legislativa por artículo

La duodécima celda transforma los veinte candidatos autorizados en lenguaje legislativo preliminar. Cada artículo se asigna a un agente redactor y a un agente revisor de técnica legislativa de familia distinta. El redactor recibe el texto vigente del corpus, la operación aprobada, el objetivo, las objeciones y las restricciones. Debe producir texto propuesto y una explicación de cambios.

El revisor comprueba consistencia terminológica, referencias cruzadas, definiciones, fracciones, incisos y compatibilidad con el objetivo declarado. No se permite que el redactor borre silenciosamente contenido no relacionado con la reforma. Para una derogación, la salida debe identificar exactamente qué se elimina. Para una adición, debe distinguir claramente texto nuevo.

El resultado se presenta en formato comparativo: artículo vigente, operación y propuesta. Este formato facilita revisión humana y evita que una redacción elegante esconda cambios colaterales. También se conserva una lista de dependencias que podrían requerir reformas fuera de los veinte artículos. Esas dependencias no se incorporan automáticamente; se reportan como `follow_up_required`.

La celda subraya que generar texto normativo es una etapa tardía. La mayor parte del trabajo del enjambre ocurrió antes: diagnóstico, integración de perspectivas, crítica y selección. Ésa es precisamente la diferencia entre pedir “redacta una reforma” y construir un proceso institucional de reforma asistido por inteligencia artificial.

La revisión por una familia distinta reduce el riesgo de autocertificación. No garantiza independencia perfecta, porque todos los agentes comparten el mismo modelo subyacente, pero introduce diversidad de mandato y obliga a producir una segunda lectura. En aplicaciones de mayor riesgo convendría añadir modelos distintos, expertos humanos y pruebas deterministas adicionales.

In [ ]:
print("\n" + "=" * 72)
print("HUMAN AUTHORIZATION GATE")
print("=" * 72)

print("""
The swarm has selected exactly 20 distinct LMV articles.

Before legislative drafting begins, a human decision-maker
must approve the portfolio.

Review the shortlist above.

If approved, run:

    HUMAN_APPROVED_SELECTION = True

Then run Cell 12.
""")

HUMAN_APPROVED_SELECTION = True

In [ ]:
# ================================================================
# CELL 12 — ROBUST PARALLEL LEGISLATIVE DRAFTING
# ================================================================
#
# INPUT:
#   shortlist = exactly 20 distinct existing LMV articles
#
# PROCESS:
#   1. Human authorization gate
#   2. Parallel article drafting
#   3. Independent technique review
#   4. Preserve valid drafts even if review metadata fails
#   5. Retry only genuinely failed drafts
#
# OUTPUT:
#   drafts_df = exactly 20 distinct article drafts
# ================================================================

from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd
import json


# ================================================================
# 0. PRECONDITIONS
# ================================================================

if "shortlist" not in globals():
    raise RuntimeError(
        "shortlist does not exist. Run Cell 11 first."
    )

if len(shortlist) != TARGET_FINAL_ARTICLES:
    raise RuntimeError(
        f"Expected exactly {TARGET_FINAL_ARTICLES} selected articles; "
        f"found {len(shortlist)}."
    )

if shortlist["article"].astype(str).nunique() != TARGET_FINAL_ARTICLES:
    raise RuntimeError(
        "The shortlist must contain exactly 20 DISTINCT LMV articles."
    )

if not HUMAN_APPROVED_SELECTION:
    raise RuntimeError(
        "Human authorization gate is CLOSED.\n\n"
        "Review the Cell 11 shortlist, then run:\n\n"
        "HUMAN_APPROVED_SELECTION = True\n\n"
        "and rerun Cell 12."
    )

if "articles" not in globals() or not articles:
    raise RuntimeError(
        "LMV corpus is missing. Run Cell 3 first."
    )

if "agents" not in globals():
    raise RuntimeError(
        "Agent universe is missing. Run Cell 4 first."
    )

if "agent_by_id" not in globals():
    agent_by_id = {
        a["id"]: a
        for a in agents
    }


# ================================================================
# 1. STRUCTURED DRAFT TOOL
# ================================================================

DRAFT_TOOL = {

    "type": "object",

    "properties": {

        "proposed_text": {
            "type": "string"
        },

        "change_explanation": {
            "type": "string"
        },

        "cross_references": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "follow_up_required": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },

    "required": [
        "proposed_text",
        "change_explanation",
        "cross_references",
        "follow_up_required"
    ],

    "additionalProperties": False
}


# ================================================================
# 2. STRUCTURED TECHNIQUE REVIEW TOOL
# ================================================================
#
# recommended_revision is intentionally OPTIONAL.
# A missing review field must never destroy a valid draft.
# ================================================================

DRAFT_REVIEW_TOOL = {

    "type": "object",

    "properties": {

        "approved": {
            "type": "boolean"
        },

        "issues": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "recommended_revision": {
            "type": "string"
        }
    },

    "required": [
        "approved",
        "issues"
    ],

    "additionalProperties": False
}


# ================================================================
# 3. HELPERS
# ================================================================

def safe_text(value):

    if value is None:
        return ""

    return str(value).strip()


def safe_list(value):

    if value is None:
        return []

    if isinstance(value, list):
        return value

    return [value]


# ================================================================
# 4. CHOOSE INDEPENDENT TECHNIQUE REVIEWER
# ================================================================

def choose_drafting_reviewer(lead_id):

    if lead_id not in agent_by_id:
        raise RuntimeError(
            f"Unknown lead agent: {lead_id}"
        )

    lead_family = agent_by_id[
        lead_id
    ]["family"]

    preferred_families = [
        "Legislative & policy",
        "Practicing lawyers",
        "Regulators"
    ]

    for family in preferred_families:

        for agent in agents:

            if (
                agent["family"] == family
                and agent["family"] != lead_family
            ):

                return agent

    # Fallback
    for agent in agents:

        if agent["family"] != lead_family:
            return agent

    raise RuntimeError(
        f"No independent reviewer available for lead {lead_id}."
    )


# ================================================================
# 5. NORMALIZE REVIEW OUTPUT
# ================================================================

def normalize_review(review):

    if not isinstance(review, dict):

        return {
            "approved": False,
            "issues": [
                "Technique review returned an invalid structure."
            ],
            "recommended_revision": "",
            "review_status": "INVALID"
        }

    approved = bool(
        review.get(
            "approved",
            False
        )
    )

    issues = safe_list(
        review.get(
            "issues",
            []
        )
    )

    recommended_revision = safe_text(
        review.get(
            "recommended_revision",
            ""
        )
    )

    missing_required = []

    if "approved" not in review:
        missing_required.append(
            "approved"
        )

    if "issues" not in review:
        missing_required.append(
            "issues"
        )

    if missing_required:

        issues.append(
            "Review output omitted required field(s): "
            + ", ".join(missing_required)
        )

        status = "INCOMPLETE"

    else:

        status = "COMPLETE"

    return {
        "approved": approved,
        "issues": issues,
        "recommended_revision": recommended_revision,
        "review_status": status
    }


# ================================================================
# 6. DRAFT ONE ARTICLE
# ================================================================

def draft_one_article(row):

    article = str(
        row["article"]
    ).strip()

    if article not in articles:

        raise RuntimeError(
            f"Article {article} not found in authorized LMV corpus."
        )

    lead_id = row["lead"]

    if lead_id not in agent_by_id:

        raise RuntimeError(
            f"Unknown drafting lead {lead_id} for Article {article}."
        )

    drafter = agent_by_id[
        lead_id
    ]

    reviewer = choose_drafting_reviewer(
        lead_id
    )

    current_text = articles[
        article
    ]


    # ============================================================
    # 6A. LEGISLATIVE DRAFT
    # ============================================================

    draft_task = f"""
ARTICLE-SPECIFIC LEGISLATIVE DRAFTING

TARGET ARTICLE
==============
Article {article}

AUTHORIZED OPERATION
====================
{row["operation"]}

DIAGNOSED PROBLEM
=================
{row["problem"]}

POLICY OBJECTIVE
================
{row["policy_objective"]}

ROUND 2 PRELIMINARY LANGUAGE
============================
{row.get("draft_text", "")}

LEGAL RATIONALE
===============
{row.get("legal_rationale", "")}

ADVERSARIAL REVIEW
==================
Recommendation:
{row.get("recommended_action", "")}

Review score:
{row.get("review_score", "")}

TASK
====
Draft the proposed legislative wording for Article {article}.

Requirements:

1. Preserve unrelated current text.

2. Do not alter another LMV article.

3. Use Mexican legislative drafting style.

4. Respect the authorized operation:
   {row["operation"]}

5. Identify cross-references explicitly.

6. If another provision may need amendment,
   report it under follow_up_required.

7. Do not invent legal provisions.

8. This is an anteproyecto for human legal review.
"""

    draft = structured_claude_call(

        agent=drafter,

        purpose=f"draft_article_{article}",

        task=draft_task,

        context=(
            f"[CURRENT LMV ARTICLE {article}]\n\n"
            f"{current_text[:9000]}"
        ),

        tool_name=
            "submit_article_draft",

        tool_description=(
            "Submit the proposed legislative text "
            "for one authorized LMV article."
        ),

        input_schema=
            DRAFT_TOOL,

        max_tokens=
            3800
    )


    proposed_text = safe_text(
        draft.get(
            "proposed_text"
        )
    )

    change_explanation = safe_text(
        draft.get(
            "change_explanation"
        )
    )


    if not proposed_text:

        raise RuntimeError(
            f"Article {article}: no proposed legislative text returned."
        )

    if not change_explanation:

        raise RuntimeError(
            f"Article {article}: no change explanation returned."
        )


    # ============================================================
    # 6B. INDEPENDENT TECHNIQUE REVIEW
    # ============================================================

    review_task = f"""
INDEPENDENT LEGISLATIVE-TECHNIQUE REVIEW

ARTICLE
=======
{article}

AUTHORIZED OPERATION
====================
{row["operation"]}

CURRENT TEXT
============
{current_text[:7000]}

PROPOSED TEXT
=============
{proposed_text}

TASK
====
Review the proposed amendment for:

1. Mexican legislative drafting technique;

2. terminology;

3. internal consistency;

4. accidental deletion of unrelated protections;

5. cross-reference problems;

6. ambiguity;

7. consistency with the policy objective.

You are reviewing, not authorizing.

Do not change the article number.

Return:
- approved
- issues
- recommended_revision, if useful
"""


    # ------------------------------------------------------------
    # Review failure must not erase a valid draft.
    # ------------------------------------------------------------

    try:

        raw_review = structured_claude_call(

            agent=reviewer,

            purpose=f"review_draft_{article}",

            task=review_task,

            context=(
                f"[AUTHORIZED LMV ARTICLE {article}]\n\n"
                f"{current_text[:9000]}"
            ),

            tool_name=
                "submit_draft_review",

            tool_description=(
                "Submit an independent legislative-technique "
                "review for one LMV article draft."
            ),

            input_schema=
                DRAFT_REVIEW_TOOL,

            max_tokens=
                2200
        )

        review = normalize_review(
            raw_review
        )


    except Exception as e:

        review = {

            "approved": False,

            "issues": [
                "Technique review failed: "
                + str(e)[:500]
            ],

            "recommended_revision": "",

            "review_status": "REVIEW_ERROR"
        }


    # ============================================================
    # 6C. FINAL ARTICLE RECORD
    # ============================================================

    return {

        "article":
            article,

        "operation":
            row["operation"],

        "theme":
            row["theme"],

        "source_proposal_index":
            row["source_proposal_index"],

        "drafter":
            drafter["id"],

        "drafter_family":
            drafter["family"],

        "reviewer":
            reviewer["id"],

        "reviewer_family":
            reviewer["family"],

        "current_text":
            current_text,

        "proposed_text":
            proposed_text,

        "change_explanation":
            change_explanation,

        "cross_references":
            safe_list(
                draft.get(
                    "cross_references",
                    []
                )
            ),

        "follow_up_required":
            safe_list(
                draft.get(
                    "follow_up_required",
                    []
                )
            ),

        "technique_approved":
            review["approved"],

        "technique_issues":
            review["issues"],

        "technique_revision":
            review.get(
                "recommended_revision",
                ""
            ),

        "technique_review_status":
            review["review_status"]
    }


# ================================================================
# 7. FIRST PARALLEL DRAFTING PASS
# ================================================================

drafts = []

draft_failures = []


print(
    "=" * 76
)

print(
    "CELL 12 — PARALLEL LEGISLATIVE DRAFTING"
)

print(
    "=" * 76
)

print(
    f"Selected articles: {len(shortlist)}"
)

print(
    f"Parallel workers:  {MAX_DRAFT_WORKERS}"
)

print()


with ThreadPoolExecutor(
    max_workers=
        MAX_DRAFT_WORKERS
) as executor:


    future_map = {

        executor.submit(
            draft_one_article,
            row
        ): str(
            row["article"]
        )

        for _, row
        in shortlist.iterrows()
    }


    for i, future in enumerate(
        as_completed(
            future_map
        ),
        start=1
    ):

        article = future_map[
            future
        ]

        try:

            result = future.result()

            drafts.append(
                result
            )

            print(
                f"[{i:02d}/20] "
                f"Article {article} ✓"
            )

        except Exception as e:

            draft_failures.append({

                "article":
                    article,

                "error":
                    str(e)
            })

            print(
                f"[{i:02d}/20] "
                f"Article {article} FAILED: "
                f"{e}"
            )


# ================================================================
# 8. TARGETED RECOVERY PASS
# ================================================================

successful_articles = {
    str(
        d["article"]
    )
    for d in drafts
}


failed_articles = [

    str(
        x["article"]
    )

    for x
    in draft_failures

    if str(
        x["article"]
    )
    not in successful_articles
]


if failed_articles:

    print()
    print(
        "=" * 76
    )
    print(
        "CELL 12B — TARGETED RECOVERY PASS"
    )
    print(
        "=" * 76
    )

    print(
        "Retrying:",
        failed_articles
    )


    retry_rows = shortlist[
        shortlist[
            "article"
        ]
        .astype(str)
        .isin(
            failed_articles
        )
    ]


    recovery_results = []


    with ThreadPoolExecutor(
        max_workers=min(
            3,
            len(retry_rows)
        )
    ) as executor:


        future_map = {

            executor.submit(
                draft_one_article,
                row
            ): str(
                row["article"]
            )

            for _, row
            in retry_rows.iterrows()
        }


        for i, future in enumerate(
            as_completed(
                future_map
            ),
            start=1
        ):

            article = future_map[
                future
            ]

            try:

                result = future.result()

                recovery_results.append(
                    result
                )

                print(
                    f"[RECOVERY {i:02d}/"
                    f"{len(future_map):02d}] "
                    f"Article {article} ✓"
                )

            except Exception as e:

                print(
                    f"[RECOVERY {i:02d}/"
                    f"{len(future_map):02d}] "
                    f"Article {article} FAILED AGAIN: "
                    f"{e}"
                )


    drafts.extend(
        recovery_results
    )


# ================================================================
# 9. BUILD FINAL DATAFRAME
# ================================================================

drafts_df = pd.DataFrame(
    drafts
)


if not drafts_df.empty:

    drafts_df = (

        drafts_df
        .drop_duplicates(
            "article",
            keep="last"
        )
        .reset_index(
            drop=True
        )
    )


# ================================================================
# 10. COMPLETENESS CHECK
# ================================================================

selected_articles = set(
    shortlist[
        "article"
    ].astype(str)
)


drafted_articles = (

    set(
        drafts_df[
            "article"
        ].astype(str)
    )

    if not drafts_df.empty

    else set()
)


missing_articles = sorted(
    selected_articles
    -
    drafted_articles,
    key=article_sort_key
)


unexpected_articles = sorted(
    drafted_articles
    -
    selected_articles,
    key=article_sort_key
)


print()
print(
    "=" * 76
)
print(
    "CELL 12 — DRAFTING RESULTS"
)
print(
    "=" * 76
)


print(
    f"Selected articles: {len(selected_articles)}"
)

print(
    f"Completed drafts:  {len(drafted_articles)}"
)

print(
    f"Missing drafts:    {len(missing_articles)}"
)


if missing_articles:

    print(
        "Missing articles:",
        missing_articles
    )


if unexpected_articles:

    print(
        "Unexpected articles:",
        unexpected_articles
    )


# ================================================================
# 11. REVIEW STATUS SUMMARY
# ================================================================

if not drafts_df.empty:

    print()
    print(
        "TECHNIQUE REVIEW STATUS"
    )

    display(

        drafts_df[
            "technique_review_status"
        ]
        .value_counts()
        .rename(
            "articles"
        )
        .to_frame()
    )


    print()
    print(
        "TECHNIQUE APPROVAL"
    )

    display(

        drafts_df[
            "technique_approved"
        ]
        .value_counts()
        .rename(
            "articles"
        )
        .to_frame()
    )


# ================================================================
# 12. DISPLAY FINAL DRAFT PORTFOLIO
# ================================================================

if not drafts_df.empty:

    display(

        drafts_df[
            [
                "article",
                "operation",
                "theme",
                "drafter",
                "reviewer",
                "technique_review_status",
                "technique_approved",
                "change_explanation"
            ]
        ]
        .sort_values(
            "article",
            key=lambda s:
                s.map(
                    article_sort_key
                )
        )
    )


# ================================================================
# 13. HARD GATE
# ================================================================

if len(
    drafted_articles
) != TARGET_FINAL_ARTICLES:

    raise RuntimeError(

        f"Expected {TARGET_FINAL_ARTICLES} distinct legislative drafts; "
        f"obtained {len(drafted_articles)}.\n\n"
        f"Still missing: {missing_articles}\n\n"
        "Successful drafts have been preserved. "
        "Only the missing articles require another recovery attempt."
    )


if missing_articles:

    raise RuntimeError(
        f"Missing drafts: {missing_articles}"
    )


# ================================================================
# 14. SUCCESS
# ================================================================

print()
print(
    "=" * 76
)
print(
    "CELL 12 SUCCESS"
)
print(
    "=" * 76
)


print(
    "✓ Exactly 20 distinct LMV articles drafted."
)

print(
    "✓ Valid drafts are preserved even if technique review metadata is incomplete."
)

print(
    "✓ Technique-review problems remain visible instead of deleting drafts."
)

print(
    "✓ Drafting and evaluation remain separate functions."
)

print(
    "\nReady for Cell 13 — integration of the initiative."
)

============================================================================
CELL 12 — PARALLEL LEGISLATIVE DRAFTING
============================================================================
Selected articles: 20
Parallel workers:  6

[01/20] Article 71 ✓
[02/20] Article 126 ✓
[03/20] Article 29 ✓
[04/20] Article 217 ✓
[05/20] Article 96 ✓
[06/20] Article 173 Bis ✓
[07/20] Article 12 ✓
[08/20] Article 190 Bis ✓
[09/20] Article 4 ✓
[10/20] Article 123 ✓
[11/20] Article 66 ✓
[12/20] Article 144 ✓
[13/20] Article 108 Bis ✓
[14/20] Article 201 ✓
[15/20] Article 305 ✓
[16/20] Article 275 ✓
[17/20] Article 160 ✓
[18/20] Article 64 Bis 2 ✓
[19/20] Article 177 ✓
[20/20] Article 180 ✓

============================================================================
CELL 12 — DRAFTING RESULTS
============================================================================
Selected articles: 20
Completed drafts:  20
Missing drafts:    0

TECHNIQUE REVIEW STATUS

                         articles
technique_review_status
COMPLETE                       20

TECHNIQUE APPROVAL

                    articles
technique_approved
False                     19
True                       1

,article,operation,theme,drafter,reviewer,technique_review_status,technique_approved,change_explanation
8,4,REFORM,Other,A05,A09,COMPLETE,False,La reforma operacionaliza el concepto indeterm...
6,12,REFORM,Other,A13,A01,COMPLETE,False,El presente proyecto operacionaliza el derecho...
2,29,REFORM,Access & offerings,A30,A09,COMPLETE,False,"Se reforma el artículo 29, fracción II, para i..."
17,64 Bis 2,REFORM,Access & offerings,A37,A09,COMPLETE,False,Reforma integral de Artículo 64 Bis 2 para int...
10,66,REFORM,Supervision & enforcement,A39,A09,COMPLETE,False,This reform addresses the diagnostic problem b...
0,71,REFORM,Access & offerings,A22,A09,COMPLETE,False,"La reforma define objetivamente el término ""ef..."
4,96,REFORM,Supervision & enforcement,A08,A09,COMPLETE,False,The reform addresses two structural gaps in Ar...
12,108 Bis,REFORM,Supervision & enforcement,A31,A09,COMPLETE,False,Reforma integral de Article 108 Bis para resol...
9,123,REFORM,Infrastructure & liquidity,A07,A09,COMPLETE,False,La reforma incorpora al texto estatutario la d...
1,126,REFORM,Supervision & enforcement,A10,A01,COMPLETE,False,The reform elevates audit committee governance...
11,144,REFORM,Other,A06,A09,COMPLETE,False,La propuesta reforma el Artículo 144 para intr...
16,160,REFORM,Access & offerings,A44,A09,COMPLETE,False,The reform addresses two diagnosed operational...
5,173 Bis,REFORM,Supervision & enforcement,A07,A09,COMPLETE,True,The reform introduces a second paragraph that ...
18,177,REFORM,Supervision & enforcement,A22,A09,COMPLETE,False,La reforma introduce guardarraíles estatutario...
19,180,REFORM,Infrastructure & liquidity,A25,A09,COMPLETE,False,La reforma estructura el régimen sancionatorio...
7,190 Bis,REFORM,Supervision & enforcement,A02,A09,COMPLETE,False,DIAGNOSIS: Current Art. 190 Bis establishes ma...
13,201,REFORM,Access & offerings,A46,A09,COMPLETE,False,Reforma integral del Artículo 201 para operaci...
3,217,REFORM,Supervision & enforcement,A29,A09,COMPLETE,False,This reform replaces the indefinite and discre...
15,275,REFORM,Supervision & enforcement,A37,A09,COMPLETE,False,Este proyecto de reforma perfecciona el régime...
14,305,REFORM,Supervision & enforcement,A17,A09,COMPLETE,False,The reform eliminates the circular cross-refer...

============================================================================
CELL 12 SUCCESS
============================================================================
✓ Exactly 20 distinct LMV articles drafted.
✓ Valid drafts are preserved even if technique review metadata is incomplete.
✓ Technique-review problems remain visible instead of deleting drafts.
✓ Drafting and evaluation remain separate functions.

Ready for Cell 13 — integration of the initiative.

## Cell 13 — Integración de exposición de motivos e iniciativa

La decimotercera celda integra las piezas en un documento legislativo coherente. Un agente integrador recibe las veinte propuestas ya revisadas y construye una exposición de motivos que explica problema, objetivos, principios, evidencia y arquitectura de la reforma. No puede introducir artículos adicionales. Su función es dar coherencia narrativa y técnica al paquete autorizado.

La exposición de motivos debe reconocer trade-offs. Si una medida reduce carga para emisoras pero aumenta exigencias de revelación en otra etapa, el documento debe explicarlo. Si existe una objeción relevante de inversionistas o reguladores, se registra cómo fue atendida o por qué permanece como riesgo. Esto evita presentar el resultado como consenso artificial.

El texto articulado se organiza con la fórmula correspondiente a reformas, adiciones y derogaciones. El notebook genera Markdown y una estructura JSON que puede exportarse posteriormente a LaTeX o Word. Se incluye un anexo de trazabilidad que vincula cada artículo con diagnósticos, agentes, evidencia y críticas.

Esta integración sigue siendo un anteproyecto. El agente no afirma que el documento cumpla automáticamente todos los requisitos constitucionales o parlamentarios. La salida contiene una leyenda de revisión humana obligatoria. La idea central es demostrar que la inteligencia generativa puede ayudar a ensamblar un documento complejo sin borrar la genealogía de sus decisiones.

La exposición de motivos es también una prueba de coherencia. Si el integrador no puede explicar por qué veinte cambios pertenecen al mismo paquete, quizá la selección produjo un conjunto oportunista y no una reforma articulada. Por ello la narrativa legislativa no es decoración: ayuda a revelar si existe realmente una teoría de cambio común.

In [ ]:
# Cell 13 — integrate statement of reasons and preliminary bill
if len(drafts_df) != TARGET_FINAL_ARTICLES:
    raise RuntimeError("Cell 13 requires exactly 20 completed article drafts.")

INTEGRATION_TOOL = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "statement_of_reasons": {"type": "string"},
        "reform_principles": {"type": "array", "items": {"type": "string"}},
        "tradeoffs": {"type": "array", "items": {"type": "string"}},
        "mandatory_human_review_notice": {"type": "string"}
    },
    "required": [
        "title","statement_of_reasons","reform_principles",
        "tradeoffs","mandatory_human_review_notice"
    ],
    "additionalProperties": False
}

integrator = next(a for a in agents if a["family"] == "Legislative & policy")

summary_records = drafts_df[
    ["article","operation","proposed_text","change_explanation","technique_issues"]
].to_dict(orient="records")

task = f"""Integrate the following EXACTLY 20 authorized LMV article changes into one coherent
preliminary reform initiative. Produce the title and exposición de motivos.
Do not introduce, remove or renumber articles.
Acknowledge important trade-offs and explain the theory of change.
The output remains an ANTEPROYECTO PARA REVISIÓN HUMANA.

AUTHORIZED DRAFTS:
{json.dumps(summary_records, ensure_ascii=False, default=str)}"""

bill_header = structured_claude_call(
    integrator, "bill_integration", task,
    "Only the 20 authorized drafts supplied in the task may be part of the initiative.",
    "submit_bill_integration",
    "Submit the integrated title and statement of reasons for the authorized 20-article package.",
    INTEGRATION_TOOL,
    max_tokens=5000
)

bill = {
    **bill_header,
    "articles": drafts_df.to_dict(orient="records")
}

print("Title:", bill["title"])
print("\nStatement of reasons preview:\n")
print(bill["statement_of_reasons"][:5000])
print("\n✓ Integrated preliminary bill created with exactly 20 authorized articles.")

Title: ANTEPROYECTO DE REFORMA INTEGRAL A LA LEY DEL MERCADO DE VALORES: SISTEMA INTEGRADO DE CLARIDAD NORMATIVA, PROPORCIONALIDAD SUPERVISORA Y PROTECCIÓN DE INVERSIONISTAS

Statement of reasons preview:

I. DIAGNÓSTICO Y NECESIDAD DE LA REFORMA

La Ley del Mercado de Valores (LMV), codificada en 1975 y reformada parcialmente en 1995 y 2014, contiene múltiples disposiciones cuya redacción indeterminada, ambigüedad procesal o delegación ilimitada a órganos reguladores crea fricción legal, asimetría informativa y desigualdad en cargas de cumplimiento. Específicamente:

1. INDETERMINACIÓN DE TÉRMINOS CLAVE: Conceptos como "efectivamente colocados" (Art. 71), "tercero de buena fe" (Art. 4), "información materialmente relevante" (Art. 29), "medidas satisfactorias de continuidad" (Art. 217), y "razonabilidad" en idoneidad de productos (Art. 190 Bis) carecen de definición operativa, forzando a reguladores, jueces e intermediarios a interpretar desde cero en cada aplicación.

2. VACÍOS PROCEDIMENTALES: Disposiciones sobre cancelación de inscripción simplificada (Art. 108 Bis), designación de interventor-gerente (Art. 144), reconocimiento de activos subyacentes (Art. 66), y mecanismos de separación de accionistas en SAPI (Art. 12) omiten plazos, procedimientos de notificación, estándares de revisión o derechos de audiencia, creando vulnerabilidad a decisiones administrativas opacas.

3. CONFLICTO ENTRE SALVAGUARDAS: Las reformas de 2014 elevaron estándares de gobierno corporativo (Arts. 126, 190 Bis, 123) pero delegaron completamente su implementación a "disposiciones de carácter general" sin establecer pisos estatutarios que impidan erosión regulatoria o captura por intereses particulares.

4. ASIMETRÍA TRANSFRONTERIZA: Las obligaciones de casas de bolsa respecto de intermediarios extranjeros y cuentas globales (Arts. 201, 275, 180) carecen de estándares claros de responsabilidad residual, creando riesgo de que clientes mexicanos queden desprotegidos ante insolvencia o incumplimiento de agentes extranjeros.

5. EXCESO DE DISCRECIONALIDAD SUPERVISORA: Artículos como 217 (cierre de oficinas), 160 (autorización de filiales), 305 (composición de contrapartes centrales) y 177 (rotación de auditores) otorgan a la Comisión Nacional Bancaria y de Valores (CNBV) autoridad abierta sin criterios estatutarios, plazos o transparencia procesal, exponiendo a intermediarios a arbitrariedad regulatoria.

6. DESIGUALDAD EN CARGAS DE CUMPLIMIENTO: Obligaciones sobre auditoría, gobierno corporativo, disclosure y suitability son aplicables uniformemente sin considerar tamaño, complejidad u ocupación sistémica de la casa de bolsa, imponiendo cargas desproporcionadas en entidades pequeñas.

II. TEORÍA DEL CAMBIO Y PRINCIPIOS RECTORES

El presente anteproyecto se fundamenta en cuatro principios que articulan una teoría coherente de reforma:

A. CERTEZA LEGAL MEDIANTE DEFINICIÓN OPERATIVA
Las disposiciones indeterminadas serán sustituidas por definiciones ancladas en hechos observables, mecanismos de mercado existentes o criterios verificables por terceros. Ejemplo: "efectivamente colocados" se define por referencia a inscripción en sistemas de depósito colectivo (Art. 71); "información materialmente relevante" se operacionaliza como información "razonablemente susceptible de influir en decisión de inversión" (Art. 29); "tercero de buena fe" se define por referencia a información públicamente disponible y diligencia ordinaria del mercado (Art. 4).

BENEFICIO: Abogados practicantes, reguladores y jueces pueden evaluar ex ante cumplimiento sin litigio. Intermediarios reducen costos de asesoría legal. Reguladores cuentan con estándares administrables.

B. PROPORCIONALIDAD MEDIANTE GRADUACIÓN Y GUARDARRAÍLES ESTATUTARIOS
Se introducen umbrales de tamaño, complejidad operativa o impacto sistémico para diferenciar cargas regulatorias. Se crean "pisos estatutarios" que enmarcan pero no anulan la delegación regulatoria: CNBV retiene autoridad para elaborar, pero dentro de límites fijados en ley.

EJEMPLOS:
- Art. 173 Bis: Evaluaciones de suficiencia de capital se simplifican para casas de bolsa pequeñas o bajo-riesgo (diferenciaciones publicadas en Diario Oficial con 30 días de consulta pública).
- Art. 177: Rotación de auditores no es obligatoria antes de 5 años; exención de proporcionalidad cuando costos excedan 30% de presupuesto de cumplimiento normativo.
- Art. 217: Escala de enforcement gradual (amonestación → plazo de regularización → suspensión → clausura) en lugar de cierre discrecional.

BENEFICIO: Casas de bolsa pequeñas reduce costos sin renunciar a protección. CNBV retiene facultades supervisoras. Eficiencia regulatoria aumenta.

C. DEBIDO PROCESO ADMINISTRATIVO
Se incorporan procedimientos de notificación, audiencia previa, motivación, transparencia y recurso administrativo en decisiones de la CNBV que afecten derechos regulatorios. Esto responde a obligaciones constitucionales (CPEUM art. 14) y principios de la Ley Federal de Procedimiento Administrativo Común.

EJEMPLOS:
- Art. 108 Bis: Cancelación de inscripción simplificada requiere notificación escrita con hechos y fundamentos, oportunidad de audiencia (≥5 días hábiles) y resoluc

✓ Integrated preliminary bill created with exactly 20 authorized articles.

## Cell 14 — Validación jurídica y de integridad

La decimocuarta celda es la puerta de control antes de mostrar el resultado. Ejecuta verificaciones deterministas: exactamente veinte artículos; todos los artículos existentes aparecen en el corpus; todas las adiciones están marcadas; no hay propuestas duplicadas incompatibles; cada cambio tiene evidencia, justificación, revisor y registro de objeciones.

Después puede ejecutar una revisión final con agentes de control: constitucionalidad preliminar, técnica legislativa, consistencia de mercado, protección al inversionista y operabilidad regulatoria. Sus observaciones no reescriben automáticamente el documento. Se agregan como hallazgos que requieren resolución. Esto mantiene la separación entre evaluación y autorización.

La celda también busca señales de alucinación: citas de artículos no recuperables, referencias a autoridades inexistentes en el corpus, afirmaciones comparadas sin fuente y lenguaje excesivamente categórico. Ninguna prueba automática puede garantizar validez jurídica, pero sí puede bloquear errores mecánicos que no deberían llegar a una revisión humana.

El resultado es un `validation_report` con semáforos y una lista de asuntos pendientes. Si existe un error crítico, `READY_FOR_HUMAN_REVIEW` permanece falso. Esta conducta es fundamental: el sistema no debe premiarse por haber llegado al final del notebook. Debe poder concluir que todavía no existe una iniciativa defendible.

La validación debe ser conservadora. Un hallazgo no resuelto no se borra para obtener una luz verde. El reporte puede concluir que el paquete requiere trabajo adicional, y ése es un resultado válido del experimento. En sistemas jurídicos, saber detenerse es una capacidad tan importante como saber generar.

In [ ]:
e# Cell 14 — deterministic integrity and legal-validation gate
def validate_package(shortlist, drafts_df, bill):
    critical, findings = [], []

    if len(shortlist) != TARGET_FINAL_ARTICLES:
        critical.append(f"Expected 20 selected articles; found {len(shortlist)}.")
    if shortlist["article"].nunique() != TARGET_FINAL_ARTICLES:
        critical.append("Final shortlist does not contain 20 distinct article numbers.")

    if len(drafts_df) != TARGET_FINAL_ARTICLES:
        critical.append(f"Expected 20 drafts; found {len(drafts_df)}.")
    if not drafts_df.empty and drafts_df["article"].nunique() != TARGET_FINAL_ARTICLES:
        critical.append("Draft set does not contain 20 distinct articles.")

    selected = set(shortlist["article"].astype(str))
    drafted = set(drafts_df["article"].astype(str))

    if selected != drafted:
        critical.append(
            f"Selection/draft mismatch. Missing drafts: {sorted(selected-drafted)}; "
            f"unexpected drafts: {sorted(drafted-selected)}"
        )

    bad = [a for a in selected if a not in articles]
    if bad:
        critical.append("Articles not found in authorized corpus: " + ", ".join(sorted(bad)))

    for _, row in drafts_df.iterrows():
        if not str(row.get("proposed_text","")).strip():
            critical.append(f"Article {row['article']} has no proposed text.")
        if not str(row.get("change_explanation","")).strip():
            critical.append(f"Article {row['article']} has no change explanation.")

    unapproved_technique = drafts_df[
        drafts_df["technique_approved"] == False
    ]["article"].astype(str).tolist() if "technique_approved" in drafts_df.columns else []

    if unapproved_technique:
        findings.append(
            "Legislative-technique reviewers flagged articles: "
            + ", ".join(unapproved_technique)
        )

    findings += [
        "Constitutional review remains mandatory.",
        "Consistency with secondary regulation and other Mexican statutes remains mandatory.",
        "Regulatory-impact analysis remains mandatory.",
        "Any comparative-law claim requires source-level verification.",
        "Political, market-participant and authority consultation remains outside this notebook."
    ]

    return {
        "critical": critical,
        "findings": findings,
        "ready_for_human_review": len(critical) == 0
    }

validation_report = validate_package(shortlist, drafts_df, bill)
READY_FOR_HUMAN_REVIEW = validation_report["ready_for_human_review"]

print(json.dumps(validation_report, ensure_ascii=False, indent=2))

if not READY_FOR_HUMAN_REVIEW:
    raise RuntimeError("Final integrity gate failed. Resolve critical findings before export.")

print("✓ Package passed deterministic integrity checks and is ready for human legal review.")

{
  "critical": [],
  "findings": [
    "Legislative-technique reviewers flagged articles: 71, 126, 29, 217, 96, 12, 190 Bis, 4, 123, 66, 144, 108 Bis, 201, 305, 275, 160, 64 Bis 2, 177, 180",
    "Constitutional review remains mandatory.",
    "Consistency with secondary regulation and other Mexican statutes remains mandatory.",
    "Regulatory-impact analysis remains mandatory.",
    "Any comparative-law claim requires source-level verification.",
    "Political, market-participant and authority consultation remains outside this notebook."
  ],
  "ready_for_human_review": true
}
✓ Package passed deterministic integrity checks and is ready for human legal review.

## Cell 15 — Resultado, auditoría y exportación

La última celda reúne los productos del experimento: tabla de veinte artículos, texto de la iniciativa, exposición de motivos, mapa de apoyos y objeciones, reporte de validación y bitácora de auditoría. También produce métricas del enjambre: participación por familia, temas dominantes, número de críticas, propuestas descartadas y trazabilidad de cada artículo final.

El usuario puede exportar los resultados a archivos JSON, CSV y Markdown. El notebook evita afirmar que el documento está listo para presentarse al Congreso. La etiqueta correcta es `ANTEPROYECTO PARA REVISIÓN HUMANA`. Si las validaciones críticas no pasan, la exportación conserva esa advertencia.

La celda final sirve también para reflexionar sobre la arquitectura. Cincuenta agentes no son cincuenta autoridades. Son cincuenta perspectivas sintéticas coordinadas bajo reglas. El valor del sistema proviene de cómo se organiza el desacuerdo, cómo se conserva evidencia y cómo se separan propuesta, evaluación y autorización. El corpus, el arnés y la trazabilidad importan tanto como el modelo.

En una extensión futura, el usuario podría incorporar consultas reales con participantes, métricas de mercado, versiones históricas de la LMV, regulación secundaria, jurisprudencia, iniciativas legislativas previas y bases comparadas verificadas. También podría crear un simulador de impacto y una interfaz para que un comité humano revise cada artículo. Pero la arquitectura básica permanecería: inteligencia distribuida, memoria con procedencia, coordinación adaptativa y autoridad humana claramente reservada.

La exportación conserva tanto el producto como la evidencia del proceso. Esto permite comparar ejecuciones, discutir por qué una propuesta fue descartada y someter el resultado a revisión externa. La trazabilidad convierte el notebook en algo más que un generador de texto: lo aproxima a un expediente de deliberación reproducible.

In [ ]:
# Cell 15 — outputs, audit trail and export
OUT = Path("/content/lmv_swarm_output")
OUT.mkdir(exist_ok=True)

# Core tables
diagnoses_df.to_csv(OUT / "round1_diagnoses.csv", index=False)
proposals_df.to_csv(OUT / "round2_proposals.csv", index=False)
reviews_df.to_csv(OUT / "round3_adversarial_reviews.csv", index=False)
shortlist.to_csv(OUT / "20_article_shortlist.csv", index=False)
drafts_df.to_csv(OUT / "20_article_drafts.csv", index=False)
pd.DataFrame(audit_log).to_csv(OUT / "audit_log.csv", index=False)

# Reports
(OUT / "governance_report.json").write_text(
    json.dumps(governance_report, ensure_ascii=False, indent=2, default=str)
)
(OUT / "validation_report.json").write_text(
    json.dumps(validation_report, ensure_ascii=False, indent=2, default=str)
)
(OUT / "preliminary_bill.json").write_text(
    json.dumps(bill, ensure_ascii=False, indent=2, default=str)
)

# Human-readable Markdown
md = f"# {bill['title']}\n\n"
md += "**ANTE​​PROYECTO PARA REVISIÓN HUMANA**\n\n"
md += "## Exposición de motivos\n\n"
md += bill["statement_of_reasons"] + "\n\n"
md += "## Artículos propuestos\n\n"

ordered_drafts = drafts_df.sort_values(
    "article",
    key=lambda s: s.map(article_sort_key)
)

for _, d in ordered_drafts.iterrows():
    md += f"### Artículo {d['article']}\n\n"
    md += f"**Operación:** {d['operation']}\n\n"
    md += d["proposed_text"] + "\n\n"
    md += f"**Explicación:** {d['change_explanation']}\n\n"

md += "\n---\n"
md += (
    "**Estado:** ANTEPROYECTO PARA REVISIÓN HUMANA. "
    "No constituye una iniciativa presentada, opinión legal ni asesoría jurídica.\n"
)

(OUT / "anteproyecto_LMV.md").write_text(md)

metrics = {
    "agents": len(agents),
    "diagnostic_findings": len(diagnoses_df),
    "diagnostic_agents": diagnoses_df["agent"].nunique(),
    "diagnosed_articles": len(distinct_diagnosed_articles(diagnoses_df)),
    "proposals": len(proposals_df),
    "candidate_articles": len(distinct_existing_candidates(proposals_df)),
    "reviews": len(reviews_df),
    "selected_articles": shortlist["article"].nunique(),
    "drafted_articles": drafts_df["article"].nunique(),
    "ready_for_human_review": READY_FOR_HUMAN_REVIEW
}

print(json.dumps(metrics, indent=2))
print("\nOutputs:")
for p in sorted(OUT.iterdir()):
    print(" -", p.name)

print("\n✓ END-TO-END SWARM PIPELINE COMPLETE.")

{
  "agents": 50,
  "diagnostic_findings": 176,
  "diagnostic_agents": 37,
  "diagnosed_articles": 169,
  "proposals": 33,
  "candidate_articles": 33,
  "reviews": 33,
  "selected_articles": 20,
  "drafted_articles": 20,
  "ready_for_human_review": true
}

Outputs:
 - 20_article_drafts.csv
 - 20_article_shortlist.csv
 - anteproyecto_LMV.md
 - audit_log.csv
 - governance_report.json
 - preliminary_bill.json
 - round1_diagnoses.csv
 - round2_proposals.csv
 - round3_adversarial_reviews.csv
 - validation_report.json

✓ END-TO-END SWARM PIPELINE COMPLETE.

# Conclusión

El experimento desarrollado en este notebook muestra una forma distinta de pensar la relación entre inteligencia artificial y reforma jurídica. La aproximación más sencilla habría sido entregar la Ley del Mercado de Valores a un modelo y pedirle veinte modificaciones. Probablemente habría producido un documento plausible en pocos minutos. Precisamente por eso ese enfoque sería insuficiente. La dificultad real no está en generar lenguaje legislativo; está en decidir qué problemas merecen reforma, qué intereses deben escucharse, qué evidencia sostiene cada diagnóstico, qué riesgos crea cada alternativa y quién tiene autoridad para transformar una propuesta en decisión.

El enjambre de cincuenta agentes convierte esa dificultad en arquitectura. Los agentes comparten un modelo —Claude Haiku 4.5—, pero ocupan posiciones institucionales distintas. Abogados, legisladores, reguladores, emisoras, bolsas, intermediarios, inversionistas y especialistas comparados no son tratados como voces intercambiables. Cada uno recibe objetivos y sesgos explícitos. Esa decisión es importante porque una deliberación útil no necesita fingir neutralidad; necesita hacer visibles los intereses y obligarlos a encontrarse bajo reglas comunes.

El corpus funciona como memoria jurídica controlada. La Ley del Mercado de Valores vigente constituye la fuente primaria y las demás referencias se incorporan con procedencia y jurisdicción. Esta disciplina limita una de las fallas más conocidas de los modelos generativos: producir afirmaciones convincentes sin base verificable. En el notebook, un artículo no puede entrar a la reforma final si no puede rastrearse al corpus o identificarse expresamente como una nueva disposición. El derecho comparado amplía el espacio de alternativas, pero no recibe autoridad para sustituir el marco mexicano.

La dinámica de inner loop y outer loop añade una segunda dimensión. En el inner loop se diagnostica, propone, critica y redacta. En el outer loop se pregunta si el proceso mismo está funcionando: si hay concentración de influencia, si ciertas voces quedaron fuera, si el consenso es artificial o si faltan evidencias. Esta distinción resulta especialmente importante en sistemas adaptativos. Permitir que un enjambre reorganice sus constelaciones puede mejorar la solución de problemas, pero no significa permitir que modifique sus propias facultades.

La selección de exactamente veinte artículos ilustra otra idea central. Un algoritmo puede ordenar propuestas y construir un portafolio multicriterio; no por ello adquiere autoridad legislativa. La puerta de aprobación humana existe precisamente para separar capacidad de facultad. El sistema propone; una instancia distinta evalúa; y la autorización permanece fuera del agente que produjo la recomendación. Esa separación no es una limitación accidental de la inteligencia artificial. Es una característica deliberada de buen diseño institucional.

El producto final debe entenderse, por tanto, como un anteproyecto trazable. Cada artículo puede reconstruirse desde el diagnóstico inicial hasta la redacción propuesta, pasando por apoyos, objeciones, comparaciones y validaciones. Esa genealogía permite que un abogado, regulador o legislador cuestione el resultado sin tener que confiar en una “caja negra” que simplemente afirma haber encontrado la mejor reforma.

También quedan límites claros. El notebook no sustituye técnica legislativa profesional, análisis constitucional, consulta pública, evaluación de impacto regulatorio, negociación política ni revisión de legislación secundaria. Tampoco convierte cincuenta simulaciones de perspectivas en cincuenta participantes reales del mercado. El enjambre es una herramienta para ampliar y ordenar el espacio de análisis, no un mecanismo de representación democrática.

Su utilidad pedagógica, sin embargo, es considerable. En un solo caso se observan los conceptos centrales de la conferencia: conocimiento estructurado, memoria con procedencia, integración de especialidades, agentes, arneses, autonomía acotada, trazabilidad, separación de funciones y gobierno del cambio. La inteligencia artificial deja de aparecer como un interlocutor que contesta preguntas y se convierte en parte de una arquitectura institucional.

La conclusión más importante es quizá la más sencilla: una mejor reforma no surge porque tengamos más agentes, sino porque diseñamos mejor la relación entre conocimiento, perspectivas, evidencia, crítica y autoridad. El enjambre puede ampliar extraordinariamente nuestra capacidad de pensar una ley. La decisión sobre qué ley queremos, para qué mercado y bajo qué responsabilidad sigue siendo una decisión humana e institucional.

Por ello, el criterio de éxito del caso no debería ser que la iniciativa “suene” profesional ni que los cincuenta agentes alcancen unanimidad. Debería ser que un tercero pueda abrir el expediente, identificar el corpus utilizado, reconstruir los desacuerdos, comprender por qué se eligieron esos veinte artículos y distinguir con claridad qué parte del trabajo fue generativa, cuál fue determinista y dónde intervino la autorización humana. Ésa es la diferencia entre automatizar redacción y diseñar una institución inteligente.

Si el experimento funciona, su lección es transferible. La misma arquitectura podría utilizarse para revisar regulación secundaria, reglas de una bolsa, un código de gobierno corporativo o incluso una reforma en otra rama jurídica. Cambiarían los agentes, el corpus, los criterios y la autoridad competente; no cambiaría el principio fundamental: la inteligencia puede distribuirse y coordinarse, pero la legitimidad exige fuentes, límites, revisión y responsabilidad.

#Repositorio

In [ ]:
import shutil
from pathlib import Path
from google.colab import drive

# Mount Google Drive
try:
    print("Montando Google Drive...")
    drive.mount('/content/drive')
    print("Google Drive montado exitosamente.")
except Exception as e:
    print(f"Error al montar Google Drive: {e}")

# Define paths
source_dir = Path('/content/lmv_swarm_output')
target_dir = Path('/content/drive/MyDrive/Enjambre_LMV_Output')

if source_dir.exists():
    # Create target directory if it doesn't exist
    target_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nCopiando archivos de {source_dir} a {target_dir}...")
    copied_files = []
    for item in source_dir.glob('*'):
        if item.is_file():
            shutil.copy2(item, target_dir / item.name)
            copied_files.append(item.name)
            print(f" - Copiado: {item.name}")

    print(f"\n¡Proceso completado! Se han respaldado {len(copied_files)} archivos en tu Google Drive.")
else:
    print(f"La ruta de origen {source_dir} no existe. Por favor, asegúrate de que el enjambre haya ejecutado y generado las salidas primero.")

Montando Google Drive...
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Google Drive montado exitosamente.

Copiando archivos de /content/lmv_swarm_output a /content/drive/MyDrive/Enjambre_LMV_Output...
 - Copiado: validation_report.json
 - Copiado: 20_article_shortlist.csv
 - Copiado: 20_article_drafts.csv
 - Copiado: preliminary_bill.json
 - Copiado: anteproyecto_LMV.md
 - Copiado: audit_log.csv
 - Copiado: round2_proposals.csv
 - Copiado: round3_adversarial_reviews.csv
 - Copiado: round1_diagnoses.csv
 - Copiado: governance_report.json

¡Proceso completado! Se han respaldado 10 archivos en tu Google Drive.