# CROSS-SCIENCE MARKET REGIME DISCOVERY WITH A 50-AGENT SWARM

Financial markets are observed continuously but their governing state is not. Prices, volatility, liquidity, correlations, credit spreads, yield curves, volume, dispersion and cross-asset relationships are visible; the latent condition that makes those signals cohere is not. Traders therefore confront an inverse problem. We see consequences and try to infer the hidden mechanism that generated them. A calm expansion, a momentum-dominated risk-on phase, an inflation shock, a liquidity crisis, a deleveraging episode and an early recovery can produce radically different mappings from the same observable signal to subsequent returns. A strategy that is sensible in one state may be destructive in another. This makes regime identification one of the deepest recurring problems in market science.

The Hidden Markov Model became famous in this setting for a good reason. It gives a disciplined probabilistic language for an unobserved state that evolves through time and emits observable data. Yet the HMM is only one member of a much larger intellectual family. Other sciences have spent decades, and sometimes centuries, solving structurally similar problems: infer an invisible state from noisy measurements; detect phase transitions; identify changes in dynamical systems; distinguish signal from noise; recover hidden sources; characterize metastable states; recognize topology changes; infer a system’s energy landscape; and determine when an apparently stable process has crossed into a different operating domain. The central premise of this notebook is that finance should borrow more aggressively from those neighboring mathematical traditions.

The experiment therefore uses transfer learning in a broad scientific sense. We are not merely transferring neural-network weights from one dataset to another. We transfer abstractions, mathematical objects, diagnostics and inferential habits from other fields into market-regime discovery. Fifty Claude Sonnet 5 agents are divided into ten disciplinary families: statistical physics, dynamical systems, electrical and signal engineering, control theory, information theory, applied mathematics, chemistry and statistical mechanics, astrophysics, network science, and geophysics/seismology. Five agents within each family receive different methodological identities. Their task is not to forecast the market directly. Their task is to ask a more foundational question: if this market-regime problem appeared in my own science, what hidden object would I infer, what observables would I measure, what mathematics would I use, and what empirical signature would convince me that the inferred state is real?

This distinction is essential. A swarm is useful only if diversity is genuine. Fifty agents repeating a financial HMM with different wording would add cost but little knowledge. Here disciplinary prompts deliberately create different priors. A physicist may see phase transitions and order parameters. A signal engineer may see a latent source embedded in multiscale noise. A control theorist may think in terms of state-space observability and filtering. A chemist may recognize metastability and transition rates. An astrophysicist may use change-point detection and weak-signal extraction. A network scientist may define regime through correlation topology rather than through the marginal distribution of returns. A geophysicist may focus on precursors, critical slowing, rupture-like transitions and multiscale event clustering. These are not metaphors for decoration; the notebook asks the agents to translate them into mathematical candidates that can be operationalized.

The architecture separates scientific imagination from empirical discipline. Claude is used for hypothesis generation, model specification, critique and synthesis. Python is used for data, feature construction, deterministic diagnostics, clustering, transition analysis, validation and provenance. The language model is never allowed to manufacture market observations. It receives a compact numerical description of the empirical feature space and proposes models against an explicit schema. This separation matters because a plausible narrative is not evidence of a regime. A useful regime model must produce states that are persistent enough to be meaningful, distinct enough to interpret, stable enough to survive perturbations, and economically consequential enough to change conditional market behavior.

The notebook also avoids the common mistake of forcing a single winning model too early. The swarm first generates a library of cross-science proposals. Those proposals are embedded into a common taxonomy: latent-state representation, transition mechanism, observation mapping, mathematical machinery, diagnostics, falsification tests and expected failure modes. A synthesis stage then looks for recurring structures across disciplines. The objective is an architecture rather than a beauty contest. In complex markets, the best representation may be composite: a probabilistic latent state for persistence, spectral features for multiscale structure, network features for collective behavior, and change-point logic for transitions. The swarm is therefore asked to identify complementarities as well as disagreements.

For the empirical substrate, the notebook downloads a diversified set of liquid market proxies and constructs signals that represent several dimensions of market state: trend, realized volatility, downside asymmetry, cross-sectional dispersion, average correlation, breadth, drawdown, volatility-of-volatility, volume pressure where available, and cross-asset relative behavior. The exact assets are replaceable. What matters is that regime inference is multivariate. A hidden state of the market should not be inferred from the S&P 500 return alone if the claim is that the state governs the market system.

The executable benchmark deliberately remains transparent. It constructs a robustly scaled feature matrix, applies several unsupervised views of the same latent problem, and produces a consensus state representation. The swarm’s theoretical proposals are not blindly converted into arbitrary code generated at runtime. Instead, they inform a controlled architecture built from auditable components. This is a crucial governance choice. Scientific creativity occurs in the proposal layer; empirical claims occur in the reproducible layer. The notebook records prompts, model identifiers, request IDs, agent outputs, consensus diagnostics and validation statistics so that the research path can be inspected later.

Validation is treated as a first-class problem. Regime discovery is unusually vulnerable to beautiful overfitting because there is no directly observed label called “true market regime.” The notebook therefore asks whether inferred states exhibit persistence, whether they differ in subsequent return and risk distributions, whether the partition is stable under feature perturbation, whether a smaller subswarm reaches similar scientific conclusions, and whether transitions concentrate around periods of unusually large changes in the market feature vector. None of these tests proves ontological truth. Together, however, they make the latent-state hypothesis more falsifiable.

The final output is a research architecture for a “Market Regime Observatory”: an ensemble that treats regime as a latent, evolving, multiscale object rather than as a single categorical label. It distinguishes state estimation from transition detection and uncertainty. Instead of saying merely “the market is in regime 3,” the system aims to report the current consensus state, its probability or confidence, the features that make the state distinctive, the degree of disagreement among alternative scientific lenses, and evidence that the system may be approaching a transition.

The ambition is deliberately high but the epistemic claim is modest. This notebook does not announce that the Holy Grail has been solved. It constructs a disciplined experiment for searching a much larger hypothesis space than finance usually explores. Its value lies in asking whether fifty scientifically diverse agents can discover transferable mathematical structures that a finance-only research team might overlook, and whether those structures can be compressed into an empirical architecture that survives transparent tests. If successful, the contribution is not a magical regime label. It is a better research machine for reasoning about hidden market conditions.

###CODE UNIT 1 - Libraries and Environment

CODE UNIT 1 establishes the research environment, the live-data substrate and the reproducibility contract. The code installs only the packages needed for the experiment, loads the Anthropic key from Colab Secrets, fixes the current Claude Sonnet 5 model identifier, and centralizes the swarm and token settings. The API design is intentionally conservative: no temperature, top-p or top-k is passed, because current Sonnet 5 rejects non-default sampling parameters. We also use low effort because the intelligence of the experiment comes from disciplinary diversity across fifty agents rather than from asking every individual call to perform maximal reasoning.

The market universe is deliberately cross-asset. Equity, Treasury, credit, commodity, dollar and volatility proxies provide a richer view of the latent market system than a single equity index. The code downloads adjusted daily histories, aligns them on a common calendar and keeps the dataset inspectable. A researcher can later replace the universe without changing the architecture.

Reproducibility begins here. Seeds, dates, model name, agent count and package assumptions are explicit. The notebook never places the API key in source code. If the secret is missing, it fails immediately with a clear instruction rather than continuing into an ambiguous state. This unit also creates output directories and a run manifest. Subsequent cells add agent prompts, request IDs, model proposals, consensus objects and validation results to that provenance trail. The objective is to make the notebook usable as a research instrument rather than a one-off demonstration.

In [ ]:
# ============================================================
# CODE CELL 1
# ENVIRONMENT, CLAUDE CONFIGURATION & MARKET DATA
# ============================================================

!pip -q install anthropic yfinance


# ============================================================
# 1. IMPORTS
# ============================================================

import json
import time
import random
import warnings
import re

from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd
import yfinance as yf

from anthropic import Anthropic
from google.colab import userdata


# ============================================================
# 2. REPRODUCIBILITY
# ============================================================

warnings.filterwarnings("ignore")

SEED = 42

np.random.seed(SEED)
random.seed(SEED)


# ============================================================
# 3. MASTER CLAUDE CONFIGURATION
# ============================================================
#
# IMPORTANT:
#
# EFFORT controls reasoning intensity.
#
# We deliberately use LOW effort because the intelligence of
# this experiment comes primarily from:
#
#     diversity across 50 scientific agents
#
# rather than expensive reasoning by every individual agent.
#
# max_tokens is an OUTPUT CEILING, not a target.
# Most agents should terminate well before the ceiling.
# ============================================================

MODEL = "claude-sonnet-5"

EFFORT = "low"

N_AGENTS = 50


# Normal structured-output allowance

INITIAL_MAX_TOKENS = 2500


# First fallback for unusually verbose agents

RETRY_MAX_TOKENS = 5000


# Absolute emergency ceiling

FINAL_MAX_TOKENS = 8000


# ============================================================
# 4. MARKET SAMPLE
# ============================================================

START = "2012-01-01"

END = None


# ============================================================
# 5. OUTPUT DIRECTORY
# ============================================================

OUT = Path(
    "/content/regime_swarm_outputs"
)

OUT.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 6. ANTHROPIC API
# ============================================================

ANTHROPIC_API_KEY = userdata.get(
    "ANTHROPIC_API_KEY"
)


if not ANTHROPIC_API_KEY:

    raise ValueError(
        "ANTHROPIC_API_KEY was not found in Colab Secrets."
    )


client = Anthropic(
    api_key=ANTHROPIC_API_KEY
)


# ============================================================
# 7. MULTI-ASSET MARKET UNIVERSE
# ============================================================

TICKERS = {

    "SPY": "US_equity",

    "QQQ": "growth_equity",

    "IWM": "small_cap",

    "TLT": "long_treasury",

    "IEF": "intermediate_treasury",

    "LQD": "investment_grade_credit",

    "HYG": "high_yield_credit",

    "GLD": "gold",

    "DBC": "commodities",

    "UUP": "usd",

    "^VIX": "vix"
}


# ============================================================
# 8. DOWNLOAD MARKET DATA
# ============================================================

print("Downloading market data...")


raw = yf.download(

    tickers=list(TICKERS.keys()),

    start=START,

    end=END,

    auto_adjust=True,

    progress=False,

    group_by="column",

    threads=True
)


# ============================================================
# 9. EXTRACT PRICES
# ============================================================

if isinstance(
    raw.columns,
    pd.MultiIndex
):

    if "Close" not in raw.columns.get_level_values(0):

        raise ValueError(
            "Yahoo Finance download does not contain Close prices."
        )

    px = raw["Close"].copy()


else:

    if "Close" not in raw.columns:

        raise ValueError(
            "Yahoo Finance download does not contain Close prices."
        )

    px = raw[["Close"]].copy()


# ============================================================
# 10. EXTRACT VOLUME
# ============================================================

if isinstance(
    raw.columns,
    pd.MultiIndex
):

    if "Volume" in raw.columns.get_level_values(0):

        vol = raw["Volume"].copy()

    else:

        vol = pd.DataFrame(
            index=px.index
        )

else:

    if "Volume" in raw.columns:

        vol = raw[["Volume"]].copy()

    else:

        vol = pd.DataFrame(
            index=px.index
        )


# ============================================================
# 11. CLEAN DATA
# ============================================================

px = (
    px
    .sort_index()
    .dropna(how="all")
    .ffill()
)


px = px.dropna(
    axis=1,
    how="all"
)


px = px.dropna()


if px.empty:

    raise ValueError(
        "No usable market observations were downloaded."
    )


# ============================================================
# 12. RUN MANIFEST
# ============================================================

manifest = {

    "project":
        "50-Agent Cross-Science Market Regime Swarm",

    "model":
        MODEL,

    "effort":
        EFFORT,

    "n_agents":
        N_AGENTS,

    "initial_max_tokens":
        INITIAL_MAX_TOKENS,

    "retry_max_tokens":
        RETRY_MAX_TOKENS,

    "final_max_tokens":
        FINAL_MAX_TOKENS,

    "seed":
        SEED,

    "start":
        START,

    "end":
        END,

    "tickers":
        TICKERS,

    "observations":
        int(len(px)),

    "assets_loaded":
        list(px.columns),

    "status":
        "EDUCATIONAL RESEARCH — NOT INVESTMENT ADVICE"
}


manifest_path = (
    OUT / "run_manifest.json"
)


manifest_path.write_text(

    json.dumps(
        manifest,
        indent=2
    ),

    encoding="utf-8"
)


# ============================================================
# 13. INITIALIZATION REPORT
# ============================================================

print("\n" + "=" * 72)

print(
    "50-AGENT CROSS-SCIENCE MARKET REGIME SWARM"
)

print("=" * 72)


print("\nCLAUDE CONFIGURATION")

print(
    f"Model              : {MODEL}"
)

print(
    f"Reasoning effort   : {EFFORT}"
)

print(
    f"Scientific agents  : {N_AGENTS}"
)

print(
    f"Initial token cap  : {INITIAL_MAX_TOKENS}"
)

print(
    f"Retry token cap    : {RETRY_MAX_TOKENS}"
)

print(
    f"Emergency cap      : {FINAL_MAX_TOKENS}"
)


print("\nMARKET DATABASE")

print(
    f"Observations       : {len(px):,}"
)

print(
    f"Assets             : {px.shape[1]}"
)

print(
    f"Start              : {px.index.min().date()}"
)

print(
    f"End                : {px.index.max().date()}"
)


print("\nASSETS")

for ticker in px.columns:

    print(
        f"{ticker:6s}  "
        f"{TICKERS.get(ticker, '')}"
    )


print("\n" + "=" * 72)

print(
    "CELL 1 COMPLETE"
)

print("=" * 72)


display(
    px.tail()
)

Downloading market data...

========================================================================
50-AGENT CROSS-SCIENCE MARKET REGIME SWARM
========================================================================

CLAUDE CONFIGURATION
Model              : claude-sonnet-5
Reasoning effort   : low
Scientific agents  : 50
Initial token cap  : 2500
Retry token cap    : 5000
Emergency cap      : 8000

MARKET DATABASE
Observations       : 3,704
Assets             : 11
Start              : 2012-01-03
End                : 2026-09-23

ASSETS
DBC     commodities
GLD     gold
HYG     high_yield_credit
IEF     intermediate_treasury
IWM     small_cap
LQD     investment_grade_credit
QQQ     growth_equity
SPY     US_equity
TLT     long_treasury
UUP     usd
^VIX    vix

========================================================================
CELL 1 COMPLETE
========================================================================

Ticker,DBC,GLD,HYG,IEF,IWM,LQD,QQQ,SPY,TLT,UUP,^VIX
Date,,,,,,,,,,,
2026-09-17,33.049999,398.359985,78.720001,91.250000,285.429993,105.160004,716.173706,760.710999,81.779999,28.379999,15.44
2026-09-18,32.930000,401.170013,78.529999,90.800003,284.100006,104.699997,720.699036,761.690002,81.250000,28.389999,14.81
2026-09-21,32.580002,398.380005,78.680000,91.150002,285.579987,105.089996,741.469971,773.500000,81.800003,28.480000,14.87
2026-09-22,32.580002,400.070007,78.680000,91.150002,287.209991,105.089996,747.460022,773.380005,81.750000,28.480000,14.87
2026-09-23,32.880001,392.880005,78.099998,90.190002,281.920013,103.889999,741.210022,767.809998,80.459999,28.650000,15.18

### CODE UNIT 2 — Building the multivariate market-state measurement system

CODE UNIT 2 turns raw prices into an observable state vector. This is the empirical heart of the inverse problem: the hidden regime is not observed, so the quality of inference depends on whether the measurements span the dimensions through which regimes reveal themselves. The feature set is intentionally compact enough for interpretation but broad enough to represent trend, volatility, dependence, breadth, drawdown and cross-asset stress.

Daily log returns are computed first. Rolling equity trend and volatility summarize directional and risk conditions. Downside volatility separates harmful variability from symmetric noise. Breadth measures the fraction of risk assets with positive medium-horizon momentum. Average rolling correlation captures the familiar phenomenon that diversification can disappear in stress. Cross-sectional dispersion measures disagreement among assets. Drawdown records path dependence. Changes in VIX and credit-relative performance introduce forward-looking risk pricing and financing conditions. Treasury/equity and gold/equity relative momentum add information about defensive rotation.

Features are winsorized through robust quantile clipping and then transformed with RobustScaler, which is less sensitive to extreme observations than mean-variance standardization. This is important because extreme market events are informative but should not numerically dominate every distance calculation. The code retains both the economically interpretable feature table and the scaled matrix used by algorithms.

The cell also constructs a compact empirical summary that later goes to the swarm. Agents do not receive thousands of daily rows. They receive feature names, moments and correlations, enough to anchor proposals in the actual measurement system while keeping calls inexpensive. This preserves the separation between language-model hypothesis generation and deterministic data analysis.

In [ ]:
from sklearn.preprocessing import RobustScaler

rets = np.log(px).diff()
risk_assets = [c for c in ["SPY","QQQ","IWM","HYG","LQD","GLD","DBC","TLT"] if c in px.columns]

F = pd.DataFrame(index=px.index)
F["spy_ret_5d"] = np.log(px["SPY"]).diff(5)
F["spy_trend_63d"] = np.log(px["SPY"]).diff(63)
F["spy_vol_21d"] = rets["SPY"].rolling(21).std() * np.sqrt(252)
F["spy_downvol_63d"] = rets["SPY"].clip(upper=0).rolling(63).std() * np.sqrt(252)
F["spy_drawdown"] = px["SPY"] / px["SPY"].cummax() - 1
F["cross_asset_dispersion"] = rets[risk_assets].rolling(21).std().mean(axis=1)

rolling_corr = rets[risk_assets].rolling(63).corr()
avg_corr = []
dates = []
for dt in px.index:
    try:
        C = rolling_corr.loc[dt]
        a = C.values[np.triu_indices_from(C.values, 1)]
        avg_corr.append(np.nanmean(a)); dates.append(dt)
    except Exception:
        pass
F.loc[dates, "avg_corr_63d"] = avg_corr

mom63 = np.log(px[risk_assets]).diff(63)
F["breadth_63d"] = (mom63 > 0).mean(axis=1)
if "^VIX" in px:
    F["vix_level"] = np.log(px["^VIX"])
    F["vix_change_21d"] = np.log(px["^VIX"]).diff(21)
if "HYG" in px and "LQD" in px:
    F["credit_risk_21d"] = np.log(px["HYG"]/px["LQD"]).diff(21)
if "TLT" in px:
    F["bond_equity_rotation_21d"] = np.log(px["TLT"]/px["SPY"]).diff(21)
if "GLD" in px:
    F["gold_equity_rotation_21d"] = np.log(px["GLD"]/px["SPY"]).diff(21)

F = F.replace([np.inf,-np.inf], np.nan).dropna()
lo, hi = F.quantile(.01), F.quantile(.99)
F_clip = F.clip(lo, hi, axis=1)

scaler = RobustScaler()
X = pd.DataFrame(scaler.fit_transform(F_clip), index=F_clip.index, columns=F_clip.columns)

empirical_summary = {
    "features": list(F.columns),
    "n_observations": int(len(F)),
    "start": str(F.index.min().date()),
    "end": str(F.index.max().date()),
    "feature_medians": F.median().round(4).to_dict(),
    "feature_correlations": F.corr().round(2).to_dict()
}
print("Feature matrix:", X.shape)
display(F.tail())

Feature matrix: (3641, 13)

,spy_ret_5d,spy_trend_63d,spy_vol_21d,spy_downvol_63d,spy_drawdown,cross_asset_dispersion,avg_corr_63d,breadth_63d,vix_level,vix_change_21d,credit_risk_21d,bond_equity_rotation_21d,gold_equity_rotation_21d
Date,,,,,,,,,,,,,
2026-09-17,0.006275,0.021017,0.093822,0.058719,-0.019643,0.007411,0.297753,0.375,2.736962,0.036272,0.002097,-0.002789,-0.029688
2026-09-18,-0.000927,0.025455,0.089267,0.058949,-0.018382,0.007306,0.296815,0.375,2.695303,-0.077911,0.001151,-0.010788,-0.035806
2026-09-21,0.018930,0.055469,0.103186,0.053866,-0.003162,0.007636,0.294097,0.500,2.699346,-0.017334,-0.002608,-0.011816,-0.073406
2026-09-22,0.023372,0.055778,0.102429,0.053914,-0.003316,0.007522,0.303529,0.625,2.699346,-0.063824,-0.001286,-0.021412,-0.079795
2026-09-23,0.020564,0.047105,0.105588,0.054556,-0.010494,0.007767,0.313422,0.500,2.719979,-0.017630,0.006427,-0.037860,-0.090740

### CODE UNIT 3 — Designing 50 agents across ten scientific disciplines

CODE UNIT 3 creates the fifty-agent scientific population. The design uses ten disciplinary families with five variants each, producing diversity by construction rather than by random wording. Every family is chosen because it contains mature methods for inferring hidden structure from noisy observations. The five variants within a family emphasize different traditions, so two physicists, for example, need not produce the same phase-transition proposal.

Each agent receives a scientific identity and a common contract. The contract asks for a latent object, a transfer principle, a mathematical core, required observables, a transition detector, a validation plan and explicit failure modes. This structure is crucial. Without it, the swarm would produce attractive essays that are difficult to compare. With it, each response becomes a candidate research specification.

The JSON schema is strict and compact. String lengths are controlled by prompting rather than enormous token budgets. Confidence is bounded between zero and one, candidate state counts are bounded, and failure modes are capped. The schema disallows additional properties so that accidental prose outside the contract does not silently contaminate downstream analysis.

This unit does not yet call Claude. It builds the population and the output contract, making the swarm inspectable before cost is incurred. The resulting roster can be displayed and audited. In a serious research process this is analogous to preregistering the expert panel: we decide what intellectual diversity we want before seeing which ideas happen to be attractive.

In [ ]:
FAMILIES = {
"Statistical Physics":[
 "phase transitions and order parameters","metastability and energy landscapes",
 "critical phenomena and susceptibility","spin systems and collective alignment",
 "non-equilibrium statistical mechanics"],
"Dynamical Systems":[
 "attractors and basins","bifurcation theory","state-space reconstruction",
 "Lyapunov stability","slow-fast systems"],
"Signal Engineering":[
 "spectral decomposition","wavelets and multiresolution analysis",
 "blind source separation","change detection","signal-to-noise filtering"],
"Control Theory":[
 "Kalman/state-space observability","switching state-space systems",
 "robust control","system identification","adaptive filtering"],
"Information Theory":[
 "entropy and mutual information","information bottleneck","minimum description length",
 "transfer entropy","distributional divergence"],
"Applied Mathematics":[
 "operator methods","topological data analysis","optimal transport",
 "manifold learning","Bayesian inverse problems"],
"Chemistry & Statistical Mechanics":[
 "reaction coordinates","transition-state theory","free-energy landscapes",
 "kinetic state models","nucleation and phase change"],
"Astrophysics":[
 "weak-signal extraction","Bayesian blocks/change points","mixture populations",
 "multiscale time-series inference","latent-source identification"],
"Network Science":[
 "correlation topology","community structure","network percolation",
 "graph spectral methods","dynamic networks"],
"Geophysics & Seismology":[
 "precursor detection","critical slowing and rupture","event clustering",
 "multiscale stress accumulation","regime shifts in complex geosystems"]
}

agents = []
i = 1
for family, variants in FAMILIES.items():
    for variant in variants:
        agents.append({"agent_id":f"A{i:02d}", "family":family, "specialty":variant})
        i += 1
assert len(agents) == 50

AGENT_SCHEMA = {
 "type":"object",
 "properties":{
   "agent_id":{"type":"string"},
   "family":{"type":"string"},
   "proposed_name":{"type":"string"},
   "latent_object":{"type":"string"},
   "transfer_principle":{"type":"string"},
   "mathematical_core":{"type":"array","items":{"type":"string"},"minItems":2,"maxItems":5},
   "required_features":{"type":"array","items":{"type":"string"},"minItems":2,"maxItems":8},
   "transition_detector":{"type":"string"},
   "state_count":{"type":"integer","minimum":2,"maximum":8},
   "validation_tests":{"type":"array","items":{"type":"string"},"minItems":2,"maxItems":5},
   "failure_modes":{"type":"array","items":{"type":"string"},"minItems":1,"maxItems":3},
   "novelty":{"type":"number","minimum":0,"maximum":1},
   "plausibility":{"type":"number","minimum":0,"maximum":1},
   "confidence":{"type":"number","minimum":0,"maximum":1},
   "rationale":{"type":"string"}
 },
 "required":["agent_id","family","proposed_name","latent_object","transfer_principle",
             "mathematical_core","required_features","transition_detector","state_count",
             "validation_tests","failure_modes","novelty","plausibility","confidence","rationale"],
 "additionalProperties":False
}

display(pd.DataFrame(agents))

,agent_id,family,specialty
0,A01,Statistical Physics,phase transitions and order parameters
1,A02,Statistical Physics,metastability and energy landscapes
2,A03,Statistical Physics,critical phenomena and susceptibility
3,A04,Statistical Physics,spin systems and collective alignment
4,A05,Statistical Physics,non-equilibrium statistical mechanics
5,A06,Dynamical Systems,attractors and basins
6,A07,Dynamical Systems,bifurcation theory
7,A08,Dynamical Systems,state-space reconstruction
8,A09,Dynamical Systems,Lyapunov stability
9,A10,Dynamical Systems,slow-fast systems
10,A11,Signal Engineering,spectral decomposition
11,A12,Signal Engineering,wavelets and multiresolution analysis
12,A13,Signal Engineering,blind source separation
13,A14,Signal Engineering,change detection
14,A15,Signal Engineering,signal-to-noise filtering
15,A16,Control Theory,Kalman/state-space observability
16,A17,Control Theory,switching state-space systems
17,A18,Control Theory,robust control
18,A19,Control Theory,system identification
19,A20,Control Theory,adaptive filtering
20,A21,Information Theory,entropy and mutual information
21,A22,Information Theory,information bottleneck
22,A23,Information Theory,minimum description length
23,A24,Information Theory,transfer entropy
24,A25,Information Theory,distributional divergence
25,A26,Applied Mathematics,operator methods
26,A27,Applied Mathematics,topological data analysis
27,A28,Applied Mathematics,optimal transport
28,A29,Applied Mathematics,manifold learning
29,A30,Applied Mathematics,Bayesian inverse problems
30,A31,Chemistry & Statistical Mechanics,reaction coordinates
31,A32,Chemistry & Statistical Mechanics,transition-state theory
32,A33,Chemistry & Statistical Mechanics,free-energy landscapes
33,A34,Chemistry & Statistical Mechanics,kinetic state models
34,A35,Chemistry & Statistical Mechanics,nucleation and phase change
35,A36,Astrophysics,weak-signal extraction
36,A37,Astrophysics,Bayesian blocks/change points
37,A38,Astrophysics,mixture populations
38,A39,Astrophysics,multiscale time-series inference
39,A40,Astrophysics,latent-source identification
40,A41,Network Science,correlation topology
41,A42,Network Science,community structure
42,A43,Network Science,network percolation
43,A44,Network Science,graph spectral methods
44,A45,Network Science,dynamic networks
45,A46,Geophysics & Seismology,precursor detection
46,A47,Geophysics & Seismology,critical slowing and rupture
47,A48,Geophysics & Seismology,event clustering
48,A49,Geophysics & Seismology,multiscale stress accumulation
49,A50,Geophysics & Seismology,regime shifts in complex geosystems

### CODE UNIT 4 — Current Claude Sonnet 5 structured-output interface and canary

CODE UNIT 4 is the live Claude interface and is deliberately engineered around the current Sonnet 5 API rather than patterns inherited from older Claude generations. The notebook uses the Messages API with the model string `claude-sonnet-5`, low effort through `output_config`, and native JSON Schema structured output. It does not use temperature, top-p, top-k, assistant prefilling, manual thinking-token budgets, regex extraction or “please return JSON” followed by hopeful parsing.

The function checks `stop_reason` before accepting the response. If the first call ends because the token ceiling was reached, it retries once with a larger output allowance. Only text blocks are concatenated, and the resulting string is parsed with `json.loads`. Request IDs and stop reasons are retained for provenance. A malformed or refused response raises an explicit error rather than being converted into a fabricated fallback opinion.

Most importantly, the code performs a canary call on the first agent. This is the protection against the failure pattern that has affected earlier notebooks: launching dozens of expensive calls with an outdated parameter or response format and discovering the incompatibility only after the swarm is underway. The remaining forty-nine calls run only after the first response has passed schema-shaped parsing and basic identity checks.

The prompt asks each agent to remain inside its scientific discipline and to translate, not merely rename, its mathematics. It also tells the agent that the output is a research hypothesis, not investment advice. The empirical summary is included in compact JSON form so proposals are connected to the actual feature space.

In [ ]:
# ============================================================
# CODE CELL 4
# CLAUDE SONNET 5 INTERFACE & CANARY TEST
# ============================================================

import json


# ============================================================
# 1. CLAUDE-COMPATIBLE STRUCTURED OUTPUT SCHEMA
# ============================================================
#
# Array lengths and numerical ranges are intentionally NOT
# encoded here.
#
# They are enforced locally after Claude returns its JSON.
# ============================================================

CLAUDE_AGENT_SCHEMA = {

    "type": "object",

    "properties": {

        "agent_id": {
            "type": "string"
        },

        "family": {
            "type": "string"
        },

        "proposed_name": {
            "type": "string"
        },

        "latent_object": {
            "type": "string"
        },

        "transfer_principle": {
            "type": "string"
        },

        "mathematical_core": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "required_features": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "transition_detector": {
            "type": "string"
        },

        "state_count": {
            "type": "integer"
        },

        "validation_tests": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "failure_modes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "novelty": {
            "type": "number"
        },

        "plausibility": {
            "type": "number"
        },

        "confidence": {
            "type": "number"
        },

        "rationale": {
            "type": "string"
        }
    },


    "required": [

        "agent_id",

        "family",

        "proposed_name",

        "latent_object",

        "transfer_principle",

        "mathematical_core",

        "required_features",

        "transition_detector",

        "state_count",

        "validation_tests",

        "failure_modes",

        "novelty",

        "plausibility",

        "confidence",

        "rationale"
    ],


    "additionalProperties": False
}


# ============================================================
# 2. SCHEMA PREFLIGHT
# ============================================================

schema_text = json.dumps(
    CLAUDE_AGENT_SCHEMA
)


FORBIDDEN_SCHEMA_TERMS = [

    '"minItems"',

    '"maxItems"',

    '"minimum"',

    '"maximum"'
]


for term in FORBIDDEN_SCHEMA_TERMS:

    assert term not in schema_text, (
        f"Unsupported schema constraint detected: {term}"
    )


print(
    "Claude structured-output schema: CLEAN"
)


# ============================================================
# 3. LOCAL SCIENTIFIC VALIDATION
# ============================================================

def validate_agent_output(
    obj,
    agent
):

    # --------------------------------------------------------
    # Identity
    # --------------------------------------------------------

    if obj["agent_id"] != agent["agent_id"]:

        raise ValueError(
            "Agent ID mismatch."
        )


    if obj["family"] != agent["family"]:

        raise ValueError(
            "Scientific family mismatch."
        )


    # --------------------------------------------------------
    # Array lengths
    # --------------------------------------------------------

    if not (
        2
        <= len(obj["mathematical_core"])
        <= 5
    ):

        raise ValueError(
            "mathematical_core must contain 2–5 items."
        )


    if not (
        2
        <= len(obj["required_features"])
        <= 8
    ):

        raise ValueError(
            "required_features must contain 2–8 items."
        )


    if not (
        2
        <= len(obj["validation_tests"])
        <= 5
    ):

        raise ValueError(
            "validation_tests must contain 2–5 items."
        )


    if not (
        1
        <= len(obj["failure_modes"])
        <= 3
    ):

        raise ValueError(
            "failure_modes must contain 1–3 items."
        )


    # --------------------------------------------------------
    # State count
    # --------------------------------------------------------

    if not (
        2
        <= int(obj["state_count"])
        <= 8
    ):

        raise ValueError(
            "state_count must be between 2 and 8."
        )


    # --------------------------------------------------------
    # Quantitative scores
    # --------------------------------------------------------

    for field in [

        "novelty",

        "plausibility",

        "confidence"

    ]:

        value = float(
            obj[field]
        )


        if not (
            0.0
            <= value
            <= 1.0
        ):

            raise ValueError(
                f"{field} must be between 0 and 1."
            )


    # --------------------------------------------------------
    # Feature validation
    # --------------------------------------------------------

    available_features = set(
        empirical_summary["features"]
    )


    requested_features = set(
        obj["required_features"]
    )


    unknown_features = (
        requested_features
        -
        available_features
    )


    if unknown_features:

        raise ValueError(
            "Agent requested unknown features: "
            f"{sorted(unknown_features)}"
        )


    return True


# ============================================================
# 4. AGENT PROMPT
# ============================================================

def build_agent_prompt(
    agent
):

    return f"""
You are Agent {agent['agent_id']} in a 50-agent
cross-science research swarm.

SCIENTIFIC FAMILY:
{agent['family']}

SPECIALTY:
{agent['specialty']}

RESEARCH QUESTION:

Can mathematical ideas from your scientific specialty reveal
latent financial market regimes that conventional approaches
may fail to identify?

The observed financial system is represented by the empirical
features below.

The true market regime is latent.

Your task is to propose ONE scientifically meaningful,
empirically falsifiable latent-state architecture inspired by
your assigned discipline.

Do not merely rename a Hidden Markov Model.

AVAILABLE MARKET FEATURES:

{json.dumps(empirical_summary, default=str)}

RESPONSE REQUIREMENTS:

mathematical_core:
2–5 concise mathematical ideas.

required_features:
2–8 names drawn ONLY from the available features.

validation_tests:
2–5 empirical falsification tests.

failure_modes:
1–3 important failure modes.

state_count:
integer from 2 through 8.

novelty:
number between 0 and 1.

plausibility:
number between 0 and 1.

confidence:
number between 0 and 1.

rationale:
approximately 60–120 words.

IMPORTANT:

Be concise.

Do not write an essay.

Use the structured output schema.

This is exploratory educational research,
not investment advice.
"""


# ============================================================
# 5. CLAUDE CALL
# ============================================================

def call_agent(
    agent,
    max_tokens=None
):

    if max_tokens is None:

        max_tokens = INITIAL_MAX_TOKENS


    response = client.messages.create(

        model=MODEL,

        max_tokens=max_tokens,

        messages=[

            {

                "role": "user",

                "content":
                    build_agent_prompt(agent)
            }

        ],

        output_config={

            "effort":
                EFFORT,

            "format": {

                "type":
                    "json_schema",

                "schema":
                    CLAUDE_AGENT_SCHEMA
            }
        }
    )


    # ========================================================
    # 6. ADAPTIVE TOKEN ESCALATION
    # ========================================================

    if response.stop_reason == "max_tokens":

        if max_tokens < RETRY_MAX_TOKENS:

            print(
                f"       ↳ {agent['agent_id']} "
                f"truncated at {max_tokens} tokens."
            )

            print(
                f"       ↳ Retrying with "
                f"{RETRY_MAX_TOKENS}..."
            )


            return call_agent(

                agent,

                max_tokens=
                    RETRY_MAX_TOKENS
            )


        elif max_tokens < FINAL_MAX_TOKENS:

            print(
                f"       ↳ {agent['agent_id']} "
                f"still truncated."
            )

            print(
                f"       ↳ Final retry with "
                f"{FINAL_MAX_TOKENS}..."
            )


            return call_agent(

                agent,

                max_tokens=
                    FINAL_MAX_TOKENS
            )


        else:

            raise RuntimeError(

                f"{agent['agent_id']} could not complete "
                f"structured output within "
                f"{FINAL_MAX_TOKENS} tokens."
            )


    # ========================================================
    # 7. EXTRACT TEXT BLOCK
    # ========================================================

    text_blocks = [

        block.text

        for block in response.content

        if getattr(
            block,
            "type",
            None
        ) == "text"
    ]


    if not text_blocks:

        raise RuntimeError(

            f"{agent['agent_id']} returned no text block. "
            f"stop_reason={response.stop_reason}"
        )


    raw_json = "".join(
        text_blocks
    )


    # ========================================================
    # 8. PARSE STRUCTURED OUTPUT
    # ========================================================

    try:

        result = json.loads(
            raw_json
        )

    except json.JSONDecodeError as exc:

        raise RuntimeError(

            f"{agent['agent_id']} returned invalid JSON."

        ) from exc


    # ========================================================
    # 9. LOCAL VALIDATION
    # ========================================================

    validate_agent_output(

        result,

        agent
    )


    # ========================================================
    # 10. PROVENANCE
    # ========================================================

    result["_request_id"] = getattr(

        response,

        "_request_id",

        None
    )


    result["_stop_reason"] = (
        response.stop_reason
    )


    result["_token_ceiling_used"] = (
        max_tokens
    )


    return result


# ============================================================
# 11. ONE-AGENT CANARY
# ============================================================

print("\n" + "=" * 72)

print(
    "CLAUDE SONNET 5 — ONE-AGENT CANARY"
)

print("=" * 72)


print(
    f"\nModel      : {MODEL}"
)

print(
    f"Effort     : {EFFORT}"
)

print(
    f"Agent      : {agents[0]['agent_id']}"
)

print(
    f"Family     : {agents[0]['family']}"
)

print(
    f"Specialty  : {agents[0]['specialty']}"
)


print(
    "\nRunning canary...\n"
)


canary = call_agent(
    agents[0]
)


# ============================================================
# 12. CANARY REPORT
# ============================================================

print("=" * 72)

print(
    "CANARY PASSED"
)

print("=" * 72)


print(
    "\nClaude Sonnet 5           : OK"
)

print(
    "Low reasoning effort      : OK"
)

print(
    "Structured JSON           : OK"
)

print(
    "Scientific validation     : OK"
)

print(
    "Feature validation        : OK"
)

print(
    "Adaptive token handling   : OK"
)


print(
    f"\nToken ceiling actually used: "
    f"{canary['_token_ceiling_used']}"
)


print(
    "\nREADY FOR THE FULL 50-AGENT SWARM"
)


display(

    pd.DataFrame(
        [canary]
    ).T
)

Claude structured-output schema: CLEAN

========================================================================
CLAUDE SONNET 5 — ONE-AGENT CANARY
========================================================================

Model      : claude-sonnet-5
Effort     : low
Agent      : A01
Family     : Statistical Physics
Specialty  : phase transitions and order parameters

Running canary...

========================================================================
CANARY PASSED
========================================================================

Claude Sonnet 5           : OK
Low reasoning effort      : OK
Structured JSON           : OK
Scientific validation     : OK
Feature validation        : OK
Adaptive token handling   : OK

Token ceiling actually used: 2500

READY FOR THE FULL 50-AGENT SWARM

                                                                     0
agent_id                                                           A01
family                                             Statistical Physics
proposed_name                Ising-Landau Market Order-Parameter Model
latent_object        A continuous order parameter (mean market alig...
transfer_principle   Near critical points, order parameters exhibit...
mathematical_core    [Landau free energy F(m)=a(T)m^2+b m^4-h m wit...
required_features    [avg_corr_63d, breadth_63d, spy_vol_21d, vix_l...
transition_detector  Fit rolling double-well potential to order par...
state_count                                                          3
validation_tests     [Test for bimodal vs unimodal distribution of ...
failure_modes        [Order parameter construction may conflate cor...
novelty                                                           0.72
plausibility                                                       0.6
confidence                                                        0.55
rationale            This model reframes regime detection as a phys...
_request_id                               req_011CfM2dqUMUL2x6G7DwUgMY
_stop_reason                                                  end_turn
_token_ceiling_used                                               2500

### CODE UNIT 5 — Launching the 50-agent hypothesis-generation swarm

CODE UNIT 5 launches the complete scientific swarm and converts fifty structured proposals into an analyzable research corpus. Calls are sequential by design. Parallelism could reduce elapsed time, but sequential execution is easier to debug, gentler on rate limits, and more transparent in an educational notebook. Progress is printed after each agent, and every successful response is checkpointed to disk immediately. If Colab disconnects later, the intellectual output already obtained is not lost.

The cell then constructs two views of the swarm. The first is a proposal table containing discipline, model name, latent object, transition detector, proposed state count, novelty, plausibility and confidence. The second is a vocabulary analysis over the mathematical-core fields. This is not intended as sophisticated natural-language processing. It is a transparent first map of which mathematical ideas recur across otherwise independent disciplines.

A useful swarm should show both convergence and disagreement. Convergence across unrelated fields can be evidence that a mathematical structure is broadly appropriate to the inverse problem. Disagreement is equally valuable because it reveals dimensions that a single model may omit. For example, several families may agree that persistence is important while disagreeing about whether transitions should be represented as probabilistic switching, topological rupture, spectral change or energy-barrier crossing.

The output is saved as JSON and CSV. No agent is silently discarded because its proposal seems unusual. The next synthesis stage receives the complete corpus and is asked to construct an architecture that preserves complementary ideas while avoiding redundant complexity.

In [ ]:
import time

# ============================================================
# CODE CELL 5
# EXECUTE THE FULL 50-AGENT SWARM
# CHECKPOINT + RESUME + FAILURE PROTECTION
# ============================================================

checkpoint = (
    OUT /
    "agent_proposals.json"
)


# ============================================================
# 1. LOAD EXISTING CHECKPOINT
# ============================================================

if checkpoint.exists():

    try:

        proposals = json.loads(

            checkpoint.read_text(
                encoding="utf-8"
            )
        )


        # Remove accidental duplicates by agent ID

        proposal_map = {

            p["agent_id"]: p

            for p in proposals

            if "agent_id" in p
        }


        proposals = [

            proposal_map[
                agent["agent_id"]
            ]

            for agent in agents

            if agent["agent_id"]
            in proposal_map
        ]


        print(
            f"Checkpoint recovered: "
            f"{len(proposals)}/50 agents."
        )


    except Exception as exc:

        print(
            "Checkpoint could not be read."
        )

        print(
            "Reason:",
            exc
        )

        print(
            "Starting from the validated canary."
        )


        proposals = [
            canary
        ]


else:

    print(
        "No previous checkpoint found."
    )

    print(
        "Starting from the validated canary."
    )


    proposals = [
        canary
    ]


# ============================================================
# 2. ENSURE CANARY EXISTS
# ============================================================

proposal_map = {

    p["agent_id"]: p

    for p in proposals
}


if canary["agent_id"] not in proposal_map:

    proposals.insert(
        0,
        canary
    )


# ============================================================
# 3. COMPLETED AGENT SET
# ============================================================

completed_ids = {

    p["agent_id"]

    for p in proposals
}


print("\n" + "=" * 72)

print(
    "FULL 50-AGENT SWARM EXECUTION"
)

print("=" * 72)


print(
    f"\nAlready completed : "
    f"{len(completed_ids)}"
)

print(
    f"Remaining         : "
    f"{50 - len(completed_ids)}"
)

print(
    f"Model             : {MODEL}"
)

print(
    f"Reasoning effort  : {EFFORT}"
)


print("\n" + "-" * 72)


# ============================================================
# 4. RUN ONLY MISSING AGENTS
# ============================================================

failed_agents = []


for j, agent in enumerate(
    agents,
    start=1
):

    agent_id = (
        agent["agent_id"]
    )


    # --------------------------------------------------------
    # Already completed
    # --------------------------------------------------------

    if agent_id in completed_ids:

        print(

            f"[{j:02d}/50] "
            f"{agent_id} "
            f"already completed — skipping."
        )

        continue


    # --------------------------------------------------------
    # New agent
    # --------------------------------------------------------

    print(
        f"\n[{j:02d}/50] "
        f"{agent_id} | "
        f"{agent['family']} | "
        f"{agent['specialty']}"
    )


    try:

        obj = call_agent(
            agent
        )


        proposals.append(
            obj
        )


        completed_ids.add(
            agent_id
        )


        # ----------------------------------------------------
        # SAVE IMMEDIATELY
        # ----------------------------------------------------

        checkpoint.write_text(

            json.dumps(
                proposals,
                indent=2,
                default=str
            ),

            encoding="utf-8"
        )


        print(
            f"       ✓ completed"
        )

        print(
            f"       ✓ checkpoint: "
            f"{len(proposals)}/50"
        )

        print(
            f"       ✓ token ceiling used: "
            f"{obj.get('_token_ceiling_used')}"
        )


    except Exception as exc:

        # ----------------------------------------------------
        # DO NOT DESTROY THE SWARM RUN
        # ----------------------------------------------------

        failed_agents.append({

            "agent_id":
                agent_id,

            "family":
                agent["family"],

            "specialty":
                agent["specialty"],

            "error_type":
                type(exc).__name__,

            "error":
                str(exc)
        })


        print(
            f"       ✗ FAILED: "
            f"{type(exc).__name__}"
        )

        print(
            f"       {exc}"
        )

        print(
            "       Continuing with the remaining agents..."
        )


    # Small pacing interval

    time.sleep(
        0.15
    )


# ============================================================
# 5. SAVE FINAL CHECKPOINT
# ============================================================

checkpoint.write_text(

    json.dumps(
        proposals,
        indent=2,
        default=str
    ),

    encoding="utf-8"
)


# ============================================================
# 6. FAILURE REPORT
# ============================================================

failure_path = (
    OUT /
    "failed_agents.json"
)


failure_path.write_text(

    json.dumps(
        failed_agents,
        indent=2,
        default=str
    ),

    encoding="utf-8"
)


# ============================================================
# 7. EXECUTION STATUS
# ============================================================

completed_ids = {

    p["agent_id"]

    for p in proposals
}


missing_agents = [

    agent

    for agent in agents

    if agent["agent_id"]
    not in completed_ids
]


print("\n" + "=" * 72)

print(
    "SWARM EXECUTION STATUS"
)

print("=" * 72)


print(
    f"\nCompleted : "
    f"{len(completed_ids)}/50"
)

print(
    f"Failed    : "
    f"{len(failed_agents)}"
)

print(
    f"Missing   : "
    f"{len(missing_agents)}"
)


if missing_agents:

    print(
        "\nAgents requiring another pass:"
    )

    for agent in missing_agents:

        print(
            f"  {agent['agent_id']} | "
            f"{agent['family']} | "
            f"{agent['specialty']}"
        )


else:

    print(
        "\n✓ ALL 50 AGENTS COMPLETED SUCCESSFULLY"
    )


# ============================================================
# 8. REQUIRE FULL SWARM BEFORE ANALYSIS
# ============================================================

if len(completed_ids) != 50:

    raise RuntimeError(

        f"The swarm currently contains "
        f"{len(completed_ids)}/50 agents. "
        f"Rerun Cell 5 to retry only the missing agents."
    )


# ============================================================
# 9. ORDER PROPOSALS A01 → A50
# ============================================================

proposal_map = {

    p["agent_id"]: p

    for p in proposals
}


proposals = [

    proposal_map[
        agent["agent_id"]
    ]

    for agent in agents
]


# ============================================================
# 10. FINAL CHECKPOINT
# ============================================================

checkpoint.write_text(

    json.dumps(
        proposals,
        indent=2,
        default=str
    ),

    encoding="utf-8"
)


# ============================================================
# 11. PROPOSAL SUMMARY
# ============================================================

proposal_df = pd.DataFrame([

    {

        "agent_id":
            p["agent_id"],

        "family":
            p["family"],

        "name":
            p["proposed_name"],

        "latent_object":
            p["latent_object"],

        "transition_detector":
            p["transition_detector"],

        "state_count":
            p["state_count"],

        "novelty":
            p["novelty"],

        "plausibility":
            p["plausibility"],

        "confidence":
            p["confidence"],

        "token_ceiling_used":
            p.get(
                "_token_ceiling_used",
                np.nan
            )
    }

    for p in proposals
])


proposal_df.to_csv(

    OUT /
    "proposal_summary.csv",

    index=False
)


# ============================================================
# 12. MATHEMATICAL VOCABULARY
# ============================================================

tokens = Counter()


for p in proposals:

    for phrase in p[
        "mathematical_core"
    ]:

        for tok in re.findall(

            r"[A-Za-z][A-Za-z\-]+",

            phrase.lower()
        ):

            if len(tok) > 4:

                tokens[tok] += 1


vocabulary_df = pd.DataFrame(

    tokens.most_common(
        30
    ),

    columns=[
        "term",
        "count"
    ]
)


print("\n" + "=" * 72)

print(
    "TOP RECURRING MATHEMATICAL VOCABULARY"
)

print("=" * 72)


display(
    vocabulary_df
)


# ============================================================
# 13. SCIENTIFIC FAMILY SUMMARY
# ============================================================

family_summary = (

    proposal_df

    .groupby(
        "family"
    )[
        [
            "novelty",
            "plausibility",
            "confidence",
            "state_count"
        ]
    ]

    .mean()

    .round(3)
)


print("\n" + "=" * 72)

print(
    "AVERAGE RESULTS BY SCIENTIFIC FAMILY"
)

print("=" * 72)


display(
    family_summary
)


# ============================================================
# 14. TOKEN-CEILING DIAGNOSTIC
# ============================================================

token_diagnostic = (

    proposal_df[
        "token_ceiling_used"
    ]

    .value_counts(
        dropna=False
    )

    .sort_index()

    .rename_axis(
        "token_ceiling"
    )

    .reset_index(
        name="agents"
    )
)


print("\n" + "=" * 72)

print(
    "TOKEN-CEILING UTILIZATION"
)

print("=" * 72)


display(
    token_diagnostic
)


print("\n" + "=" * 72)

print(
    "CELL 5 COMPLETE — 50 SCIENTIFIC PROPOSALS AVAILABLE"
)

print("=" * 72)

Checkpoint recovered: 36/50 agents.

========================================================================
FULL 50-AGENT SWARM EXECUTION
========================================================================

Already completed : 36
Remaining         : 14
Model             : claude-sonnet-5
Reasoning effort  : low

------------------------------------------------------------------------
[01/50] A01 already completed — skipping.
[02/50] A02 already completed — skipping.
[03/50] A03 already completed — skipping.
[04/50] A04 already completed — skipping.
[05/50] A05 already completed — skipping.
[06/50] A06 already completed — skipping.
[07/50] A07 already completed — skipping.
[08/50] A08 already completed — skipping.
[09/50] A09 already completed — skipping.
[10/50] A10 already completed — skipping.
[11/50] A11 already completed — skipping.
[12/50] A12 already completed — skipping.
[13/50] A13 already completed — skipping.
[14/50] A14 already completed — skipping.
[15/50] A15 already completed — skipping.
[16/50] A16 already completed — skipping.
[17/50] A17 already completed — skipping.
[18/50] A18 already completed — skipping.
[19/50] A19 already completed — skipping.
[20/50] A20 already completed — skipping.
[21/50] A21 already completed — skipping.
[22/50] A22 already completed — skipping.
[23/50] A23 already completed — skipping.
[24/50] A24 already completed — skipping.
[25/50] A25 already completed — skipping.
[26/50] A26 already completed — skipping.
[27/50] A27 already completed — skipping.
[28/50] A28 already completed — skipping.
[29/50] A29 already completed — skipping.
[30/50] A30 already completed — skipping.
[31/50] A31 already completed — skipping.
[32/50] A32 already completed — skipping.
[33/50] A33 already completed — skipping.
[34/50] A34 already completed — skipping.
[35/50] A35 already completed — skipping.
[36/50] A36 already completed — skipping.

[37/50] A37 | Astrophysics | Bayesian blocks/change points
       ✓ completed
       ✓ checkpoint: 37/50
       ✓ token ceiling used: 2500

[38/50] A38 | Astrophysics | mixture populations
       ✓ completed
       ✓ checkpoint: 38/50
       ✓ token ceiling used: 2500

[39/50] A39 | Astrophysics | multiscale time-series inference
       ✓ completed
       ✓ checkpoint: 39/50
       ✓ token ceiling used: 2500

[40/50] A40 | Astrophysics | latent-source identification
       ✓ completed
       ✓ checkpoint: 40/50
       ✓ token ceiling used: 2500

[41/50] A41 | Network Science | correlation topology
       ✓ completed
       ✓ checkpoint: 41/50
       ✓ token ceiling used: 2500

[42/50] A42 | Network Science | community structure
       ✓ completed
       ✓ checkpoint: 42/50
       ✓ token ceiling used: 2500

[43/50] A43 | Network Science | network percolation
       ✓ completed
       ✓ checkpoint: 43/50
       ✓ token ceiling used: 2500

[44/50] A44 | Network Science | graph spectral methods
       ✓ completed
       ✓ checkpoint: 44/50
       ✓ token ceiling used: 2500

[45/50] A45 | Network Science | dynamic networks
       ✓ completed
       ✓ checkpoint: 45/50
       ✓ token ceiling used: 2500

[46/50] A46 | Geophysics & Seismology | precursor detection
       ✓ completed
       ✓ checkpoint: 46/50
       ✓ token ceiling used: 2500

[47/50] A47 | Geophysics & Seismology | critical slowing and rupture
       ✓ completed
       ✓ checkpoint: 47/50
       ✓ token ceiling used: 2500

[48/50] A48 | Geophysics & Seismology | event clustering
       ✓ completed
       ✓ checkpoint: 48/50
       ✓ token ceiling used: 2500

[49/50] A49 | Geophysics & Seismology | multiscale stress accumulation
       ✓ completed
       ✓ checkpoint: 49/50
       ✓ token ceiling used: 2500

[50/50] A50 | Geophysics & Seismology | regime shifts in complex geosystems
       ✓ completed
       ✓ checkpoint: 50/50
       ✓ token ceiling used: 2500

========================================================================
SWARM EXECUTION STATUS
========================================================================

Completed : 50/50
Failed    : 0
Missing   : 0

✓ ALL 50 AGENTS COMPLETED SUCCESSFULLY

========================================================================
TOP RECURRING MATHEMATICAL VOCABULARY
========================================================================

               term  count
0            regime     43
1           between     22
2          critical     20
3        transition     20
4             model     19
5           rolling     18
6       correlation     17
7        dispersion     17
8          variance     16
9             state     16
10            local     15
11        parameter     13
12          feature     13
13            order     12
14  autocorrelation     12
15           matrix     11
16          regimes     11
17            ratio     10
18            asset     10
19          entropy     10
20           detect     10
21      persistence     10
22           across     10
23           energy      9
24          slowing      9
25        diffusion      9
26        stability      9
27        estimated      9
28           change      9
29            cross      9

========================================================================
AVERAGE RESULTS BY SCIENTIFIC FAMILY
========================================================================

,novelty,plausibility,confidence,state_count
family,,,,
Applied Mathematics,0.752,0.622,0.570,4.4
Astrophysics,0.692,0.586,0.530,4.2
Chemistry & Statistical Mechanics,0.738,0.622,0.566,4.0
Control Theory,0.692,0.646,0.580,4.0
Dynamical Systems,0.730,0.584,0.530,3.8
Geophysics & Seismology,0.720,0.594,0.540,4.0
Information Theory,0.668,0.666,0.590,4.4
Network Science,0.646,0.612,0.550,4.0
Signal Engineering,0.680,0.666,0.600,4.2
Statistical Physics,0.652,0.628,0.570,3.4

========================================================================
TOKEN-CEILING UTILIZATION
========================================================================

   token_ceiling  agents
0         2500.0      14
1            NaN      36

========================================================================
CELL 5 COMPLETE — 50 SCIENTIFIC PROPOSALS AVAILABLE
========================================================================

### CODE UNIT 6 — Cross-disciplinary synthesis into one research architecture

CODE UNIT 6 asks a separate synthesis call to act as a scientific architect rather than as a fifty-first domain specialist. Its input is the complete proposal corpus, compressed enough to fit comfortably in context. The synthesis contract requires the model to identify cross-disciplinary motifs, preserve meaningful dissent, and specify a concrete hybrid architecture with four layers: representation, state inference, transition detection and uncertainty/validation.

This stage is intentionally not a vote. Majority rule would reward familiar ideas and could erase the rare transfer that makes the exercise worthwhile. Instead, the synthesizer must explain why selected components are complementary and which ideas remain competing hypotheses. It must also produce an executable blueprint using only a controlled menu of empirical components available in the notebook: robust scaling, PCA, Gaussian mixtures, K-means, spectral clustering, rolling transition intensity and consensus voting. This constraint prevents the language model from inventing a library or algorithm that the subsequent code cannot reproduce.

The scientific architecture is therefore a negotiated boundary between open-ended theory generation and reproducible implementation. The swarm can propose topological data analysis, free-energy landscapes or Bayesian change points, but the first empirical prototype translates recurring concepts into transparent approximations. Later research can implement the more specialized methods one by one and test whether they improve out-of-sample behavior.

The output also specifies a target state count. That number is treated as a hypothesis rather than an unquestionable truth; the next unit compares nearby values using separation and persistence diagnostics. The synthesis is stored with request provenance so that later revisions can be compared.

In [ ]:
# ============================================================
# CODE CELL 6
# SWARM SYNTHESIS — FROM 50 PROPOSALS TO ONE ARCHITECTURE
# CLAUDE SONNET 5 / LOW EFFORT / STRUCTURED OUTPUT
# ============================================================

import json
import pandas as pd


# ============================================================
# 1. PRECONDITIONS
# ============================================================

if "proposals" not in globals():
    raise RuntimeError(
        "The variable 'proposals' does not exist. "
        "Run Cell 5 first."
    )

if len(proposals) != 50:
    raise RuntimeError(
        f"Cell 6 requires the complete 50-agent swarm. "
        f"Currently available: {len(proposals)}/50."
    )

print("=" * 72)
print("CELL 6 — SWARM SYNTHESIS")
print("=" * 72)

print(f"\nProposals available : {len(proposals)}")
print(f"Model               : {MODEL}")
print(f"Effort              : {EFFORT}")


# ============================================================
# 2. CLAUDE-COMPATIBLE SYNTHESIS SCHEMA
# ============================================================
#
# IMPORTANT:
#
# Do NOT place unsupported constraints such as:
#
#     minItems: 3
#     maxItems: 8
#     minimum: 2
#     maximum: 8
#
# inside the raw Anthropic schema.
#
# Those constraints are enforced locally after generation.
# ============================================================

SYNTH_SCHEMA = {

    "type": "object",

    "properties": {

        "architecture_name": {
            "type": "string"
        },

        "core_motifs": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "minority_ideas_to_preserve": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "representation_layer": {
            "type": "string"
        },

        "state_inference_layer": {
            "type": "string"
        },

        "transition_layer": {
            "type": "string"
        },

        "uncertainty_layer": {
            "type": "string"
        },

        "target_states": {
            "type": "integer"
        },

        "empirical_components": {

            "type": "array",

            "items": {

                "type": "string",

                "enum": [
                    "PCA",
                    "GaussianMixture",
                    "KMeans",
                    "SpectralClustering",
                    "TransitionIntensity",
                    "ConsensusVoting"
                ]
            }
        },

        "falsification_criteria": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "research_rationale": {
            "type": "string"
        }
    },

    "required": [

        "architecture_name",

        "core_motifs",

        "minority_ideas_to_preserve",

        "representation_layer",

        "state_inference_layer",

        "transition_layer",

        "uncertainty_layer",

        "target_states",

        "empirical_components",

        "falsification_criteria",

        "research_rationale"
    ],

    "additionalProperties": False
}


# ============================================================
# 3. SCHEMA PREFLIGHT
# ============================================================

schema_text = json.dumps(
    SYNTH_SCHEMA
)

FORBIDDEN_SCHEMA_TERMS = [
    '"minItems"',
    '"maxItems"',
    '"minimum"',
    '"maximum"'
]

for term in FORBIDDEN_SCHEMA_TERMS:

    if term in schema_text:

        raise RuntimeError(
            f"Unsupported schema term detected: {term}"
        )

print("\nStructured-output schema: CLEAN")


# ============================================================
# 4. COMPACT THE 50 AGENT PROPOSALS
# ============================================================
#
# Cell 6 does not need provenance fields or long metadata.
# We retain only the scientific content required for synthesis.
# ============================================================

KEEP_FIELDS = [

    "agent_id",

    "family",

    "proposed_name",

    "latent_object",

    "transfer_principle",

    "mathematical_core",

    "transition_detector",

    "state_count",

    "validation_tests",

    "failure_modes",

    "novelty",

    "plausibility",

    "confidence"
]


compact = []


for p in proposals:

    compact.append({

        field: p[field]

        for field in KEEP_FIELDS

        if field in p
    })


assert len(compact) == 50


# ============================================================
# 5. SCIENTIFIC FAMILY SUMMARY
# ============================================================
#
# This gives Claude a second view of the swarm:
# individual proposals + aggregate disciplinary structure.
# ============================================================

family_summary_for_prompt = (

    proposal_df

    .groupby("family")[

        [
            "novelty",
            "plausibility",
            "confidence",
            "state_count"
        ]
    ]

    .mean()

    .round(3)

    .reset_index()

    .to_dict(
        orient="records"
    )
)


# ============================================================
# 6. LOCAL VALIDATOR
# ============================================================

ALLOWED_COMPONENTS = {

    "PCA",

    "GaussianMixture",

    "KMeans",

    "SpectralClustering",

    "TransitionIntensity",

    "ConsensusVoting"
}


def validate_synthesis(obj):

    # --------------------------------------------------------
    # Core motifs
    # --------------------------------------------------------

    if not (
        3 <= len(obj["core_motifs"]) <= 8
    ):

        raise ValueError(
            "core_motifs must contain 3–8 items."
        )


    # --------------------------------------------------------
    # Minority ideas
    # --------------------------------------------------------

    if not (
        2
        <= len(obj["minority_ideas_to_preserve"])
        <= 6
    ):

        raise ValueError(
            "minority_ideas_to_preserve "
            "must contain 2–6 items."
        )


    # --------------------------------------------------------
    # Number of latent states
    # --------------------------------------------------------

    K_candidate = int(
        obj["target_states"]
    )


    if not (
        2 <= K_candidate <= 8
    ):

        raise ValueError(
            "target_states must be between 2 and 8."
        )


    # --------------------------------------------------------
    # Empirical components
    # --------------------------------------------------------

    components = (
        obj["empirical_components"]
    )


    if not (
        3 <= len(components) <= 6
    ):

        raise ValueError(
            "empirical_components "
            "must contain 3–6 items."
        )


    unknown = (
        set(components)
        -
        ALLOWED_COMPONENTS
    )


    if unknown:

        raise ValueError(
            "Unsupported empirical components: "
            f"{sorted(unknown)}"
        )


    # --------------------------------------------------------
    # Falsification criteria
    # --------------------------------------------------------

    if not (
        3
        <= len(obj["falsification_criteria"])
        <= 7
    ):

        raise ValueError(
            "falsification_criteria "
            "must contain 3–7 items."
        )


    # --------------------------------------------------------
    # Required textual layers
    # --------------------------------------------------------

    text_fields = [

        "architecture_name",

        "representation_layer",

        "state_inference_layer",

        "transition_layer",

        "uncertainty_layer",

        "research_rationale"
    ]


    for field in text_fields:

        if not str(
            obj[field]
        ).strip():

            raise ValueError(
                f"{field} cannot be empty."
            )


    return True


# ============================================================
# 7. SYNTHESIS PROMPT
# ============================================================

system_prompt = """
You are the scientific architect of a 50-agent
cross-science research swarm.

Fifty independent scientific agents have proposed ways of
understanding latent financial market regimes using ideas
transferred from statistical physics, dynamical systems,
signal engineering, control theory, information theory,
applied mathematics, chemistry, astrophysics, network
science, and geophysics.

Your task is SYNTHESIS, not voting.

Look for mathematical structures that recur independently
across disciplines.

Preserve valuable minority ideas when they add something
different from the dominant consensus.

Prefer a parsimonious architecture.

The final architecture must be:

1. mathematically interpretable;
2. empirically implementable;
3. falsifiable;
4. auditable;
5. robust enough to compare competing latent-state methods.

Do not invent empirical algorithms outside the explicitly
allowed list.

Keep the response concise.

Extended deliberation is unnecessary. Respond directly once
you have identified the major cross-disciplinary structure.

This is educational quantitative research and not
investment advice.
"""


user_prompt = f"""
SYNTHESIZE THE 50-AGENT SWARM.

The objective is to construct ONE empirical architecture for
discovering latent market regimes.

------------------------------------------------------------
AGGREGATE DISCIPLINARY SUMMARY
------------------------------------------------------------

{json.dumps(
    family_summary_for_prompt,
    ensure_ascii=False
)}

------------------------------------------------------------
50 SCIENTIFIC PROPOSALS
------------------------------------------------------------

{json.dumps(
    compact,
    ensure_ascii=False,
    separators=(",", ":")
)}

------------------------------------------------------------
DESIGN REQUIREMENTS
------------------------------------------------------------

CORE MOTIFS

Identify 3–8 mathematical motifs that recur across otherwise
different scientific disciplines.

MINORITY IDEAS

Preserve 2–6 scientifically interesting ideas that may not
dominate the swarm but add genuinely distinct information.

REPRESENTATION LAYER

Explain how the high-dimensional observable market system
should be represented before latent-state inference.

STATE-INFERENCE LAYER

Explain how hidden market states should be inferred.

TRANSITION LAYER

Explain how movement between latent states should be
identified independently of simply changing cluster labels.

UNCERTAINTY LAYER

Explain how disagreement across different clustering
architectures should be interpreted.

TARGET STATES

Choose an initial number of latent regimes between 2 and 8.

The number is an empirical starting hypothesis, not an
ontological claim about the true number of market regimes.

EMPIRICAL COMPONENTS

Select 3–6 components ONLY from:

PCA
GaussianMixture
KMeans
SpectralClustering
TransitionIntensity
ConsensusVoting

FALSIFICATION

Provide 3–7 empirical conditions under which the proposed
architecture should be rejected or substantially revised.

RESEARCH RATIONALE

Explain the synthesis in approximately 100–180 words.

Return only the required structured output.
"""


# ============================================================
# 8. SYNTHESIS API CALL WITH CONTROLLED RETRIES
# ============================================================

SYNTH_INITIAL_TOKENS = 3000

SYNTH_RETRY_TOKENS = 5000

SYNTH_FINAL_TOKENS = 8000


def call_synthesis(
    max_tokens=SYNTH_INITIAL_TOKENS
):

    print(
        f"\nCalling synthesis architect "
        f"(max_tokens={max_tokens}, effort={EFFORT})..."
    )


    response = client.messages.create(

        model=MODEL,

        max_tokens=max_tokens,

        system=system_prompt,

        messages=[

            {
                "role": "user",
                "content": user_prompt
            }

        ],

        output_config={

            "effort":
                EFFORT,

            "format": {

                "type":
                    "json_schema",

                "schema":
                    SYNTH_SCHEMA
            }
        }
    )


    # --------------------------------------------------------
    # Truncation handling
    # --------------------------------------------------------

    if response.stop_reason == "max_tokens":

        if max_tokens < SYNTH_RETRY_TOKENS:

            print(
                "Synthesis truncated. "
                "Retrying with 5000 tokens..."
            )

            return call_synthesis(
                SYNTH_RETRY_TOKENS
            )


        elif max_tokens < SYNTH_FINAL_TOKENS:

            print(
                "Synthesis still truncated. "
                "Final retry with 8000 tokens..."
            )

            return call_synthesis(
                SYNTH_FINAL_TOKENS
            )


        raise RuntimeError(
            "Synthesis could not complete within "
            f"{SYNTH_FINAL_TOKENS} tokens."
        )


    # --------------------------------------------------------
    # Refusal / abnormal termination
    # --------------------------------------------------------

    if response.stop_reason == "refusal":

        raise RuntimeError(
            "Claude returned a refusal for the synthesis."
        )


    # --------------------------------------------------------
    # Extract TEXT blocks by type
    # --------------------------------------------------------

    text_blocks = [

        block.text

        for block in response.content

        if getattr(
            block,
            "type",
            None
        ) == "text"
    ]


    if not text_blocks:

        raise RuntimeError(
            "Synthesis returned no text block. "
            f"stop_reason={response.stop_reason}"
        )


    raw_text = "".join(
        text_blocks
    )


    # --------------------------------------------------------
    # Parse structured JSON
    # --------------------------------------------------------

    try:

        obj = json.loads(
            raw_text
        )

    except json.JSONDecodeError as exc:

        print(
            "\nRAW RESPONSE PREVIEW:\n"
        )

        print(
            raw_text[:2000]
        )

        raise RuntimeError(
            "Synthesis response was not valid JSON."
        ) from exc


    # --------------------------------------------------------
    # Local scientific validation
    # --------------------------------------------------------

    validate_synthesis(
        obj
    )


    # --------------------------------------------------------
    # Provenance
    # --------------------------------------------------------

    obj["_request_id"] = getattr(
        response,
        "_request_id",
        None
    )


    obj["_stop_reason"] = (
        response.stop_reason
    )


    obj["_token_ceiling_used"] = (
        max_tokens
    )


    return obj


# ============================================================
# 9. RUN THE SYNTHESIS
# ============================================================

synthesis = call_synthesis()


# ============================================================
# 10. SAVE SYNTHESIS
# ============================================================

synthesis_path = (
    OUT /
    "swarm_synthesis.json"
)


synthesis_path.write_text(

    json.dumps(
        synthesis,
        indent=2,
        ensure_ascii=False
    ),

    encoding="utf-8"
)


# ============================================================
# 11. SYNTHESIS REPORT
# ============================================================

print("\n" + "=" * 72)

print(
    "SWARM SYNTHESIS COMPLETE"
)

print("=" * 72)


print(
    f"\nArchitecture : "
    f"{synthesis['architecture_name']}"
)

print(
    f"Target states: "
    f"{synthesis['target_states']}"
)

print(
    f"Token ceiling used: "
    f"{synthesis['_token_ceiling_used']}"
)


print(
    "\nEMPIRICAL COMPONENTS"
)

for component in synthesis[
    "empirical_components"
]:

    print(
        f"  • {component}"
    )


print(
    "\nCORE CROSS-SCIENCE MOTIFS"
)

for motif in synthesis[
    "core_motifs"
]:

    print(
        f"  • {motif}"
    )


print(
    "\nMINORITY IDEAS PRESERVED"
)

for idea in synthesis[
    "minority_ideas_to_preserve"
]:

    print(
        f"  • {idea}"
    )


print(
    "\nARCHITECTURE"
)

print(
    "\nRepresentation layer:"
)

print(
    synthesis[
        "representation_layer"
    ]
)


print(
    "\nState-inference layer:"
)

print(
    synthesis[
        "state_inference_layer"
    ]
)


print(
    "\nTransition layer:"
)

print(
    synthesis[
        "transition_layer"
    ]
)


print(
    "\nUncertainty layer:"
)

print(
    synthesis[
        "uncertainty_layer"
    ]
)


print(
    "\nFALSIFICATION CRITERIA"
)

for criterion in synthesis[
    "falsification_criteria"
]:

    print(
        f"  • {criterion}"
    )


print(
    "\nRESEARCH RATIONALE"
)

print(
    synthesis[
        "research_rationale"
    ]
)


print(
    "\nSaved to:"
)

print(
    synthesis_path
)


print("\n" + "=" * 72)

print(
    "CELL 6 COMPLETE — READY FOR EMPIRICAL REGIME INFERENCE"
)

print("=" * 72)

========================================================================
CELL 6 — SWARM SYNTHESIS
========================================================================

Proposals available : 50
Model               : claude-sonnet-5
Effort              : low

Structured-output schema: CLEAN

Calling synthesis architect (max_tokens=3000, effort=low)...

========================================================================
SWARM SYNTHESIS COMPLETE
========================================================================

Architecture : Metastable Basin-Transition Architecture (MBTA)
Target states: 4
Token ceiling used: 3000

EMPIRICAL COMPONENTS
  • PCA
  • GaussianMixture
  • KMeans
  • SpectralClustering
  • TransitionIntensity
  • ConsensusVoting

CORE CROSS-SCIENCE MOTIFS
  • Free-energy/potential landscape with metastable basins separated by barriers (Landau, Kramers, reaction-coordinate chemistry, geophysical stress-release)
  • Critical slowing down: rising variance/autocorrelation as universal early-warning precursor across physics, ecology, seismology
  • Spectral/operator decomposition of coupled systems (Koopman, graph Laplacian, correlation eigenstructure) revealing dominant coherent modes
  • Self-exciting/triggered cascades with power-law or Omori-type decay (ETAS, nucleation, aftershocks)
  • Information-theoretic divergence between successive local distributions as a model-free change signal (KL/JS divergence, transfer entropy)
  • Low-dimensional manifold/order-parameter reduction of high-dimensional observables via embedding or factorization

MINORITY IDEAS PRESERVED
  • Directed information/transfer-entropy network reconfiguration as a regime signature distinct from marginal statistics (A21, A24)
  • Topological data analysis (persistent homology) capturing shape/cyclicality beyond covariance (A27)
  • Nucleation-style supercritical growth dynamics distinguishing false starts from propagating regime shifts (A35)
  • Structured singular value / robust-margin framing of fragility as a continuous precursor rather than discrete state (A18)
  • Switched linear dynamical systems with guard-set/geometric transition boundaries rather than free-floating transition probabilities (A17)

ARCHITECTURE

Representation layer:
Construct a standardized multivariate feature vector (volatility, dispersion, correlation, credit, rotation, trend/breadth) over rolling windows, then reduce dimensionality via PCA to extract a small set of orthogonal order-parameter coordinates capturing >80% variance; this low-dimensional embedding serves as the common substrate for all downstream inference, analogous to order-parameter reduction used independently across physics, chemistry, and network-science proposals.

State-inference layer:
Apply parallel unsupervised architectures on the PCA-reduced space: GaussianMixture for probabilistic soft-membership basins (free-energy minima analog), KMeans for hard-partition baseline, and SpectralClustering on a correlation/affinity graph to capture non-convex or network-topology-defined regimes; each yields a candidate regime labeling to be reconciled downstream rather than assumed correct individually.

Transition layer:
Regime change is defined not by label-switching alone but by evidence of dynamical instability: use TransitionIntensity metrics (rate-of-change/persistence of state-occupancy probability, analogous to Kramers escape rate or CUSUM-style intensity) combined with rolling variance/autocorrelation of the order parameter (critical-slowing-down proxy) to confirm that a genuine barrier-crossing/dynamical event underlies the label change, filtering out noise-driven relabeling.

Uncertainty layer:
Disagreement among PCA+GMM, KMeans, and SpectralClustering partitions is treated as an empirical uncertainty signal rather than noise to be averaged away: apply ConsensusVoting across architectures per time step; low-consensus periods are flagged as ambiguous/transitional zones (analogous to transition-state or committor regions in reaction-coordinate theory), while high-consensus periods define confidently-labeled regimes.

FALSIFICATION CRITERIA
  • Consensus across clustering architectures is no better than chance-level agreement (adjusted Rand index near zero) on out-of-sample data
  • TransitionIntensity-flagged transitions show no lead-time relationship (via cross-correlation/event study) to realized volatility or drawdown spikes
  • Critical-slowing-down proxies (rolling variance/autocorrelation) fail to rise before historically labeled regime shifts (2015, 2018, 2020, 2022) more than chance
  • Regime count selected by PCA+GMM information criteria is unstable across bootstrap resamples or rolling windows, undermining the 4-state hypothesis
  • Consensus-low ('ambiguous') periods do not correspond to elevated forward realized volatility or classification instability, contradicting the transition-state interpretation
  • Simple mean/variance threshold models achieve equal or better predictive/discriminative power than the full architecture, indicating unnecessary complexity
  • Regime labels fail to generalize out-of-sample, showing large drift in cluster centroids/covariances when refit on later data

RESEARCH RATIONALE
Across 50 disciplinary transfers, three structures recur robustly: (1) metastable multi-well landscapes with barrier-crossing dynamics, (2) critical-slowing-down precursors preceding transitions, and (3) spectral/topological reduction of high-dimensional coupling. Rather than adopt any single exotic physical analogy (Ising, Kramers, percolation, seismic ETAS), MBTA extracts their shared mathematical skeleton using only sanctioned empirical primitives: PCA for order-parameter reduction, multiple clustering algorithms as competing basin-estimators, TransitionIntensity as a dynamics-aware transition detector distinct from relabeling, and ConsensusVoting to operationalize cross-method disagreement as a genuine uncertainty signal rather than an artifact. This preserves interpretability and falsifiability while remaining parsimonious, and explicitly retains minority contributions (topology, information flow, nucleation, robustness margins) as auxiliary diagnostics rather than core machinery, avoiding overfitting to any single discipline's metaphor of financial regime change.

Saved to:
/content/regime_swarm_outputs/swarm_synthesis.json

========================================================================
CELL 6 COMPLETE — READY FOR EMPIRICAL REGIME INFERENCE
========================================================================

### CODE UNIT 7 — Executable ensemble for latent-state inference

CODE UNIT 7 converts the swarm’s conceptual synthesis into a controlled ensemble of empirical regime views. The purpose is not to pretend that PCA, Gaussian mixtures, K-means and spectral clustering literally implement every sophisticated proposal. They serve as transparent representatives of several recurring scientific ideas: low-dimensional order parameters, probabilistic metastable states, geometric basins and graph-like neighborhood structure.

PCA extracts dominant collective coordinates from the market feature system. In physics language these can be interpreted as candidate order parameters; in signal processing they are dominant modes; in control language they are a reduced state representation. The first components are then passed to multiple unsupervised estimators. Gaussian mixtures provide soft probabilistic membership, K-means supplies a geometric partition, and spectral clustering offers a nonlinear neighborhood view. The target number of states is taken from the swarm synthesis but is checked against nearby alternatives.

Because cluster labels are arbitrary, the code aligns model labels to a Gaussian-mixture reference using the Hungarian assignment algorithm. Consensus is then the modal aligned label, while disagreement is the fraction of models that do not support that label. This gives a simple but important uncertainty measure: the system can say not only which state is most supported but how much the scientific views disagree.

The state count is not chosen by a single score. For each candidate K, the code records silhouette separation and average state persistence. Extremely fragmented partitions may separate points geometrically yet fail the economic meaning of a regime. The selected K therefore remains inspectable, and the diagnostics are exported for later challenge.

In [ ]:
# ============================================================
# CODE CELL 7
# EMPIRICAL LATENT-STATE INFERENCE
# PCA + GMM + KMEANS + SPECTRAL + CONSENSUS
# ============================================================

# ------------------------------------------------------------
# IMPORTANT
# ------------------------------------------------------------
#
# Cell 1 deliberately did NOT upgrade or reinstall NumPy,
# SciPy or scikit-learn.
#
# We import the scientific tools here, where they are needed,
# using the versions already provided by the Colab runtime.
# ------------------------------------------------------------

from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.cluster import KMeans, SpectralClustering
from sklearn.metrics import silhouette_score
from scipy.optimize import linear_sum_assignment

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 1. PRECONDITIONS
# ============================================================

if "X" not in globals():

    raise RuntimeError(
        "Standardized feature matrix X is missing. "
        "Run Cell 2 first."
    )


if "synthesis" not in globals():

    raise RuntimeError(
        "Swarm synthesis is missing. "
        "Run Cell 6 first."
    )


if len(X) < 250:

    raise RuntimeError(
        "Too few observations for reliable "
        "latent-state inference."
    )


print("=" * 72)

print(
    "CELL 7 — EMPIRICAL LATENT-STATE INFERENCE"
)

print("=" * 72)


print(
    f"\nObservations        : {len(X):,}"
)

print(
    f"Observed features   : {X.shape[1]}"
)

print(
    f"Architecture        : "
    f"{synthesis['architecture_name']}"
)


# ============================================================
# 2. TARGET NUMBER OF REGIMES
# ============================================================
#
# Cell 6 provides the swarm's initial hypothesis for K.
#
# We do NOT treat K as an unquestionable truth.
# We test nearby alternatives below.
# ============================================================

K = int(
    synthesis["target_states"]
)


if not (
    2 <= K <= 8
):

    raise ValueError(
        f"Invalid target state count from Cell 6: {K}"
    )


print(
    f"Target regimes (K) : {K}"
)


# ============================================================
# 3. PCA REPRESENTATION LAYER
# ============================================================
#
# The observable market system may contain correlated and
# redundant features.
#
# PCA provides a lower-dimensional representation before
# competing state-inference algorithms are applied.
# ============================================================

MAX_PCS = min(
    6,
    X.shape[1],
    len(X)
)


pca_full = PCA(
    n_components=MAX_PCS
)


Z_full = pca_full.fit_transform(
    X.values
)


pc_columns = [

    f"PC{i+1}"

    for i in range(
        MAX_PCS
    )
]


Zdf = pd.DataFrame(

    Z_full,

    index=X.index,

    columns=pc_columns
)


# ------------------------------------------------------------
# Clustering representation
# ------------------------------------------------------------

N_CLUSTER_PCS = min(
    4,
    MAX_PCS
)


Z = Zdf.iloc[
    :,
    :N_CLUSTER_PCS
].values


explained = (
    pca_full
    .explained_variance_ratio_
)


cumulative_explained = (
    np.cumsum(
        explained
    )
)


print(
    f"\nPCA dimensions used for clustering: "
    f"{N_CLUSTER_PCS}"
)

print(
    f"Cumulative variance explained: "
    f"{cumulative_explained[N_CLUSTER_PCS - 1]:.3f}"
)


# ============================================================
# 4. PCA DIAGNOSTIC TABLE
# ============================================================

pca_diagnostic = pd.DataFrame({

    "component":
        pc_columns,

    "variance_explained":
        explained,

    "cumulative_variance":
        cumulative_explained
})


display(
    pca_diagnostic.round(4)
)


# ============================================================
# 5. REGIME PERSISTENCE FUNCTION
# ============================================================

def regime_persistence(labels):

    labels = np.asarray(
        labels
    )


    if len(labels) < 2:

        return np.nan


    return float(
        np.mean(
            labels[1:]
            ==
            labels[:-1]
        )
    )


# ============================================================
# 6. TEST NEARBY VALUES OF K
# ============================================================
#
# The swarm proposes K.
#
# We inspect nearby state counts rather than blindly accepting
# a single number.
#
# Diagnostics:
#
#     GMM BIC
#     silhouette score
#     persistence
#
# ============================================================

k_min = max(
    2,
    K - 1
)


k_max = min(
    8,
    K + 1
)


k_grid = list(
    range(
        k_min,
        k_max + 1
    )
)


diagnostic_rows = []


for k_test in k_grid:

    gmm_test = GaussianMixture(

        n_components=k_test,

        covariance_type="full",

        reg_covar=1e-5,

        n_init=5,

        max_iter=500,

        random_state=SEED
    )


    labels_test = (
        gmm_test
        .fit_predict(Z)
    )


    if len(
        np.unique(
            labels_test
        )
    ) > 1:

        sil = silhouette_score(
            Z,
            labels_test
        )

    else:

        sil = np.nan


    diagnostic_rows.append({

        "K":
            k_test,

        "GMM_BIC":
            gmm_test.bic(Z),

        "silhouette":
            sil,

        "persistence":
            regime_persistence(
                labels_test
            )
    })


k_diagnostics = pd.DataFrame(
    diagnostic_rows
)


print(
    "\nNEARBY STATE-COUNT DIAGNOSTICS"
)


display(
    k_diagnostics.round(4)
)


# ============================================================
# 7. GAUSSIAN MIXTURE MODEL
# ============================================================

gmm = GaussianMixture(

    n_components=K,

    covariance_type="full",

    reg_covar=1e-5,

    n_init=10,

    max_iter=750,

    random_state=SEED
)


gmm_labels = (
    gmm
    .fit_predict(Z)
)


gmm_probabilities = (
    gmm
    .predict_proba(Z)
)


gmm_confidence = (
    gmm_probabilities.max(
        axis=1
    )
)


if len(
    np.unique(
        gmm_labels
    )
) > 1:

    gmm_silhouette = (
        silhouette_score(
            Z,
            gmm_labels
        )
    )

else:

    gmm_silhouette = np.nan


print(
    f"\nGMM silhouette      : "
    f"{gmm_silhouette:.3f}"
)

print(
    f"GMM persistence     : "
    f"{regime_persistence(gmm_labels):.3f}"
)

print(
    f"GMM mean confidence : "
    f"{np.mean(gmm_confidence):.3f}"
)


# ============================================================
# 8. K-MEANS
# ============================================================

kmeans = KMeans(

    n_clusters=K,

    n_init=20,

    max_iter=500,

    random_state=SEED
)


kmeans_labels = (
    kmeans
    .fit_predict(Z)
)


if len(
    np.unique(
        kmeans_labels
    )
) > 1:

    kmeans_silhouette = (
        silhouette_score(
            Z,
            kmeans_labels
        )
    )

else:

    kmeans_silhouette = np.nan


print(
    f"\nKMeans silhouette   : "
    f"{kmeans_silhouette:.3f}"
)

print(
    f"KMeans persistence  : "
    f"{regime_persistence(kmeans_labels):.3f}"
)


# ============================================================
# 9. SPECTRAL CLUSTERING
# ============================================================
#
# Spectral clustering becomes expensive on very long samples.
#
# Therefore it is applied to the most recent observations.
#
# Earlier observations are deliberately left missing for this
# model rather than inventing spectral labels.
# ============================================================

SPECTRAL_MAX_OBS = min(
    2500,
    len(Z)
)


spectral_start = (
    len(Z)
    -
    SPECTRAL_MAX_OBS
)


Z_spectral = Z[
    spectral_start:
]


spectral = SpectralClustering(

    n_clusters=K,

    affinity="nearest_neighbors",

    n_neighbors=min(
        20,
        max(
            5,
            len(Z_spectral) - 1
        )
    ),

    assign_labels="kmeans",

    n_init=10,

    random_state=SEED
)


spectral_recent_labels = (
    spectral
    .fit_predict(
        Z_spectral
    )
)


print(
    f"\nSpectral observations: "
    f"{len(Z_spectral):,}"
)

print(
    f"Spectral persistence : "
    f"{regime_persistence(spectral_recent_labels):.3f}"
)


# ============================================================
# 10. LABEL ALIGNMENT
# ============================================================
#
# Cluster labels are arbitrary.
#
# GMM state 0 does not automatically mean the same thing as
# KMeans state 0.
#
# We therefore align competing methods to the GMM reference
# using maximum-overlap assignment.
# ============================================================

def align_to_reference(
    reference,
    candidate,
    K
):

    reference = np.asarray(
        reference,
        dtype=int
    )


    candidate = np.asarray(
        candidate,
        dtype=int
    )


    if len(reference) != len(candidate):

        raise ValueError(
            "Reference and candidate label arrays "
            "must have equal length."
        )


    overlap = np.zeros(
        (K, K),
        dtype=int
    )


    for ref_state in range(K):

        for cand_state in range(K):

            overlap[
                ref_state,
                cand_state
            ] = np.sum(

                (reference == ref_state)
                &
                (candidate == cand_state)
            )


    row_ind, col_ind = (
        linear_sum_assignment(
            -overlap
        )
    )


    mapping = {

        int(cand):
            int(ref)

        for ref, cand in zip(
            row_ind,
            col_ind
        )
    }


    aligned = np.array([

        mapping.get(
            int(label),
            int(label)
        )

        for label in candidate

    ])


    return (
        aligned,
        mapping,
        overlap
    )


# ============================================================
# 11. ALIGN K-MEANS TO GMM
# ============================================================

kmeans_aligned, kmeans_mapping, kmeans_overlap = (
    align_to_reference(

        gmm_labels,

        kmeans_labels,

        K
    )
)


# ============================================================
# 12. ALIGN SPECTRAL TO GMM
# ============================================================
#
# Only the overlapping recent sample is used.
# ============================================================

gmm_recent = (
    gmm_labels[
        spectral_start:
    ]
)


spectral_aligned_recent, spectral_mapping, spectral_overlap = (
    align_to_reference(

        gmm_recent,

        spectral_recent_labels,

        K
    )
)


# ============================================================
# 13. LABEL DATAFRAME
# ============================================================

labdf = pd.DataFrame(

    index=X.index
)


labdf[
    "GMM"
] = gmm_labels


labdf[
    "KMeans"
] = kmeans_aligned


labdf[
    "Spectral"
] = np.nan


labdf.loc[

    X.index[
        spectral_start:
    ],

    "Spectral"

] = spectral_aligned_recent


# ============================================================
# 14. CONSENSUS FUNCTION
# ============================================================
#
# Consensus is calculated from whatever models are available
# at each observation.
#
# Earlier observations:
#
#     GMM + KMeans
#
# Recent observations:
#
#     GMM + KMeans + Spectral
#
# Disagreement is:
#
#     1 - fraction voting for winning state
#
# ============================================================

def consensus_vote(row):

    votes = (
        row
        .dropna()
        .astype(int)
        .tolist()
    )


    if len(votes) == 0:

        return pd.Series({

            "regime":
                np.nan,

            "disagreement":
                np.nan,

            "models_available":
                0
        })


    counts = pd.Series(
        votes
    ).value_counts()


    winner = int(
        counts.index[0]
    )


    winner_votes = int(
        counts.iloc[0]
    )


    disagreement = (
        1.0
        -
        winner_votes
        /
        len(votes)
    )


    return pd.Series({

        "regime":
            winner,

        "disagreement":
            disagreement,

        "models_available":
            len(votes)
    })


consensus = labdf.apply(

    consensus_vote,

    axis=1
)


labdf[
    "regime"
] = consensus[
    "regime"
].astype(int)


labdf[
    "disagreement"
] = consensus[
    "disagreement"
]


labdf[
    "models_available"
] = consensus[
    "models_available"
].astype(int)


# ============================================================
# 15. CONSENSUS PERSISTENCE
# ============================================================

consensus_persistence = (
    regime_persistence(
        labdf[
            "regime"
        ].values
    )
)


mean_disagreement = float(

    labdf[
        "disagreement"
    ].mean()
)


print(
    f"\nConsensus persistence : "
    f"{consensus_persistence:.3f}"
)

print(
    f"Mean disagreement      : "
    f"{mean_disagreement:.3f}"
)


# ============================================================
# 16. BUILD MASTER STATE DATAFRAME
# ============================================================

state = pd.concat(

    [

        F.loc[
            X.index
        ],

        Zdf,

        labdf

    ],

    axis=1
)


state[
    "gmm_confidence"
] = gmm_confidence


# ============================================================
# 17. REGIME FREQUENCIES
# ============================================================

regime_frequency = (

    state[
        "regime"
    ]

    .value_counts(
        normalize=True
    )

    .sort_index()

    .rename(
        "fraction"
    )

    .to_frame()
)


regime_frequency[
    "percent"
] = (

    100
    *
    regime_frequency[
        "fraction"
    ]
)


print(
    "\nCONSENSUS REGIME FREQUENCIES"
)


display(
    regime_frequency.round(3)
)


# ============================================================
# 18. FEATURE PROFILES BY REGIME
# ============================================================

feature_profiles_cell7 = (

    state

    .groupby(
        "regime"
    )[
        list(
            X.columns
        )
    ]

    .median()
)


print(
    "\nMEDIAN FEATURE PROFILE BY REGIME"
)


display(
    feature_profiles_cell7.round(3)
)


# ============================================================
# 19. METHOD AGREEMENT MATRIX
# ============================================================

agreement = pd.DataFrame(

    index=[
        "GMM",
        "KMeans",
        "Spectral"
    ],

    columns=[
        "GMM",
        "KMeans",
        "Spectral"
    ],

    dtype=float
)


methods = [
    "GMM",
    "KMeans",
    "Spectral"
]


for m1 in methods:

    for m2 in methods:

        valid = (
            labdf[m1].notna()
            &
            labdf[m2].notna()
        )


        if valid.sum() == 0:

            agreement.loc[
                m1,
                m2
            ] = np.nan

        else:

            agreement.loc[
                m1,
                m2
            ] = np.mean(

                labdf.loc[
                    valid,
                    m1
                ].astype(int).values

                ==

                labdf.loc[
                    valid,
                    m2
                ].astype(int).values
            )


print(
    "\nALIGNED METHOD AGREEMENT"
)


display(
    agreement.round(3)
)


# ============================================================
# 20. VISUAL DIAGNOSTIC:
# PCA STATE SPACE
# ============================================================

plt.figure(
    figsize=(10, 6)
)


scatter = plt.scatter(

    Zdf["PC1"],

    Zdf["PC2"],

    c=state["regime"],

    s=8,

    alpha=0.55
)


plt.xlabel(
    "Principal Component 1"
)

plt.ylabel(
    "Principal Component 2"
)

plt.title(
    "Consensus Latent Market States in PCA Space"
)

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 21. VISUAL DIAGNOSTIC:
# REGIME THROUGH TIME
# ============================================================

plt.figure(
    figsize=(14, 4)
)


plt.scatter(

    state.index,

    state["regime"],

    c=state["regime"],

    s=8
)


plt.yticks(
    range(K)
)

plt.xlabel(
    "Date"
)

plt.ylabel(
    "Consensus regime"
)

plt.title(
    "Inferred Latent Market Regime Through Time"
)

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 22. SAVE CELL 7 OUTPUTS
# ============================================================

state.to_csv(

    OUT /
    "latent_state_history.csv"
)


k_diagnostics.to_csv(

    OUT /
    "state_count_diagnostics.csv",

    index=False
)


regime_frequency.to_csv(

    OUT /
    "regime_frequency.csv"
)


feature_profiles_cell7.to_csv(

    OUT /
    "regime_feature_profiles_cell7.csv"
)


agreement.to_csv(

    OUT /
    "method_agreement.csv"
)


# ============================================================
# 23. CELL 7 SUMMARY OBJECT
# ============================================================

cell7_report = {

    "architecture":
        synthesis[
            "architecture_name"
        ],

    "target_states":
        int(K),

    "observations":
        int(len(state)),

    "observed_features":
        int(X.shape[1]),

    "pca_components_computed":
        int(MAX_PCS),

    "pca_components_clustered":
        int(N_CLUSTER_PCS),

    "pca_variance_explained":
        float(
            cumulative_explained[
                N_CLUSTER_PCS - 1
            ]
        ),

    "gmm_silhouette":
        float(
            gmm_silhouette
        ),

    "gmm_persistence":
        float(
            regime_persistence(
                gmm_labels
            )
        ),

    "kmeans_silhouette":
        float(
            kmeans_silhouette
        ),

    "kmeans_persistence":
        float(
            regime_persistence(
                kmeans_labels
            )
        ),

    "consensus_persistence":
        float(
            consensus_persistence
        ),

    "mean_disagreement":
        float(
            mean_disagreement
        ),

    "spectral_observations":
        int(
            SPECTRAL_MAX_OBS
        )
}


(
    OUT /
    "cell7_regime_inference_report.json"
).write_text(

    json.dumps(
        cell7_report,
        indent=2
    ),

    encoding="utf-8"
)


# ============================================================
# 24. FINAL REPORT
# ============================================================

print("\n" + "=" * 72)

print(
    "CELL 7 COMPLETE"
)

print("=" * 72)


print(
    f"\nLatent states inferred       : {K}"
)

print(
    f"Observations classified      : {len(state):,}"
)

print(
    f"GMM silhouette               : {gmm_silhouette:.3f}"
)

print(
    f"Consensus persistence        : {consensus_persistence:.3f}"
)

print(
    f"Mean model disagreement      : {mean_disagreement:.3f}"
)

print(
    f"Spectral sample              : {SPECTRAL_MAX_OBS:,}"
)


print(
    "\nThe market now has an empirical latent-state history."
)

print(
    "Cell 8 can characterize those states and study "
    "their transition dynamics."
)

print("=" * 72)

========================================================================
CELL 7 — EMPIRICAL LATENT-STATE INFERENCE
========================================================================

Observations        : 3,641
Observed features   : 13
Architecture        : Metastable Basin-Transition Architecture (MBTA)
Target regimes (K) : 4

PCA dimensions used for clustering: 4
Cumulative variance explained: 0.797

  component  variance_explained  cumulative_variance
0       PC1              0.4707               0.4707
1       PC2              0.1821               0.6528
2       PC3              0.0840               0.7367
3       PC4              0.0607               0.7975
4       PC5              0.0487               0.8461
5       PC6              0.0396               0.8857

NEARBY STATE-COUNT DIAGNOSTICS

   K     GMM_BIC  silhouette  persistence
0  3  43215.7505      0.3195       0.9341
1  4  43030.2457      0.1758       0.8813
2  5  42722.9617      0.1424       0.8846

GMM silhouette      : 0.176
GMM persistence     : 0.881
GMM mean confidence : 0.829

KMeans silhouette   : 0.264
KMeans persistence  : 0.889

Spectral observations: 2,500
Spectral persistence : 0.890

Consensus persistence : 0.873
Mean disagreement      : 0.144

CONSENSUS REGIME FREQUENCIES

        fraction  percent
regime
0          0.241   24.087
1          0.464   46.388
2          0.228   22.796
3          0.067    6.729

MEDIAN FEATURE PROFILE BY REGIME

,spy_ret_5d,spy_trend_63d,spy_vol_21d,spy_downvol_63d,spy_drawdown,cross_asset_dispersion,avg_corr_63d,breadth_63d,vix_level,vix_change_21d,credit_risk_21d,bond_equity_rotation_21d,gold_equity_rotation_21d
regime,,,,,,,,,,,,,
0,-0.010,-0.006,0.175,0.099,-0.063,0.010,0.271,0.50,3.030,0.155,-0.003,0.019,0.029
1,0.003,0.056,0.092,0.058,-0.006,0.007,0.237,0.75,2.640,-0.004,0.002,-0.015,-0.015
2,0.015,0.051,0.135,0.084,-0.006,0.008,0.270,0.75,2.736,-0.160,0.009,-0.046,-0.044
3,0.007,-0.085,0.289,0.178,-0.162,0.015,0.370,0.25,3.338,-0.035,-0.001,-0.006,0.011

ALIGNED METHOD AGREEMENT

            GMM  KMeans  Spectral
GMM       1.000   0.792     0.640
KMeans    0.792   1.000     0.592
Spectral  0.640   0.592     1.000

========================================================================
CELL 7 COMPLETE
========================================================================

Latent states inferred       : 4
Observations classified      : 3,641
GMM silhouette               : 0.176
Consensus persistence        : 0.873
Mean model disagreement      : 0.144
Spectral sample              : 2,500

The market now has an empirical latent-state history.
Cell 8 can characterize those states and study their transition dynamics.
========================================================================

### CODE UNIT 8 — Regime interpretation, transition pressure and observatory

CODE UNIT 8 turns anonymous cluster numbers into economically interpretable state profiles and separates stable-state inference from transition pressure. A cluster label has no intrinsic meaning: regime 0 is not “good” or “bad.” The code therefore computes the median standardized feature vector within each consensus state and uses those profiles to characterize the regimes. This allows the researcher to see whether a state is associated with high volatility, deep drawdown, strong breadth, defensive rotation, correlation spikes or other observable structures.

Transition intensity is constructed independently from the labels. It measures the rolling magnitude of changes in the robustly scaled feature vector. This is a deliberately simple approximation to several cross-science ideas: velocity in state space, stress accumulation, distributional change, precursor activity and movement toward a new basin. A high transition-intensity reading does not automatically force a state switch; it says that the observed system is moving unusually rapidly. This distinction is important because transition detection and state classification are different inferential tasks.

The cell also estimates an empirical transition matrix for the consensus labels and average dwell times. These quantities connect naturally to Markov and kinetic-state interpretations while remaining model-agnostic. A regime with one-day average dwell time is probably a cluster rather than a meaningful market condition. A persistent regime with distinctive features and nontrivial transition structure is more interesting.

Finally, the code creates a compact visual observatory: the S&P 500 price is shown against regime-colored backgrounds, while transition intensity and model disagreement are plotted separately. The graphics are diagnostics, not trading signals. They make it easier to inspect whether the inferred states correspond to recognizable structural episodes and whether uncertainty rises around transitions.

In [ ]:
# ============================================================
# CODE CELL 8
# REGIME CHARACTERIZATION & TRANSITION DYNAMICS
#
# PURPOSE
# ------------------------------------------------------------
# Cell 7 inferred the latent market states.
#
# Cell 8 asks:
#
#   1. What does each regime economically look like?
#   2. How persistent is each regime?
#   3. How does the market move between regimes?
#   4. Does observable state-space movement accelerate
#      around regime transitions?
#   5. Does model disagreement rise near transitions?
#
# No new clustering is performed here.
# ============================================================

import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 1. PRECONDITIONS
# ============================================================

required_objects = [
    "state",
    "X",
    "px",
    "K"
]

missing_objects = [
    name
    for name in required_objects
    if name not in globals()
]

if missing_objects:

    raise RuntimeError(
        "Cell 8 requires Cell 7 outputs. "
        f"Missing objects: {missing_objects}"
    )


required_state_columns = [
    "regime",
    "disagreement"
]

missing_columns = [
    col
    for col in required_state_columns
    if col not in state.columns
]

if missing_columns:

    raise RuntimeError(
        "The state dataframe is missing required columns: "
        f"{missing_columns}"
    )


if "SPY" not in px.columns:

    raise RuntimeError(
        "SPY is required for the market-regime observatory."
    )


print("=" * 72)
print("CELL 8 — REGIME CHARACTERIZATION & TRANSITION DYNAMICS")
print("=" * 72)

print(f"\nObservations        : {len(state):,}")
print(f"Latent regimes (K) : {K}")
print(f"Features            : {len(X.columns)}")


# ============================================================
# 2. CLEAN REGIME SERIES
# ============================================================

regime = (
    state["regime"]
    .dropna()
    .astype(int)
)


if len(regime) == 0:

    raise RuntimeError(
        "No valid regime observations were found."
    )


unexpected_states = (
    set(regime.unique())
    -
    set(range(K))
)

if unexpected_states:

    raise RuntimeError(
        "Unexpected regime labels found: "
        f"{sorted(unexpected_states)}"
    )


# ============================================================
# 3. FEATURE PROFILES BY REGIME
# ============================================================
#
# We characterize each latent state using the median of the
# original market features.
#
# Median profiles are preferred here because several market
# variables — volatility, VIX changes, drawdowns and credit
# stress — can be highly skewed.
# ============================================================

feature_profiles = (

    state

    .groupby("regime")[
        list(X.columns)
    ]

    .median()

    .reindex(
        range(K)
    )
)


feature_means = (

    state

    .groupby("regime")[
        list(X.columns)
    ]

    .mean()

    .reindex(
        range(K)
    )
)


regime_counts = (

    state["regime"]

    .value_counts()

    .reindex(
        range(K),
        fill_value=0
    )

    .sort_index()
)


regime_shares = (
    regime_counts
    /
    regime_counts.sum()
)


print("\n" + "=" * 72)
print("MEDIAN MARKET FEATURE PROFILE BY REGIME")
print("=" * 72)

display(
    feature_profiles.round(3)
)


# ============================================================
# 4. ECONOMIC SUMMARY TABLE
# ============================================================

summary_rows = []


for k in range(K):

    mask = (
        state["regime"] == k
    )

    row = {

        "regime":
            k,

        "observations":
            int(mask.sum()),

        "share":
            float(mask.mean()),

        "mean_disagreement":
            float(
                state.loc[
                    mask,
                    "disagreement"
                ].mean()
            )
    }


    # --------------------------------------------------------
    # Include economically interpretable variables when they
    # exist in the feature set.
    # --------------------------------------------------------

    useful_features = [

        "spy_ret_5d",

        "spy_trend_63d",

        "spy_vol_21d",

        "spy_downvol_63d",

        "spy_drawdown",

        "cross_asset_dispersion",

        "avg_corr_63d",

        "breadth_63d",

        "vix_level",

        "vix_change_21d",

        "credit_risk_21d",

        "bond_equity_rotation_21d",

        "gold_equity_rotation_21d"
    ]


    for feature in useful_features:

        if feature in state.columns:

            row[feature] = float(

                state.loc[
                    mask,
                    feature
                ].median()
            )


    summary_rows.append(
        row
    )


regime_summary = pd.DataFrame(
    summary_rows
)


print("\n" + "=" * 72)
print("ECONOMIC REGIME SUMMARY")
print("=" * 72)

display(
    regime_summary.round(4)
)


# ============================================================
# 5. TRANSITION MATRIX
# ============================================================
#
# T[i,j] estimates:
#
#       P(S_t = j | S_{t-1} = i)
#
# Diagonal values measure one-day regime persistence.
# Off-diagonal values describe observed transitions.
# ============================================================

previous_regime = (
    regime.shift(1)
)


transition_counts = pd.crosstab(

    previous_regime,

    regime
)


transition_counts = (
    transition_counts
    .reindex(
        index=range(K),
        columns=range(K),
        fill_value=0
    )
)


row_totals = (
    transition_counts
    .sum(axis=1)
    .replace(0, np.nan)
)


transition_matrix = (
    transition_counts
    .div(
        row_totals,
        axis=0
    )
    .fillna(0.0)
)


print("\n" + "=" * 72)
print("CONSENSUS TRANSITION MATRIX")
print("=" * 72)

display(
    transition_matrix.round(3)
)


# ============================================================
# 6. REGIME PERSISTENCE
# ============================================================

persistence_by_regime = pd.DataFrame({

    "regime":
        range(K),

    "one_day_persistence": [

        float(
            transition_matrix.loc[
                k,
                k
            ]
        )

        for k in range(K)
    ]
})


print("\n" + "=" * 72)
print("ONE-DAY REGIME PERSISTENCE")
print("=" * 72)

display(
    persistence_by_regime.round(4)
)


# ============================================================
# 7. DWELL-TIME ANALYSIS
# ============================================================
#
# A dwell is a consecutive sequence of observations in the
# same latent regime.
#
# This is distinct from the diagonal transition probability:
# it gives the empirical duration of complete regime episodes.
# ============================================================

regime_full = (
    state["regime"]
    .astype(int)
)


run_id = (
    regime_full
    !=
    regime_full.shift(1)
).cumsum()


dwell = (

    pd.DataFrame({

        "regime":
            regime_full,

        "run_id":
            run_id
    })

    .groupby("run_id")

    .agg(

        regime=(
            "regime",
            "first"
        ),

        length=(
            "regime",
            "size"
        ),

        start=(
            "regime",
            lambda x: x.index.min()
        ),

        end=(
            "regime",
            lambda x: x.index.max()
        )
    )
)


dwell_summary = (

    dwell

    .groupby("regime")[
        "length"
    ]

    .agg(
        [
            "count",
            "mean",
            "median",
            "max"
        ]
    )

    .reindex(
        range(K)
    )
)


dwell_summary.columns = [

    "episodes",

    "mean_days",

    "median_days",

    "max_days"
]


print("\n" + "=" * 72)
print("REGIME DWELL TIMES")
print("=" * 72)

display(
    dwell_summary.round(2)
)


# ============================================================
# 8. STATE-SPACE VELOCITY
# ============================================================
#
# Regime labels are discrete.
#
# But the observable market system moves continuously through
# feature space.
#
# We therefore construct:
#
#       velocity_t =
#       sqrt(mean_j[(X_j,t - X_j,t-1)^2])
#
# using standardized features.
#
# This is a model-independent measure of how rapidly the
# observable market state is changing.
# ============================================================

dX = (
    X
    .diff()
)


state_space_velocity = (

    np.sqrt(
        np.mean(
            np.square(dX),
            axis=1
        )
    )
)


state_space_velocity = pd.Series(

    state_space_velocity,

    index=X.index,

    name="state_space_velocity"
)


# ============================================================
# 9. TRANSITION INTENSITY
# ============================================================
#
# Smooth short-term state-space movement.
#
# The purpose is not to predict a transition automatically,
# but to measure pressure or instability in the observable
# system.
# ============================================================

TRANSITION_WINDOW = 10


transition_intensity = (

    state_space_velocity

    .rolling(
        TRANSITION_WINDOW,
        min_periods=3
    )

    .mean()
)


transition_intensity.name = (
    "transition_intensity"
)


# ============================================================
# 10. ROLLING ROBUST NORMALIZATION
# ============================================================
#
# A raw velocity of 0.5 may be extreme in one historical
# period and ordinary in another.
#
# We therefore normalize transition intensity relative to a
# trailing one-year window.
# ============================================================

NORMALIZATION_WINDOW = 252


rolling_median = (

    transition_intensity

    .rolling(
        NORMALIZATION_WINDOW,
        min_periods=60
    )

    .median()
)


rolling_std = (

    transition_intensity

    .rolling(
        NORMALIZATION_WINDOW,
        min_periods=60
    )

    .std()
)


transition_z = (

    (
        transition_intensity
        -
        rolling_median
    )

    /
    (
        rolling_std
        +
        1e-9
    )
)


transition_z.name = (
    "transition_z"
)


# ============================================================
# 11. ADD DYNAMICS TO MASTER STATE DATAFRAME
# ============================================================

state[
    "state_space_velocity"
] = state_space_velocity


state[
    "transition_intensity"
] = transition_intensity


state[
    "transition_z"
] = transition_z


# ============================================================
# 12. IDENTIFY ACTUAL REGIME SWITCHES
# ============================================================

state[
    "regime_switch"
] = (

    state["regime"]
    !=
    state["regime"].shift(1)
)


# First observation is not a genuine transition.

state.iloc[
    0,
    state.columns.get_loc(
        "regime_switch"
    )
] = False


state[
    "regime_switch"
] = (

    state[
        "regime_switch"
    ]

    .astype(bool)
)


n_switches = int(

    state[
        "regime_switch"
    ].sum()
)


print(
    f"\nObserved consensus regime switches: "
    f"{n_switches:,}"
)


# ============================================================
# 13. TRANSITION INTENSITY:
# SWITCH DAYS VS NON-SWITCH DAYS
# ============================================================

switch_intensity = (

    state.loc[
        state["regime_switch"],
        "transition_intensity"
    ]

    .dropna()
)


quiet_intensity = (

    state.loc[
        ~state["regime_switch"],
        "transition_intensity"
    ]

    .dropna()
)


if (
    len(switch_intensity) > 0
    and
    len(quiet_intensity) > 0
):

    switch_mean = float(
        switch_intensity.mean()
    )

    quiet_mean = float(
        quiet_intensity.mean()
    )


    transition_intensity_ratio = (

        switch_mean
        /
        (
            quiet_mean
            +
            1e-12
        )
    )

else:

    switch_mean = np.nan

    quiet_mean = np.nan

    transition_intensity_ratio = np.nan


transition_test = pd.DataFrame({

    "group": [
        "Regime-switch observations",
        "Non-switch observations"
    ],

    "n": [
        len(switch_intensity),
        len(quiet_intensity)
    ],

    "mean_transition_intensity": [
        switch_mean,
        quiet_mean
    ],

    "median_transition_intensity": [

        float(
            switch_intensity.median()
        )
        if len(switch_intensity)
        else np.nan,

        float(
            quiet_intensity.median()
        )
        if len(quiet_intensity)
        else np.nan
    ]
})


print("\n" + "=" * 72)
print("TRANSITION-INTENSITY TEST")
print("=" * 72)

display(
    transition_test.round(4)
)


print(
    f"\nSwitch / non-switch intensity ratio: "
    f"{transition_intensity_ratio:.3f}"
)


# ============================================================
# 14. MODEL DISAGREEMENT AROUND TRANSITIONS
# ============================================================
#
# The ensemble may begin to disagree before or during periods
# in which the inferred market state is changing.
#
# This gives disagreement an epistemic interpretation:
#
#     high disagreement =
#     lower confidence in a unique latent-state assignment.
# ============================================================

switch_disagreement = (

    state.loc[
        state["regime_switch"],
        "disagreement"
    ]

    .dropna()
)


quiet_disagreement = (

    state.loc[
        ~state["regime_switch"],
        "disagreement"
    ]

    .dropna()
)


if (
    len(switch_disagreement) > 0
    and
    len(quiet_disagreement) > 0
):

    disagreement_ratio = (

        switch_disagreement.mean()

        /
        (
            quiet_disagreement.mean()
            +
            1e-12
        )
    )

else:

    disagreement_ratio = np.nan


disagreement_test = pd.DataFrame({

    "group": [
        "Regime-switch observations",
        "Non-switch observations"
    ],

    "mean_disagreement": [

        switch_disagreement.mean()
        if len(switch_disagreement)
        else np.nan,

        quiet_disagreement.mean()
        if len(quiet_disagreement)
        else np.nan
    ],

    "median_disagreement": [

        switch_disagreement.median()
        if len(switch_disagreement)
        else np.nan,

        quiet_disagreement.median()
        if len(quiet_disagreement)
        else np.nan
    ]
})


print("\n" + "=" * 72)
print("MODEL DISAGREEMENT AROUND REGIME CHANGES")
print("=" * 72)

display(
    disagreement_test.round(4)
)


# ============================================================
# 15. HIGH TRANSITION-PRESSURE OBSERVATIONS
# ============================================================

TRANSITION_Z_THRESHOLD = 2.0


state[
    "high_transition_pressure"
] = (

    state[
        "transition_z"
    ]
    >
    TRANSITION_Z_THRESHOLD
)


high_pressure_share = float(

    state[
        "high_transition_pressure"
    ].mean()
)


print(
    f"\nShare of observations with "
    f"transition_z > {TRANSITION_Z_THRESHOLD}: "
    f"{100 * high_pressure_share:.2f}%"
)


# ============================================================
# 16. SPY MARKET SERIES
# ============================================================

spy = (

    px["SPY"]

    .reindex(
        state.index
    )

    .ffill()
)


state[
    "SPY"
] = spy


# ============================================================
# 17. MARKET REGIME OBSERVATORY
# ============================================================
#
# Each observation is colored by the inferred consensus
# latent state.
#
# The plot does not assign semantic names such as "crisis" or
# "expansion" automatically. Economic interpretation should
# come from the regime profiles, not from arbitrary labels.
# ============================================================

plt.figure(
    figsize=(15, 6)
)


for k in range(K):

    mask = (
        state["regime"] == k
    )


    plt.scatter(

        state.index[
            mask
        ],

        state.loc[
            mask,
            "SPY"
        ],

        s=9,

        label=f"Regime {k}"
    )


plt.yscale(
    "log"
)


plt.xlabel(
    "Date"
)


plt.ylabel(
    "SPY — log scale"
)


plt.title(
    "Market Regime Observatory — Consensus Latent States"
)


plt.legend(
    ncol=min(
        K,
        4
    )
)


plt.grid(
    alpha=0.2
)


plt.show()


# ============================================================
# 18. TRANSITION-PRESSURE OBSERVATORY
# ============================================================

plt.figure(
    figsize=(15, 5)
)


plt.plot(

    state.index,

    state[
        "transition_z"
    ],

    linewidth=1.0,

    label="Transition pressure"
)


plt.axhline(

    TRANSITION_Z_THRESHOLD,

    linestyle="--",

    linewidth=1.0,

    label=f"Threshold = {TRANSITION_Z_THRESHOLD}"
)


plt.axhline(

    0,

    linewidth=0.8
)


plt.xlabel(
    "Date"
)


plt.ylabel(
    "Rolling normalized transition intensity"
)


plt.title(
    "Observable Market State-Space Transition Pressure"
)


plt.legend()


plt.grid(
    alpha=0.2
)


plt.show()


# ============================================================
# 19. MODEL-DISAGREEMENT OBSERVATORY
# ============================================================

plt.figure(
    figsize=(15, 4)
)


plt.plot(

    state.index,

    state[
        "disagreement"
    ],

    linewidth=1.0
)


plt.xlabel(
    "Date"
)


plt.ylabel(
    "Model disagreement"
)


plt.title(
    "Epistemic Uncertainty Across Latent-State Models"
)


plt.grid(
    alpha=0.2
)


plt.show()


# ============================================================
# 20. JOINT TRANSITION DIAGNOSTIC
# ============================================================
#
# Transition pressure:
#     movement in observable market feature space.
#
# Disagreement:
#     uncertainty across state-inference models.
#
# They are conceptually different and should not be collapsed
# into one number.
# ============================================================

joint_transition_diagnostic = (

    state[
        [
            "regime",
            "regime_switch",
            "transition_intensity",
            "transition_z",
            "disagreement",
            "high_transition_pressure"
        ]
    ]

    .copy()
)


print("\n" + "=" * 72)
print("MOST EXTREME TRANSITION-PRESSURE OBSERVATIONS")
print("=" * 72)


display(

    joint_transition_diagnostic

    .sort_values(
        "transition_z",
        ascending=False
    )

    .head(20)

    .round(4)
)


# ============================================================
# 21. TRANSITION EVENT TABLE
# ============================================================
#
# Record every consensus state change.
# ============================================================

transition_events = (

    state.loc[
        state["regime_switch"],
        [
            "regime",
            "transition_intensity",
            "transition_z",
            "disagreement",
            "SPY"
        ]
    ]

    .copy()
)


transition_events[
    "previous_regime"
] = (

    state[
        "regime"
    ]

    .shift(1)

    .reindex(
        transition_events.index
    )
)


transition_events = transition_events[
    [
        "previous_regime",
        "regime",
        "transition_intensity",
        "transition_z",
        "disagreement",
        "SPY"
    ]
]


transition_events = transition_events.rename(

    columns={
        "regime":
            "new_regime"
    }
)


print("\n" + "=" * 72)
print("RECENT REGIME TRANSITIONS")
print("=" * 72)


display(

    transition_events
    .tail(20)
    .round(4)
)


# ============================================================
# 22. SAVE OUTPUT TABLES
# ============================================================

feature_profiles.to_csv(

    OUT /
    "regime_feature_profiles.csv"
)


regime_summary.to_csv(

    OUT /
    "regime_economic_summary.csv",

    index=False
)


transition_counts.to_csv(

    OUT /
    "transition_counts.csv"
)


transition_matrix.to_csv(

    OUT /
    "transition_matrix.csv"
)


dwell.to_csv(

    OUT /
    "regime_dwell_events.csv"
)


dwell_summary.to_csv(

    OUT /
    "regime_dwell_summary.csv"
)


transition_test.to_csv(

    OUT /
    "transition_intensity_test.csv",

    index=False
)


disagreement_test.to_csv(

    OUT /
    "transition_disagreement_test.csv",

    index=False
)


transition_events.to_csv(

    OUT /
    "transition_events.csv"
)


state.to_csv(

    OUT /
    "state_history_with_dynamics.csv"
)


# ============================================================
# 23. CELL 8 REPORT
# ============================================================

cell8_report = {

    "number_of_regimes":
        int(K),

    "observations":
        int(len(state)),

    "number_of_regime_switches":
        int(n_switches),

    "consensus_persistence":
        float(
            np.mean(
                regime.values[1:]
                ==
                regime.values[:-1]
            )
        ),

    "mean_transition_intensity_switch":
        (
            float(switch_mean)
            if np.isfinite(switch_mean)
            else None
        ),

    "mean_transition_intensity_non_switch":
        (
            float(quiet_mean)
            if np.isfinite(quiet_mean)
            else None
        ),

    "transition_intensity_switch_ratio":
        (
            float(
                transition_intensity_ratio
            )
            if np.isfinite(
                transition_intensity_ratio
            )
            else None
        ),

    "mean_model_disagreement":
        float(
            state[
                "disagreement"
            ].mean()
        ),

    "disagreement_switch_ratio":
        (
            float(
                disagreement_ratio
            )
            if np.isfinite(
                disagreement_ratio
            )
            else None
        ),

    "transition_z_threshold":
        float(
            TRANSITION_Z_THRESHOLD
        ),

    "high_transition_pressure_share":
        float(
            high_pressure_share
        )
}


cell8_path = (

    OUT /
    "cell8_transition_dynamics_report.json"
)


cell8_path.write_text(

    json.dumps(
        cell8_report,
        indent=2
    ),

    encoding="utf-8"
)


# ============================================================
# 24. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 72)

print(
    "CELL 8 COMPLETE — REGIME DYNAMICS CHARACTERIZED"
)

print("=" * 72)


print(
    f"\nLatent regimes                : {K}"
)

print(
    f"Consensus regime switches     : {n_switches:,}"
)

print(
    f"Overall regime persistence    : "
    f"{cell8_report['consensus_persistence']:.3f}"
)


if np.isfinite(
    transition_intensity_ratio
):

    print(
        f"Transition intensity ratio    : "
        f"{transition_intensity_ratio:.3f}"
    )


print(
    f"Mean model disagreement       : "
    f"{cell8_report['mean_model_disagreement']:.3f}"
)

print(
    f"High transition-pressure share: "
    f"{100 * high_pressure_share:.2f}%"
)


print(
    "\nInterpretation:"
)

print(
    "Cell 7 inferred WHERE the market is in latent-state space."
)

print(
    "Cell 8 measures WHAT those states look like and HOW the "
    "system moves between them."
)

print(
    "Transition pressure and model disagreement remain separate:"
)

print(
    "the first measures movement in observable market space; "
    "the second measures uncertainty about latent-state identity."
)

print(
    "\nCell 9 can now test whether these structures survive "
    "perturbation and whether transitions have empirical content."
)

print("=" * 72)

========================================================================
CELL 8 — REGIME CHARACTERIZATION & TRANSITION DYNAMICS
========================================================================

Observations        : 3,641
Latent regimes (K) : 4
Features            : 13

========================================================================
MEDIAN MARKET FEATURE PROFILE BY REGIME
========================================================================

,spy_ret_5d,spy_trend_63d,spy_vol_21d,spy_downvol_63d,spy_drawdown,cross_asset_dispersion,avg_corr_63d,breadth_63d,vix_level,vix_change_21d,credit_risk_21d,bond_equity_rotation_21d,gold_equity_rotation_21d
regime,,,,,,,,,,,,,
0,-0.010,-0.006,0.175,0.099,-0.063,0.010,0.271,0.50,3.030,0.155,-0.003,0.019,0.029
1,0.003,0.056,0.092,0.058,-0.006,0.007,0.237,0.75,2.640,-0.004,0.002,-0.015,-0.015
2,0.015,0.051,0.135,0.084,-0.006,0.008,0.270,0.75,2.736,-0.160,0.009,-0.046,-0.044
3,0.007,-0.085,0.289,0.178,-0.162,0.015,0.370,0.25,3.338,-0.035,-0.001,-0.006,0.011

========================================================================
ECONOMIC REGIME SUMMARY
========================================================================

,regime,observations,share,mean_disagreement,spy_ret_5d,spy_trend_63d,spy_vol_21d,spy_downvol_63d,spy_drawdown,cross_asset_dispersion,avg_corr_63d,breadth_63d,vix_level,vix_change_21d,credit_risk_21d,bond_equity_rotation_21d,gold_equity_rotation_21d
0,0,877,0.2409,0.1256,-0.0100,-0.0061,0.1746,0.0990,-0.0634,0.0098,0.2712,0.50,3.0301,0.1554,-0.0028,0.0193,0.0294
1,1,1689,0.4639,0.1436,0.0029,0.0564,0.0917,0.0584,-0.0059,0.0066,0.2365,0.75,2.6405,-0.0037,0.0016,-0.0147,-0.0152
2,2,830,0.2280,0.1886,0.0151,0.0505,0.1352,0.0843,-0.0055,0.0085,0.2697,0.75,2.7360,-0.1595,0.0092,-0.0464,-0.0437
3,3,245,0.0673,0.0639,0.0068,-0.0854,0.2893,0.1782,-0.1620,0.0151,0.3701,0.25,3.3379,-0.0346,-0.0007,-0.0058,0.0107

========================================================================
CONSENSUS TRANSITION MATRIX
========================================================================

regime      0      1      2      3
regime
0       0.846  0.057  0.078  0.019
1       0.041  0.909  0.049  0.000
2       0.059  0.124  0.814  0.002
3       0.065  0.000  0.012  0.922

========================================================================
ONE-DAY REGIME PERSISTENCE
========================================================================

   regime  one_day_persistence
0       0               0.8461
1       1               0.9094
2       2               0.8145
3       3               0.9224

========================================================================
REGIME DWELL TIMES
========================================================================

        episodes  mean_days  median_days  max_days
regime
0            135       6.50          2.0        47
1            154      10.97          3.0       284
2            154       5.39          3.0        41
3             19      12.89          2.0        64

Observed consensus regime switches: 461

========================================================================
TRANSITION-INTENSITY TEST
========================================================================

,group,n,mean_transition_intensity,median_transition_intensity
0,Regime-switch observations,461,0.2522,0.2474
1,Non-switch observations,3177,0.2392,0.2209

Switch / non-switch intensity ratio: 1.054

========================================================================
MODEL DISAGREEMENT AROUND REGIME CHANGES
========================================================================

                        group  mean_disagreement  median_disagreement
0  Regime-switch observations             0.2697               0.3333
1     Non-switch observations             0.1259               0.0000

Share of observations with transition_z > 2.0: 6.48%

========================================================================
MOST EXTREME TRANSITION-PRESSURE OBSERVATIONS
========================================================================

,regime,regime_switch,transition_intensity,transition_z,disagreement,high_transition_pressure
Date,,,,,,
2018-02-15,0,False,0.4894,5.8432,0.3333,True
2018-02-12,0,False,0.4290,5.7142,0.0000,True
2024-08-12,0,False,0.4288,5.5275,0.0000,True
2024-08-13,0,False,0.4422,5.5016,0.0000,True
2025-04-16,3,False,0.6794,5.4911,0.0000,True
2018-02-14,0,False,0.4428,5.3718,0.0000,True
2024-08-08,0,False,0.3945,5.3310,0.0000,True
2024-08-09,0,False,0.4029,5.2498,0.0000,True
2025-04-11,3,False,0.5966,5.2232,0.0000,True
2018-02-13,0,False,0.4156,5.1464,0.0000,True
2018-02-08,0,False,0.3751,5.1370,0.0000,True
2018-02-09,0,False,0.3857,5.1204,0.0000,True
2018-02-06,0,False,0.3531,5.0653,0.0000,True
2018-02-05,0,False,0.3418,5.0200,0.0000,True
2025-04-14,3,False,0.5965,4.9720,0.0000,True
2025-04-17,3,False,0.6372,4.7523,0.0000,True
2024-08-06,0,False,0.3540,4.7369,0.0000,True
2018-02-16,0,False,0.4377,4.7157,0.3333,True
2020-03-09,3,False,0.5359,4.5849,0.0000,True
2020-03-11,3,False,0.5627,4.5832,0.0000,True

========================================================================
RECENT REGIME TRANSITIONS
========================================================================

,previous_regime,new_regime,transition_intensity,transition_z,disagreement,SPY
Date,,,,,,
2026-03-02,0.0,1,0.2175,-0.0683,0.3333,681.0605
2026-03-03,1.0,0,0.2409,0.1628,0.0000,675.0573
2026-04-07,0.0,2,0.3134,0.8812,0.3333,655.8973
2026-06-03,2.0,1,0.1334,-1.6943,0.3333,750.4384
2026-06-10,1.0,0,0.1980,-0.2285,0.0000,721.7736
2026-06-11,0.0,1,0.2154,0.1460,0.3333,734.0415
2026-06-12,1.0,2,0.2491,0.8726,0.0000,738.0114
2026-06-23,2.0,0,0.2706,1.3270,0.3333,731.7629
2026-06-24,0.0,1,0.2728,1.3734,0.3333,731.4237
2026-06-25,1.0,0,0.2690,1.2921,0.3333,732.4811
2026-06-30,0.0,2,0.2557,1.0036,0.0000,744.9202
2026-07-17,2.0,1,0.2383,0.4915,0.3333,741.4488
2026-07-20,1.0,2,0.2340,0.4017,0.3333,740.2518
2026-07-22,2.0,1,0.1931,-0.4744,0.3333,745.5586
2026-07-28,1.0,2,0.1856,-0.6344,0.3333,739.0248
2026-07-29,2.0,0,0.2091,-0.1364,0.3333,727.6531
2026-07-30,0.0,2,0.2247,0.1899,0.3333,739.8528
2026-08-19,2.0,1,0.1784,-0.8703,0.3333,767.1550
2026-08-27,1.0,2,0.1785,-0.8730,0.0000,769.1899
2026-08-28,2.0,1,0.1865,-0.7011,0.3333,767.4443

========================================================================
CELL 8 COMPLETE — REGIME DYNAMICS CHARACTERIZED
========================================================================

Latent regimes                : 4
Consensus regime switches     : 461
Overall regime persistence    : 0.873
Transition intensity ratio    : 1.054
Mean model disagreement       : 0.144
High transition-pressure share: 6.48%

Interpretation:
Cell 7 inferred WHERE the market is in latent-state space.
Cell 8 measures WHAT those states look like and HOW the system moves between them.
Transition pressure and model disagreement remain separate:
the first measures movement in observable market space; the second measures uncertainty about latent-state identity.

Cell 9 can now test whether these structures survive perturbation and whether transitions have empirical content.
========================================================================

### CODE UNIT 9 — Falsification, robustness and swarm-convergence diagnostics

CODE UNIT 9 is the falsification and robustness layer. Because the true regime is unobserved, validation must ask whether the inferred partition has properties that a useful latent market state should possess. The first test is conditional economic differentiation. For each regime, the code measures subsequent S&P 500 return and realized volatility over a fixed horizon. A regime representation that produces indistinguishable forward distributions may still describe the present, but it is less useful for investment and risk applications.

The second test is stability under feature perturbation. A small amount of noise is added to the standardized feature matrix, the Gaussian-mixture model is refitted, and the resulting labels are compared with the original partition using Adjusted Rand Index. Repeating this procedure creates a distribution of stability rather than one lucky score. The third test examines transition concentration: are actual regime switches associated with higher transition intensity than ordinary days? This links the state classifier to the independent change-pressure measure.

The fourth test examines scientific convergence across swarm size. Rather than making additional API calls, the cell takes prefixes of the existing fifty-agent corpus and compares their distributions of proposed state counts and mathematical vocabulary with the full swarm. This asks whether the intellectual architecture stabilizes as the population grows. It is not a proof that fifty is optimal, but it reveals whether the final synthesis depends on the last few agents.

The code produces a validation report without declaring success automatically. Thresholds are shown as diagnostics, not as a hidden optimization target. A researcher should inspect failures and revise the feature system or architecture rather than tuning until every metric looks attractive.

In [ ]:
# ============================================================
# CODE CELL 9
# VALIDATION, ROBUSTNESS & SWARM CONVERGENCE
#
# PURPOSE
# ------------------------------------------------------------
# Cells 6–8 established:
#
#   Cell 6 — Cross-science synthesis
#   Cell 7 — Empirical latent-state inference
#   Cell 8 — Regime characterization and transition dynamics
#
# Cell 9 asks whether the resulting latent-state architecture
# survives empirical scrutiny.
#
# VALIDATION LAYERS
#
#   1. Conditional forward market behavior
#   2. Cross-regime economic separation
#   3. Perturbation stability
#   4. Transition-intensity validation
#   5. Model-disagreement validation
#   6. 50-agent swarm convergence
#   7. Consolidated validation dashboard
#
# IMPORTANT
# ------------------------------------------------------------
# This is NOT a trading backtest.
#
# The objective is scientific validation of the inferred
# latent-state architecture.
# ============================================================


# ============================================================
# 0. IMPORTS
# ============================================================

import json
import re

from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.metrics import adjusted_rand_score


# ============================================================
# 1. PRECONDITIONS
# ============================================================

required_objects = [
    "state",
    "X",
    "px",
    "K",
    "proposals",
    "synthesis"
]


missing_objects = [

    obj

    for obj in required_objects

    if obj not in globals()
]


if missing_objects:

    raise RuntimeError(
        "Cell 9 requires outputs from Cells 5–8. "
        f"Missing objects: {missing_objects}"
    )


required_state_columns = [
    "regime",
    "disagreement",
    "transition_intensity",
    "transition_z",
    "regime_switch"
]


missing_state_columns = [

    col

    for col in required_state_columns

    if col not in state.columns
]


if missing_state_columns:

    raise RuntimeError(
        "The state dataframe is missing Cell 8 outputs: "
        f"{missing_state_columns}"
    )


if "SPY" not in px.columns:

    raise RuntimeError(
        "SPY is required for forward-behavior validation."
    )


if len(proposals) != 50:

    raise RuntimeError(
        "Swarm-convergence analysis requires all 50 proposals. "
        f"Currently available: {len(proposals)}."
    )


if not (
    2 <= int(K) <= 8
):

    raise RuntimeError(
        f"Invalid number of latent states: K={K}"
    )


print("=" * 72)

print(
    "CELL 9 — VALIDATION, ROBUSTNESS & SWARM CONVERGENCE"
)

print("=" * 72)


print(
    f"\nObservations       : {len(state):,}"
)

print(
    f"Latent regimes     : {K}"
)

print(
    f"Scientific agents  : {len(proposals)}"
)

print(
    f"Architecture       : "
    f"{synthesis['architecture_name']}"
)


# ============================================================
# 2. FORWARD MARKET BEHAVIOR
# ============================================================
#
# For every observation t:
#
#     regime_t
#
# is compared with market behavior over the NEXT 21 trading
# days.
#
# We calculate:
#
#     R(t,t+H) = log(P[t+H]) - log(P[t])
#
# and forward realized volatility from:
#
#     r[t+1], r[t+2], ..., r[t+H]
#
# The regime is therefore defined at time t and the validation
# quantities occur strictly after t.
# ============================================================

FORWARD_HORIZON = 21


# ------------------------------------------------------------
# Align SPY exactly to state history
# ------------------------------------------------------------

spy = (

    px["SPY"]

    .reindex(
        state.index
    )

    .ffill()
)


if spy.isna().all():

    raise RuntimeError(
        "SPY could not be aligned to the state dataframe."
    )


log_spy = np.log(
    spy
)


daily_spy_return = (
    log_spy.diff()
)


# ============================================================
# 3. FORWARD RETURN
# ============================================================

future_return = (

    log_spy.shift(
        -FORWARD_HORIZON
    )

    -

    log_spy
)


future_return.name = (
    "future_return"
)


# ============================================================
# 4. FORWARD REALIZED VOLATILITY
# ============================================================
#
# Construct explicitly:
#
#   r[t+1]
#   r[t+2]
#   ...
#   r[t+21]
#
# This avoids accidental backward-looking contamination.
# ============================================================

future_return_matrix = pd.concat(

    [

        daily_spy_return.shift(
            -h
        )

        for h in range(
            1,
            FORWARD_HORIZON + 1
        )

    ],

    axis=1
)


future_return_matrix.columns = [

    f"r_plus_{h}"

    for h in range(
        1,
        FORWARD_HORIZON + 1
    )
]


# ------------------------------------------------------------
# Require a complete 21-day future window
# ------------------------------------------------------------

complete_forward_window = (

    future_return_matrix

    .notna()

    .sum(axis=1)

    ==
    FORWARD_HORIZON
)


# ------------------------------------------------------------
# Annualized realized volatility
# ------------------------------------------------------------

future_volatility = (

    future_return_matrix

    .std(
        axis=1,
        ddof=1
    )

    *
    np.sqrt(252)
)


future_volatility.name = (
    "future_volatility"
)


# ------------------------------------------------------------
# Mask incomplete tail observations
# ------------------------------------------------------------

future_return = (

    future_return

    .where(
        complete_forward_window
    )
)


future_volatility = (

    future_volatility

    .where(
        complete_forward_window
    )
)


# ============================================================
# 5. FORWARD VALIDATION DATAFRAME
# ============================================================

forward_df = pd.DataFrame({

    "regime":
        state["regime"],

    "future_return":
        future_return,

    "future_volatility":
        future_volatility
})


forward_valid = (

    forward_df

    .dropna(
        subset=[
            "regime",
            "future_return",
            "future_volatility"
        ]
    )

    .copy()
)


forward_valid[
    "regime"
] = (

    forward_valid[
        "regime"
    ]

    .astype(int)
)


# ============================================================
# 6. FORWARD-DATA SANITY CHECK
# ============================================================

print("\n" + "=" * 72)

print(
    "FORWARD-VALIDATION DATA CHECK"
)

print("=" * 72)


print(
    f"\nState observations       : "
    f"{len(state):,}"
)

print(
    f"Complete forward windows : "
    f"{len(forward_valid):,}"
)

print(
    f"Forward horizon          : "
    f"{FORWARD_HORIZON} trading days"
)


if len(forward_valid) == 0:

    raise RuntimeError(
        "Forward-validation sample is empty. "
        "Check SPY/state date alignment."
    )


forward_counts = (

    forward_valid[
        "regime"
    ]

    .value_counts()

    .sort_index()
)


print(
    "\nComplete forward observations by regime:"
)


print(
    forward_counts
)


missing_forward_regimes = (

    set(
        range(K)
    )

    -

    set(
        forward_valid[
            "regime"
        ].unique()
    )
)


if missing_forward_regimes:

    print(
        "\nWARNING:"
    )

    print(
        "No complete forward observations exist for regimes:",
        sorted(
            missing_forward_regimes
        )
    )


# ============================================================
# 7. CONDITIONAL FORWARD BEHAVIOR
# ============================================================

conditional_forward = (

    forward_valid

    .groupby(
        "regime"
    )

    .agg(

        n=(
            "future_return",
            "size"
        ),

        mean_forward_return=(
            "future_return",
            "mean"
        ),

        median_forward_return=(
            "future_return",
            "median"
        ),

        std_forward_return=(
            "future_return",
            "std"
        ),

        mean_forward_volatility=(
            "future_volatility",
            "mean"
        ),

        median_forward_volatility=(
            "future_volatility",
            "median"
        )
    )

    .reindex(
        range(K)
    )
)


# ------------------------------------------------------------
# Descriptive annualization
# ------------------------------------------------------------

conditional_forward[
    "annualized_forward_return_approx"
] = (

    conditional_forward[
        "mean_forward_return"
    ]

    *
    (
        252
        /
        FORWARD_HORIZON
    )
)


print("\n" + "=" * 72)

print(
    f"CONDITIONAL FORWARD BEHAVIOR — "
    f"{FORWARD_HORIZON} DAYS"
)

print("=" * 72)


display(
    conditional_forward.round(4)
)


# ============================================================
# 8. CROSS-REGIME ECONOMIC SEPARATION
# ============================================================
#
# These are descriptive separation measures.
#
# We are NOT claiming causality or forecasting power.
# ============================================================

valid_forward_summary = (

    conditional_forward

    .dropna(
        subset=[
            "mean_forward_return",
            "mean_forward_volatility"
        ]
    )
)


if len(
    valid_forward_summary
) > 1:

    forward_return_range = float(

        valid_forward_summary[
            "mean_forward_return"
        ].max()

        -

        valid_forward_summary[
            "mean_forward_return"
        ].min()
    )


    forward_vol_range = float(

        valid_forward_summary[
            "mean_forward_volatility"
        ].max()

        -

        valid_forward_summary[
            "mean_forward_volatility"
        ].min()
    )


else:

    forward_return_range = np.nan

    forward_vol_range = np.nan


print("\n" + "=" * 72)

print(
    "CROSS-REGIME ECONOMIC SEPARATION"
)

print("=" * 72)


print(
    f"\nMean forward-return range     : "
    f"{forward_return_range:.4f}"
)


print(
    f"Mean forward-volatility range : "
    f"{forward_vol_range:.4f}"
)


# ============================================================
# 9. BASELINE REPRESENTATION FOR ROBUSTNESS
# ============================================================
#
# Reconstruct the PCA + GMM component of Cell 7.
#
# This becomes the baseline partition against which slightly
# perturbed versions of the feature matrix are compared.
# ============================================================

N_CLUSTER_PCS = min(
    4,
    X.shape[1],
    len(X)
)


base_pca = PCA(
    n_components=N_CLUSTER_PCS
)


base_Z = (

    base_pca

    .fit_transform(
        X.values
    )
)


base_gmm = GaussianMixture(

    n_components=K,

    covariance_type="full",

    reg_covar=1e-5,

    n_init=10,

    max_iter=750,

    random_state=SEED
)


base_labels = (

    base_gmm

    .fit_predict(
        base_Z
    )
)


# ============================================================
# 10. PERTURBATION STABILITY
# ============================================================
#
# A scientifically useful latent-state architecture should not
# collapse when the standardized market features are perturbed
# slightly.
#
# For each experiment:
#
#   X* = X + epsilon
#
# where epsilon is small Gaussian noise.
#
# We then refit:
#
#   PCA -> GMM
#
# and compare the resulting partition with the baseline using
# Adjusted Rand Index.
#
# ARI is permutation invariant, which is essential because
# cluster labels themselves are arbitrary.
# ============================================================

N_PERTURBATIONS = 20

PERTURBATION_SCALE = 0.05


rng = np.random.default_rng(
    SEED
)


ari_scores = []


for run in range(
    N_PERTURBATIONS
):

    noise = rng.normal(

        loc=0.0,

        scale=PERTURBATION_SCALE,

        size=X.shape
    )


    X_perturbed = (
        X.values
        +
        noise
    )


    pca_perturbed = PCA(
        n_components=N_CLUSTER_PCS
    )


    Z_perturbed = (

        pca_perturbed

        .fit_transform(
            X_perturbed
        )
    )


    gmm_perturbed = GaussianMixture(

        n_components=K,

        covariance_type="full",

        reg_covar=1e-5,

        n_init=5,

        max_iter=500,

        random_state=(
            SEED
            +
            run
            +
            1
        )
    )


    labels_perturbed = (

        gmm_perturbed

        .fit_predict(
            Z_perturbed
        )
    )


    ari = adjusted_rand_score(

        base_labels,

        labels_perturbed
    )


    ari_scores.append(
        float(ari)
    )


ari_scores = np.asarray(
    ari_scores,
    dtype=float
)


perturbation_report = pd.DataFrame({

    "run":
        np.arange(
            1,
            N_PERTURBATIONS + 1
        ),

    "ARI":
        ari_scores
})


print("\n" + "=" * 72)

print(
    "PERTURBATION STABILITY"
)

print("=" * 72)


print(
    f"\nNoise scale      : "
    f"{PERTURBATION_SCALE}"
)

print(
    f"Perturbations    : "
    f"{N_PERTURBATIONS}"
)

print(
    f"Mean ARI         : "
    f"{ari_scores.mean():.3f}"
)

print(
    f"Median ARI       : "
    f"{np.median(ari_scores):.3f}"
)

print(
    f"Minimum ARI      : "
    f"{ari_scores.min():.3f}"
)

print(
    f"Maximum ARI      : "
    f"{ari_scores.max():.3f}"
)


# ============================================================
# 11. PERTURBATION DISTRIBUTION
# ============================================================

plt.figure(
    figsize=(9, 5)
)


plt.hist(

    ari_scores,

    bins=min(
        10,
        N_PERTURBATIONS
    )
)


plt.xlabel(
    "Adjusted Rand Index"
)

plt.ylabel(
    "Frequency"
)

plt.title(
    "Latent-State Stability Under Small Feature Perturbations"
)

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 12. TRANSITION-INTENSITY VALIDATION
# ============================================================
#
# Cell 8 defined transition intensity independently of the
# regime labels.
#
# We test whether realized consensus regime changes occur
# during periods of greater observable state-space movement.
# ============================================================

switch_mask = (

    state[
        "regime_switch"
    ]

    .fillna(False)

    .astype(bool)
)


switch_intensity = (

    state.loc[
        switch_mask,
        "transition_intensity"
    ]

    .dropna()
)


quiet_intensity = (

    state.loc[
        ~switch_mask,
        "transition_intensity"
    ]

    .dropna()
)


if (
    len(switch_intensity) > 0
    and
    len(quiet_intensity) > 0
):

    switch_intensity_mean = float(
        switch_intensity.mean()
    )


    quiet_intensity_mean = float(
        quiet_intensity.mean()
    )


    transition_intensity_ratio = (

        switch_intensity_mean

        /

        (
            quiet_intensity_mean
            +
            1e-12
        )
    )


else:

    switch_intensity_mean = np.nan

    quiet_intensity_mean = np.nan

    transition_intensity_ratio = np.nan


transition_validation = pd.DataFrame({

    "sample": [
        "Regime switch",
        "No regime switch"
    ],

    "observations": [
        len(switch_intensity),
        len(quiet_intensity)
    ],

    "mean_intensity": [
        switch_intensity_mean,
        quiet_intensity_mean
    ],

    "median_intensity": [

        (
            float(
                switch_intensity.median()
            )
            if len(switch_intensity)
            else np.nan
        ),

        (
            float(
                quiet_intensity.median()
            )
            if len(quiet_intensity)
            else np.nan
        )
    ]
})


print("\n" + "=" * 72)

print(
    "TRANSITION-INTENSITY VALIDATION"
)

print("=" * 72)


display(
    transition_validation.round(4)
)


print(
    f"\nSwitch / quiet intensity ratio: "
    f"{transition_intensity_ratio:.3f}"
)


# ============================================================
# 13. MODEL-DISAGREEMENT VALIDATION
# ============================================================
#
# Transition pressure and disagreement are distinct:
#
# transition intensity:
#     movement in observable market feature space
#
# disagreement:
#     uncertainty across latent-state estimators
#
# We test whether model disagreement rises on regime-switch
# observations.
# ============================================================

switch_disagreement = (

    state.loc[
        switch_mask,
        "disagreement"
    ]

    .dropna()
)


quiet_disagreement = (

    state.loc[
        ~switch_mask,
        "disagreement"
    ]

    .dropna()
)


if (
    len(switch_disagreement) > 0
    and
    len(quiet_disagreement) > 0
):

    switch_disagreement_mean = float(
        switch_disagreement.mean()
    )


    quiet_disagreement_mean = float(
        quiet_disagreement.mean()
    )


    disagreement_ratio = (

        switch_disagreement_mean

        /

        (
            quiet_disagreement_mean
            +
            1e-12
        )
    )


else:

    switch_disagreement_mean = np.nan

    quiet_disagreement_mean = np.nan

    disagreement_ratio = np.nan


disagreement_validation = pd.DataFrame({

    "sample": [
        "Regime switch",
        "No regime switch"
    ],

    "observations": [
        len(switch_disagreement),
        len(quiet_disagreement)
    ],

    "mean_disagreement": [
        switch_disagreement_mean,
        quiet_disagreement_mean
    ],

    "median_disagreement": [

        (
            float(
                switch_disagreement.median()
            )
            if len(switch_disagreement)
            else np.nan
        ),

        (
            float(
                quiet_disagreement.median()
            )
            if len(quiet_disagreement)
            else np.nan
        )
    ]
})


print("\n" + "=" * 72)

print(
    "MODEL-DISAGREEMENT VALIDATION"
)

print("=" * 72)


display(
    disagreement_validation.round(4)
)


print(
    f"\nSwitch / quiet disagreement ratio: "
    f"{disagreement_ratio:.3f}"
)


# ============================================================
# 14. SWARM SIGNATURE
# ============================================================
#
# We now validate the scientific swarm itself.
#
# Does the collective scientific picture stabilize as the
# number of agents increases?
#
# We examine:
#
#   A. preferred latent-state count distribution
#   B. mathematical vocabulary
# ============================================================

def swarm_signature(
    proposal_subset,
    vocabulary_size=20
):

    # --------------------------------------------------------
    # Preferred state-count distribution
    # --------------------------------------------------------

    state_counts = Counter(

        int(
            p["state_count"]
        )

        for p in proposal_subset
    )


    state_distribution = np.array([

        state_counts.get(
            k,
            0
        )

        for k in range(
            2,
            9
        )

    ], dtype=float)


    if state_distribution.sum() > 0:

        state_distribution = (

            state_distribution

            /
            state_distribution.sum()
        )


    # --------------------------------------------------------
    # Mathematical vocabulary
    # --------------------------------------------------------

    vocabulary = Counter()


    for p in proposal_subset:

        for phrase in p[
            "mathematical_core"
        ]:

            words = re.findall(

                r"[A-Za-z][A-Za-z\-]+",

                str(
                    phrase
                ).lower()
            )


            for word in words:

                if len(word) > 4:

                    vocabulary[
                        word
                    ] += 1


    top_vocabulary = {

        word

        for word, _

        in vocabulary.most_common(
            vocabulary_size
        )
    }


    return {

        "state_distribution":
            state_distribution,

        "top_vocabulary":
            top_vocabulary
    }


# ============================================================
# 15. FULL-SWARM REFERENCE SIGNATURE
# ============================================================

full_signature = swarm_signature(
    proposals
)


full_state_distribution = (

    full_signature[
        "state_distribution"
    ]
)


full_vocabulary = (

    full_signature[
        "top_vocabulary"
    ]
)


# ============================================================
# 16. PREFIX CONVERGENCE
# ============================================================
#
# Evaluate the collective scientific signature after:
#
#     5
#     10
#     20
#     30
#     40
#     50
#
# agents.
#
# State-count convergence:
#
#     L1 distance from final 50-agent distribution.
#
# Vocabulary convergence:
#
#     Jaccard similarity with final top vocabulary.
# ============================================================

prefix_sizes = [
    5,
    10,
    20,
    30,
    40,
    50
]


convergence_rows = []


for n_agents in prefix_sizes:

    signature_n = swarm_signature(

        proposals[
            :n_agents
        ]
    )


    state_dist_n = (

        signature_n[
            "state_distribution"
        ]
    )


    vocabulary_n = (

        signature_n[
            "top_vocabulary"
        ]
    )


    # --------------------------------------------------------
    # State-count L1 distance
    # --------------------------------------------------------

    state_l1_distance = float(

        np.abs(

            state_dist_n

            -

            full_state_distribution

        ).sum()
    )


    # --------------------------------------------------------
    # Vocabulary Jaccard similarity
    # --------------------------------------------------------

    vocabulary_union = (

        vocabulary_n

        |

        full_vocabulary
    )


    vocabulary_intersection = (

        vocabulary_n

        &

        full_vocabulary
    )


    if len(
        vocabulary_union
    ) > 0:

        vocabulary_jaccard = float(

            len(
                vocabulary_intersection
            )

            /

            len(
                vocabulary_union
            )
        )


    else:

        vocabulary_jaccard = np.nan


    convergence_rows.append({

        "agents":
            n_agents,

        "state_count_L1_distance":
            state_l1_distance,

        "vocabulary_Jaccard":
            vocabulary_jaccard
    })


swarm_convergence = pd.DataFrame(
    convergence_rows
)


print("\n" + "=" * 72)

print(
    "SWARM CONVERGENCE"
)

print("=" * 72)


display(
    swarm_convergence.round(4)
)


# ============================================================
# 17. STATE-COUNT CONVERGENCE PLOT
# ============================================================

plt.figure(
    figsize=(9, 5)
)


plt.plot(

    swarm_convergence[
        "agents"
    ],

    swarm_convergence[
        "state_count_L1_distance"
    ],

    marker="o"
)


plt.xlabel(
    "Number of scientific agents"
)

plt.ylabel(
    "L1 distance from full-swarm distribution"
)

plt.title(
    "Swarm Convergence — Preferred Number of Latent States"
)

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 18. VOCABULARY CONVERGENCE PLOT
# ============================================================

plt.figure(
    figsize=(9, 5)
)


plt.plot(

    swarm_convergence[
        "agents"
    ],

    swarm_convergence[
        "vocabulary_Jaccard"
    ],

    marker="o"
)


plt.xlabel(
    "Number of scientific agents"
)

plt.ylabel(
    "Jaccard similarity with full-swarm vocabulary"
)

plt.title(
    "Swarm Convergence — Mathematical Vocabulary"
)

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 19. CORE LATENT-STATE METRICS
# ============================================================

if "gmm_silhouette" in globals():

    final_gmm_silhouette = float(
        gmm_silhouette
    )


else:

    final_gmm_silhouette = np.nan


if "consensus_persistence" in globals():

    final_consensus_persistence = float(
        consensus_persistence
    )


else:

    regime_values = (

        state[
            "regime"
        ]

        .dropna()

        .astype(int)

        .values
    )


    if len(regime_values) > 1:

        final_consensus_persistence = float(

            np.mean(

                regime_values[1:]

                ==

                regime_values[:-1]
            )
        )


    else:

        final_consensus_persistence = np.nan


final_mean_disagreement = float(

    state[
        "disagreement"
    ].mean()
)


# ============================================================
# 20. VALIDATION REPORT
# ============================================================
#
# We deliberately DO NOT collapse all metrics into one
# arbitrary "validation score."
#
# Each statistic answers a different scientific question.
# ============================================================

validation_report = {

    "architecture":
        synthesis[
            "architecture_name"
        ],

    "target_regimes":
        int(K),

    "number_of_observations":
        int(
            len(state)
        ),

    "number_of_agents":
        int(
            len(proposals)
        ),

    "forward_horizon_days":
        int(
            FORWARD_HORIZON
        ),

    "complete_forward_windows":
        int(
            len(forward_valid)
        ),

    "gmm_silhouette":
        (
            float(
                final_gmm_silhouette
            )

            if np.isfinite(
                final_gmm_silhouette
            )

            else None
        ),

    "consensus_persistence":
        (
            float(
                final_consensus_persistence
            )

            if np.isfinite(
                final_consensus_persistence
            )

            else None
        ),

    "perturbation_ARI_mean":
        float(
            ari_scores.mean()
        ),

    "perturbation_ARI_median":
        float(
            np.median(
                ari_scores
            )
        ),

    "perturbation_ARI_min":
        float(
            ari_scores.min()
        ),

    "perturbation_ARI_max":
        float(
            ari_scores.max()
        ),

    "transition_intensity_switch_ratio":
        (
            float(
                transition_intensity_ratio
            )

            if np.isfinite(
                transition_intensity_ratio
            )

            else None
        ),

    "mean_model_disagreement":
        float(
            final_mean_disagreement
        ),

    "switch_disagreement_ratio":
        (
            float(
                disagreement_ratio
            )

            if np.isfinite(
                disagreement_ratio
            )

            else None
        ),

    "cross_regime_forward_return_range":
        (
            float(
                forward_return_range
            )

            if np.isfinite(
                forward_return_range
            )

            else None
        ),

    "cross_regime_forward_volatility_range":
        (
            float(
                forward_vol_range
            )

            if np.isfinite(
                forward_vol_range
            )

            else None
        ),

    "status":
        "EDUCATIONAL RESEARCH — NOT INVESTMENT ADVICE"
}


# ============================================================
# 21. VALIDATION DASHBOARD
# ============================================================

dashboard_rows = [

    {
        "Metric":
            "Number of regimes",

        "Value":
            K
    },

    {
        "Metric":
            "Complete forward windows",

        "Value":
            len(forward_valid)
    },

    {
        "Metric":
            "GMM silhouette",

        "Value":
            final_gmm_silhouette
    },

    {
        "Metric":
            "Consensus persistence",

        "Value":
            final_consensus_persistence
    },

    {
        "Metric":
            "Perturbation ARI — mean",

        "Value":
            ari_scores.mean()
    },

    {
        "Metric":
            "Perturbation ARI — minimum",

        "Value":
            ari_scores.min()
    },

    {
        "Metric":
            "Transition-intensity switch ratio",

        "Value":
            transition_intensity_ratio
    },

    {
        "Metric":
            "Mean model disagreement",

        "Value":
            final_mean_disagreement
    },

    {
        "Metric":
            "Switch disagreement ratio",

        "Value":
            disagreement_ratio
    },

    {
        "Metric":
            "Cross-regime forward-return range",

        "Value":
            forward_return_range
    },

    {
        "Metric":
            "Cross-regime forward-volatility range",

        "Value":
            forward_vol_range
    },

    {
        "Metric":
            "Scientific agents",

        "Value":
            len(proposals)
    }
]


validation_dashboard = pd.DataFrame(
    dashboard_rows
)


print("\n" + "=" * 72)

print(
    "VALIDATION DASHBOARD"
)

print("=" * 72)


display(
    validation_dashboard.round(4)
)


# ============================================================
# 22. VALIDATED MARKET-REGIME OBSERVATORY
# ============================================================

plt.figure(
    figsize=(15, 6)
)


for k in range(K):

    mask = (
        state[
            "regime"
        ]

        ==

        k
    )


    plt.scatter(

        state.index[
            mask
        ],

        spy.reindex(
            state.index[
                mask
            ]
        ),

        s=8,

        label=f"Regime {k}"
    )


plt.yscale(
    "log"
)


plt.xlabel(
    "Date"
)

plt.ylabel(
    "SPY — log scale"
)

plt.title(
    "Validated Consensus Market-Regime Observatory"
)

plt.legend(
    ncol=min(
        K,
        4
    )
)

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 23. TRANSITION-PRESSURE OBSERVATORY
# ============================================================

plt.figure(
    figsize=(15, 5)
)


plt.plot(

    state.index,

    state[
        "transition_z"
    ],

    label="Transition pressure"
)


plt.axhline(

    2.0,

    linestyle="--",

    linewidth=1.0,

    label="High-pressure threshold"
)


plt.axhline(

    0.0,

    linewidth=0.8
)


plt.xlabel(
    "Date"
)

plt.ylabel(
    "Transition-pressure z-score"
)

plt.title(
    "Observable Market State-Space Transition Pressure"
)

plt.legend()

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 24. MODEL-DISAGREEMENT OBSERVATORY
# ============================================================

plt.figure(
    figsize=(15, 4)
)


plt.plot(

    state.index,

    state[
        "disagreement"
    ]
)


plt.xlabel(
    "Date"
)

plt.ylabel(
    "Model disagreement"
)

plt.title(
    "Epistemic Uncertainty Across Latent-State Models"
)

plt.grid(
    alpha=0.2
)

plt.show()


# ============================================================
# 25. SAVE VALIDATION OUTPUTS
# ============================================================

conditional_forward.to_csv(

    OUT /
    "conditional_forward_behavior.csv"
)


forward_valid.to_csv(

    OUT /
    "forward_validation_sample.csv"
)


perturbation_report.to_csv(

    OUT /
    "perturbation_stability.csv",

    index=False
)


transition_validation.to_csv(

    OUT /
    "transition_validation_cell9.csv",

    index=False
)


disagreement_validation.to_csv(

    OUT /
    "disagreement_validation_cell9.csv",

    index=False
)


swarm_convergence.to_csv(

    OUT /
    "swarm_convergence.csv",

    index=False
)


validation_dashboard.to_csv(

    OUT /
    "validation_dashboard.csv",

    index=False
)


validation_path = (

    OUT /
    "validation_report.json"
)


validation_path.write_text(

    json.dumps(
        validation_report,
        indent=2
    ),

    encoding="utf-8"
)


# ============================================================
# 26. FINAL CELL 9 REPORT
# ============================================================

print("\n" + "=" * 72)

print(
    "CELL 9 COMPLETE — VALIDATION LAYER FINISHED"
)

print("=" * 72)


print(
    f"\nLatent regimes                  : "
    f"{K}"
)

print(
    f"Complete forward windows        : "
    f"{len(forward_valid):,}"
)


if np.isfinite(
    final_gmm_silhouette
):

    print(
        f"GMM silhouette                  : "
        f"{final_gmm_silhouette:.3f}"
    )


if np.isfinite(
    final_consensus_persistence
):

    print(
        f"Consensus persistence           : "
        f"{final_consensus_persistence:.3f}"
    )


print(
    f"Perturbation ARI — mean         : "
    f"{ari_scores.mean():.3f}"
)

print(
    f"Perturbation ARI — minimum      : "
    f"{ari_scores.min():.3f}"
)


if np.isfinite(
    transition_intensity_ratio
):

    print(
        f"Transition-intensity ratio      : "
        f"{transition_intensity_ratio:.3f}"
    )


print(
    f"Mean model disagreement         : "
    f"{final_mean_disagreement:.3f}"
)


if np.isfinite(
    disagreement_ratio
):

    print(
        f"Switch disagreement ratio       : "
        f"{disagreement_ratio:.3f}"
    )


if np.isfinite(
    forward_return_range
):

    print(
        f"Forward-return regime range     : "
        f"{forward_return_range:.4f}"
    )


if np.isfinite(
    forward_vol_range
):

    print(
        f"Forward-volatility regime range : "
        f"{forward_vol_range:.4f}"
    )


print(
    f"Forward horizon                 : "
    f"{FORWARD_HORIZON} trading days"
)

print(
    f"Scientific agents               : "
    f"{len(proposals)}"
)


print("\n" + "-" * 72)

print(
    "SCIENTIFIC INTERPRETATION"
)

print("-" * 72)


print(
    "\nThe latent-state architecture has now been examined "
    "along several independent dimensions."
)


print(
    "\nFirst, conditional forward behavior tests whether states "
    "identified at time t correspond to distinguishable market "
    "behavior during the following 21 trading days."
)


print(
    "\nSecond, perturbation analysis tests whether small changes "
    "in the observed feature matrix materially alter the "
    "latent-state partition."
)


print(
    "\nThird, transition-intensity analysis tests whether regime "
    "changes coincide with stronger movement through observable "
    "market state space."
)


print(
    "\nFourth, model disagreement measures epistemic uncertainty "
    "across alternative latent-state estimators."
)


print(
    "\nFinally, swarm-convergence analysis asks whether the "
    "scientific conclusions stabilize as the number of "
    "independent disciplinary agents increases."
)


print(
    "\nNo single metric is treated as proof that the inferred "
    "regimes constitute a unique or true market ontology."
)


print(
    "The architecture is retained only to the extent that "
    "multiple independent tests support its robustness, "
    "interpretability and empirical usefulness."
)


print(
    "\nCell 10 can now consolidate the complete experiment, "
    "provenance, outputs and final research conclusions."
)


print("\n" + "=" * 72)

print(
    "READY FOR CELL 10"
)

print("=" * 72)

========================================================================
CELL 9 — VALIDATION, ROBUSTNESS & SWARM CONVERGENCE
========================================================================

Observations       : 3,641
Latent regimes     : 4
Scientific agents  : 50
Architecture       : Metastable Basin-Transition Architecture (MBTA)

========================================================================
FORWARD-VALIDATION DATA CHECK
========================================================================

State observations       : 3,641
Complete forward windows : 3,620
Forward horizon          : 21 trading days

Complete forward observations by regime:
regime
0     877
1    1669
2     829
3     245
Name: count, dtype: int64

========================================================================
CONDITIONAL FORWARD BEHAVIOR — 21 DAYS
========================================================================

,n,mean_forward_return,median_forward_return,std_forward_return,mean_forward_volatility,median_forward_volatility,annualized_forward_return_approx
regime,,,,,,,
0,877,0.0145,0.0277,0.0514,0.1794,0.1624,0.1736
1,1669,0.0053,0.0121,0.0370,0.1157,0.1054,0.0639
2,829,0.0132,0.0175,0.0311,0.1175,0.1042,0.1583
3,245,0.0350,0.0475,0.0630,0.2645,0.2572,0.4203

========================================================================
CROSS-REGIME ECONOMIC SEPARATION
========================================================================

Mean forward-return range     : 0.0297
Mean forward-volatility range : 0.1487

========================================================================
PERTURBATION STABILITY
========================================================================

Noise scale      : 0.05
Perturbations    : 20
Mean ARI         : 0.870
Median ARI       : 0.949
Minimum ARI      : 0.402
Maximum ARI      : 0.965

========================================================================
TRANSITION-INTENSITY VALIDATION
========================================================================

             sample  observations  mean_intensity  median_intensity
0     Regime switch           461          0.2522            0.2474
1  No regime switch          3177          0.2392            0.2209

Switch / quiet intensity ratio: 1.054

========================================================================
MODEL-DISAGREEMENT VALIDATION
========================================================================

             sample  observations  mean_disagreement  median_disagreement
0     Regime switch           461             0.2697               0.3333
1  No regime switch          3180             0.1259               0.0000

Switch / quiet disagreement ratio: 2.141

========================================================================
SWARM CONVERGENCE
========================================================================

   agents  state_count_L1_distance  vocabulary_Jaccard
0       5                     1.00              0.3333
1      10                     0.60              0.3793
2      20                     0.20              0.6000
3      30                     0.20              0.4815
4      40                     0.11              0.7391
5      50                     0.00              1.0000

========================================================================
VALIDATION DASHBOARD
========================================================================

                                   Metric      Value
0                       Number of regimes     4.0000
1                Complete forward windows  3620.0000
2                          GMM silhouette     0.1758
3                   Consensus persistence     0.8734
4                 Perturbation ARI — mean     0.8697
5              Perturbation ARI — minimum     0.4021
6       Transition-intensity switch ratio     1.0542
7                 Mean model disagreement     0.1441
8               Switch disagreement ratio     2.1415
9       Cross-regime forward-return range     0.0297
10  Cross-regime forward-volatility range     0.1487
11                      Scientific agents    50.0000

========================================================================
CELL 9 COMPLETE — VALIDATION LAYER FINISHED
========================================================================

Latent regimes                  : 4
Complete forward windows        : 3,620
GMM silhouette                  : 0.176
Consensus persistence           : 0.873
Perturbation ARI — mean         : 0.870
Perturbation ARI — minimum      : 0.402
Transition-intensity ratio      : 1.054
Mean model disagreement         : 0.144
Switch disagreement ratio       : 2.141
Forward-return regime range     : 0.0297
Forward-volatility regime range : 0.1487
Forward horizon                 : 21 trading days
Scientific agents               : 50

------------------------------------------------------------------------
SCIENTIFIC INTERPRETATION
------------------------------------------------------------------------

The latent-state architecture has now been examined along several independent dimensions.

First, conditional forward behavior tests whether states identified at time t correspond to distinguishable market behavior during the following 21 trading days.

Second, perturbation analysis tests whether small changes in the observed feature matrix materially alter the latent-state partition.

Third, transition-intensity analysis tests whether regime changes coincide with stronger movement through observable market state space.

Fourth, model disagreement measures epistemic uncertainty across alternative latent-state estimators.

Finally, swarm-convergence analysis asks whether the scientific conclusions stabilize as the number of independent disciplinary agents increases.

No single metric is treated as proof that the inferred regimes constitute a unique or true market ontology.
The architecture is retained only to the extent that multiple independent tests support its robustness, interpretability and empirical usefulness.

Cell 10 can now consolidate the complete experiment, provenance, outputs and final research conclusions.

========================================================================
READY FOR CELL 10
========================================================================

### CODE UNIT 10 — Provenance export, research report and conclusion

CODE UNIT 10 closes the research loop by exporting a board-level scientific report, a machine-readable research package and the full provenance trail. The report does not convert exploratory evidence into a claim of profitable predictability. Instead, it records the swarm architecture, the empirical state profiles, validation diagnostics, transition matrix, convergence evidence and the limitations that should govern interpretation.

The cell also creates a current-state snapshot. This is the operational form of the Market Regime Observatory: latest consensus state, model disagreement, transition pressure and the most distinctive standardized features. The snapshot is descriptive. A downstream portfolio system could eventually consume it, but this notebook intentionally stops before converting the state estimate into a trading rule. That separation avoids contaminating regime discovery with strategy optimization.

All major artifacts are written to a single output directory and compressed into a ZIP file: run manifest, fifty agent proposals, synthesis, proposal summary, feature profiles, transition matrix, validation report, convergence diagnostics, state history and final report. This makes the experiment portable and auditable.

The conclusion embedded below emphasizes the main intellectual result: the swarm is a mechanism for systematic scientific transfer. Its purpose is not to replace HMMs with a fashionable metaphor. It is to search across mature mathematical traditions for structures that can be stated precisely, implemented reproducibly and rejected when the data do not support them. The most promising future extension is a hierarchical observatory in which slow macro states, medium-horizon market phases and fast liquidity events coexist rather than being forced into one categorical label.

In [ ]:
# ============================================================
# CODE CELL 10
# FINAL SYNTHESIS, PROVENANCE & RESEARCH EXPORT
#
# 50-AGENT CROSS-SCIENCE MARKET REGIME SWARM
#
# PURPOSE
# ------------------------------------------------------------
# This is the capstone cell.
#
# Cells 1–9 performed the experiment:
#
#   Cell 1 — Environment and market data
#   Cell 2 — Feature engineering
#   Cell 3 — 50-agent scientific swarm
#   Cell 4 — Claude Sonnet 5 interface
#   Cell 5 — Full swarm execution
#   Cell 6 — Cross-science synthesis
#   Cell 7 — Latent-state inference
#   Cell 8 — Regime characterization and transitions
#   Cell 9 — Validation, robustness and convergence
#
# Cell 10 DOES NOT estimate a new model.
#
# It consolidates:
#
#   1. Scientific architecture
#   2. Swarm provenance
#   3. Empirical regime structure
#   4. Transition dynamics
#   5. Validation evidence
#   6. Swarm convergence
#   7. Falsification criteria
#   8. Research conclusions
#   9. Machine-readable provenance
#  10. Complete export package
#
# IMPORTANT
# ------------------------------------------------------------
# All numerical conclusions in this cell are taken from the
# ACTUAL outputs generated by the preceding cells.
#
# No illustrative performance numbers are introduced here.
#
# EDUCATIONAL RESEARCH — NOT INVESTMENT ADVICE
# ============================================================


# ============================================================
# 0. IMPORTS
# ============================================================

import json
import shutil
import platform

from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 1. PRECONDITIONS
# ============================================================

required_objects = [

    "state",
    "X",
    "px",
    "K",
    "proposals",
    "synthesis",
    "validation_report",
    "conditional_forward",
    "swarm_convergence",
    "transition_matrix",
    "dwell_summary",
    "feature_profiles"
]


missing_objects = [

    obj

    for obj in required_objects

    if obj not in globals()
]


if missing_objects:

    raise RuntimeError(

        "Cell 10 requires the completed outputs of Cells 1–9. "
        f"Missing objects: {missing_objects}"
    )


if len(proposals) != 50:

    raise RuntimeError(

        "Final synthesis requires all 50 scientific agents. "
        f"Currently available: {len(proposals)}."
    )


print("=" * 78)

print(
    "CELL 10 — FINAL SYNTHESIS, PROVENANCE & RESEARCH EXPORT"
)

print("=" * 78)


print(
    f"\nArchitecture      : "
    f"{synthesis['architecture_name']}"
)

print(
    f"Latent regimes    : "
    f"{K}"
)

print(
    f"Observations      : "
    f"{len(state):,}"
)

print(
    f"Scientific agents : "
    f"{len(proposals)}"
)


# ============================================================
# 2. SAFE SERIALIZATION UTILITIES
# ============================================================
#
# NumPy and pandas objects are not always directly JSON
# serializable.
#
# This function converts the objects created by the notebook
# into portable Python types.
# ============================================================

def json_safe(value):

    if isinstance(
        value,
        dict
    ):

        return {

            str(k):
                json_safe(v)

            for k, v in value.items()
        }


    if isinstance(
        value,
        (list, tuple, set)
    ):

        return [

            json_safe(v)

            for v in value
        ]


    if isinstance(
        value,
        np.ndarray
    ):

        return value.tolist()


    if isinstance(
        value,
        (
            np.integer,
        )
    ):

        return int(value)


    if isinstance(
        value,
        (
            np.floating,
        )
    ):

        if np.isnan(value):

            return None

        if np.isinf(value):

            return None

        return float(value)


    if isinstance(
        value,
        (
            np.bool_,
        )
    ):

        return bool(value)


    if isinstance(
        value,
        (
            pd.Timestamp,
            datetime
        )
    ):

        return value.isoformat()


    if pd.isna(value):

        return None


    return value


# ============================================================
# 3. SAFE METRIC ACCESSOR
# ============================================================

def metric(
    name,
    default=None
):

    value = validation_report.get(
        name,
        default
    )

    if value is None:

        return default

    return value


# ============================================================
# 4. EXPERIMENT IDENTITY
# ============================================================

experiment_timestamp = (
    datetime.now(
        timezone.utc
    )
    .isoformat()
)


experiment_id = (

    "cross_science_market_regime_swarm_"
    +
    datetime.now(
        timezone.utc
    ).strftime(
        "%Y%m%dT%H%M%SZ"
    )
)


experiment_identity = {

    "experiment_id":
        experiment_id,

    "timestamp_utc":
        experiment_timestamp,

    "title":
        "50-Agent Cross-Science Market Regime Swarm",

    "objective":
        (
            "Infer and validate latent market regimes by "
            "transferring mathematical ideas from multiple "
            "scientific disciplines into a common empirical "
            "market-state architecture."
        ),

    "model":
        MODEL
        if "MODEL" in globals()
        else None,

    "effort":
        EFFORT
        if "EFFORT" in globals()
        else None,

    "seed":
        SEED
        if "SEED" in globals()
        else None,

    "agents":
        len(proposals),

    "latent_regimes":
        int(K),

    "observations":
        int(len(state)),

    "features":
        int(X.shape[1]),

    "sample_start":
        str(
            state.index.min().date()
        ),

    "sample_end":
        str(
            state.index.max().date()
        ),

    "status":
        "EDUCATIONAL RESEARCH — NOT INVESTMENT ADVICE"
}


# ============================================================
# 5. SCIENTIFIC ARCHITECTURE
# ============================================================

architecture_summary = {

    "architecture_name":
        synthesis[
            "architecture_name"
        ],

    "target_states":
        int(
            synthesis[
                "target_states"
            ]
        ),

    "representation_layer":
        synthesis[
            "representation_layer"
        ],

    "state_inference_layer":
        synthesis[
            "state_inference_layer"
        ],

    "transition_layer":
        synthesis[
            "transition_layer"
        ],

    "uncertainty_layer":
        synthesis[
            "uncertainty_layer"
        ],

    "empirical_components":
        synthesis[
            "empirical_components"
        ],

    "core_motifs":
        synthesis[
            "core_motifs"
        ],

    "minority_ideas_to_preserve":
        synthesis[
            "minority_ideas_to_preserve"
        ],

    "falsification_criteria":
        synthesis[
            "falsification_criteria"
        ],

    "research_rationale":
        synthesis[
            "research_rationale"
        ]
}


print("\n" + "=" * 78)

print(
    "FINAL SCIENTIFIC ARCHITECTURE"
)

print("=" * 78)


print(
    f"\n{synthesis['architecture_name']}"
)


print(
    "\nRepresentation layer:"
)

print(
    synthesis[
        "representation_layer"
    ]
)


print(
    "\nState-inference layer:"
)

print(
    synthesis[
        "state_inference_layer"
    ]
)


print(
    "\nTransition layer:"
)

print(
    synthesis[
        "transition_layer"
    ]
)


print(
    "\nUncertainty layer:"
)

print(
    synthesis[
        "uncertainty_layer"
    ]
)


# ============================================================
# 6. CORE CROSS-SCIENCE MOTIFS
# ============================================================

print("\n" + "=" * 78)

print(
    "CORE CROSS-SCIENCE MOTIFS"
)

print("=" * 78)


for i, motif in enumerate(

    synthesis[
        "core_motifs"
    ],

    start=1
):

    print(
        f"\n{i}. {motif}"
    )


# ============================================================
# 7. MINORITY SCIENTIFIC IDEAS PRESERVED
# ============================================================

print("\n" + "=" * 78)

print(
    "MINORITY IDEAS PRESERVED BY THE SYNTHESIS"
)

print("=" * 78)


for i, idea in enumerate(

    synthesis[
        "minority_ideas_to_preserve"
    ],

    start=1
):

    print(
        f"\n{i}. {idea}"
    )


# ============================================================
# 8. EMPIRICAL REGIME SUMMARY
# ============================================================

regime_counts_final = (

    state[
        "regime"
    ]

    .value_counts()

    .reindex(
        range(K),
        fill_value=0
    )

    .sort_index()
)


regime_shares_final = (

    regime_counts_final

    /
    regime_counts_final.sum()
)


regime_empirical_summary = pd.DataFrame({

    "regime":
        range(K),

    "observations":
        regime_counts_final.values,

    "share":
        regime_shares_final.values
})


# ------------------------------------------------------------
# Add persistence
# ------------------------------------------------------------

regime_empirical_summary[
    "one_day_persistence"
] = [

    (
        float(
            transition_matrix.loc[
                k,
                k
            ]
        )

        if (
            k in transition_matrix.index
            and
            k in transition_matrix.columns
        )

        else np.nan
    )

    for k in range(K)
]


# ------------------------------------------------------------
# Add dwell-time statistics
# ------------------------------------------------------------

for column in [
    "episodes",
    "mean_days",
    "median_days",
    "max_days"
]:

    if column in dwell_summary.columns:

        regime_empirical_summary[
            column
        ] = [

            (
                dwell_summary.loc[
                    k,
                    column
                ]

                if k in dwell_summary.index

                else np.nan
            )

            for k in range(K)
        ]


# ------------------------------------------------------------
# Add forward behavior
# ------------------------------------------------------------

forward_columns = [

    "mean_forward_return",

    "median_forward_return",

    "mean_forward_volatility",

    "median_forward_volatility"
]


for column in forward_columns:

    if column in conditional_forward.columns:

        regime_empirical_summary[
            column
        ] = [

            (
                conditional_forward.loc[
                    k,
                    column
                ]

                if k in conditional_forward.index

                else np.nan
            )

            for k in range(K)
        ]


print("\n" + "=" * 78)

print(
    "EMPIRICAL REGIME SUMMARY"
)

print("=" * 78)


display(
    regime_empirical_summary.round(4)
)


# ============================================================
# 9. FEATURE PROFILES
# ============================================================

print("\n" + "=" * 78)

print(
    "MEDIAN OBSERVABLE FEATURE PROFILE BY REGIME"
)

print("=" * 78)


display(
    feature_profiles.round(3)
)


# ============================================================
# 10. TRANSITION MATRIX
# ============================================================

print("\n" + "=" * 78)

print(
    "EMPIRICAL REGIME TRANSITION MATRIX"
)

print("=" * 78)


display(
    transition_matrix.round(3)
)


# ============================================================
# 11. VALIDATION EVIDENCE
# ============================================================

validation_summary = pd.DataFrame({

    "metric": [

        "Latent regimes",

        "GMM silhouette",

        "Consensus persistence",

        "Perturbation ARI — mean",

        "Perturbation ARI — minimum",

        "Transition-intensity switch ratio",

        "Mean model disagreement",

        "Switch disagreement ratio",

        "Cross-regime forward-return range",

        "Cross-regime forward-volatility range",

        "Complete forward windows",

        "Scientific agents"
    ],

    "value": [

        K,

        metric(
            "gmm_silhouette"
        ),

        metric(
            "consensus_persistence"
        ),

        metric(
            "perturbation_ARI_mean"
        ),

        metric(
            "perturbation_ARI_min"
        ),

        metric(
            "transition_intensity_switch_ratio"
        ),

        metric(
            "mean_model_disagreement"
        ),

        metric(
            "switch_disagreement_ratio"
        ),

        metric(
            "cross_regime_forward_return_range"
        ),

        metric(
            "cross_regime_forward_volatility_range"
        ),

        metric(
            "complete_forward_windows"
        ),

        len(proposals)
    ]
})


print("\n" + "=" * 78)

print(
    "CONSOLIDATED VALIDATION EVIDENCE"
)

print("=" * 78)


display(
    validation_summary.round(4)
)


# ============================================================
# 12. SWARM CONVERGENCE
# ============================================================

print("\n" + "=" * 78)

print(
    "50-AGENT SWARM CONVERGENCE"
)

print("=" * 78)


display(
    swarm_convergence.round(4)
)


# ============================================================
# 13. FALSIFICATION CRITERIA
# ============================================================
#
# These criteria came from Cell 6.
#
# They are preserved explicitly because the architecture is a
# scientific hypothesis, not a claim of revealed truth.
# ============================================================

print("\n" + "=" * 78)

print(
    "FALSIFICATION CRITERIA"
)

print("=" * 78)


for i, criterion in enumerate(

    synthesis[
        "falsification_criteria"
    ],

    start=1
):

    print(
        f"\n{i}. {criterion}"
    )


# ============================================================
# 14. EMPIRICAL EVIDENCE FLAGS
# ============================================================
#
# These are descriptive flags.
#
# They are NOT combined into a score and are NOT interpreted
# as proof that the model is true.
#
# The thresholds simply make the final provenance record
# easier to audit.
# ============================================================

ari_mean = metric(
    "perturbation_ARI_mean"
)


transition_ratio = metric(
    "transition_intensity_switch_ratio"
)


consensus_persistence_final = metric(
    "consensus_persistence"
)


forward_return_range_final = metric(
    "cross_regime_forward_return_range"
)


forward_vol_range_final = metric(
    "cross_regime_forward_volatility_range"
)


evidence_flags = {

    "perturbation_structure_present":
        (
            ari_mean is not None
            and
            ari_mean > 0
        ),

    "transition_intensity_higher_on_switches":
        (
            transition_ratio is not None
            and
            transition_ratio > 1
        ),

    "consensus_has_temporal_persistence":
        (
            consensus_persistence_final is not None
            and
            consensus_persistence_final > 0.5
        ),

    "forward_return_differs_across_regimes":
        (
            forward_return_range_final is not None
            and
            abs(
                forward_return_range_final
            ) > 0
        ),

    "forward_volatility_differs_across_regimes":
        (
            forward_vol_range_final is not None
            and
            abs(
                forward_vol_range_final
            ) > 0
        )
}


evidence_flag_table = pd.DataFrame({

    "evidence_dimension":
        list(
            evidence_flags.keys()
        ),

    "observed":
        list(
            evidence_flags.values()
        )
})


print("\n" + "=" * 78)

print(
    "EMPIRICAL EVIDENCE FLAGS"
)

print("=" * 78)


display(
    evidence_flag_table
)


# ============================================================
# 15. RESEARCH CONCLUSIONS
# ============================================================
#
# Conclusions are generated deterministically from the actual
# notebook outputs.
#
# No new LLM call is needed.
# ============================================================

research_conclusions = []


research_conclusions.append(

    (
        f"The 50-agent cross-science swarm converged on an "
        f"empirical architecture initialized with {K} latent "
        f"market states. The final architecture combines "
        f"dimensionality reduction, multiple competing state "
        f"estimators, explicit transition measurement and "
        f"model-disagreement analysis."
    )
)


if (
    ari_mean is not None
):

    research_conclusions.append(

        (
            "Small perturbations of the standardized market "
            "features produced a mean Adjusted Rand Index of "
            f"{ari_mean:.3f}. This measures the stability of "
            "the PCA-GMM partition under the perturbation "
            "experiment implemented in Cell 9."
        )
    )


if (
    consensus_persistence_final
    is not None
):

    research_conclusions.append(

        (
            "The consensus latent-state sequence exhibited "
            "one-step persistence of "
            f"{consensus_persistence_final:.3f}. "
            "The inferred states therefore possess measurable "
            "temporal continuity rather than behaving as "
            "independent daily classifications."
        )
    )


if (
    transition_ratio
    is not None
):

    research_conclusions.append(

        (
            "The ratio of mean transition intensity on regime-"
            "switch observations to non-switch observations was "
            f"{transition_ratio:.3f}. This directly tests the "
            "cross-science hypothesis that discrete regime "
            "changes should be associated with stronger "
            "movement through observable market state space."
        )
    )


mean_disagreement_final = metric(
    "mean_model_disagreement"
)


if (
    mean_disagreement_final
    is not None
):

    research_conclusions.append(

        (
            "Mean disagreement across the competing latent-state "
            "estimators was "
            f"{mean_disagreement_final:.3f}. The experiment "
            "therefore preserves epistemic uncertainty rather "
            "than forcing every observation into an apparently "
            "certain classification."
        )
    )


if (
    forward_return_range_final
    is not None
    and
    forward_vol_range_final
    is not None
):

    research_conclusions.append(

        (
            "Across the inferred regimes, the range in mean "
            "21-day forward log returns was "
            f"{forward_return_range_final:.4f}, while the range "
            "in mean forward realized volatility was "
            f"{forward_vol_range_final:.4f}. These are "
            "descriptive measures of economic differentiation; "
            "they are not causal estimates or trading claims."
        )
    )


research_conclusions.append(

    (
        "The experiment does not establish that the inferred "
        "regimes constitute a unique or permanent ontology of "
        "financial markets. The state count, representation, "
        "clustering algorithms and transition measures remain "
        "research hypotheses subject to out-of-sample testing, "
        "alternative data, alternative state architectures and "
        "the explicit falsification criteria proposed by the "
        "swarm."
    )
)


print("\n" + "=" * 78)

print(
    "RESEARCH CONCLUSIONS"
)

print("=" * 78)


for i, conclusion in enumerate(

    research_conclusions,

    start=1
):

    print(
        f"\n{i}. {conclusion}"
    )


# ============================================================
# 16. RESEARCH LIMITATIONS
# ============================================================

research_limitations = [

    (
        "The experiment is observational. Differences across "
        "latent regimes do not establish causal relationships."
    ),

    (
        "The feature universe is intentionally compact and "
        "cannot represent every dimension of market structure."
    ),

    (
        "PCA, Gaussian mixtures, K-means and spectral "
        "clustering impose different geometric assumptions on "
        "the latent-state problem."
    ),

    (
        "The consensus architecture reduces model dependence "
        "but does not eliminate model risk."
    ),

    (
        "Spectral clustering is estimated only on the recent "
        "subsample defined in Cell 7, whereas GMM and K-means "
        "use the complete feature history."
    ),

    (
        "The 21-day conditional forward analysis is descriptive "
        "and overlapping forward windows create serial "
        "dependence across observations."
    ),

    (
        "Perturbation robustness demonstrates local stability "
        "to the specified noise experiment; it does not imply "
        "robustness to structural breaks or different feature "
        "universes."
    ),

    (
        "The scientific swarm is deliberately heterogeneous, "
        "but its synthesis remains constrained by the prompts, "
        "the selected disciplines and the empirical algorithms "
        "made available to the synthesis layer."
    )
]


print("\n" + "=" * 78)

print(
    "RESEARCH LIMITATIONS"
)

print("=" * 78)


for i, limitation in enumerate(

    research_limitations,

    start=1
):

    print(
        f"\n{i}. {limitation}"
    )


# ============================================================
# 17. NEXT RESEARCH FRONTIER
# ============================================================
#
# These extensions follow naturally from the architecture.
# They are not results of the present experiment.
# ============================================================

next_research_frontier = [

    (
        "Out-of-sample regime inference with an explicit "
        "training, validation and untouched test period."
    ),

    (
        "Hierarchical latent states in which slow macro regimes "
        "coexist with faster liquidity, volatility and "
        "microstructure states."
    ),

    (
        "Factorial state models allowing multiple latent "
        "conditions to coexist rather than forcing the market "
        "into a single mutually exclusive regime."
    ),

    (
        "Online and recursive adaptation so that the state "
        "architecture can respond to structural change without "
        "silently rewriting historical classifications."
    ),

    (
        "Formal precursor analysis testing whether transition "
        "pressure and model disagreement contain information "
        "before, rather than merely during, regime changes."
    ),

    (
        "Comparison against explicit benchmarks including HMMs, "
        "Markov-switching models, Bayesian change-point models "
        "and other conventional latent-state approaches."
    ),

    (
        "Extension of the scientific swarm so that competing "
        "architectures can themselves be created, challenged "
        "and recursively revised."
    )
]


print("\n" + "=" * 78)

print(
    "NEXT RESEARCH FRONTIER"
)

print("=" * 78)


for i, frontier in enumerate(

    next_research_frontier,

    start=1
):

    print(
        f"\n{i}. {frontier}"
    )


# ============================================================
# 18. COMPLETE PROVENANCE MANIFEST
# ============================================================

provenance_manifest = {

    "experiment":
        experiment_identity,

    "architecture":
        architecture_summary,

    "validation":
        validation_report,

    "evidence_flags":
        evidence_flags,

    "research_conclusions":
        research_conclusions,

    "research_limitations":
        research_limitations,

    "next_research_frontier":
        next_research_frontier,

    "software_environment": {

        "python":
            platform.python_version(),

        "numpy":
            np.__version__,

        "pandas":
            pd.__version__
    },

    "data_dimensions": {

        "state_rows":
            int(
                state.shape[0]
            ),

        "state_columns":
            int(
                state.shape[1]
            ),

        "feature_rows":
            int(
                X.shape[0]
            ),

        "feature_columns":
            int(
                X.shape[1]
            )
    }
}


# ============================================================
# 19. SAVE CORE FINAL TABLES
# ============================================================

regime_empirical_summary.to_csv(

    OUT /
    "final_regime_summary.csv",

    index=False
)


feature_profiles.to_csv(

    OUT /
    "final_regime_feature_profiles.csv"
)


transition_matrix.to_csv(

    OUT /
    "final_transition_matrix.csv"
)


conditional_forward.to_csv(

    OUT /
    "final_conditional_forward_behavior.csv"
)


swarm_convergence.to_csv(

    OUT /
    "final_swarm_convergence.csv",

    index=False
)


validation_summary.to_csv(

    OUT /
    "final_validation_summary.csv",

    index=False
)


evidence_flag_table.to_csv(

    OUT /
    "final_evidence_flags.csv",

    index=False
)


state.to_csv(

    OUT /
    "final_state_history.csv"
)


# ============================================================
# 20. SAVE JSON OBJECTS
# ============================================================

(
    OUT /
    "final_architecture.json"
).write_text(

    json.dumps(
        json_safe(
            architecture_summary
        ),
        indent=2,
        ensure_ascii=False
    ),

    encoding="utf-8"
)


(
    OUT /
    "final_provenance_manifest.json"
).write_text(

    json.dumps(
        json_safe(
            provenance_manifest
        ),
        indent=2,
        ensure_ascii=False
    ),

    encoding="utf-8"
)


(
    OUT /
    "final_research_conclusions.json"
).write_text(

    json.dumps(

        json_safe({

            "conclusions":
                research_conclusions,

            "limitations":
                research_limitations,

            "next_research_frontier":
                next_research_frontier
        }),

        indent=2,

        ensure_ascii=False
    ),

    encoding="utf-8"
)


# ============================================================
# 21. SAVE COMPLETE AGENT PROVENANCE
# ============================================================

(
    OUT /
    "final_50_agent_proposals.json"
).write_text(

    json.dumps(
        json_safe(
            proposals
        ),
        indent=2,
        ensure_ascii=False
    ),

    encoding="utf-8"
)


# ============================================================
# 22. HUMAN-READABLE FINAL RESEARCH REPORT
# ============================================================

report_lines = []


report_lines.append(
    "# 50-Agent Cross-Science Market Regime Swarm"
)

report_lines.append("")

report_lines.append(
    "## Final Research Report"
)

report_lines.append("")

report_lines.append(
    f"Experiment ID: `{experiment_id}`"
)

report_lines.append("")

report_lines.append(
    f"Sample: {experiment_identity['sample_start']} "
    f"to {experiment_identity['sample_end']}"
)

report_lines.append("")

report_lines.append(
    f"Observations: {len(state):,}"
)

report_lines.append("")

report_lines.append(
    f"Scientific agents: {len(proposals)}"
)

report_lines.append("")

report_lines.append(
    f"Latent regimes: {K}"
)

report_lines.append("")

report_lines.append(
    "EDUCATIONAL RESEARCH — NOT INVESTMENT ADVICE"
)

report_lines.append("")


# ------------------------------------------------------------
# Architecture
# ------------------------------------------------------------

report_lines.append(
    "## 1. Scientific Architecture"
)

report_lines.append("")

report_lines.append(
    f"**Architecture:** "
    f"{synthesis['architecture_name']}"
)

report_lines.append("")

report_lines.append(
    "**Representation layer:** "
    +
    synthesis[
        "representation_layer"
    ]
)

report_lines.append("")

report_lines.append(
    "**State-inference layer:** "
    +
    synthesis[
        "state_inference_layer"
    ]
)

report_lines.append("")

report_lines.append(
    "**Transition layer:** "
    +
    synthesis[
        "transition_layer"
    ]
)

report_lines.append("")

report_lines.append(
    "**Uncertainty layer:** "
    +
    synthesis[
        "uncertainty_layer"
    ]
)

report_lines.append("")


# ------------------------------------------------------------
# Core motifs
# ------------------------------------------------------------

report_lines.append(
    "## 2. Cross-Science Motifs"
)

report_lines.append("")


for motif in synthesis[
    "core_motifs"
]:

    report_lines.append(
        f"- {motif}"
    )


report_lines.append("")


# ------------------------------------------------------------
# Minority ideas
# ------------------------------------------------------------

report_lines.append(
    "## 3. Minority Ideas Preserved"
)

report_lines.append("")


for idea in synthesis[
    "minority_ideas_to_preserve"
]:

    report_lines.append(
        f"- {idea}"
    )


report_lines.append("")


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

report_lines.append(
    "## 4. Validation Evidence"
)

report_lines.append("")


for _, row in validation_summary.iterrows():

    report_lines.append(

        f"- **{row['metric']}:** "
        f"{row['value']}"
    )


report_lines.append("")


# ------------------------------------------------------------
# Conclusions
# ------------------------------------------------------------

report_lines.append(
    "## 5. Research Conclusions"
)

report_lines.append("")


for conclusion in research_conclusions:

    report_lines.append(
        f"- {conclusion}"
    )


report_lines.append("")


# ------------------------------------------------------------
# Falsification
# ------------------------------------------------------------

report_lines.append(
    "## 6. Falsification Criteria"
)

report_lines.append("")


for criterion in synthesis[
    "falsification_criteria"
]:

    report_lines.append(
        f"- {criterion}"
    )


report_lines.append("")


# ------------------------------------------------------------
# Limitations
# ------------------------------------------------------------

report_lines.append(
    "## 7. Limitations"
)

report_lines.append("")


for limitation in research_limitations:

    report_lines.append(
        f"- {limitation}"
    )


report_lines.append("")


# ------------------------------------------------------------
# Research frontier
# ------------------------------------------------------------

report_lines.append(
    "## 8. Next Research Frontier"
)

report_lines.append("")


for frontier in next_research_frontier:

    report_lines.append(
        f"- {frontier}"
    )


report_lines.append("")


report_lines.append(
    "---"
)

report_lines.append("")

report_lines.append(
    "This notebook is an educational research experiment. "
    "Its outputs are not investment recommendations."
)


final_report_text = "\n".join(
    report_lines
)


final_report_path = (

    OUT /
    "FINAL_RESEARCH_REPORT.md"
)


final_report_path.write_text(

    final_report_text,

    encoding="utf-8"
)


# ============================================================
# 23. FINAL MARKET-REGIME OBSERVATORY
# ============================================================

spy_final = (

    px["SPY"]

    .reindex(
        state.index
    )

    .ffill()
)


plt.figure(
    figsize=(15, 6)
)


for k in range(K):

    mask = (
        state[
            "regime"
        ]
        ==
        k
    )


    plt.scatter(

        state.index[
            mask
        ],

        spy_final.loc[
            state.index[
                mask
            ]
        ],

        s=8,

        label=f"Regime {k}"
    )


plt.yscale(
    "log"
)


plt.xlabel(
    "Date"
)

plt.ylabel(
    "SPY — log scale"
)

plt.title(
    "Final Market-Regime Observatory"
)

plt.legend(
    ncol=min(
        K,
        4
    )
)

plt.grid(
    alpha=0.2
)

plt.tight_layout()


final_observatory_path = (

    OUT /
    "final_market_regime_observatory.png"
)


plt.savefig(

    final_observatory_path,

    dpi=180,

    bbox_inches="tight"
)


plt.show()


# ============================================================
# 24. FINAL TRANSITION OBSERVATORY
# ============================================================

plt.figure(
    figsize=(15, 5)
)


plt.plot(

    state.index,

    state[
        "transition_z"
    ],

    label="Transition pressure"
)


plt.axhline(

    2.0,

    linestyle="--",

    linewidth=1.0,

    label="High-pressure threshold"
)


plt.axhline(

    0.0,

    linewidth=0.8
)


plt.xlabel(
    "Date"
)

plt.ylabel(
    "Transition-pressure z-score"
)

plt.title(
    "Final Transition-Pressure Observatory"
)

plt.legend()

plt.grid(
    alpha=0.2
)

plt.tight_layout()


final_transition_path = (

    OUT /
    "final_transition_pressure.png"
)


plt.savefig(

    final_transition_path,

    dpi=180,

    bbox_inches="tight"
)


plt.show()


# ============================================================
# 25. FINAL SWARM-CONVERGENCE OBSERVATORY
# ============================================================

plt.figure(
    figsize=(10, 5)
)


plt.plot(

    swarm_convergence[
        "agents"
    ],

    swarm_convergence[
        "state_count_L1_distance"
    ],

    marker="o",

    label="State-count distance"
)


plt.xlabel(
    "Number of scientific agents"
)

plt.ylabel(
    "L1 distance from full-swarm state-count distribution"
)

plt.title(
    "Final Swarm-Convergence Observatory"
)

plt.grid(
    alpha=0.2
)

plt.tight_layout()


final_convergence_path = (

    OUT /
    "final_swarm_convergence.png"
)


plt.savefig(

    final_convergence_path,

    dpi=180,

    bbox_inches="tight"
)


plt.show()


# ============================================================
# 26. OUTPUT INVENTORY
# ============================================================

output_inventory = []


for path in sorted(
    OUT.iterdir()
):

    if path.is_file():

        output_inventory.append({

            "filename":
                path.name,

            "size_bytes":
                int(
                    path.stat().st_size
                ),

            "suffix":
                path.suffix
        })


output_inventory_df = pd.DataFrame(
    output_inventory
)


output_inventory_df.to_csv(

    OUT /
    "FINAL_OUTPUT_INVENTORY.csv",

    index=False
)


print("\n" + "=" * 78)

print(
    "FINAL OUTPUT INVENTORY"
)

print("=" * 78)


display(
    output_inventory_df
)


# ============================================================
# 27. CREATE COMPLETE RESEARCH BUNDLE
# ============================================================
#
# Archive everything in OUT.
#
# The archive is created OUTSIDE the OUT directory so that it
# does not recursively include itself.
# ============================================================

bundle_base = Path(
    "/content/market_regime_swarm_research_bundle"
)


bundle_zip = Path(

    shutil.make_archive(

        str(
            bundle_base
        ),

        "zip",

        root_dir=str(
            OUT
        )
    )
)


# ============================================================
# 28. FINAL MACHINE-READABLE MANIFEST UPDATE
# ============================================================

final_manifest = {

    "experiment":
        experiment_identity,

    "architecture":
        architecture_summary,

    "validation":
        validation_report,

    "evidence_flags":
        evidence_flags,

    "outputs": {

        "output_directory":
            str(
                OUT
            ),

        "final_report":
            str(
                final_report_path
            ),

        "market_regime_observatory":
            str(
                final_observatory_path
            ),

        "transition_observatory":
            str(
                final_transition_path
            ),

        "swarm_convergence_observatory":
            str(
                final_convergence_path
            ),

        "research_bundle":
            str(
                bundle_zip
            )
    },

    "completion_status":
        "COMPLETE"
}


(
    OUT /
    "FINAL_MANIFEST.json"
).write_text(

    json.dumps(
        json_safe(
            final_manifest
        ),
        indent=2,
        ensure_ascii=False
    ),

    encoding="utf-8"
)


# ============================================================
# 29. FINAL CAPSTONE REPORT
# ============================================================

print("\n" + "=" * 78)

print(
    "50-AGENT CROSS-SCIENCE MARKET REGIME SWARM"
)

print(
    "FINAL RESEARCH SYNTHESIS"
)

print("=" * 78)


print(
    f"\nExperiment ID       : "
    f"{experiment_id}"
)

print(
    f"Architecture        : "
    f"{synthesis['architecture_name']}"
)

print(
    f"Scientific agents   : "
    f"{len(proposals)}"
)

print(
    f"Scientific families : "
    f"{len(set(p.get('family', '') for p in proposals))}"
)

print(
    f"Market observations : "
    f"{len(state):,}"
)

print(
    f"Observed features   : "
    f"{X.shape[1]}"
)

print(
    f"Latent regimes      : "
    f"{K}"
)


# ------------------------------------------------------------
# Validation results
# ------------------------------------------------------------

print("\n" + "-" * 78)

print(
    "EMPIRICAL VALIDATION"
)

print("-" * 78)


if metric(
    "gmm_silhouette"
) is not None:

    print(
        f"GMM silhouette                  : "
        f"{metric('gmm_silhouette'):.3f}"
    )


if metric(
    "consensus_persistence"
) is not None:

    print(
        f"Consensus persistence           : "
        f"{metric('consensus_persistence'):.3f}"
    )


if metric(
    "perturbation_ARI_mean"
) is not None:

    print(
        f"Perturbation ARI — mean         : "
        f"{metric('perturbation_ARI_mean'):.3f}"
    )


if metric(
    "perturbation_ARI_min"
) is not None:

    print(
        f"Perturbation ARI — minimum      : "
        f"{metric('perturbation_ARI_min'):.3f}"
    )


if metric(
    "transition_intensity_switch_ratio"
) is not None:

    print(
        f"Transition-intensity ratio      : "
        f"{metric('transition_intensity_switch_ratio'):.3f}"
    )


if metric(
    "mean_model_disagreement"
) is not None:

    print(
        f"Mean model disagreement         : "
        f"{metric('mean_model_disagreement'):.3f}"
    )


if metric(
    "cross_regime_forward_return_range"
) is not None:

    print(
        f"Forward-return regime range     : "
        f"{metric('cross_regime_forward_return_range'):.4f}"
    )


if metric(
    "cross_regime_forward_volatility_range"
) is not None:

    print(
        f"Forward-volatility regime range : "
        f"{metric('cross_regime_forward_volatility_range'):.4f}"
    )


# ------------------------------------------------------------
# Final interpretation
# ------------------------------------------------------------

print("\n" + "-" * 78)

print(
    "FINAL INTERPRETATION"
)

print("-" * 78)


print(
    "\nThe experiment began with 50 independent scientific "
    "perspectives drawn from multiple disciplines rather than "
    "with a single predetermined financial regime model."
)


print(
    "\nThose proposals were synthesized into a common empirical "
    "architecture separating representation, latent-state "
    "inference, transition dynamics and epistemic uncertainty."
)


print(
    "\nThe resulting market states were then examined for "
    "economic differentiation, temporal persistence, "
    "perturbation stability, transition behavior and "
    "cross-model disagreement."
)


print(
    "\nThe swarm itself was also evaluated for convergence, "
    "allowing the experiment to distinguish stability of the "
    "scientific collective from stability of the empirical "
    "market-state model."
)


print(
    "\nThe resulting architecture should therefore be understood "
    "as a falsifiable research framework rather than as a claim "
    "that financial markets possess one uniquely correct set of "
    "regimes."
)


print(
    "\nThe principal methodological contribution is the workflow:"
)


print(
    "\n    DIVERSE SCIENTIFIC CONJECTURES"
)

print(
    "                ↓"
)

print(
    "    CROSS-DISCIPLINARY SYNTHESIS"
)

print(
    "                ↓"
)

print(
    "    EMPIRICAL LATENT-STATE INFERENCE"
)

print(
    "                ↓"
)

print(
    "    TRANSITION DYNAMICS"
)

print(
    "                ↓"
)

print(
    "    EPISTEMIC UNCERTAINTY"
)

print(
    "                ↓"
)

print(
    "    FALSIFICATION & ROBUSTNESS"
)


# ------------------------------------------------------------
# Files
# ------------------------------------------------------------

print("\n" + "-" * 78)

print(
    "RESEARCH OUTPUTS"
)

print("-" * 78)


print(
    f"\nOutput directory:"
)

print(
    OUT
)


print(
    f"\nFinal research report:"
)

print(
    final_report_path
)


print(
    f"\nProvenance manifest:"
)

print(
    OUT /
    "final_provenance_manifest.json"
)


print(
    f"\nComplete research bundle:"
)

print(
    bundle_zip
)


print("\n" + "=" * 78)

print(
    "EXPERIMENT COMPLETE"
)

print(
    "50 SCIENTIFIC AGENTS → ONE FALSIFIABLE MARKET-REGIME ARCHITECTURE"
)

print("=" * 78)


print(
    "\nEDUCATIONAL RESEARCH — NOT INVESTMENT ADVICE"
)

==============================================================================
CELL 10 — FINAL SYNTHESIS, PROVENANCE & RESEARCH EXPORT
==============================================================================

Architecture      : Metastable Basin-Transition Architecture (MBTA)
Latent regimes    : 4
Observations      : 3,641
Scientific agents : 50

==============================================================================
FINAL SCIENTIFIC ARCHITECTURE
==============================================================================

Metastable Basin-Transition Architecture (MBTA)

Representation layer:
Construct a standardized multivariate feature vector (volatility, dispersion, correlation, credit, rotation, trend/breadth) over rolling windows, then reduce dimensionality via PCA to extract a small set of orthogonal order-parameter coordinates capturing >80% variance; this low-dimensional embedding serves as the common substrate for all downstream inference, analogous to order-parameter reduction used independently across physics, chemistry, and network-science proposals.

State-inference layer:
Apply parallel unsupervised architectures on the PCA-reduced space: GaussianMixture for probabilistic soft-membership basins (free-energy minima analog), KMeans for hard-partition baseline, and SpectralClustering on a correlation/affinity graph to capture non-convex or network-topology-defined regimes; each yields a candidate regime labeling to be reconciled downstream rather than assumed correct individually.

Transition layer:
Regime change is defined not by label-switching alone but by evidence of dynamical instability: use TransitionIntensity metrics (rate-of-change/persistence of state-occupancy probability, analogous to Kramers escape rate or CUSUM-style intensity) combined with rolling variance/autocorrelation of the order parameter (critical-slowing-down proxy) to confirm that a genuine barrier-crossing/dynamical event underlies the label change, filtering out noise-driven relabeling.

Uncertainty layer:
Disagreement among PCA+GMM, KMeans, and SpectralClustering partitions is treated as an empirical uncertainty signal rather than noise to be averaged away: apply ConsensusVoting across architectures per time step; low-consensus periods are flagged as ambiguous/transitional zones (analogous to transition-state or committor regions in reaction-coordinate theory), while high-consensus periods define confidently-labeled regimes.

==============================================================================
CORE CROSS-SCIENCE MOTIFS
==============================================================================

1. Free-energy/potential landscape with metastable basins separated by barriers (Landau, Kramers, reaction-coordinate chemistry, geophysical stress-release)

2. Critical slowing down: rising variance/autocorrelation as universal early-warning precursor across physics, ecology, seismology

3. Spectral/operator decomposition of coupled systems (Koopman, graph Laplacian, correlation eigenstructure) revealing dominant coherent modes

4. Self-exciting/triggered cascades with power-law or Omori-type decay (ETAS, nucleation, aftershocks)

5. Information-theoretic divergence between successive local distributions as a model-free change signal (KL/JS divergence, transfer entropy)

6. Low-dimensional manifold/order-parameter reduction of high-dimensional observables via embedding or factorization

==============================================================================
MINORITY IDEAS PRESERVED BY THE SYNTHESIS
==============================================================================

1. Directed information/transfer-entropy network reconfiguration as a regime signature distinct from marginal statistics (A21, A24)

2. Topological data analysis (persistent homology) capturing shape/cyclicality beyond covariance (A27)

3. Nucleation-style supercritical growth dynamics distinguishing false starts from propagating regime shifts (A35)

4. Structured singular value / robust-margin framing of fragility as a continuous precursor rather than discrete state (A18)

5. Switched linear dynamical systems with guard-set/geometric transition boundaries rather than free-floating transition probabilities (A17)

==============================================================================
EMPIRICAL REGIME SUMMARY
==============================================================================

,regime,observations,share,one_day_persistence,episodes,mean_days,median_days,max_days,mean_forward_return,median_forward_return,mean_forward_volatility,median_forward_volatility
0,0,877,0.2409,0.8461,135,6.4963,2.0,47,0.0145,0.0277,0.1794,0.1624
1,1,1689,0.4639,0.9094,154,10.9675,3.0,284,0.0053,0.0121,0.1157,0.1054
2,2,830,0.2280,0.8145,154,5.3896,3.0,41,0.0132,0.0175,0.1175,0.1042
3,3,245,0.0673,0.9224,19,12.8947,2.0,64,0.0350,0.0475,0.2645,0.2572

==============================================================================
MEDIAN OBSERVABLE FEATURE PROFILE BY REGIME
==============================================================================

,spy_ret_5d,spy_trend_63d,spy_vol_21d,spy_downvol_63d,spy_drawdown,cross_asset_dispersion,avg_corr_63d,breadth_63d,vix_level,vix_change_21d,credit_risk_21d,bond_equity_rotation_21d,gold_equity_rotation_21d
regime,,,,,,,,,,,,,
0,-0.010,-0.006,0.175,0.099,-0.063,0.010,0.271,0.50,3.030,0.155,-0.003,0.019,0.029
1,0.003,0.056,0.092,0.058,-0.006,0.007,0.237,0.75,2.640,-0.004,0.002,-0.015,-0.015
2,0.015,0.051,0.135,0.084,-0.006,0.008,0.270,0.75,2.736,-0.160,0.009,-0.046,-0.044
3,0.007,-0.085,0.289,0.178,-0.162,0.015,0.370,0.25,3.338,-0.035,-0.001,-0.006,0.011

==============================================================================
EMPIRICAL REGIME TRANSITION MATRIX
==============================================================================

regime      0      1      2      3
regime
0       0.846  0.057  0.078  0.019
1       0.041  0.909  0.049  0.000
2       0.059  0.124  0.814  0.002
3       0.065  0.000  0.012  0.922

==============================================================================
CONSOLIDATED VALIDATION EVIDENCE
==============================================================================

                                   metric      value
0                          Latent regimes     4.0000
1                          GMM silhouette     0.1758
2                   Consensus persistence     0.8734
3                 Perturbation ARI — mean     0.8697
4              Perturbation ARI — minimum     0.4021
5       Transition-intensity switch ratio     1.0542
6                 Mean model disagreement     0.1441
7               Switch disagreement ratio     2.1415
8       Cross-regime forward-return range     0.0297
9   Cross-regime forward-volatility range     0.1487
10               Complete forward windows  3620.0000
11                      Scientific agents    50.0000

==============================================================================
50-AGENT SWARM CONVERGENCE
==============================================================================

   agents  state_count_L1_distance  vocabulary_Jaccard
0       5                     1.00              0.3333
1      10                     0.60              0.3793
2      20                     0.20              0.6000
3      30                     0.20              0.4815
4      40                     0.11              0.7391
5      50                     0.00              1.0000

==============================================================================
FALSIFICATION CRITERIA
==============================================================================

1. Consensus across clustering architectures is no better than chance-level agreement (adjusted Rand index near zero) on out-of-sample data

2. TransitionIntensity-flagged transitions show no lead-time relationship (via cross-correlation/event study) to realized volatility or drawdown spikes

3. Critical-slowing-down proxies (rolling variance/autocorrelation) fail to rise before historically labeled regime shifts (2015, 2018, 2020, 2022) more than chance

4. Regime count selected by PCA+GMM information criteria is unstable across bootstrap resamples or rolling windows, undermining the 4-state hypothesis

5. Consensus-low ('ambiguous') periods do not correspond to elevated forward realized volatility or classification instability, contradicting the transition-state interpretation

6. Simple mean/variance threshold models achieve equal or better predictive/discriminative power than the full architecture, indicating unnecessary complexity

7. Regime labels fail to generalize out-of-sample, showing large drift in cluster centroids/covariances when refit on later data

==============================================================================
EMPIRICAL EVIDENCE FLAGS
==============================================================================

                          evidence_dimension  observed
0             perturbation_structure_present      True
1    transition_intensity_higher_on_switches      True
2         consensus_has_temporal_persistence      True
3      forward_return_differs_across_regimes      True
4  forward_volatility_differs_across_regimes      True

==============================================================================
RESEARCH CONCLUSIONS
==============================================================================

1. The 50-agent cross-science swarm converged on an empirical architecture initialized with 4 latent market states. The final architecture combines dimensionality reduction, multiple competing state estimators, explicit transition measurement and model-disagreement analysis.

2. Small perturbations of the standardized market features produced a mean Adjusted Rand Index of 0.870. This measures the stability of the PCA-GMM partition under the perturbation experiment implemented in Cell 9.

3. The consensus latent-state sequence exhibited one-step persistence of 0.873. The inferred states therefore possess measurable temporal continuity rather than behaving as independent daily classifications.

4. The ratio of mean transition intensity on regime-switch observations to non-switch observations was 1.054. This directly tests the cross-science hypothesis that discrete regime changes should be associated with stronger movement through observable market state space.

5. Mean disagreement across the competing latent-state estimators was 0.144. The experiment therefore preserves epistemic uncertainty rather than forcing every observation into an apparently certain classification.

6. Across the inferred regimes, the range in mean 21-day forward log returns was 0.0297, while the range in mean forward realized volatility was 0.1487. These are descriptive measures of economic differentiation; they are not causal estimates or trading claims.

7. The experiment does not establish that the inferred regimes constitute a unique or permanent ontology of financial markets. The state count, representation, clustering algorithms and transition measures remain research hypotheses subject to out-of-sample testing, alternative data, alternative state architectures and the explicit falsification criteria proposed by the swarm.

==============================================================================
RESEARCH LIMITATIONS
==============================================================================

1. The experiment is observational. Differences across latent regimes do not establish causal relationships.

2. The feature universe is intentionally compact and cannot represent every dimension of market structure.

3. PCA, Gaussian mixtures, K-means and spectral clustering impose different geometric assumptions on the latent-state problem.

4. The consensus architecture reduces model dependence but does not eliminate model risk.

5. Spectral clustering is estimated only on the recent subsample defined in Cell 7, whereas GMM and K-means use the complete feature history.

6. The 21-day conditional forward analysis is descriptive and overlapping forward windows create serial dependence across observations.

7. Perturbation robustness demonstrates local stability to the specified noise experiment; it does not imply robustness to structural breaks or different feature universes.

8. The scientific swarm is deliberately heterogeneous, but its synthesis remains constrained by the prompts, the selected disciplines and the empirical algorithms made available to the synthesis layer.

==============================================================================
NEXT RESEARCH FRONTIER
==============================================================================

1. Out-of-sample regime inference with an explicit training, validation and untouched test period.

2. Hierarchical latent states in which slow macro regimes coexist with faster liquidity, volatility and microstructure states.

3. Factorial state models allowing multiple latent conditions to coexist rather than forcing the market into a single mutually exclusive regime.

4. Online and recursive adaptation so that the state architecture can respond to structural change without silently rewriting historical classifications.

5. Formal precursor analysis testing whether transition pressure and model disagreement contain information before, rather than merely during, regime changes.

6. Comparison against explicit benchmarks including HMMs, Markov-switching models, Bayesian change-point models and other conventional latent-state approaches.

7. Extension of the scientific swarm so that competing architectures can themselves be created, challenged and recursively revised.

==============================================================================
FINAL OUTPUT INVENTORY
==============================================================================

                                  filename  size_bytes suffix
0                 FINAL_RESEARCH_REPORT.md        9497    .md
1                     agent_proposals.json      191339  .json
2       cell7_regime_inference_report.json         546  .json
3    cell8_transition_dynamics_report.json         506  .json
4         conditional_forward_behavior.csv         659   .csv
5        disagreement_validation_cell9.csv         161   .csv
6                       failed_agents.json           2  .json
7            final_50_agent_proposals.json      190611  .json
8                  final_architecture.json        5921  .json
9   final_conditional_forward_behavior.csv         659   .csv
10                final_evidence_flags.csv         239   .csv
11     final_market_regime_observatory.png      135779   .png
12          final_provenance_manifest.json       12187  .json
13       final_regime_feature_profiles.csv        1231   .csv
14                final_regime_summary.csv         800   .csv
15         final_research_conclusions.json        4059  .json
16                 final_state_history.csv     1839383   .csv
17             final_swarm_convergence.csv         239   .csv
18             final_swarm_convergence.png       77939   .png
19             final_transition_matrix.csv         311   .csv
20           final_transition_pressure.png      245299   .png
21            final_validation_summary.csv         508   .csv
22           forward_validation_sample.csv      194111   .csv
23                latent_state_history.csv     1517301   .csv
24                    method_agreement.csv         115   .csv
25              perturbation_stability.csv         439   .csv
26                    proposal_summary.csv       29877   .csv
27                 regime_dwell_events.csv       13872   .csv
28                regime_dwell_summary.csv         174   .csv
29             regime_economic_summary.csv        1444   .csv
30             regime_feature_profiles.csv        1231   .csv
31       regime_feature_profiles_cell7.csv        1231   .csv
32                    regime_frequency.csv         187   .csv
33                       run_manifest.json         815  .json
34             state_count_diagnostics.csv         208   .csv
35         state_history_with_dynamics.csv     1839383   .csv
36                   swarm_convergence.csv         239   .csv
37                    swarm_synthesis.json        6031  .json
38                   transition_counts.csv          73   .csv
39        transition_disagreement_test.csv         158   .csv
40                   transition_events.csv       40003   .csv
41           transition_intensity_test.csv         202   .csv
42                   transition_matrix.csv         311   .csv
43         transition_validation_cell9.csv         172   .csv
44                validation_dashboard.csv         511   .csv
45                  validation_report.json         843  .json

==============================================================================
50-AGENT CROSS-SCIENCE MARKET REGIME SWARM
FINAL RESEARCH SYNTHESIS
==============================================================================

Experiment ID       : cross_science_market_regime_swarm_20260923T213320Z
Architecture        : Metastable Basin-Transition Architecture (MBTA)
Scientific agents   : 50
Scientific families : 10
Market observations : 3,641
Observed features   : 13
Latent regimes      : 4

------------------------------------------------------------------------------
EMPIRICAL VALIDATION
------------------------------------------------------------------------------
GMM silhouette                  : 0.176
Consensus persistence           : 0.873
Perturbation ARI — mean         : 0.870
Perturbation ARI — minimum      : 0.402
Transition-intensity ratio      : 1.054
Mean model disagreement         : 0.144
Forward-return regime range     : 0.0297
Forward-volatility regime range : 0.1487

------------------------------------------------------------------------------
FINAL INTERPRETATION
------------------------------------------------------------------------------

The experiment began with 50 independent scientific perspectives drawn from multiple disciplines rather than with a single predetermined financial regime model.

Those proposals were synthesized into a common empirical architecture separating representation, latent-state inference, transition dynamics and epistemic uncertainty.

The resulting market states were then examined for economic differentiation, temporal persistence, perturbation stability, transition behavior and cross-model disagreement.

The swarm itself was also evaluated for convergence, allowing the experiment to distinguish stability of the scientific collective from stability of the empirical market-state model.

The resulting architecture should therefore be understood as a falsifiable research framework rather than as a claim that financial markets possess one uniquely correct set of regimes.

The principal methodological contribution is the workflow:

    DIVERSE SCIENTIFIC CONJECTURES
                ↓
    CROSS-DISCIPLINARY SYNTHESIS
                ↓
    EMPIRICAL LATENT-STATE INFERENCE
                ↓
    TRANSITION DYNAMICS
                ↓
    EPISTEMIC UNCERTAINTY
                ↓
    FALSIFICATION & ROBUSTNESS

------------------------------------------------------------------------------
RESEARCH OUTPUTS
------------------------------------------------------------------------------

Output directory:
/content/regime_swarm_outputs

Final research report:
/content/regime_swarm_outputs/FINAL_RESEARCH_REPORT.md

Provenance manifest:
/content/regime_swarm_outputs/final_provenance_manifest.json

Complete research bundle:
/content/market_regime_swarm_research_bundle.zip

==============================================================================
EXPERIMENT COMPLETE
50 SCIENTIFIC AGENTS → ONE FALSIFIABLE MARKET-REGIME ARCHITECTURE
==============================================================================

EDUCATIONAL RESEARCH — NOT INVESTMENT ADVICE

## The Narrative: From Fifty Scientific Minds to a Market-Regime Observatory

## A 50-Agent Cross-Science Experiment in Market-Regime Discovery

Financial professionals have always understood that markets behave differently under different conditions. A portfolio that performs well during a stable expansion may behave very differently during a liquidity shock. Correlations that appear dependable in ordinary markets can suddenly converge toward one during periods of stress. Credit, equities, bonds, commodities and volatility can move from relatively independent sources of information to components of a single systemic event.

We usually describe these different configurations with the word **regime**.

The difficulty is that the regime itself is not observable. We observe prices, returns, volatility, correlations, spreads, trends and rotations. We do not observe a variable called *the market regime*. Regime discovery is therefore an inverse problem: from a collection of observable financial signals, we attempt to infer the hidden state of the system that may have generated them.

Traditional finance already possesses sophisticated methods for attacking this problem. Hidden Markov Models, Markov-switching models, mixture models and change-point methods are familiar examples. The notebook developed here begins from a different question:

**What if finance has been searching too narrowly?**

Physics, chemistry, electrical engineering, control theory, information theory, mathematics, network science, astrophysics and geophysics all confront versions of the same fundamental problem. They observe complex systems whose underlying states cannot be measured directly. They must infer those states from noisy, incomplete and sometimes contradictory signals.

The notebook therefore does not begin by selecting a favorite financial model. It begins by constructing a **swarm of fifty scientific agents** and asking them to search a much larger intellectual universe.

The result is a progression from scientific diversity to empirical discipline:

> **50 scientific conjectures → cross-disciplinary synthesis → executable architecture → latent market states → transition dynamics → robustness and falsification.**

That sequence is the key to understanding the experiment.

---

## 1. Why a Swarm Rather Than One Powerful Model?

Imagine asking a single highly capable AI system:

> “Find the best way to identify market regimes.”

The system might produce an intelligent answer. But there is a substantial risk that it would gravitate toward the most familiar concepts in its training distribution: Hidden Markov Models, clustering, volatility states, perhaps neural networks. The answer could be sophisticated while remaining intellectually narrow.

The swarm changes the problem.

Instead of asking one model to be universally intelligent, the notebook deliberately gives fifty agents **different scientific identities and different mathematical starting points**. They are organized into ten disciplinary families, with five specialists inside each family.

The families cover statistical physics, dynamical systems, signal engineering, control theory, information theory, applied mathematics, chemistry and statistical mechanics, astrophysics, network science, and geophysics/seismology.

The distinction matters because each discipline sees the hidden-state problem differently.

A statistical physicist might ask whether financial markets occupy **metastable phases** separated by transitions. Another may search for an **order parameter** that summarizes collective market organization.

A dynamical-systems specialist might think in terms of **attractors, basins of attraction, bifurcations, Lyapunov stability or slow-fast systems**.

A signal engineer may regard the observed market as a noisy mixture of latent signals and ask whether spectral decomposition, wavelets, blind-source separation or change detection can recover the hidden structure.

A control theorist naturally thinks about **state-space representation, observability, Kalman filtering, switching systems and system identification**.

An information theorist asks a different question: when does the information structure of the market change? Entropy, mutual information, information bottlenecks, minimum-description-length ideas, transfer entropy and distributional divergence become candidate tools.

Applied mathematics contributes operator methods, topology, optimal transport, manifold learning and inverse problems.

Chemistry brings a particularly powerful analogy: a complex system can remain for long periods inside a **metastable basin**, occasionally acquire enough pressure to cross an energy barrier, pass through a transition state, and settle into another basin. That is strikingly close to the intuitive language financial professionals already use when describing stable markets interrupted by abrupt transitions.

Astrophysics contributes methods designed to recover weak latent sources from extremely noisy observations. Network science asks whether the regime is encoded not in individual asset returns but in the **topology of relationships among assets**. Geophysics and seismology contribute ideas about stress accumulation, precursor signals, critical transitions, rupture and event clustering.

The fifty agents therefore do not represent fifty repetitions of the same analysis. They represent **fifty different lenses through which the same hidden-state problem can be viewed**.

That is the first important role of the swarm:

> **Expansion of the hypothesis space.**

---

## 2. Giving Every Scientist the Same Empirical Reality

Scientific imagination is useful only if it remains connected to the data.

The notebook therefore constructs a common empirical environment before asking the agents to reason. The market universe includes major equity exposures such as SPY, QQQ and IWM; Treasury instruments such as TLT and IEF; investment-grade and high-yield credit through LQD and HYG; gold through GLD; commodities through DBC; the dollar through UUP; and the VIX as a direct market-volatility indicator.

From this multivariate system, the notebook constructs thirteen observable market features.

These include short-horizon equity return, medium-horizon trend, realized volatility, downside volatility, drawdown, cross-asset dispersion, average correlation, market breadth, the VIX level and its change, credit risk, bond-versus-equity rotation, and gold-versus-equity rotation.

This feature system is important pedagogically because a market regime should not be confused with the direction of the S&P 500 alone.

A genuine market state may involve simultaneously rising volatility, deteriorating credit, increasing cross-asset correlation, weakening breadth, defensive bond rotation and demand for gold. The regime is therefore conceived as a **multidimensional configuration of the financial system**.

The features are robustly standardized. This prevents a variable with a naturally large numerical scale from dominating the representation merely because of its units.

The fifty agents consequently face the same empirical reality. They can propose radically different theories, but they cannot invent different markets.

This creates a productive separation:

> **The swarm is free in theory, but constrained by evidence.**

---

## 3. What Exactly Does Each Agent Produce?

Each agent receives a structured scientific assignment. It must explain what it believes the latent object actually is, which scientific principle it proposes transferring to finance, the mathematical core of that transfer, which observable features would be required, how transitions should be detected, how many states might be appropriate, how the proposal should be validated, how it could fail, and how novel, plausible and confident the agent considers its hypothesis.

The output is not free-form prose. Claude Sonnet 5 is required to return a defined structured object.

This is a crucial engineering choice.

Without a common schema, fifty scientists would produce fifty essays that would be difficult to compare systematically. Structured output transforms the swarm from a collection of interesting conversations into a **research dataset containing fifty hypotheses**.

The notebook also uses a canary call before launching the complete swarm. One agent is executed first. Only after the API response has passed the structured-output and parsing checks are the other forty-nine agents launched.

Each successful proposal is checkpointed. A failed connection or interrupted Colab session therefore does not destroy the intellectual work already completed.

The individual agents are deliberately run with relatively low reasoning effort. This reflects a deeper design principle: the intelligence of this experiment does not come primarily from making one agent think for an extremely long time. It comes from **diversity across the population**.

We are purchasing breadth before depth.

---

## 4. Fifty Ideas Do Not Solve the Problem

At this point the notebook has deliberately created a new difficulty.

We began with uncertainty about market regimes. We now possess fifty competing scientific descriptions of them.

A naïve solution would be majority voting: count how many agents favor each idea and select the winner.

The notebook explicitly rejects that approach.

Scientific innovation is not necessarily democratic. An unusual proposal from geophysics or topology could contain precisely the idea that forty conventional proposals miss. If the swarm were reduced immediately to majority rule, diversity would have been generated only to be destroyed.

Instead, Cell 6 introduces a separate **scientific synthesizer**.

Its task is not to become agent fifty-one. Its task is architectural.

It receives the proposal corpus and searches for structures that recur across disciplines, complementary ideas that can coexist, and minority insights worth preserving.

The synthesis that emerged from the notebook is called the **Metastable Basin-Transition Architecture, or MBTA**.

This is a revealing result because the architecture is not simply the favorite model of one discipline. It is a convergence of ideas that appear under different names across multiple sciences.

The synthesis identifies six major recurring motifs.

The first is the idea of a **free-energy or potential landscape containing metastable basins separated by barriers**. Versions of this appear in statistical physics, chemistry and geophysics.

The second is **critical slowing down**: before some complex systems undergo a major transition, their ability to recover from disturbances weakens, potentially producing changes in variance and autocorrelation.

The third is **spectral or operator decomposition**, appearing through concepts such as Koopman operators, graph Laplacians and correlation eigenstructures.

The fourth involves **self-exciting cascades and triggered events**, connecting nucleation, aftershocks and propagation processes.

The fifth is **information-theoretic divergence** between local distributions as a model-free signal that the system itself is changing.

The sixth is **low-dimensional order-parameter reduction**: the possibility that many observable variables are manifestations of a smaller number of hidden collective coordinates.

Notice what has happened. The swarm did not simply tell us, “Use clustering.” It gave us a scientific interpretation of what clustering is attempting to recover.

---

## 5. How Was the “Best” Architecture Chosen?

It is important to be precise here. The notebook does **not** claim to have discovered the universally best theory of market regimes.

Instead, it selects the most promising architecture for this experiment using three filters.

### Cross-disciplinary recurrence

Ideas that independently emerge in unrelated sciences deserve attention because they may capture structural properties of hidden-state problems rather than conventions specific to finance.

### Complementarity

Representation, state identification, transition detection and uncertainty are different problems. A useful architecture can therefore combine ideas rather than forcing one algorithm to perform every task.

### Empirical implementability and falsifiability

An elegant scientific metaphor that cannot be connected to observable data is not enough. The synthesis is constrained to an executable empirical vocabulary available in the notebook.

This produces four layers.

The **representation layer** uses PCA to compress the thirteen-dimensional standardized market system into a smaller number of dominant coordinates. A physicist can interpret these as approximate order parameters; a signal engineer as dominant modes; a financial professional can simply regard them as the principal common dimensions along which the market system moves.

The **state-inference layer** deliberately uses several competing algorithms. Gaussian mixtures identify probabilistic basins. K-means provides a simple geometric partition. Spectral clustering contributes a neighborhood-based nonlinear perspective.

The **transition layer** is separated from state classification. The notebook constructs transition intensity from the speed at which the observable feature vector moves through standardized state space.

Finally, the **uncertainty layer** uses disagreement among models as information. If GMM, K-means and spectral clustering disagree, the notebook does not hide the disagreement by pretending that one answer is certain. It records the disagreement as epistemic uncertainty.

This is the architecture selected from the scientific universe opened by the swarm.

Importantly, the synthesis also preserves minority ideas that were not implemented in the first prototype: transfer-entropy networks, persistent homology, nucleation dynamics, robust-control fragility measures and switched dynamical systems with explicit guard boundaries.

They are not discarded. They become part of the research frontier.

---

## 6. Turning the Scientific Architecture into Market Regimes

The empirical implementation begins with PCA.

The reduced representation is passed through Gaussian Mixture Models, K-means and spectral clustering. Because unsupervised labels are arbitrary—a model's “state 0” has no reason to correspond to another model's “state 0”—the notebook uses the Hungarian assignment algorithm to align the classifications.

A consensus state can then be constructed.

The experiment settles on **four latent regimes**, but this number is treated as a working scientific hypothesis rather than a metaphysical fact about markets.

The notebook contains **3,641 market observations** and thirteen features. Rather than naming the four states prematurely as “bull,” “bear,” “crisis” and “recovery,” it examines their empirical feature profiles. This is good scientific discipline. A cluster should earn its economic interpretation from the data.

The resulting sequence is also persistent. The measured one-period consensus persistence is:

> **0.873**

That matters enormously.

If the algorithm changed its mind every day, it might be identifying clusters without identifying regimes. A regime, almost by definition, should have some temporal persistence.

A persistence of 0.873 therefore indicates substantial continuity in the inferred state sequence.

---

## 7. State and Transition Are Not the Same Thing

One of the strongest conceptual features of the notebook is the distinction between **where the market is** and **how rapidly it is moving**.

Cell 7 answers the first question through latent-state inference.

Cell 8 answers the second through transition intensity.

Transition intensity measures the velocity of the standardized market-feature vector. It therefore captures movement through observable state space without requiring the regime label to change immediately.

This distinction is intuitive for a financial professional.

A market can remain classified as the same regime while its internal conditions deteriorate rapidly. Conversely, a classification boundary can occasionally be crossed without an economically dramatic event.

The experiment records **461 consensus regime switches**. Overall persistence remains **0.873**. Transition intensity on switch observations is **1.054 times** that on non-switch observations.

That ratio is above one, but only modestly so. This should not be exaggerated. It provides some support for the idea that switches occur during stronger movement in observable state space, but it is not overwhelming evidence.

The disagreement result is more striking.

Average model disagreement is **0.144**, while disagreement on switch observations relative to ordinary observations rises by a factor of:

> **2.141**

This is economically interesting. The models become much less unanimous around the points where the consensus regime changes.

In other words:

> **Uncertainty itself appears to contain information about transitions.**

---

## 8. Does the Architecture Actually Perform?

Because the true regime is hidden, there is no externally supplied answer key. We cannot calculate ordinary classification accuracy.

The notebook therefore evaluates performance through several independent falsification-oriented tests.

### Geometric separation

The GMM silhouette score is:

> **0.176**

This is modest rather than spectacular. That is informative.

Financial regimes overlap. The market does not divide itself into four perfectly separated clouds for our convenience. A low-to-moderate silhouette warns us against pretending that the states are naturally isolated categories.

### Temporal persistence

The consensus persistence is:

> **0.873**

This is considerably stronger. The inferred states demonstrate meaningful temporal continuity.

### Perturbation stability

The notebook adds small random disturbances to the feature system and repeatedly rebuilds the PCA-GMM partition.

Across twenty perturbation experiments:

- Mean Adjusted Rand Index: **0.870**
- Median Adjusted Rand Index: **0.949**
- Maximum Adjusted Rand Index: **0.965**
- Minimum Adjusted Rand Index: **0.402**

This is encouraging.

It suggests that the architecture is generally not destroyed by small measurement changes.

But the minimum ARI of 0.402 is equally important. Robustness is strong on average but not universal. Some perturbations materially change the inferred partition.

A scientifically responsible interpretation must preserve both observations.

### Economic differentiation

The notebook then asks whether the regimes possess economic differentiation after they are identified.

Using **3,620 observations with complete forward windows**, it calculates subsequent 21-trading-day S&P 500 return and realized volatility conditional on the state observed today.

Across regimes, the range of mean 21-day forward log returns is:

> **0.0297**

while the range in mean forward realized volatility is:

> **0.1487**

Those numbers do not prove predictability.

The analysis uses overlapping windows and is descriptive rather than causal. But they do show that the inferred states are associated with materially different subsequent market environments.

That is precisely what we would hope to see if the latent states contain economically relevant information.

---

## 9. We Validate the Swarm as Well as the Market Model

There is another subtle question.

Even if the empirical architecture performs reasonably well, how do we know that the fifty-agent process itself was meaningful?

Cell 9 therefore studies **swarm convergence**.

It takes the existing proposal population at sizes:

> **5 → 10 → 20 → 30 → 40 → 50 agents**

At each stage it examines the distribution of preferred state counts and the mathematical vocabulary emerging from the agents, and compares these with the final fifty-agent population.

This asks whether scientific thinking begins to stabilize as additional independent perspectives are introduced.

The exercise does not prove that fifty is the mathematically optimal number of agents. That would require a different experiment.

But it makes the swarm auditable.

We can inspect whether the architecture is a broad collective phenomenon or an accident produced by the final few prompts.

This is important because the notebook has two completely different forms of convergence:

> **Scientific convergence among agents**

and

> **Empirical convergence among models**

They should never be confused.

---

## 10. What Has the Experiment Actually Demonstrated?

The strongest conclusion is not that we have finally discovered the four true regimes of financial markets.

That would go well beyond the evidence.

The deeper achievement is methodological.

We started with an enormous intellectual search space. Fifty agents explored hidden-state inference through ten scientific traditions and fifty specialized perspectives.

Structured outputs converted that exploration into a comparable hypothesis corpus.

A separate synthesizer searched for recurring structures without simply counting votes.

Minority ideas were preserved rather than erased.

The resulting architecture was then constrained to algorithms that could actually be executed.

Only after that intellectual expansion did empirical compression begin.

PCA created a reduced market representation.

GMM, K-means and spectral clustering supplied competing views of the hidden states.

Consensus produced a practical state estimate.

Disagreement measured epistemic uncertainty.

Transition intensity measured movement independently of classification.

Persistence, forward behavior, perturbation tests and swarm convergence then challenged the result.

The final architecture—MBTA—is therefore not merely another clustering exercise.

It embodies a different philosophy of AI-assisted financial research:

> **Use artificial intelligence first to enlarge the universe of scientific possibilities, then use mathematical structure and empirical evidence to reduce it.**

That ordering is essential.

An LLM should not be allowed to manufacture empirical truth. Its comparative advantage here is scientific imagination, translation across disciplines and hypothesis generation. Python and market data then impose discipline.

For financial professionals, this is perhaps the most important lesson of the notebook.

The future of AI in quantitative finance may not consist simply of replacing one econometric model with a larger AI model.

A more powerful architecture may consist of **societies of specialized intelligences that explore competing explanations, followed by explicit mechanisms for synthesis, implementation, uncertainty measurement and falsification**.

The market-regime problem is an ideal demonstration because no one observes the hidden state directly. We are forced to distinguish hypothesis from evidence.

And that is precisely what the swarm makes possible.

It does not eliminate uncertainty.

**It organizes uncertainty.**

It does not prove that four regimes are the final description of markets.

It gives us a disciplined way to discover, compare, challenge and eventually replace regime descriptions.

The natural next step is therefore not to declare the problem solved. It is to make the observatory more sophisticated: out-of-sample estimation; explicit comparison with HMM and Markov-switching benchmarks; hierarchical regimes operating at different time scales; factorial states in which several hidden conditions coexist; richer credit, options and liquidity information; precursor analysis; and eventually recursive systems capable of recognizing when their own regime vocabulary has become obsolete.

At that point, the architecture moves beyond a static regime classifier.

It becomes an:

> **Adaptive scientific observatory of the market itself.**




## CONCLUSION — FROM REGIME LABELS TO A MARKET-STATE OBSERVATORY

The central result of this notebook is methodological. Market-regime discovery is reframed from a narrow model-selection exercise into a cross-science latent-state inference problem. The fifty-agent swarm is valuable not because fifty opinions are automatically better than one, but because the agents are assigned genuinely different mathematical traditions. Their collective task is to enlarge the hypothesis space before empirical discipline compresses it again.

That distinction changes the research workflow. A conventional project might begin with an HMM, choose the number of states, fit the model and then interpret the resulting clusters. Here the sequence is reversed. We begin by asking what a “hidden regime” could mean under multiple scientific ontologies. It might be a metastable phase, a state-space variable, a spectral configuration, a network topology, an information regime, a basin of attraction, a chemical-like transition state, a weak latent source, or a precursor-and-rupture process. Each interpretation suggests different observables and different failure tests. Only after collecting these possibilities do we build a common empirical representation.

The resulting architecture is intentionally hybrid. Persistence matters because market conditions do not normally redraw themselves independently every day. Multiscale structure matters because slow macroeconomic conditions and fast liquidity disturbances coexist. Network structure matters because crises often appear as changes in collective dependence rather than merely changes in average returns. Transition detection matters because the economically important moment is often not the stable regime itself but the movement between regimes. Uncertainty matters because a market can sit near a boundary where competing models disagree. A useful observatory therefore should report state, transition pressure and model disagreement separately.

The notebook also establishes a practical principle for AI-assisted quantitative research: language models should expand scientific imagination without being allowed to fabricate the empirical world. Claude Sonnet 5 generates hypotheses under a strict JSON schema, and the code checks completion status before parsing structured output. The notebook deliberately avoids obsolete sampling parameters and old JSON-extraction tricks. A one-agent canary call is executed before the remaining swarm, preventing an API mismatch from being multiplied fifty times. Low effort and concise response contracts keep the individual agents inexpensive; collective diversity, rather than maximal reasoning per call, is the source of intelligence. The market data, transformations, clustering, validation and exports remain deterministic Python objects.

No unsupervised regime model can be validated in the same way as a supervised classifier with known labels. That is why the notebook uses a portfolio of falsification-oriented diagnostics. Persistence asks whether states last long enough to deserve the word regime. Conditional forward distributions ask whether the states have economic consequences. Perturbation stability asks whether small changes in inputs destroy the partition. Transition-intensity analysis asks whether inferred switches coincide with large changes in the observable market system. Cross-agent convergence asks whether the scientific architecture is dependent on one idiosyncratic prompt. A serious extension should add walk-forward estimation, transaction-cost-aware strategy tests, alternative universes, macroeconomic releases, options surfaces, intraday liquidity measures and explicit out-of-sample crisis episodes.

The most important conceptual move is to stop treating regime as a perfectly observed categorical truth waiting to be uncovered. In real markets, regimes may overlap, nest and evolve at different speeds. A slow inflationary state can coexist with a fast liquidity event; a risk-on equity trend can coexist with deteriorating credit structure. Future versions should therefore allow hierarchical and factorial latent states, where several hidden processes jointly generate the observations. The current consensus representation is a bridge toward that richer formulation.

There is also a natural path toward recursive adaptation. Once the observatory can estimate state and transition uncertainty, downstream portfolio agents can condition their models, risk budgets and execution logic on those estimates. More importantly, the observatory itself can monitor when its regime vocabulary becomes inadequate. Persistent disagreement, falling cluster separation, unstable transition probabilities or new feature relationships can become triggers for scientific re-inquiry. At that point a new swarm could be convened to propose revised state representations. The architecture would then move from regime detection to regime-model adaptation.

The exercise therefore points toward a different vision of quantitative finance. Rather than selecting one favored model and defending it indefinitely, we can build institutions that maintain a population of scientific lenses, expose their disagreements, test their implications and revise their ontology when the market changes. Artificial intelligence becomes most interesting not when it imitates a single analyst, but when it makes structured intellectual pluralism operational.

This notebook should be read as a research platform, not as trading advice and not as evidence that any discovered state will remain stable in live markets. Its strongest claim is that the hidden-regime problem deserves a broader mathematical search process than finance normally gives it. Physics, engineering, chemistry, astrophysics, mathematics, information theory and network science all contain mature ideas about invisible states and transitions. A fifty-agent swarm gives us a practical way to interrogate those traditions simultaneously. The resulting Market Regime Observatory is the first synthesis: a transparent, falsifiable and extensible architecture for turning that collective scientific imagination into measurable hypotheses.



## REFERENCES
1. Hamilton, J. D. (1989). A New Approach to the Economic Analysis of Nonstationary Time Series and the Business Cycle. Econometrica.
2. Rabiner, L. R. (1989). A Tutorial on Hidden Markov Models and Selected Applications in Speech Recognition. Proceedings of the IEEE.
3. Bishop, C. M. (2006). Pattern Recognition and Machine Learning. Springer.
4. Kritzman, M., Page, S., & Turkington, D. (2012). Regime Shifts: Implications for Dynamic Strategies. Financial Analysts Journal.
5. Ang, A., & Timmermann, A. (2012). Regime Changes and Financial Markets. Annual Review of Financial Economics.
6. Hamilton, J. D. (1994). Time Series Analysis. Princeton University Press.
7. Strogatz, S. H. (2015). Nonlinear Dynamics and Chaos. Westview Press.
8. Cover, T. M., & Thomas, J. A. (2006). Elements of Information Theory. Wiley.
9. Newman, M. (2018). Networks. Oxford University Press.
10. Scheffer, M. et al. (2009). Early-warning signals for critical transitions. Nature.
11. Page, E. S. (1954). Continuous Inspection Schemes. Biometrika.
12. Kalman, R. E. (1960). A New Approach to Linear Filtering and Prediction Problems. Journal of Basic Engineering.
13. Anthropic. Claude Platform documentation: Messages API, structured outputs, model migration and prompting guidance.
14. scikit-learn documentation: GaussianMixture, PCA, clustering metrics and preprocessing.
15. yfinance documentation/project resources for reproducible educational market-data retrieval.